//this fixes issues with 1112 firmids

//create virtual variable for owner name so we don't persistenly modify it
tempvar owner_name_virtual

gen `owner_name_virtual' = a002
replace `owner_name_virtual' = a001 if `owner_name_virtual'==""
replace `owner_name_virtual' = a001 if `owner_name_virtual'=="Same"
replace `owner_name_virtual' = a001 if `owner_name_virtual'=="SAme"
replace `owner_name_virtual' = a001 if `owner_name_virtual'=="Same]"
replace `owner_name_virtual' = a001 if	`owner_name_virtual'=="Corporation" & firmid_1112==""

replace `owner_name_virtual'=ustrtrim(`owner_name_virtual')	
replace firmid_1112="27" if `owner_name_virtual'=="(Stock Corporation)"
replace firmid_1112="39" if `owner_name_virtual'=="(con't from above) Coupler Co."
replace firmid_1112="42" if `owner_name_virtual'=="(stock corporation)"
replace firmid_1112="43" if `owner_name_virtual'=="28th & Smallman Sts., Pittsburgh, PA"
replace firmid_1112="41" if `owner_name_virtual'=="A Michigan Corporation"
replace firmid_1112="amb" if `owner_name_virtual'=="A. M. Byers Company"
replace firmid_1112="co" if `owner_name_virtual'=="A. M. Clark"
replace firmid_1112="38" if `owner_name_virtual'=="A.A. Arueson"
replace firmid_1112="cr" if `owner_name_virtual'=="A.C. Lange  Pres & Gen'l Mgr."
replace firmid_1112="amb" if `owner_name_virtual'=="A.M. Byers Co."
replace firmid_1112="amb" if `owner_name_virtual'=="A.M. Byers Company"
replace firmid_1112="36" if `owner_name_virtual'=="Abel Davis, Receiver"
replace firmid_1112="36" if `owner_name_virtual'=="Abel Davis, Trustee"
replace firmid_1112="2" if `owner_name_virtual'=="Above"
replace firmid_1112="ac" if `owner_name_virtual'=="Acme Steel Company"
replace firmid_1112="27" if `owner_name_virtual'=="Adirondack Steel Foundries Corporation"
replace firmid_1112="aw" if `owner_name_virtual'=="Alan Wood Steel Company"
replace firmid_1112="al" if `owner_name_virtual'=="Allegheny Steel Co."
replace firmid_1112="al" if `owner_name_virtual'=="Allegheny Steel Company"
replace firmid_1112="1" if `owner_name_virtual'=="Allied Steel Castings Co."
replace firmid_1112="1" if `owner_name_virtual'=="Allied Steel Castings Company"
replace firmid_1112="2" if `owner_name_virtual'=="Alloy Cast Steel Company"
replace firmid_1112="2" if `owner_name_virtual'=="Alloy Steel & Metals Company"
replace firmid_1112="2" if `owner_name_virtual'=="Alloy Steel And Metals Co."
replace firmid_1112="2" if `owner_name_virtual'=="Alloy Steel Metals Companies"
replace firmid_1112="2" if `owner_name_virtual'=="Alloy Steel and Metals Company"
replace firmid_1112="1a" if `owner_name_virtual'=="Altoria Iron Company"
replace firmid_1112="3" if `owner_name_virtual'=="American Bridge Company"
replace firmid_1112="4" if `owner_name_virtual'=="American Car and Foundry Co."
replace firmid_1112="4" if `owner_name_virtual'=="American Car and Foundry Company"
replace firmid_1112="5" if `owner_name_virtual'=="American Chain Co., Inc"
replace firmid_1112="5" if `owner_name_virtual'=="American Chain Company, Inc."
replace firmid_1112="6" if `owner_name_virtual'=="American Foundry & Machine Co."
replace firmid_1112="6" if `owner_name_virtual'=="American Foundry & Machine Company"
replace firmid_1112="6" if `owner_name_virtual'=="American Foundry and Machine Co."
replace firmid_1112="7" if `owner_name_virtual'=="American Locomotive"
replace firmid_1112="7" if `owner_name_virtual'=="American Locomotive Company"
replace firmid_1112="am" if `owner_name_virtual'=="American Manganese Steel"
replace firmid_1112="am" if `owner_name_virtual'=="American Manganese Steel Co"
replace firmid_1112="am" if `owner_name_virtual'=="American Manganese Steel Co."
replace firmid_1112="am" if `owner_name_virtual'=="American Manganese Steel Co.  Plant "C""
replace firmid_1112="am" if `owner_name_virtual'=="American Manganese Steel Company"
replace firmid_1112="8" if `owner_name_virtual'=="American Radiator Co."
replace firmid_1112="8" if `owner_name_virtual'=="American Radiator Company"
replace firmid_1112="ast" if `owner_name_virtual'=="American Sheet & Tin Plate Co."
replace firmid_1112="ast" if `owner_name_virtual'=="American Sheet & Tin Plate Company"
replace firmid_1112="ast" if `owner_name_virtual'=="American Sheet and Tin Plate Co."
replace firmid_1112="ast" if `owner_name_virtual'=="American Sheet and Tin Plate Company"
replace firmid_1112="asw" if `owner_name_virtual'=="American Steel & Wire Co."
replace firmid_1112="asw" if `owner_name_virtual'=="American Steel & Wire Company"
replace firmid_1112="asw" if `owner_name_virtual'=="American Steel & Wire co."
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundries"
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundries  Granite City Works"
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundries  Pittsburgh Works"
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundries - East St. Louis Works"
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundries - Granite City Works"
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundries - Indiana Harbor Works"
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundries Verrons Works"
replace firmid_1112="asf" if `owner_name_virtual'=="American Steel Foundry  Thurlow Works"
replace firmid_1112="asw" if `owner_name_virtual'=="American Steel and Wire Company"
replace firmid_1112="9" if `owner_name_virtual'=="American-Swedo Iron Company"
replace firmid_1112="1b" if `owner_name_virtual'=="Anniston Steel Casting Co."
replace firmid_1112="10" if `owner_name_virtual'=="Apollo Steel Co."
replace firmid_1112="10" if `owner_name_virtual'=="Apollo Steel Company"
replace firmid_1112="10" if `owner_name_virtual'=="Apollo Still Company"
replace firmid_1112="11" if `owner_name_virtual'=="Arthur Roeder, Receiver for The Colorado Fuel & Iron Co."
replace firmid_1112="11" if `owner_name_virtual'=="Arthur Roeder, Trustee, Colo. Fuel & Iron Co."
replace firmid_1112="em" if `owner_name_virtual'=="Ashtabula"
replace firmid_1112="12" if `owner_name_virtual'=="Atlantic Foundry Company"
replace firmid_1112="12" if `owner_name_virtual'=="Atlantic Steel Company"
replace firmid_1112="13" if `owner_name_virtual'=="Atlas Steel Casting Co."
replace firmid_1112="13" if `owner_name_virtual'=="Atlas Steel Casting Company"
replace firmid_1112="13" if `owner_name_virtual'=="Atlas Steel Castings Co."
replace firmid_1112="14" if `owner_name_virtual'=="B A Fuller (Pres.)"
replace firmid_1112="15" if `owner_name_virtual'=="Baltimore & Ohio Railroad Company"
replace firmid_1112="15" if `owner_name_virtual'=="Baltimore and Ohio Railroad Company"
replace firmid_1112="16" if `owner_name_virtual'=="Ban Alens & Co.        E.G. van Alen"
replace firmid_1112="17" if `owner_name_virtual'=="Bancroft & Martin Rolling Mills Company"
replace firmid_1112="18" if `owner_name_virtual'=="Barium Steel Corp."
replace firmid_1112="19" if `owner_name_virtual'=="Bay City Electric Steel Casting Company"
replace firmid_1112="20" if `owner_name_virtual'=="Beaver Falls Steel Co."
replace firmid_1112="20" if `owner_name_virtual'=="Beaver Falls Steel Company"
replace firmid_1112="21" if `owner_name_virtual'=="Belle City Malleable Iron Co."
replace firmid_1112="21" if `owner_name_virtual'=="Belle City Malleable Iron Company"
replace firmid_1112="22" if `owner_name_virtual'=="Best Steel Casting Co."
replace firmid_1112="be" if `owner_name_virtual'=="Bethlehem Steel Co."
replace firmid_1112="be" if `owner_name_virtual'=="Bethlehem Steel Company"
replace firmid_1112="be" if `owner_name_virtual'=="Bethlehem Steel Corporation"
replace firmid_1112="be" if `owner_name_virtual'=="Bethlehem Steel Division"
replace firmid_1112="23" if `owner_name_virtual'=="Birdsboro Steel Foundry and Machine Company"
replace firmid_1112="bk" if `owner_name_virtual'=="Blaw Knox Company"
replace firmid_1112="bk" if `owner_name_virtual'=="Blaw-Knox Company"
replace firmid_1112="24" if `owner_name_virtual'=="Borg-Warner Corp"
replace firmid_1112="24" if `owner_name_virtual'=="Borg-Warner Corp."
replace firmid_1112="24" if `owner_name_virtual'=="Borg-Warner Corporation"
replace firmid_1112="25" if `owner_name_virtual'=="Brackburn Alloy Steel Corp."
replace firmid_1112="26" if `owner_name_virtual'=="Braeburn Alloy Steel Corporation"
replace firmid_1112="27" if `owner_name_virtual'=="Brighton Electric Steel Casting Co."
replace firmid_1112="27" if `owner_name_virtual'=="Brighton Electric Steel Casting Company"
replace firmid_1112="27" if `owner_name_virtual'=="Brighton Electric Steel Castings Company"
replace firmid_1112="28" if `owner_name_virtual'=="Buckeye Rolling Mill Company"
replace firmid_1112="29" if `owner_name_virtual'=="Buffalo Bolt Co."
replace firmid_1112="29" if `owner_name_virtual'=="Buffalo Bolt Company"
replace firmid_1112="30" if `owner_name_virtual'=="Buffalo Steel Co."
replace firmid_1112="30" if `owner_name_virtual'=="Buffalo Steel Company"
replace firmid_1112="31" if `owner_name_virtual'=="Burden Iron Company"
replace firmid_1112="1d" if `owner_name_virtual'=="Burnside Steel Foundry Co."
replace firmid_1112="1d" if `owner_name_virtual'=="Burnside Steel Foundry Company"
replace firmid_1112="luk" if `owner_name_virtual'=="By-Products Steel Corporation"
replace firmid_1112="32" if `owner_name_virtual'=="C. M. Walsh"
replace firmid_1112="33" if `owner_name_virtual'=="Calumet Steel Co."
replace firmid_1112="33" if `owner_name_virtual'=="Calumet Steel Company"
replace firmid_1112="34" if `owner_name_virtual'=="Canonsburg Steel & Iron Works Inc."
replace firmid_1112="34" if `owner_name_virtual'=="Canonsburgh Steel & Iron Works"
replace firmid_1112="35" if `owner_name_virtual'=="Canton Tin Plate Corporation"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Co. of NJ Lessee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Co. of Pa. Carnegie Steel Co. of NJ Lessee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Co. of Pa., Carnegie Steel Co. (of NJ) Leassee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Co., (of NJ) Lessee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (NJ)"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (NJ) lessee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (of N.J.)"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (of N.J.) Lessee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (of NJ)"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (of NJ) Leases"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (of NJ) Lessee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (of New Jersey)"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company (of New Jersey) Leased"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company of N.J."
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie Steel Company, (of NJ) Lessee"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie-Illinios Steel Corporation"
replace firmid_1112="ca" if `owner_name_virtual'=="Carnegie-Illinois Steel Corporation"
replace firmid_1112="cna" if `owner_name_virtual'=="Central Alloy Steel Corporation"
replace firmid_1112="1g" if `owner_name_virtual'=="Central Iron & Steel Co."
replace firmid_1112="1g" if `owner_name_virtual'=="Central Iron & Steel Company"
replace firmid_1112="1g" if `owner_name_virtual'=="Central Iron Steel Co"
replace firmid_1112="1g" if `owner_name_virtual'=="Central Iron and Steel Company"
replace firmid_1112="1h" if `owner_name_virtual'=="Charles W. Tuttle"
replace firmid_1112="1i" if `owner_name_virtual'=="Chicago Railway Equipment Co."
replace firmid_1112="1i" if `owner_name_virtual'=="Chicago Railway Equipment Company"
replace firmid_1112="1k" if `owner_name_virtual'=="Chicago Steel Foundry Company"
replace firmid_1112="1l" if `owner_name_virtual'=="Chrome Steel Corporation"
replace firmid_1112="ca" if `owner_name_virtual'=="Clairton Steel Company (of N.J.) Lessee"
replace firmid_1112="em" if `owner_name_virtual'=="Cleveland"
replace firmid_1112="1m" if `owner_name_virtual'=="Cleveland Hardware Co."
replace firmid_1112="1n" if `owner_name_virtual'=="Cohoes Rolling Mill Co."
replace firmid_1112="co" if `owner_name_virtual'=="Colonial Steel Company"
replace firmid_1112="co" if `owner_name_virtual'=="Columbia Steel Company"
replace firmid_1112="co" if `owner_name_virtual'=="Columbia Steel Corp."
replace firmid_1112="co" if `owner_name_virtual'=="Columbia Steel Corporation"
replace firmid_1112="100" if `owner_name_virtual'=="Columbia Tool Steel Co."
replace firmid_1112="100" if `owner_name_virtual'=="Columbia Tool Steel Company"
replace firmid_1112="101" if `owner_name_virtual'=="Connolly Steel Casting Co."
replace firmid_1112="101" if `owner_name_virtual'=="Connolly Steel Castings Company"
replace firmid_1112="102" if `owner_name_virtual'=="Connors Steel Company"
replace firmid_1112="103" if `owner_name_virtual'=="Continental Can Co. Inc."
replace firmid_1112="103" if `owner_name_virtual'=="Continental Can Co., Inc."
replace firmid_1112="103" if `owner_name_virtual'=="Continental Can Company, Inc."
replace firmid_1112="103" if `owner_name_virtual'=="Continental Can Company, inc."
replace firmid_1112="104" if `owner_name_virtual'=="Continental Roll & Steel Foundry Co."
replace firmid_1112="104" if `owner_name_virtual'=="Continental Roll & Steel Foundry Company"
replace firmid_1112="104" if `owner_name_virtual'=="Continental Roll and Steel Foundry Co."
replace firmid_1112="cs" if `owner_name_virtual'=="Continental STeel Corporation"
replace firmid_1112="cs" if `owner_name_virtual'=="Continental Steel Company"
replace firmid_1112="cs" if `owner_name_virtual'=="Continental Steel Corp."
replace firmid_1112="cs" if `owner_name_virtual'=="Continental Steel Corporation"
replace firmid_1112="cs" if `owner_name_virtual'=="Continental Steel Corporation - Kokomo, Indiana"
replace firmid_1112="cs" if `owner_name_virtual'=="Continental Steel Corporation, Kokomo, Indiana"
replace firmid_1112="cs" if `owner_name_virtual'=="Continental Stele Corp."
replace firmid_1112="105" if `owner_name_virtual'=="Copperweld Steel Co."
replace firmid_1112="105" if `owner_name_virtual'=="Copperweld Steel Company"
replace firmid_1112="106" if `owner_name_virtual'=="Corp W.E. Norck Mgr."
replace firmid_1112="" if `owner_name_virtual'=="Corporation"
replace firmid_1112="122" if `owner_name_virtual'=="Cramp Morris Industrials, Inc."
replace firmid_1112="122" if `owner_name_virtual'=="Cramp-Morris Industries"
replace firmid_1112="cr" if `owner_name_virtual'=="Crucible Steel Casting Company"
replace firmid_1112="cr" if `owner_name_virtual'=="Crucible Steel Co. of America"
replace firmid_1112="cr" if `owner_name_virtual'=="Crucible Steel Company of America"
replace firmid_1112="cr" if `owner_name_virtual'=="Crucible Stel Company of America"
replace firmid_1112="107" if `owner_name_virtual'=="Cyclope Steel Co."
replace firmid_1112="107" if `owner_name_virtual'=="Cyclops Steel Co."
replace firmid_1112="107" if `owner_name_virtual'=="Cyclops Steel Company"
replace firmid_1112="108" if `owner_name_virtual'=="Damascus Steel Casting Co."
replace firmid_1112="108" if `owner_name_virtual'=="Damascus Steel Casting Company"
replace firmid_1112="108" if `owner_name_virtual'=="Damascus Steel Castings Co."
replace firmid_1112="109" if `owner_name_virtual'=="Danville Structure Steel Co."
replace firmid_1112="110" if `owner_name_virtual'=="Davis Bros, Inc."
replace firmid_1112="111" if `owner_name_virtual'=="Dayton Malleable Iron Co."
replace firmid_1112="111" if `owner_name_virtual'=="Dayton Malleable Iron Company"
replace firmid_1112="112" if `owner_name_virtual'=="DeSoto Foundry & Machine Co. Ltd."
replace firmid_1112="113" if `owner_name_virtual'=="DeSoto Foundry Inc"
replace firmid_1112="113" if `owner_name_virtual'=="DeSoto Foundry, Inc."
replace firmid_1112="114" if `owner_name_virtual'=="Deemer Steel Casting Company"
replace firmid_1112="114" if `owner_name_virtual'=="Deemer Steel Castings Company"
replace firmid_1112="115" if `owner_name_virtual'=="Detroit Alloy Steel Co."
replace firmid_1112="115" if `owner_name_virtual'=="Detroit Alloy Steel Company"
replace firmid_1112="116" if `owner_name_virtual'=="Detroit Seamless Steel Tubes Co."
replace firmid_1112="116" if `owner_name_virtual'=="Detroit Seamless Steel Tubes Company"
replace firmid_1112="116" if `owner_name_virtual'=="Detroit Semaless Steel Tubes Company"
replace firmid_1112="117" if `owner_name_virtual'=="Dilworth Porter & Co. Inc."
replace firmid_1112="117" if `owner_name_virtual'=="Driver-Harris Co."
replace firmid_1112="118" if `owner_name_virtual'=="Duquesne Steel Foundry Company"
replace firmid_1112="119" if `owner_name_virtual'=="E. T. Edwards (Owner)"
replace firmid_1112="ww" if `owner_name_virtual'=="E.C. Bowers & C.L. Feldman, Receivers"
replace firmid_1112="120" if `owner_name_virtual'=="E.F. Swigart, Jr.  President"
replace firmid_1112="121" if `owner_name_virtual'=="E.G. Lilly"
replace firmid_1112="123" if `owner_name_virtual'=="E.I. Edwards (owner)"
replace firmid_1112="124" if `owner_name_virtual'=="E.L. Herndon Receiver"
replace firmid_1112="125" if `owner_name_virtual'=="E.M. Mills"
replace firmid_1112="123" if `owner_name_virtual'=="E.T. Edwards (owner)"
replace firmid_1112="126" if `owner_name_virtual'=="Eashburn Wire Company of Delaware"
replace firmid_1112="127" if `owner_name_virtual'=="Eastern Steel Castings"
replace firmid_1112="128" if `owner_name_virtual'=="Eckels Wye Steel Co."
replace firmid_1112="128" if `owner_name_virtual'=="Eckols-Nye Steel Co."
replace firmid_1112="129" if `owner_name_virtual'=="Eddystone Steel Company"
replace firmid_1112="130" if `owner_name_virtual'=="Edgewater Steel Company"
replace firmid_1112="ww" if `owner_name_virtual'=="Edward C. Bowers and Charles L. Feldman, Trustees"
replace firmid_1112="131" if `owner_name_virtual'=="Edward Ehlers"
replace firmid_1112="132" if `owner_name_virtual'=="Eld Metal Co. Ltd."
replace firmid_1112="133" if `owner_name_virtual'=="Electric Steel Castings Co"
replace firmid_1112="133" if `owner_name_virtual'=="Electric Steel Castings Co."
replace firmid_1112="134" if `owner_name_virtual'=="Electric Steel Foundry Co."
replace firmid_1112="134" if `owner_name_virtual'=="Electric Steel Foundry Co. Inc."
replace firmid_1112="134" if `owner_name_virtual'=="Electric Steel Foundry Co., Inc."
replace firmid_1112="134" if `owner_name_virtual'=="Electric Steel Foundry Company"
replace firmid_1112="135" if `owner_name_virtual'=="Electrocast Steel Foundry Co."
replace firmid_1112="135" if `owner_name_virtual'=="Electrocast Steel Foundry Company"
replace firmid_1112="135" if `owner_name_virtual'=="Electrotast Steel Foundry Company"
replace firmid_1112="136" if `owner_name_virtual'=="Ellwood Iron Steel Tube Works"
replace firmid_1112="136" if `owner_name_virtual'=="Ellwood Irvins Steel Tube Works"
replace firmid_1112="136" if `owner_name_virtual'=="Ellwood Ivins Steel Tube Works"
replace firmid_1112="137" if `owner_name_virtual'=="Empire Sheet & Tin Plate Company"
replace firmid_1112="137" if `owner_name_virtual'=="Empire Sheet and Tin Plate Co."
replace firmid_1112="em" if `owner_name_virtual'=="Empire Steel Castings Inc."
replace firmid_1112="em" if `owner_name_virtual'=="Empire Steel Castings, Inc."
replace firmid_1112="em" if `owner_name_virtual'=="Empire Steel Corp"
replace firmid_1112="em" if `owner_name_virtual'=="Empire Steel Corporation"
replace firmid_1112="139" if `owner_name_virtual'=="Erie Forge & Steel Company"
replace firmid_1112="139" if `owner_name_virtual'=="Erie Forge Company"
replace firmid_1112="139" if `owner_name_virtual'=="Erie Forge and Steel Company"
replace firmid_1112="140" if `owner_name_virtual'=="Ewald Iron Co."
replace firmid_1112="141" if `owner_name_virtual'=="Ewald Iron Co. Inc."
replace firmid_1112="141" if `owner_name_virtual'=="Ewald Iron Company"
replace firmid_1112="142" if `owner_name_virtual'=="F.A. Fahrenwald"
replace firmid_1112="142" if `owner_name_virtual'=="F.A. Lange, Jr., President"
replace firmid_1112="143" if `owner_name_virtual'=="Falk (?)"
replace firmid_1112="144" if `owner_name_virtual'=="Farrel-Cheek Steel Foundry Co."
replace firmid_1112="144" if `owner_name_virtual'=="Farrell-Cheek Steel Foundry Co."
replace firmid_1112="145" if `owner_name_virtual'=="Firth Sterling Steel Company"
replace firmid_1112="145" if `owner_name_virtual'=="Firth-Sterling Steel Company"
replace firmid_1112="fo" if `owner_name_virtual'=="Follansbee Bros. Co."
replace firmid_1112="fo" if `owner_name_virtual'=="Follansbee Brothers Company"
replace firmid_1112="fo" if `owner_name_virtual'=="Follensbee Brothers Company"
replace firmid_1112="fo" if `owner_name_virtual'=="Follenshee Brothers Company"
replace firmid_1112="146" if `owner_name_virtual'=="Foote Bros.  Gear and Machine Company"
replace firmid_1112="146" if `owner_name_virtual'=="Foote Bros. Gear and Machine Co."
replace firmid_1112="fd" if `owner_name_virtual'=="Ford Motor Co."
replace firmid_1112="fd" if `owner_name_virtual'=="Ford Motor Company"
replace firmid_1112="147" if `owner_name_virtual'=="Fort Pitt Steel Casting Company"
replace firmid_1112="148" if `owner_name_virtual'=="Frank Hodson and Chas. S. Payson"
replace firmid_1112="148" if `owner_name_virtual'=="Frank Hodson, President"
replace firmid_1112="149" if `owner_name_virtual'=="G. W. Balkwill"
replace firmid_1112="150" if `owner_name_virtual'=="G.B. & N.W. Warman and Associates"
replace firmid_1112="150" if `owner_name_virtual'=="G.B. Warman, N.W. Warman and Associates"
replace firmid_1112="151" if `owner_name_virtual'=="G.D. Berry"
replace firmid_1112="152" if `owner_name_virtual'=="G.W. Armstrong"
replace firmid_1112="153" if `owner_name_virtual'=="General Electric Co"
replace firmid_1112="153" if `owner_name_virtual'=="General Electric Co."
replace firmid_1112="153" if `owner_name_virtual'=="General Electric Company"
replace firmid_1112="153" if `owner_name_virtual'=="General Electric Company  Everett Works"
replace firmid_1112="154" if `owner_name_virtual'=="General Metals Corporation"
replace firmid_1112="155" if `owner_name_virtual'=="General Steel Castings Corporation"
replace firmid_1112="156" if `owner_name_virtual'=="Geo. H. Smith Steel Casting Co."
replace firmid_1112="156" if `owner_name_virtual'=="Geo. H. Smyth Steel Casting Company"
replace firmid_1112="156" if `owner_name_virtual'=="Geo. N Smith Steel Casting Co."
replace firmid_1112="157" if `owner_name_virtual'=="Geo. W. Backwill"
replace firmid_1112="158" if `owner_name_virtual'=="George H. Smith Steel Castings Company"
replace firmid_1112="159" if `owner_name_virtual'=="George W. Armstrong"
replace firmid_1112="160" if `owner_name_virtual'=="Glasgow Iron Company"
replace firmid_1112="161" if `owner_name_virtual'=="Globe Steel Tubes Co."
replace firmid_1112="161" if `owner_name_virtual'=="Globe Steel Tubes Company"
replace firmid_1112="162" if `owner_name_virtual'=="Glover Machine Wks."
replace firmid_1112="162" if `owner_name_virtual'=="Glover Machine Works, Inc"
replace firmid_1112="163" if `owner_name_virtual'=="Granite City Steel Company"
replace firmid_1112="na" if `owner_name_virtual'=="Great Lakes Steel Corporation"
replace firmid_1112="164" if `owner_name_virtual'=="Greene Manufacturing Co., Ltd."
replace firmid_1112="gs" if `owner_name_virtual'=="Grey States Steel Co."
replace firmid_1112="gs" if `owner_name_virtual'=="Gulf States Steel Company"
replace firmid_1112="165" if `owner_name_virtual'=="H.F. Stratton and B.W. Miller"
replace firmid_1112="165" if `owner_name_virtual'=="H.F. Stratton, B.W. Miller"
replace firmid_1112="166" if `owner_name_virtual'=="H.F. Wardwall"
replace firmid_1112="167" if `owner_name_virtual'=="H.W. Wehr, W.E. Wehr, C.F. Wehr, E.R. Wehr"
replace firmid_1112="cr" if `owner_name_virtual'=="Halcomb Steel Company"
replace firmid_1112="168" if `owner_name_virtual'=="Hanford Iron Works, Inc."
replace firmid_1112="169" if `owner_name_virtual'=="Harnischeger Corp."
replace firmid_1112="170" if `owner_name_virtual'=="Harnischfeger Corporation (Steel Foundries)"
replace firmid_1112="171" if `owner_name_virtual'=="Harrisburg Pipe & Pipe Bending Co."
replace firmid_1112="171" if `owner_name_virtual'=="Harrisburg Pipe & Pipe Bending Co.  No. 2 Plant"
replace firmid_1112="171" if `owner_name_virtual'=="Harrisburg Pipe & Pipe Bending Company"
replace firmid_1112="172" if `owner_name_virtual'=="Harrisburg Steel Corporation"
replace firmid_1112="171" if `owner_name_virtual'=="Harrisburgh Pipe & Pipe Bending Co.  No2 Plant"
replace firmid_1112="173" if `owner_name_virtual'=="Hartford Electric Steel Corp."
replace firmid_1112="173" if `owner_name_virtual'=="Hartford Electric Steel Corporation"
replace firmid_1112="174" if `owner_name_virtual'=="Heller Brothers Company - Arthur Heller"
replace firmid_1112="174" if `owner_name_virtual'=="Heller Brothers Steel Works"
replace firmid_1112="175" if `owner_name_virtual'=="Henry Disston & Sons, Inc."
replace firmid_1112="175" if `owner_name_virtual'==`"Henry Disston & Sons, Inc. "Steel Works""'
replace firmid_1112="175" if `owner_name_virtual'=="Henry Disston and Sons, Inc."
replace firmid_1112="175" if `owner_name_virtual'==`"Henry Distton & Sons Inc.  "Steel Works""'
replace firmid_1112="176" if `owner_name_virtual'=="Heppenstall Company"
replace firmid_1112="177" if `owner_name_virtual'=="Hercules Manufacturing Co."
replace firmid_1112="177" if `owner_name_virtual'=="Hercules Mfg. Co."
replace firmid_1112="il" if `owner_name_virtual'=="Illinois Steel Company"
replace firmid_1112="il" if `owner_name_virtual'=="Illinois Steel Company - Carnegie Illinois Steel Company"
replace firmid_1112="il" if `owner_name_virtual'=="Imperial Steel & Disc Co., New Castle Plant"
replace firmid_1112="223" if `owner_name_virtual'=="Inc."
replace firmid_1112="224" if `owner_name_virtual'=="Incorporated"
replace firmid_1112="222" if `owner_name_virtual'=="Indiana Rolling Mill Company"
replace firmid_1112="il" if `owner_name_virtual'=="Indiana Steel Co. Leased by Illinois Steel Co."
replace firmid_1112="il" if `owner_name_virtual'=="Indiana Steel Co. leased by Illinois Steel Co."
replace firmid_1112="il" if `owner_name_virtual'=="Industrial Steel Casting Company"
replace firmid_1112="in" if `owner_name_virtual'=="Inland Steel Co."
replace firmid_1112="in" if `owner_name_virtual'=="Inland Steel Co., of Wisconsin"
replace firmid_1112="in" if `owner_name_virtual'=="Inland Steel Company"
replace firmid_1112="in" if `owner_name_virtual'=="Inland Steel Works"
replace firmid_1112="in" if `owner_name_virtual'=="Inland Steel co. of Wisconsin"
replace firmid_1112="ih" if `owner_name_virtual'=="International Harvester Co."
replace firmid_1112="ih" if `owner_name_virtual'=="International Harvester Company"
replace firmid_1112="cna" if `owner_name_virtual'=="Interstate Iron and Steel Company"
replace firmid_1112="221" if `owner_name_virtual'=="J.J. Walsh"
replace firmid_1112="222" if `owner_name_virtual'=="J.M. Johnson  Pres."
replace firmid_1112="178" if `owner_name_virtual'=="James H. Beans Fdy Co."
replace firmid_1112="178" if `owner_name_virtual'=="James H. Beaus Fdry Co"
replace firmid_1112="179" if `owner_name_virtual'=="Janson Steel & Iron Co."
replace firmid_1112="179" if `owner_name_virtual'=="Janson Steel & Iron Company"
replace firmid_1112="179" if `owner_name_virtual'=="Janson Steel and Iron Company"
replace firmid_1112="220" if `owner_name_virtual'=="Jas. J. Burke, Pres. & General Electric."
replace firmid_1112="180" if `owner_name_virtual'=="Jessop"
replace firmid_1112="180" if `owner_name_virtual'=="Jessop Steel Company"
replace firmid_1112="181" if `owner_name_virtual'=="John A Roebling's Sons Company"
replace firmid_1112="181" if `owner_name_virtual'=="John A. Roebling's Sons Co."
replace firmid_1112="181" if `owner_name_virtual'=="John A. Roeblings Sons Co."
replace firmid_1112="182" if `owner_name_virtual'=="John A. Williams  Jos. A. Tedesco"
replace firmid_1112="182" if `owner_name_virtual'=="John A. Williams & Jos A. Tedesco"
replace firmid_1112="183" if `owner_name_virtual'=="John W. Johnson"
replace firmid_1112="jl" if `owner_name_virtual'=="Jones & Laughlin Steel Corporation"
replace firmid_1112="jl" if `owner_name_virtual'=="Jones and Laughlin Steel Corp."
replace firmid_1112="jl" if `owner_name_virtual'=="Jones and Laughlin Steel Corporation"
replace firmid_1112="184" if `owner_name_virtual'=="Joslyn Manufacturing & Supply Company"
replace firmid_1112="184" if `owner_name_virtual'=="Joslyn Mfg. & Supply Co."
replace firmid_1112="184" if `owner_name_virtual'=="Josylyn MFG & Supply Co"
replace firmid_1112="184" if `owner_name_virtual'=="Joslyn MFG - & Supply Co."
replace firmid_1112="184" if `owner_name_virtual'=="Joslyn Mfg. & Supply Co"
replace firmid_1112="185" if `owner_name_virtual'=="Judson Manufacturing Company"
replace firmid_1112="186" if `owner_name_virtual'=="K.A. Lange, Jr., President"
replace firmid_1112="187" if `owner_name_virtual'=="Kay-Brunner Steel Products Inc."
replace firmid_1112="187" if `owner_name_virtual'=="Kay-Brunner Steel Products, Inc."
replace firmid_1112="188" if `owner_name_virtual'=="Kelley Car Foundry Co."
replace firmid_1112="189" if `owner_name_virtual'=="Kenneth T. Burr"
replace firmid_1112="189" if `owner_name_virtual'=="Kenneth T. Burr, Treasurer"
replace firmid_1112="189" if `owner_name_virtual'=="Kenneth T. Burr, Treasurer & Manager"
replace firmid_1112="300" if `owner_name_virtual'=="Kensington Steel Company"
replace firmid_1112="190" if `owner_name_virtual'=="Keobuck Steel Casting Company"
replace firmid_1112="190" if `owner_name_virtual'=="Keokuk Steel Casting Company"
replace firmid_1112="191" if `owner_name_virtual'=="Keystone Steel & Wire Co."
replace firmid_1112="191" if `owner_name_virtual'=="Keystone Steel & Wire Company"
replace firmid_1112="192" if `owner_name_virtual'=="Kilbly Car & Foundry Co."
replace firmid_1112="192" if `owner_name_virtual'=="Kilby Car & Foundry Co."
replace firmid_1112="192" if `owner_name_virtual'=="Kilby Car & Foundry Company"
replace firmid_1112="193" if `owner_name_virtual'=="Kinite Corp."
replace firmid_1112="193" if `owner_name_virtual'=="Kinite Corporation"
replace firmid_1112="194" if `owner_name_virtual'=="Knoxville Iron Co."
replace firmid_1112="194" if `owner_name_virtual'=="Knoxville Iron Company"
replace firmid_1112="cr" if `owner_name_virtual'=="La Belle Works"
replace firmid_1112="lc" if `owner_name_virtual'=="Laclede Steel Company"
replace firmid_1112="lc" if `owner_name_virtual'=="Laclede Steel Company  Alton Works"
replace firmid_1112="lc" if `owner_name_virtual'=="Laclede Steel Company  Madison Works"
replace firmid_1112="195" if `owner_name_virtual'=="Latex Iron & Steel Works Inc."
replace firmid_1112="196" if `owner_name_virtual'=="Latrobe Electric Steel Co."
replace firmid_1112="196" if `owner_name_virtual'=="Latrobe Electric Steel Company"
replace firmid_1112="197" if `owner_name_virtual'=="Lebanon Steel Foundry"
replace firmid_1112="198" if `owner_name_virtual'=="Lenoir Car Works"
replace firmid_1112="199" if `owner_name_virtual'=="Link Belt Co."
replace firmid_1112="199" if `owner_name_virtual'=="Link Belt Company"
replace firmid_1112="199" if `owner_name_virtual'=="Link-Belt Company"
replace firmid_1112="200" if `owner_name_virtual'=="Lockhart Iron & Steel Co."
replace firmid_1112="200" if `owner_name_virtual'=="Lockhart Iron & Steel Company"
replace firmid_1112="200" if `owner_name_virtual'=="Lockhart Iron and Steel Co."
replace firmid_1112="201" if `owner_name_virtual'=="Logan Iron & Steel Company"
replace firmid_1112="201" if `owner_name_virtual'=="Logan Iron and Steel Company"
replace firmid_1112="202" if `owner_name_virtual'=="Los Angeles Steel Casting Co"
replace firmid_1112="202" if `owner_name_virtual'=="Los Angeles Steel Casting Co. Ltd."
replace firmid_1112="202" if `owner_name_virtual'=="Los Angeles Steel Casting Company, Ltd."
replace firmid_1112="202" if `owner_name_virtual'=="Los Angeles Steel Castings Co. Ltd."
replace firmid_1112="lu" if `owner_name_virtual'=="Ludlum Steel Co"
replace firmid_1112="lu" if `owner_name_virtual'=="Ludlum Steel Co."
replace firmid_1112="luk" if `owner_name_virtual'=="Lukens Steel Company"
replace firmid_1112="203" if `owner_name_virtual'=="Mackintosh - Hemphill Co."
replace firmid_1112="203" if `owner_name_virtual'=="Mackintosh Hemphill Company"
replace firmid_1112="204" if `owner_name_virtual'=="Mackintosh-Hemphill Co."
replace firmid_1112="204" if `owner_name_virtual'=="Malcolm Foundry Co Inc."
replace firmid_1112="204" if `owner_name_virtual'=="Malcolm Foundry Co., Inc."
replace firmid_1112="204" if `owner_name_virtual'=="Malcolm Foundry Company Inc."
replace firmid_1112="205" if `owner_name_virtual'=="Maynard Electric Steel Casting Co."
replace firmid_1112="205" if `owner_name_virtual'=="Maynard Electric Steel Casting Company"
replace firmid_1112="205" if `owner_name_virtual'=="Maynard Electric Steel Castings Co."
replace firmid_1112="206" if `owner_name_virtual'=="McConway & Torley Corporation"
replace firmid_1112="206" if `owner_name_virtual'=="McConway and Torley Corporation"
replace firmid_1112="207" if `owner_name_virtual'=="McInnes Steel Company"
replace firmid_1112="207" if `owner_name_virtual'=="McInnes Steel Company Limited"
replace firmid_1112="208" if `owner_name_virtual'=="McKeesport Tin Plate Co."
replace firmid_1112="208" if `owner_name_virtual'=="McKeesport Tin Plate Company"
replace firmid_1112="209" if `owner_name_virtual'=="McKenna Process Co. of Illinois"
replace firmid_1112="209" if `owner_name_virtual'=="McKenna Process Company of Illinois"
replace firmid_1112="210" if `owner_name_virtual'=="McLouth Steel Corporation"
replace firmid_1112="211" if `owner_name_virtual'=="Mesta Machine Co."
replace firmid_1112="211" if `owner_name_virtual'=="Mesta Machine Company"
replace firmid_1112="212" if `owner_name_virtual'=="Michiana Products Corporation"
replace firmid_1112="213" if `owner_name_virtual'=="Michigan Seamless Tube Co."
replace firmid_1112="213" if `owner_name_virtual'=="Michigan Seamless Tube Coy"
replace firmid_1112="214" if `owner_name_virtual'=="Michigan Steel Casting Co."
replace firmid_1112="214" if `owner_name_virtual'=="Michigan Steel Casting Company"
replace firmid_1112="214" if `owner_name_virtual'=="Michigan Steel Castings Company"
replace firmid_1112="214" if `owner_name_virtual'=="Michigan Steel Corporation"
replace firmid_1112="215" if `owner_name_virtual'=="Millbury Steel Foundry Co."
replace firmid_1112="215" if `owner_name_virtual'=="Milwaukee Steel Foundry Co."
replace firmid_1112="215" if `owner_name_virtual'=="Milwaukee Steel Foundry, Inc."
replace firmid_1112="216" if `owner_name_virtual'=="Minneapolis Electric Steel Castings Co."
replace firmid_1112="216" if `owner_name_virtual'=="Minneapolis Electric Steel Castings Company"
replace firmid_1112="mn" if `owner_name_virtual'=="Minnesota Steel Company"
replace firmid_1112="217" if `owner_name_virtual'=="Missouri Rolling Mill Corporation"
replace firmid_1112="218" if `owner_name_virtual'=="Monarch Foundry & Engineering Corp. Ltd."
replace firmid_1112="219" if `owner_name_virtual'=="Monongahela Iron & Steel Co."
replace firmid_1112="41" if `owner_name_virtual'=="Monroe Steel Castings Co."
replace firmid_1112="41" if `owner_name_virtual'=="Monroe Steel Castings Co.--A Michigan Corporation"
replace firmid_1112="220" if `owner_name_virtual'=="Mountain State Steel Foundries"
replace firmid_1112="221" if `owner_name_virtual'=="Mr A.M. Clark, President"
replace firmid_1112="221" if `owner_name_virtual'=="Mr. Clark"
replace firmid_1112="222" if `owner_name_virtual'=="Mrs. Jane J. Walsh"
replace firmid_1112="cm" if `owner_name_virtual'=="N. & G. Taylor Co"
replace firmid_1112="223" if `owner_name_virtual'=="N.L. Olson"
replace firmid_1112="bk" if `owner_name_virtual'=="National Alloy Steel Company"
replace firmid_1112="224" if `owner_name_virtual'=="National Brake & Electric Co."
replace firmid_1112="224" if `owner_name_virtual'=="National Brake & Electric Co. (National Steel Foundries)"
replace firmid_1112="225" if `owner_name_virtual'=="National Erie Co."
replace firmid_1112="226" if `owner_name_virtual'=="National Forge & Ordnance Company"
replace firmid_1112="226" if `owner_name_virtual'=="National Forge and Ordnance Co."
replace firmid_1112="227" if `owner_name_virtual'=="National Maleable & Steel Castings Company"
replace firmid_1112="227" if `owner_name_virtual'=="National Malleable & Steel Castings Company"
replace firmid_1112="227" if `owner_name_virtual'=="National Malleable and Steel Castings Co."
replace firmid_1112="227" if `owner_name_virtual'=="National Malleable and Steel Castings Company"
replace firmid_1112="na" if `owner_name_virtual'=="National Steel Corporation"
replace firmid_1112="nt" if `owner_name_virtual'=="National Tube Company"
replace firmid_1112="228" if `owner_name_virtual'=="National-Erie Corporation"
replace firmid_1112="228" if `owner_name_virtual'=="National-Erie Corportaion"
replace firmid_1112="229" if `owner_name_virtual'=="Nicetown Plate Washer Co., Inc."
replace firmid_1112="230" if `owner_name_virtual'=="Northern Steel Company"
replace firmid_1112="230" if `owner_name_virtual'=="Northwest Steel Rolling Mills"
replace firmid_1112="230" if `owner_name_virtual'=="Northwest Steel Rolling Mills Inc."
replace firmid_1112="230" if `owner_name_virtual'=="Northwest Steel Rolling Mills, Inc."
replace firmid_1112="231" if `owner_name_virtual'=="Nutmeg Crucible Steel Co"
replace firmid_1112="231" if `owner_name_virtual'=="Nutmeg Crucible Steel Co."
replace firmid_1112="231" if `owner_name_virtual'=="Nutmeg Crucible Steel Company"
replace firmid_1112="232" if `owner_name_virtual'=="Oakland Steel Foundry Co"
replace firmid_1112="232" if `owner_name_virtual'=="Oakland Steel Foundry Co., Inc."
replace firmid_1112="232" if `owner_name_virtual'=="Oakland Steel Foundry Company"
replace firmid_1112="232" if `owner_name_virtual'=="Oakland Steel foundry Company"
replace firmid_1112="233" if `owner_name_virtual'=="Ohio Falls Iron Company"
replace firmid_1112="234" if `owner_name_virtual'=="Ohio Seamless Tube Co."
replace firmid_1112="235" if `owner_name_virtual'=="Ohio Steel Idy Co."
replace firmid_1112="236" if `owner_name_virtual'=="Oklahoma Steel Castings Co."
replace firmid_1112="236" if `owner_name_virtual'=="Oklahoma Steel Castings Company"
replace firmid_1112="237" if `owner_name_virtual'=="Ola A. Arneson"
replace firmid_1112="238" if `owner_name_virtual'=="Old Dominion Iron & Steel Works, Inc."
replace firmid_1112="238" if `owner_name_virtual'=="Old Dominion Iron and Steel Works, Inc."
replace firmid_1112="239" if `owner_name_virtual'=="Ole A. Aruesou"
replace firmid_1112="239" if `owner_name_virtual'=="Ole Arneson"
replace firmid_1112="240" if `owner_name_virtual'=="Olympic Steel Works"
replace firmid_1112="241" if `owner_name_virtual'=="Omaha Steel Works"
replace firmid_1112="be" if `owner_name_virtual'=="Pacific Coast Steel Company"
replace firmid_1112="be" if `owner_name_virtual'=="Pacific Coast Steel Corp."
replace firmid_1112="be" if `owner_name_virtual'=="Pacific Coast Steel Corporation"
replace firmid_1112="242" if `owner_name_virtual'=="Pacific Steel Casting Co."
replace firmid_1112="243" if `owner_name_virtual'=="Page Steel and Wire Co."
replace firmid_1112="cr" if `owner_name_virtual'=="Park Works"
replace firmid_1112="244" if `owner_name_virtual'=="Pelton Steel Casting Company"
replace firmid_1112="245" if `owner_name_virtual'=="Penn Iron & Steel Company"
replace firmid_1112="245" if `owner_name_virtual'=="Penn Iron and Steel Company"
replace firmid_1112="245" if `owner_name_virtual'=="Penn Steel Castings Company"
replace firmid_1112="246" if `owner_name_virtual'=="Penn Steel Castings Corporation"
replace firmid_1112="247" if `owner_name_virtual'=="Pennsylvania Electric Steel Castings"
replace firmid_1112="247" if `owner_name_virtual'=="Pennsylvania Electric Steel Castings Co."
replace firmid_1112="247" if `owner_name_virtual'=="Pennsylvania Electric Steel Castings Company"
replace firmid_1112="247" if `owner_name_virtual'=="Pennsylvania Electrical Steel Casting Company"
replace firmid_1112="248" if `owner_name_virtual'=="Pettibone Mulliken Co."
replace firmid_1112="248" if `owner_name_virtual'=="Pettibone Mulliken Company"
replace firmid_1112="249" if `owner_name_virtual'=="Phoenix  Manufacturing Company"
replace firmid_1112="249" if `owner_name_virtual'=="Phoenix Iron Works"
replace firmid_1112="249" if `owner_name_virtual'=="Phoenix Manufacturers Company"
replace firmid_1112="249" if `owner_name_virtual'=="Phoenix Manufacturing Co."
replace firmid_1112="249" if `owner_name_virtual'=="Phoenix Manufacturing Company"
replace firmid_1112="249" if `owner_name_virtual'=="Phornice Manufacturing Company"
replace firmid_1112="250" if `owner_name_virtual'=="Pine Iron Works Company"
replace firmid_1112="cr" if `owner_name_virtual'=="Pittsburgh Crucible Steel Co."
replace firmid_1112="cr" if `owner_name_virtual'=="Pittsburgh Crucible Steel Company"
replace firmid_1112="251" if `owner_name_virtual'=="Pittsburgh Forge & Iron Co."
replace firmid_1112="ps" if `owner_name_virtual'=="Pittsburgh Steel Co."
replace firmid_1112="ps" if `owner_name_virtual'=="Pittsburgh Steel Company"
replace firmid_1112="ps" if `owner_name_virtual'=="Pittsburgh Steel Foundry Corporation"
replace firmid_1112="ps" if `owner_name_virtual'=="Pittsburgh Steel Products Co."
replace firmid_1112="252" if `owner_name_virtual'=="Plant No. 1-2-5-6-7"
replace firmid_1112="fo" if `owner_name_virtual'=="Pollansbee Brothers Company"
replace firmid_1112="253" if `owner_name_virtual'=="Poncels Nye Steel Co."
replace firmid_1112="254" if `owner_name_virtual'=="Poor & Company"
replace firmid_1112="255" if `owner_name_virtual'=="Pratt and Letchworth Co., Inc."
replace firmid_1112="256" if `owner_name_virtual'=="Quincy Steel Casting Co., Inc."
replace firmid_1112="256" if `owner_name_virtual'=="Quincy Steel Casting Company, Inc."
replace firmid_1112="256" if `owner_name_virtual'=="Quincy Steel Castings Co."
replace firmid_1112="256" if `owner_name_virtual'=="Quincy Steel Castings Co. Inc."
replace firmid_1112="257" if `owner_name_virtual'=="R H Wess"
replace firmid_1112="258" if `owner_name_virtual'=="R.O. Shive"
replace firmid_1112="259" if `owner_name_virtual'=="R.P. Drummond"
replace firmid_1112="259" if `owner_name_virtual'=="R.P.Drummond"
replace firmid_1112="260" if `owner_name_virtual'=="R.W. Wehr, W.E. Wehr, C.F. Wehr, E.R. Wehr"
replace firmid_1112="re" if `owner_name_virtual'=="REpublic Steel Corporartion"
replace firmid_1112="re" if `owner_name_virtual'=="REpublic Steel Corporation"
replace firmid_1112="261" if `owner_name_virtual'=="RO Shine"
replace firmid_1112="262" if `owner_name_virtual'=="Rail Joint Company"
replace firmid_1112="263" if `owner_name_virtual'=="Railway Steel Spring Company"
replace firmid_1112="263" if `owner_name_virtual'=="Railway Steel-Spring Company"
replace firmid_1112="ri" if `owner_name_virtual'=="Reading Iron Company"
replace firmid_1112="ri" if `owner_name_virtual'=="Reading Iron Mills"
replace firmid_1112="264" if `owner_name_virtual'=="Reading-Pratt & Cady Company, Inc."
replace firmid_1112="264" if `owner_name_virtual'=="Reading-Pratt and Cady Company, Inc."
replace firmid_1112="44" if `owner_name_virtual'=="Reed Foundry & Machine Co."
replace firmid_1112="44" if `owner_name_virtual'=="Reed Foundry and Machine Co."
replace firmid_1112="43" if `owner_name_virtual'=="Reliance Steel Casting Company"
replace firmid_1112="re" if `owner_name_virtual'=="Republic Iron & Steel Company"
replace firmid_1112="re" if `owner_name_virtual'=="Republic Iron and Steel Co."
replace firmid_1112="re" if `owner_name_virtual'=="Republic Iron and Steel Company"
replace firmid_1112="re" if `owner_name_virtual'=="Republic Steel Corp"
replace firmid_1112="re" if `owner_name_virtual'=="Republic Steel Corp.  Buffalo Division"
replace firmid_1112="re" if `owner_name_virtual'=="Republic Steel Corporation"
replace firmid_1112="cm" if `owner_name_virtual'=="River"
replace firmid_1112="265" if `owner_name_virtual'=="Riverside Steel Casting Company"
replace firmid_1112="266" if `owner_name_virtual'=="Robert J. Hughes & Wm. H. Hughes"
replace firmid_1112="267" if `owner_name_virtual'=="Rolling Mill"
replace firmid_1112="268" if `owner_name_virtual'=="Rotary Electric Steel Co."
replace firmid_1112="269" if `owner_name_virtual'=="Roxbury Steel Casting Co."
replace firmid_1112="269" if `owner_name_virtual'=="Roxbury Steel Casting Company"
replace firmid_1112="296" if `owner_name_virtual'=="Roxbury Steel Castings Co."
replace firmid_1112="270" if `owner_name_virtual'=="Rustless Iron Corporation of America"
replace firmid_1112="271" if `owner_name_virtual'=="S. Fair & Son"
replace firmid_1112="271" if `owner_name_virtual'=="S. Fair & Son Inc."
replace firmid_1112="271" if `owner_name_virtual'=="S. Fair T... Inc."
replace firmid_1112="271" if `owner_name_virtual'=="S. Fair and Son, Inc."
replace firmid_1112="ac" if `owner_name_virtual'=="S.M. Hazlett, President"
replace firmid_1112="272" if `owner_name_virtual'=="Samuel S Fair & E M Neilly"
replace firmid_1112="272" if `owner_name_virtual'=="Samuel S. Fair and E.M. Mills"
replace firmid_1112="201" if `owner_name_virtual'=="Sane"
replace firmid_1112="202" if `owner_name_virtual'=="Scullin Steel Co"
replace firmid_1112="202" if `owner_name_virtual'=="Scullin Steel Co."
replace firmid_1112="202" if `owner_name_virtual'=="Sculling Steel Company"
replace firmid_1112="35" if `owner_name_virtual'=="See Above"
replace firmid_1112="203" if `owner_name_virtual'=="Sellers Manufacturing Company"
replace firmid_1112="204" if `owner_name_virtual'=="Seneca Iron & Steel Co."
replace firmid_1112="204" if `owner_name_virtual'=="Seneca Iron & Steel Company"
replace firmid_1112="ssh" if `owner_name_virtual'=="Sharon Steel Hoop Co., Sharon, PA"
replace firmid_1112="ssh" if `owner_name_virtual'=="Sharon Steel Hoop Company"
replace firmid_1112="arm" if `owner_name_virtual'=="Sheffield Steel Corporation"
replace firmid_1112="205" if `owner_name_virtual'=="Silver Steel Casting Company"
replace firmid_1112="206" if `owner_name_virtual'=="Simmon Company, New York"
replace firmid_1112="206" if `owner_name_virtual'=="Simmonds Saw and Steel Co."
replace firmid_1112="206" if `owner_name_virtual'=="Simmons Co. of California Inc."
replace firmid_1112="206" if `owner_name_virtual'=="Simmons Company"
replace firmid_1112="206" if `owner_name_virtual'=="Simmons Company of California, Inc."
replace firmid_1112="206" if `owner_name_virtual'=="Simmons Company, New York, NY"
replace firmid_1112="207" if `owner_name_virtual'=="Simonds Saw and Steel Co."
replace firmid_1112="207" if `owner_name_virtual'=="Simonds Saw and Steel Company"
replace firmid_1112="207" if `owner_name_virtual'=="Simonds Sew and Steel Company"
replace firmid_1112="208" if `owner_name_virtual'=="Sivyer Steel Casting Co."
replace firmid_1112="208" if `owner_name_virtual'=="Sivyer Steel Casting Company"
replace firmid_1112="pc" if `owner_name_virtual'=="South San Francisco Plant"
replace firmid_1112="209" if `owner_name_virtual'=="Southern California Iron & Steel Company"
replace firmid_1112="am" if `owner_name_virtual'=="Southern Manganese Steel Co."
replace firmid_1112="210" if `owner_name_virtual'=="Southern Pacific Company"
replace firmid_1112="211" if `owner_name_virtual'=="Spang, Chalfant & Co., Inc."
replace firmid_1112="211" if `owner_name_virtual'=="Spang, Chalfant and Co., Inc."
replace firmid_1112="211" if `owner_name_virtual'=="Spang, Chalfant and Co., Incorporated"
replace firmid_1112="211" if `owner_name_virtual'=="Spang, Chalfant, and Co., Inc."
replace firmid_1112="212" if `owner_name_virtual'=="St. Joseph Electric Steel Castings Co."
replace firmid_1112="213" if `owner_name_virtual'=="St. Louis Screw & Bolt Co."
replace firmid_1112="213" if `owner_name_virtual'=="St. Louis Steel Casting Company"
replace firmid_1112="214" if `owner_name_virtual'=="Standard Alloy Co. Inc."
replace firmid_1112="215" if `owner_name_virtual'=="Standard Electric Steel Castings Co."
replace firmid_1112="216" if `owner_name_virtual'=="Standard Horse Shoe Co."
replace firmid_1112="217" if `owner_name_virtual'=="Standard Steel Works Company"
replace firmid_1112="ot" if `owner_name_virtual'=="Steel Division & Mills Division, Riverside Works"
replace firmid_1112="re" if `owner_name_virtual'=="Steel and Tubes, Inc.  Cleveland, Ohio"
replace firmid_1112="re" if `owner_name_virtual'=="Steel and Tubes, Inc.  Sub-Republic Iron & Steel Co."
replace firmid_1112="re" if `owner_name_virtual'=="Steel and Tubes, Inc. Sub. Republic Steel Corp."
replace firmid_1112="re" if `owner_name_virtual'=="Steel and Tubes, Inc.--Cleveland, Ohio"
replace firmid_1112="218" if `owner_name_virtual'=="Sterling Steel Casting Co."
replace firmid_1112="218" if `owner_name_virtual'=="Sterling Steel Casting Company"
replace firmid_1112="218" if `owner_name_virtual'=="Sterling Steel Foundry Co."
replace firmid_1112="218" if `owner_name_virtual'=="Sterling Steel Foundry Company"
replace firmid_1112="225" if `owner_name_virtual'=="Stock Company"
replace firmid_1112="219" if `owner_name_virtual'=="Stock Company - Corporation"
replace firmid_1112="27" if `owner_name_virtual'=="Stock Corp."
replace firmid_1112="27" if `owner_name_virtual'=="Stock Corporation"
replace firmid_1112="225" if `owner_name_virtual'=="Strong Steel Foundry Company"
replace firmid_1112="cs" if `owner_name_virtual'=="Subsidiary of Continental Steel Corp"
replace firmid_1112="ss" if `owner_name_virtual'=="Superior Steel & Malleable Castings Co."
replace firmid_1112="ss" if `owner_name_virtual'=="Superior Steel Corporation"
replace firmid_1112="ss" if `owner_name_virtual'=="Superior Steel and Malleable Castings Co."
replace firmid_1112="227" if `owner_name_virtual'=="Swedish Crucible Steel Company"
replace firmid_1112="228" if `owner_name_virtual'=="Sweet Steel Company"
replace firmid_1112="228" if `owner_name_virtual'=="Sweet's Steel Company"
replace firmid_1112="205" if `owner_name_virtual'=="Sylvester J. Wabiszewski"
replace firmid_1112="224" if `owner_name_virtual'=="T.H. Steffens Runner"
replace firmid_1112="231" if `owner_name_virtual'=="Taylor Forge and Pipe Works"
replace firmid_1112="230" if `owner_name_virtual'=="Taylor Wharton Iron & Steel Co."
replace firmid_1112="230" if `owner_name_virtual'=="Taylor Wharton Iron and Steel Company"
replace firmid_1112="230" if `owner_name_virtual'=="Taylor-Wharton Iron & Steel Co."
replace firmid_1112="230" if `owner_name_virtual'=="Taylor-Wharton Iron and Steel Company"
replace firmid_1112="tsc" if `owner_name_virtual'=="Tennent Steel Corporation"
replace firmid_1112="tsc" if `owner_name_virtual'=="Tennent Steel Corporation of Oregon"
replace firmid_1112="tn" if `owner_name_virtual'=="Tennessee Coal Iron & RR Co."
replace firmid_1112="tn" if `owner_name_virtual'=="Tennessee Coal, Iron & Railroad Co"
replace firmid_1112="tn" if `owner_name_virtual'=="Tennessee Coal, Iron & Railroad Company"
replace firmid_1112="tn" if `owner_name_virtual'=="Tennessee Coal, Iron and Railroad Company"
replace firmid_1112="tn" if `owner_name_virtual'=="Tennessee Coal, Iron and Railroad Company (Operator)"
replace firmid_1112="232" if `owner_name_virtual'=="Texas Electric Steel Casting Company"
replace firmid_1112="232" if `owner_name_virtual'=="Texas Electric Steel Casting Company, Inc."
replace firmid_1112="232" if `owner_name_virtual'=="Texas Steel Company"
replace firmid_1112="233" if `owner_name_virtual'=="The Alloy Cast Steel Company"
replace firmid_1112="234" if `owner_name_virtual'=="The American Brake Shoe and Foundry Company"
replace firmid_1112="arm" if `owner_name_virtual'=="The American Roling Mill Co."
replace firmid_1112="arm" if `owner_name_virtual'=="The American Rolling Mill Co."
replace firmid_1112="arm" if `owner_name_virtual'=="The American Rolling Mill Company"
replace firmid_1112="arm" if `owner_name_virtual'=="The American rolling Mill Co."
replace firmid_1112="asw" if `owner_name_virtual'=="The American-Swedo Iron Company"
replace firmid_1112="356" if `owner_name_virtual'=="The Andrews Steel Company"
replace firmid_1112="357" if `owner_name_virtual'=="The Atlantic Foundry Co."
replace firmid_1112="352" if `owner_name_virtual'=="The Atlantic Steel Castings Co."
replace firmid_1112="352" if `owner_name_virtual'=="The Atlantic Steel Castings Company"
replace firmid_1112="353" if `owner_name_virtual'=="The BAltimore & Ohio Railroad Company"
replace firmid_1112="351" if `owner_name_virtual'=="The Babcock & Wilcox Tube Company"
replace firmid_1112="351" if `owner_name_virtual'=="The Babcock and Wilcox Tube Co."
replace firmid_1112="354" if `owner_name_virtual'=="The Barclay Company"
replace firmid_1112="bf" if `owner_name_virtual'=="The Bonney Floyd Company"
replace firmid_1112="bf" if `owner_name_virtual'=="The Bonney-FLoyd Company"
replace firmid_1112="bf" if `owner_name_virtual'=="The Bonney-Floyd Company"
replace firmid_1112="bf" if `owner_name_virtual'=="The Bourne-Fuller Company"
replace firmid_1112="355" if `owner_name_virtual'=="The Buckeye Rolling Mill Company"
replace firmid_1112="261" if `owner_name_virtual'=="The Buckeye Steel Castings Co."
replace firmid_1112="261" if `owner_name_virtual'=="The Buckeye Steel Castings Company"
replace firmid_1112="262" if `owner_name_virtual'=="The Burden Iron Company"
replace firmid_1112="262" if `owner_name_virtual'=="The Burden Iron Works"
replace firmid_1112="263" if `owner_name_virtual'=="The Carpenter Steel Company"
replace firmid_1112="259" if `owner_name_virtual'=="The Cincinnati Steel Castings Co"
replace firmid_1112="259" if `owner_name_virtual'=="The Cincinnati Steel Castings Co."
replace firmid_1112="259" if `owner_name_virtual'=="The Cincinnati Steel Castings Co.,"
replace firmid_1112="347" if `owner_name_virtual'=="The Cleveland Alloys Company"
replace firmid_1112="348" if `owner_name_virtual'=="The Cleveland Hardware Company"
replace firmid_1112="col" if `owner_name_virtual'=="The Colorado Fuel and Iron Co."
replace firmid_1112="col" if `owner_name_virtual'=="The Colorado Fuel and Iron Company"
replace firmid_1112="349" if `owner_name_virtual'=="The Cooper Alloy Foundry Co."
replace firmid_1112="cm" if `owner_name_virtual'=="The Corrigan, McKinney Steel Co."
replace firmid_1112="350" if `owner_name_virtual'=="The Crucible Steel Casting Co."
replace firmid_1112="252" if `owner_name_virtual'=="The Dayton Malleable Iron Company, Dayton, Ohio"
replace firmid_1112="252" if `owner_name_virtual'=="The Dayton Steel FOundry Company"
replace firmid_1112="252" if `owner_name_virtual'=="The Dayton Steel Foundry Company"
replace firmid_1112="253" if `owner_name_virtual'=="The Detroit Steel Casting Co."
replace firmid_1112="253" if `owner_name_virtual'=="The Detroit Steel Casting Company"
replace firmid_1112="253" if `owner_name_virtual'=="The Detroit Steel Castings Co."
replace firmid_1112="254" if `owner_name_virtual'=="The Duraloy Co."
replace firmid_1112="254" if `owner_name_virtual'=="The Duraloy Company"
replace firmid_1112="255" if `owner_name_virtual'=="The Eastern Rolling Mill Company"
replace firmid_1112="256" if `owner_name_virtual'=="The Electro-Alloys Company"
replace firmid_1112="257" if `owner_name_virtual'=="The Falk Corp."
replace firmid_1112="257" if `owner_name_virtual'=="The Falk Corporation"
replace firmid_1112="258" if `owner_name_virtual'=="The Forging & Casting Corporation"
replace firmid_1112="249" if `owner_name_virtual'=="The Frog, Switch & Manufacturing Co."
replace firmid_1112="249" if `owner_name_virtual'=="The Frog, Switch & Manufacturing Company"
replace firmid_1112="249" if `owner_name_virtual'=="The Frog, Switch & Mfg. Co."
replace firmid_1112="249" if `owner_name_virtual'=="The Frog, Switch, and Manufacturing Company"
replace firmid_1112="250" if `owner_name_virtual'=="The Gould Coupler Co."
replace firmid_1112="250" if `owner_name_virtual'=="The Gould Coupler Company"
replace firmid_1112="251" if `owner_name_virtual'=="The Harrison Steel Castings Co"
replace firmid_1112="251" if `owner_name_virtual'=="The Harrison Steel Castings Company"
replace firmid_1112="246" if `owner_name_virtual'=="The Hartford Electric Steel Companies"
replace firmid_1112="246" if `owner_name_virtual'=="The Hartford Electric Steel Corporation"
replace firmid_1112="247" if `owner_name_virtual'=="The Highland Iron & Steel Co."
replace firmid_1112="247" if `owner_name_virtual'=="The Highland Iron & Steel Company"
replace firmid_1112="247" if `owner_name_virtual'=="The Highland Iron and Steel Company"
replace firmid_1112="346" if `owner_name_virtual'=="The Industrial Steel Casting Company"
replace firmid_1112="248" if `owner_name_virtual'=="The John Illingworth Steel Co."
replace firmid_1112="248" if `owner_name_virtual'=="The John Illinworth Steel Co."
replace firmid_1112="lo" if `owner_name_virtual'=="The Lorain Steel Company"
replace firmid_1112="345" if `owner_name_virtual'=="The Machined Steel Casting Co."
replace firmid_1112="345" if `owner_name_virtual'=="The Machined Steel Casting Company"
replace firmid_1112="345" if `owner_name_virtual'=="The Machined Steel Castings Co."
replace firmid_1112="340" if `owner_name_virtual'=="The Mahoning Valley Steel Co."
replace firmid_1112="340" if `owner_name_virtual'=="The Mahoning Valley Steel Company"
replace firmid_1112="341" if `owner_name_virtual'=="The Massillon Steel Casting Co."
replace firmid_1112="341" if `owner_name_virtual'=="The Massillon Steel Company"
replace firmid_1112="342" if `owner_name_virtual'=="The Mathews Steel Castings Co."
replace firmid_1112="343" if `owner_name_virtual'=="The McConway & Torley Company"
replace firmid_1112="245" if `owner_name_virtual'=="The Midvale Company"
replace firmid_1112="245" if `owner_name_virtual'=="The Midwale Company"
replace firmid_1112="344" if `owner_name_virtual'=="The Milton Manufacturing Company"
replace firmid_1112="re" if `owner_name_virtual'=="The N & G Taylor Company"
replace firmid_1112="cm" if `owner_name_virtual'=="The N. & G. Taylor Company"
replace firmid_1112="334" if `owner_name_virtual'=="The National Lock Washer Company"
replace firmid_1112="335" if `owner_name_virtual'=="The Newport Rolling Mill Co."
replace firmid_1112="335" if `owner_name_virtual'=="The Newport Rolling Mill Company"
replace firmid_1112="336" if `owner_name_virtual'=="The Newton Steel Company"
replace firmid_1112="337" if `owner_name_virtual'=="The Niles Rolling Mill Company"
replace firmid_1112="338" if `owner_name_virtual'=="The Nugent Steel Castings Co."
replace firmid_1112="339" if `owner_name_virtual'=="The Ohio Seamless Tube Co."
replace firmid_1112="osf" if `owner_name_virtual'=="The Ohio Steel Foundry Co."
replace firmid_1112="osf" if `owner_name_virtual'=="The Ohio Steel Foundry Company"
replace firmid_1112="243" if `owner_name_virtual'=="The Osgood Co"
replace firmid_1112="243" if `owner_name_virtual'=="The Osgood Co."
replace firmid_1112="ot" if `owner_name_virtual'=="The Otis Steel Company"
replace firmid_1112="244" if `owner_name_virtual'=="The Parkersburg Iron & Steel Company"
replace firmid_1112="244" if `owner_name_virtual'=="The Parkersburg Iron and Steel Company"
replace firmid_1112="244" if `owner_name_virtual'=="The Parkersburgh Iron and Steel Company"
replace firmid_1112="331" if `owner_name_virtual'=="The Pelton Steel Casting Co."
replace firmid_1112="332" if `owner_name_virtual'=="The Phoenix Iron Company"
replace firmid_1112="333" if `owner_name_virtual'=="The Pollack Steel Company"
replace firmid_1112="333" if `owner_name_virtual'=="The Pollak Steel Co."
replace firmid_1112="333" if `owner_name_virtual'=="The Pollak Steel Company"
replace firmid_1112="325" if `owner_name_virtual'=="The Rail Joint Co."
replace firmid_1112="325" if `owner_name_virtual'=="The Rail Joint Company"
replace firmid_1112="326" if `owner_name_virtual'=="The Reeves Manufacturing Co."
replace firmid_1112="326" if `owner_name_virtual'=="The Reeves Manufacturing Company"
replace firmid_1112="327" if `owner_name_virtual'=="The Rockaway Rolling Mill"
replace firmid_1112="328" if `owner_name_virtual'=="The Roxbury Steel Casting Co"
replace firmid_1112="328" if `owner_name_virtual'=="The Sawbrook Steel Castings Co."
replace firmid_1112="328" if `owner_name_virtual'=="The Sawbrook Steel Castings Company"
replace firmid_1112="329" if `owner_name_virtual'=="The Simmons Company"
replace firmid_1112="330" if `owner_name_virtual'=="The Stanley Works"
replace firmid_1112="cs" if `owner_name_virtual'=="The Superior Sheet Steel Company"
replace firmid_1112="322" if `owner_name_virtual'=="The Timken Roller Bearing Co."
replace firmid_1112="322" if `owner_name_virtual'=="The Timken Roller Bearing Company"
replace firmid_1112="322" if `owner_name_virtual'=="The Timkern Roller Bearing Co."
replace firmid_1112="323" if `owner_name_virtual'=="The Toledo Steel Casting Co."
replace firmid_1112="324" if `owner_name_virtual'=="The West Steel Casting Co."
replace firmid_1112="320" if `owner_name_virtual'=="The West Virginia Rail Co."
replace firmid_1112="320" if `owner_name_virtual'=="The West Virginia Rail Company"
replace firmid_1112="321" if `owner_name_virtual'=="The Wyoming Shovel Works"
replace firmid_1112="yo" if `owner_name_virtual'=="The Youngston Sheet and Tube Company"
replace firmid_1112="yo" if `owner_name_virtual'=="The Youngstown Sheet and Tube Company"
replace firmid_1112="yo" if `owner_name_virtual'=="The Youngstown Steel and Tube Company"
replace firmid_1112="317" if `owner_name_virtual'=="Thos. H. Shartle, President"
replace firmid_1112="318" if `owner_name_virtual'=="Tidewater Rolling Mill, Inc."
replace firmid_1112="319" if `owner_name_virtual'=="Toledo Steel Casting Co."
replace firmid_1112="303" if `owner_name_virtual'=="Tonawanda Electric Steel Casting Co."
replace firmid_1112="303" if `owner_name_virtual'=="Tonawanda Electric Steel Casting Company"
replace firmid_1112="303" if `owner_name_virtual'=="Tonawanda Electric Steel Casting Corp."
replace firmid_1112="304" if `owner_name_virtual'=="Tradegar Company"
replace firmid_1112="315" if `owner_name_virtual'=="Treadwell Engineering Comapny"
replace firmid_1112="315" if `owner_name_virtual'=="Treadwell Engineering Company"
replace firmid_1112="304" if `owner_name_virtual'=="Tredegar Company"
replace firmid_1112="314" if `owner_name_virtual'=="Trojan Electric Steel Co."
replace firmid_1112="fo" if `owner_name_virtual'=="Trustees of Folansbee Bros. Co."
replace firmid_1112="fo" if `owner_name_virtual'=="Trustees of Follansbee Brothers Company"
replace firmid_1112="224" if `owner_name_virtual'=="Tulsa Rolling Mills Co."
replace firmid_1112="313" if `owner_name_virtual'=="Twin City Forge & Foundry Company"
replace firmid_1112="310" if `owner_name_virtual'=="U.S. Foundries Inc."
replace firmid_1112="310" if `owner_name_virtual'=="U.S. Foundries, Inc."
replace firmid_1112="311" if `owner_name_virtual'=="UNiversal Steel Company"
replace firmid_1112="312" if `owner_name_virtual'=="Ulster Iron Works"
replace firmid_1112="309" if `owner_name_virtual'=="Union Electric Steel Corp."
replace firmid_1112="309" if `owner_name_virtual'=="Union Electric Steel Corporation"
replace firmid_1112="bk" if `owner_name_virtual'=="Union Steel Casting Co."
replace firmid_1112="bk" if `owner_name_virtual'=="Union Steel Castings Company"
replace firmid_1112="308" if `owner_name_virtual'=="United Eng. & Fdry. Co., Pgh. Pa."
replace firmid_1112="308" if `owner_name_virtual'=="United Engineering and Foundry Co."
replace firmid_1112="308" if `owner_name_virtual'=="United Engineering and Foundry Company"
replace firmid_1112="308" if `owner_name_virtual'=="United Engineering and Foundry Company, Pittsburgh, PA"
replace firmid_1112="bk" if `owner_name_virtual'=="Universal Steel Co."
replace firmid_1112="bk" if `owner_name_virtual'=="Universal Steel Company"
replace firmid_1112="308" if `owner_name_virtual'=="Utility Trailer Manufacturing Company"
replace firmid_1112="275" if `owner_name_virtual'=="V.G. Honstain"
replace firmid_1112="264" if `owner_name_virtual'=="Vanadium Alloy Steel Co."
replace firmid_1112="264" if `owner_name_virtual'=="Vanadium Alloys Steel Company"
replace firmid_1112="264" if `owner_name_virtual'=="Vanadium-Alloys Steel Company"
replace firmid_1112="265" if `owner_name_virtual'=="Vulcan Crucible Steel Co."
replace firmid_1112="265" if `owner_name_virtual'=="Vulcan Crucible Steel Company"
replace firmid_1112="266" if `owner_name_virtual'=="Vulcan Iron Works"
replace firmid_1112="267" if `owner_name_virtual'=="W. A. Ames Co."
replace firmid_1112="267" if `owner_name_virtual'=="W. Ames & Co."
replace firmid_1112="267" if `owner_name_virtual'=="W. Ames and Co."
replace firmid_1112="113" if `owner_name_virtual'=="W.C. Nabors, Receiver"
replace firmid_1112="304" if `owner_name_virtual'=="W.E. Wehr, H.W. Wehr, E.R. Wehr, C.F. Wehr"
replace firmid_1112="305" if `owner_name_virtual'=="W.H. Davey"
replace firmid_1112="306" if `owner_name_virtual'=="W.K. Henderson"
replace firmid_1112="268" if `owner_name_virtual'=="Wareham Manufacturing Co."
replace firmid_1112="268" if `owner_name_virtual'=="Wareham Manufacturing Co., Inc."
replace firmid_1112="268" if `owner_name_virtual'=="Wareham Manufacturing Company"
replace firmid_1112="268" if `owner_name_virtual'=="Warman Steel Casting Company"
replace firmid_1112="269" if `owner_name_virtual'=="Warman Steel Casting Company, Ltd."
replace firmid_1112="269" if `owner_name_virtual'=="Warman Steel Castings Co."
replace firmid_1112="270" if `owner_name_virtual'=="Washburn Wire Co. (a Delaware corporation)"
replace firmid_1112="270" if `owner_name_virtual'=="Washburn Wire Company of Delaware"
replace firmid_1112="271" if `owner_name_virtual'=="Washington Tin Plate Company"
replace firmid_1112="272" if `owner_name_virtual'=="Washurn Wire Company of Rhode Island"
replace firmid_1112="273" if `owner_name_virtual'=="Weatherly Steel Castings Co."
replace firmid_1112="273" if `owner_name_virtual'=="Weatherly  Steel Castings Company"
replace firmid_1112="274" if `owner_name_virtual'=="Wehe Steel Co."
replace firmid_1112="na" if `owner_name_virtual'=="Weirton Steel Company"
replace firmid_1112="237" if `owner_name_virtual'=="West Leechburg Steel Company"
replace firmid_1112="237" if `owner_name_virtual'=="West Leechburgh Steel Company"
replace firmid_1112="235" if `owner_name_virtual'=="West Michigan Steel Foundry Co"
replace firmid_1112="235" if `owner_name_virtual'=="West Michigan Steel Foundry Co."
replace firmid_1112="235" if `owner_name_virtual'=="West Michigan Steel Foundry Company"
replace firmid_1112="236" if `owner_name_virtual'=="Western Alloyed Steel Casting Co."
replace firmid_1112="275" if `owner_name_virtual'=="Western Crucible Steel Casting Co."
replace firmid_1112="220" if `owner_name_virtual'=="Western Steel Casting Co."
replace firmid_1112="220" if `owner_name_virtual'=="Western Steel Casting Co. of Oregon"
replace firmid_1112="220" if `owner_name_virtual'=="Western Steel Casting Company"
replace firmid_1112="220" if `owner_name_virtual'=="Western Steel Casting Company of Oregon"
replace firmid_1112="276" if `owner_name_virtual'=="Westlectric Castings, Inc."
replace firmid_1112="277" if `owner_name_virtual'=="Westson Steel Casting Company"
replace firmid_1112="278" if `owner_name_virtual'=="Wheeling Mold & Foundry Co."
replace firmid_1112="wh" if `owner_name_virtual'=="Wheeling Steel Company"
replace firmid_1112="wh" if `owner_name_virtual'=="Wheeling Steel Corporation"
replace firmid_1112="ww" if `owner_name_virtual'=="Wickwin Brothers"
replace firmid_1112="ww" if `owner_name_virtual'=="Wickwire Brothers"
replace firmid_1112="ww" if `owner_name_virtual'=="Wickwire Brothers Inc."
replace firmid_1112="ww" if `owner_name_virtual'=="Wickwire Brothers, Inc."
replace firmid_1112="242" if `owner_name_virtual'=="Witherow Steel Corporation"
replace firmid_1112="241" if `owner_name_virtual'=="Worth Steel Company"
replace firmid_1112="238" if `owner_name_virtual'=="Wrought Iron Co of America"
replace firmid_1112="238" if `owner_name_virtual'=="Wrought Iron Co. of America"
replace firmid_1112="238" if `owner_name_virtual'=="Wrought Iron Company"
replace firmid_1112="238" if `owner_name_virtual'=="Wrought Iron Company of America  Rome Plant"
replace firmid_1112="amb" if `owner_name_virtual'=="Yes"
replace firmid_1112="239" if `owner_name_virtual'=="Youngstown Alloy Casting Corp."
replace firmid_1112="240" if `owner_name_virtual'=="Zimmerman Steel Co."
replace firmid_1112="218" if `owner_name_virtual'=="a corporation"
replace firmid_1112="128" if `owner_name_virtual'=="as above"
replace firmid_1112="1k" if `owner_name_virtual'=="corporation"
replace firmid_1112="300" if `owner_name_virtual'=="incorporated"
replace firmid_1112="225" if `owner_name_virtual'=="national Erie Corp."
replace firmid_1112="ps" if `owner_name_virtual'=="same"
replace firmid_1112="303" if `owner_name_virtual'=="stockholdrs--L.J. Fitzpatrick, R.C. Towne, H.M. Lewis"
