//Cleaning script for BR "B" spreadsheet: 803_1935. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/803"
import excel "`data_dir'/080335B0.xls", allstring sheet("080335B0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""
capture drop C //Column name in spreadsheet: plntname
capture drop D //Column name in spreadsheet: ownrname
capture drop E //Column name in spreadsheet: state
capture drop F //Column name in spreadsheet: county
capture drop G //Column name in spreadsheet: tothp
capture drop H //Column name in spreadsheet: tothp2

capture rename I hp001gn
capture rename J hp001gh
capture rename K hp001gk
capture rename L hp001on
capture rename M hp001oh

capture rename N hp002gn
capture rename O hp002gh
capture rename P hp002gk
capture rename Q hp002on
capture rename R hp002oh

capture rename S hp005gn
capture rename T hp005gh
capture rename U hp005gk
capture rename V hp005on
capture rename W hp005oh

capture rename X hp006gn
capture rename Y hp006gh
capture rename Z hp006gk
capture rename AA hp006on
capture rename AB hp006oh

capture rename AC hp004gn
capture rename AD hp004gh
capture rename AE hp004gk
capture rename AF hp004on
capture rename AG hp004oh

capture drop AH
capture drop AI
capture drop AJ
capture drop AK
capture drop AL
capture drop AM

rename AN he001n //Column name in spreadsheet: 
rename AO he001h //Column name in spreadsheet: 
rename AP he002n //Column name in spreadsheet: 
rename AQ he002h //Column name in spreadsheet: 

//rename fuel variables
capture rename AR ff001q
capture rename AS ff00v1
capture rename AT ff002q
capture rename AU ff002v
capture rename AV ff003q
capture rename AW ff003v
capture rename AX ff004q
capture rename AY ff004v
capture rename AZ ff005q
capture rename BA ff005v
capture rename BB ff006q
capture rename BC cff006v
capture rename BD ff007q
capture rename BE ff007v
capture drop BF //Column name in spreadsheet: chk
capture rename BG total_fuel_value
capture drop BH //Column name in spreadsheet: diff1
capture drop BI //Column name in spreadsheet: electric_e
capture drop BJ //Column name in spreadsheet: electric_e
capture drop BK //Column name in spreadsheet: electric_e

//rename input variables
capture rename BL j_v_crude_rubber
capture rename BM j_q_crude_rubber
capture rename BN j_v_reclaimed_rubber1
capture rename BO j_q_reclaimed_rubber1
capture rename BP j_v_reclaimed_rubber2
capture rename BQ j_q_reclaimed_rubber2
capture drop BR //Column name in spreadsheet: **_fnlbgnd
capture drop BS //Column name in spreadsheet: fnlenddt
capture drop BT //Column name in spreadsheet: remark01
capture drop BU //Column name in spreadsheet: remark02
capture drop BV //Column name in spreadsheet: remark03
capture drop BW //Column name in spreadsheet: remark04
capture drop BX //Column name in spreadsheet: remark05
capture drop BY //Column name in spreadsheet: remark06
capture drop BZ //Column name in spreadsheet: remark07
capture drop CA //Column name in spreadsheet: remark08
capture drop CB //Column name in spreadsheet: remark09
capture drop CC //Column name in spreadsheet: remark10
capture drop CD //Column name in spreadsheet: remark11
capture drop CE //Column name in spreadsheet: ca01info
capture drop CF //Column name in spreadsheet: ca01
capture drop CG //Column name in spreadsheet: ca02info
capture drop CH //Column name in spreadsheet: ca02
capture drop CI //Column name in spreadsheet: ca03info
capture drop CJ //Column name in spreadsheet: ca03
capture drop CK //Column name in spreadsheet: ca04info
capture drop CL //Column name in spreadsheet: ca04
capture drop CM //Column name in spreadsheet: ca05info
capture drop CN //Column name in spreadsheet: ca05
capture drop CO //Column name in spreadsheet: ca06info
capture drop CP //Column name in spreadsheet: ca06
capture drop CQ //Column name in spreadsheet: ca07info
capture drop CR //Column name in spreadsheet: ca07
capture drop CS //Column name in spreadsheet: ca08info
capture drop CT //Column name in spreadsheet: ca08
capture drop CU //Column name in spreadsheet: ca09info
capture drop CV //Column name in spreadsheet: ca09
capture drop CW //Column name in spreadsheet: ca10info
capture drop CX //Column name in spreadsheet: ca10
capture drop CY //Column name in spreadsheet: ca11info
capture drop CZ //Column name in spreadsheet: ca11
capture drop DA //Column name in spreadsheet: ca12info
capture drop DB //Column name in spreadsheet: ca12
capture drop DC //Column name in spreadsheet: ca13info
capture drop DD //Column name in spreadsheet: ca13
capture drop DE //Column name in spreadsheet: ca14info
capture drop DF //Column name in spreadsheet: ca14
capture drop DG //Column name in spreadsheet: ca15info
capture drop DH //Column name in spreadsheet: ca15
capture drop DI //Column name in spreadsheet: ca16info
capture drop DJ //Column name in spreadsheet: ca16
capture drop DK //Column name in spreadsheet: ca17info
capture drop DL //Column name in spreadsheet: ca17
capture drop DM //Column name in spreadsheet: ca18info
capture drop DN //Column name in spreadsheet: ca18
capture drop DO //Column name in spreadsheet: ca19info
capture drop DP //Column name in spreadsheet: ca19
capture drop DQ //Column name in spreadsheet: ca20info
capture drop DR //Column name in spreadsheet: ca20
capture drop DS //Column name in spreadsheet: ca21info
capture drop DT //Column name in spreadsheet: ca21
capture drop DU //Column name in spreadsheet: ca22info
capture drop DV //Column name in spreadsheet: ca22
capture drop DW //Column name in spreadsheet: ca23info
capture drop DX //Column name in spreadsheet: ca23'

save "$rootDir_dataBR/1935/803/803_1935_clean_B", replace
