//Cleaning script for BR spreadsheet: 1008_1935. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/1008"
import excel "`data_dir'/100835A1_PDSPL.xls", allstring sheet("100835A1") clear

drop in 1/2 //this row is variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indarea
capture rename K indnm
capture rename L formnm
capture rename M how_many_p
capture rename N plntname
capture rename O ownrname
capture rename P a003
capture rename Q ctlotryn
capture rename R a004
capture rename S state
capture rename T city
capture rename U county
capture rename V street
capture rename W othraddr
capture rename X incityyn
capture rename Y sbsdryyn
capture rename Z mthrinfo
capture rename AA nmchngyn
capture rename AB lnchngyn
capture rename AC owchngyn
capture rename AD bschngyn
capture rename AE frmrinfo
capture rename AF products
capture rename AG mtlsusd1
capture rename AH mtlsusd2

//rename utilization variables
capture rename AI d001
capture rename AJ d008
capture rename AK d004
capture rename AL d006

//rename employment variables
capture rename AM a_propriet
capture rename AN b_salaried
capture rename AO offcslry
capture rename AP c_supervis
capture rename AQ e003tas
capture rename AR d_technica
capture rename AS techwgs
capture rename AT cmar
capture rename AU cjun
capture rename AV csep
capture rename AW cdec
capture rename AX e003tcs
capture rename AY number
capture rename AZ wages4
capture drop BA
capture drop BB
capture drop BC //diff
capture drop BD //diff1
capture drop BE //salry/non-

//rename wage earners variables
capture rename BF wejannm
capture rename BG wemaynm
capture rename BH wesepnm
capture rename BI wefebnm
capture rename BJ wejunnm
capture rename BK weoctnm
capture rename BL wemarnm
capture rename BM wejulnm
capture rename BN wenovnm
capture rename BO weaprnm
capture rename BP weaugnm
capture rename BQ wedecnm
capture drop BR
capture rename BS wetotlnm
capture rename BT diff2
capture rename BU e005s
capture rename BV e005sp
capture drop BW

capture drop BX //xm1
capture drop BY //xm1wenm
capture drop BZ //xm3
capture drop CA //xm3wenm
capture drop CB //xm5
capture drop CC //xm5wenm
capture drop CD //xm2
capture drop CE //xm2wenm
capture drop CF //xm4
capture drop CG //xm4wenm
capture drop CH //xm6
capture drop CI //xm6wenm

//rename manhours variables
capture rename CJ emh01
capture rename CK emh02
capture rename CL emh03
capture rename CM emh04
capture rename CN emh05
capture rename CO emh06
capture rename CP emh07
capture rename CQ emh08
capture rename CR emh09
capture rename CS emh10
capture rename CT emh11
capture rename CU emh12
capture rename CV emht
capture drop CW
capture drop CX //diff3

//rename costs of inputs variables
capture rename CY f001
capture rename CZ f002
capture rename DA f003
//CZV I have no idea what this column is. It doesn't seem to actually be on the form for the sample I checked
capture rename DB cost_of_co
capture drop DC
capture rename DD f009
capture rename DE f004
capture drop DF //diff4
capture drop DG
capture drop DH

//rename output variables
capture rename DI gp_q_plateglass
capture rename DJ gp_q_plateglass_rough
capture rename DK gp_v_plateglass_rough
capture drop DL
capture rename DM gp_q_plateglass_polished
capture rename DN gp_v_plateglass_polished
capture drop DO
capture rename DP gp_q_glass_laminated
capture rename DQ gp_v_glass_laminated
capture drop DR
capture rename DS gp_q_glass_otherlaminated
capture rename DT gp_v_glass_otherlaminated
capture drop DU
capture rename DV gp_q_glass_window
capture rename DW gp_v_glass_window
capture drop DX
capture rename DY 
capture rename DZ gp_q_glass_obscured 
capture rename EA gp_v_glass_obscured
capture rename EB gp_q_wireglass_rough 
capture rename EC gp_v_wireglass_rough
capture rename ED gp_q_wireglass_polished 
capture rename EE gp_v_wireglass_polished
capture drop EF
capture rename EG gp_v_buildingglass_other
capture rename EH gp_q_spectacleglass 
capture rename EI gp_v_spectacleglass
capture rename EJ gp_q_tumbler_machinemade 
capture rename EK gp_v_tumbler_machinemade
capture rename EL gp_q_other_machinemade 
capture rename EM gp_v_other_machinemade
capture rename EN gp_q_tumbler_handmade_pressed 
capture rename EO gp_v_tumbler_handmade_pressed
capture rename EP gp_q_other_handmade_pressed 
capture rename EQ gp_v_other_handmade_pressed
capture rename ER gp_q_tumbler_handmade_blown 
capture rename ES gp_v_tumbler_handmade_blown
capture rename ET gp_q_other_handmade_blown 
capture rename EU gp_v_other_handmade_blown
capture rename EV gp_q_lighting_bulb 
capture rename EW gp_v_lighting_bulb
capture drop EX
capture rename EY gp_v_lighting_shade
capture rename EZ gp_q_lighting_chimney
capture rename FA gp_v_lighting_chimney
capture rename FB gp_q_lantern_globe 
capture rename FC gp_v_lantern_globe
capture rename FD gp_q_lamp 
capture rename FE gp_v_lamp
capture rename FG gp_q_lighting_other
capture rename FG gp_v_lighting_other
capture rename FH gp_q_lenses_motor
capture rename FI gp_v_lenses_motor
capture rename FJ gp_q_lenses_other
capture rename FK gp_v_lenses_other
capture rename FL gp_q_technicalglass_tubing
capture rename FM gp_v_technicalglass_tubing
capture rename FN gp_v_technicalglass_insulator
capture rename FO gp_v_technicalglass_other
capture rename FP gp_v_otherglass_pressed
capture rename FQ gp_q_milkbottles
capture rename FR gp_v_milkbottles
capture rename FS gp_q_container_narrowneck
capture rename FT gp_v_container_narrowneck
capture rename FU gp_q_container_widemouth
capture rename FV gp_v_container_widemouth
capture rename FW gp_q_container_pressed
capture rename FX gp_v_container_pressed
capture rename FY gp_q_container_fruitjar
capture rename FZ gp_v_container_fruitjar
capture rename GA gp_q_container_jellyglass
capture rename GB gp_v_container_jellyglass
capture rename GC gp_q_container_beerbottle
capture rename GD gp_v_container_beerbottle
capture rename GE gp_q_container_liquorware
capture rename GF gp_v_container_liquorware
capture rename GG gp_q_container_otherware
capture rename GH gp_v_container_otherware
capture rename GI gp_q_container_medicinal
capture rename GJ gp_v_container_medicinal
capture rename GK gp_q_container_generalpurpose
capture rename GL gp_v_container_generalpurpose
capture rename GM gp_v_otherglass
capture rename GN gp_v_allother
capture rename GO receipt_electricity
capture rename GP receipt_contract

replace record = "me0100" if ownrname=="Pittsburgh Plate Glass Co." & record=="me0110"	//fix a mistake in an identifier
replace record = "me0064" if record=="Me0064"	//Typo

save "$rootDir_dataBR/1935/1008/1008_1935", replace

//now clean B spreadsheets
do "$rootDir_code/1935/clean_1008_1935_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1935/1008/1008_1935", replace
merge 1:1 record using "$rootDir_dataBR/1935/1008/1008_1935_clean_B", nogen

capture drop year
gen year = 1935
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace

save "$rootDir_dataBR/1935/1008/1008_1935", replace
