//Cleaning script for BR spreadsheet: 705_1935. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/705"
import excel "`data_dir'/070535A0_PDSPL.xls", allstring sheet("070535A0") clear

drop in 1/2 //these rows are blank and then ahve variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indarea
capture rename K indnm
capture rename L formnm
capture rename M a_plntname
capture rename N b_ownrname
capture rename O incyn
capture rename P ctlotryn
capture rename Q a004
capture rename R state
capture rename S city
capture rename T f_county
capture rename U street
capture rename V h_othraddr
capture rename W i_incityyn
capture rename X j_sbsdryyn
capture rename Y mthrinfo
capture rename Z k_nmchngyn
capture rename AA lnchngyn
capture rename AB owchngyn
capture rename AC bschngyn
capture rename AD frmrinfo
capture rename AE a_products
capture rename AF b_mtlsusd1
capture rename AG mtlsusd2

//rename utilization variables
capture rename AH d001
capture rename AI d008
capture rename AJ d004
capture rename AK d006

//rename employment variables
capture rename AL a_propriet
capture rename AM b_salaried
capture rename AN soffcwgs
capture rename AO c_supervis
capture rename AP e003tas
capture rename AQ d_technica
capture rename AR techwgs
capture rename AS cmar
capture rename AT cjun
capture rename AU csep
capture rename AV cdec
capture rename AW cwgs
capture drop AX
capture drop AY
capture rename AZ nonwewgm
capture rename BA nonwewgs

//rename wage earners variables 
capture rename BB wejannm
capture rename BC wemaynm
capture rename BD wesepnm
capture rename BE wefebnm
capture rename BF wejunnm
capture rename BG weoctnm
capture rename BH wemarnm
capture rename BI wejulnm
capture rename BJ wenovnm
capture rename BK weaprnm
capture rename BL weaugnm
capture rename BM wedecnm
capture drop BN
capture rename BO wetotlnm
capture rename BP e005s
capture rename BQ e005sp

capture drop BR //xm1
capture drop BS //xm1wenm
capture drop BT //xm3
capture drop BU //xm3wenm
capture drop BV //xm5
capture drop BW //xm5wenm
capture drop BX //xm2
capture drop BY //xm2wenm
capture drop BZ //xm4
capture drop CA //xm4wenm
capture drop CB //xm6
capture drop CC //xm6wenm

//rename manhours variables
capture rename CD emh01
capture rename CE emh02
capture rename CF emh03
capture rename CG emh04
capture rename CH emh05
capture rename CI emh06
capture rename CJ emh07
capture rename CK emh08
capture rename CL emh09
capture rename CM emh10
capture rename CN emh11
capture rename CO emh12
capture drop CP
capture rename CQ emht

//rename costs of inputs variables
capture rename CR f001
capture rename CS f002
capture rename CT f003
capture drop CU
capture rename CV f009
capture rename CW f004

//rename output variables
capture rename CX gp_q_gasoline
capture rename CY gp_v_gasoline
capture rename CZ gp_q_naphtha
capture rename DA gp_v_naphtha
capture rename DB gp_q_benzine
capture rename DC gp_v_benzine
capture rename DD gp_q_tops
capture rename DE gp_v_tops
capture rename DF gp_q_illuminating_oil
capture rename DG gp_v_illuminating_oil
capture rename DH gp_q_distillate
capture rename DI gp_v_distillate
capture rename DJ gp_q_gas_oils
capture rename DK gp_v_gas_oils
capture rename DL gp_q_residual_fuel_oils
capture rename DM gp_v_residual_fuel_oils
capture rename DN gp_q_above_fuel_oil
capture rename DO gp_v_above_fuel_oil
capture rename DP gp_q_at_fuel_oil
capture rename DQ gp_v_at_fuel_oil
capture rename DR gp_q_below_fuel_oil
capture rename DS gp_v_below_fuel_oil
capture rename DT gp_q_red_neutral_pale_parrafin
capture rename DU gp_v_red_neutral_pale_parrafin
capture rename DV gp_q_black_lubricating_oil
capture rename DW gp_v_black_lubricating_oil
capture drop DX 
capture rename DY gp_q_all_other_lubricating_oil
capture rename DZ gp_v_all_other_lubricating_oil
capture rename EA gp_q_liquid_asphalt
capture rename EB gp_v_liquid_asphalt
capture rename EC gp_q_residuum_or_tar
capture rename ED gp_v_residuum_or_tar
capture rename EE gp_q_axle_grease
capture rename EF gp_v_axle_grease
capture rename EG gp_q_paraffin_wax
capture rename EH gp_v_paraffin_wax
capture rename EI gp_q_acid_oil
capture rename EJ gp_v_acid_oil
capture rename EK gp_q_asphalt_other
capture rename EL gp_v_asphalt_other
capture rename EM gp_q_coke
capture rename EN gp_v_coke
capture rename EO gp_q_reclaimed_acid
capture rename EP gp_v_reclaimed_acid
capture rename EQ gp_q_candles
capture rename ER gp_v_candles
capture rename ES gp_q_insecticides
capture rename ET gp_v_insecticides
capture rename EU gp_q_otherRefinery1
capture rename EV gp_v_otherRefinery1
capture rename EW gp_v_allother
capture rename EX energy_sold
capture rename EY receipts_for_contract_work

save "$rootDir_dataBR/1935/705/705_1935", replace

//now clean B spreadsheets
do "$rootDir_code/1935/clean_705_1935_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1935/705/705_1935", replace
merge 1:1 record using "$rootDir_dataBR/1935/705/705_1935_clean_B"
//this should really be a 1-1 mapping
drop _merge

capture drop year
gen year = 1935
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"

//tostring all variables for consistent appending later
tostring *, replace

save "$rootDir_dataBR/1935/705/705_1935", replace
