//Cleaning script for BR "B" spreadsheet: 237_1935. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/237"
import excel "`data_dir'/023735B0.xls", allstring sheet("023735B0") clear

drop in 1 //this row has the column names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""
capture drop C //Column name in spreadsheet: plntname
capture drop D //Column name in spreadsheet: ownrname
capture drop E //Column name in spreadsheet: state
capture drop F //Column name in spreadsheet: county

//rename fuel variables
capture rename G ff001q
capture rename H ff001v
capture rename I ff002q
capture rename J ff002v
capture rename K ff003q
capture rename L ff003v
capture rename M ff004q
capture rename N ff004v
capture rename O ff005q
capture rename P ff005v
capture rename Q ff006q
capture rename R ff006v
capture rename S ff007q
capture rename T ff007v
capture rename U total_fuel_cost
capture drop V //Column name in spreadsheet: check
capture drop W //Column name in spreadsheet: diff
capture drop X //Column name in spreadsheet:electric_e
capture drop Y //Column name in spreadsheet:electric_e
capture drop Z //Column name in spreadsheet:electric_e
capture drop AA //Column name in spreadsheet:cost8
capture drop AB //Column name in spreadsheet:crude_rubb
capture drop AC //Column name in spreadsheet:cost9
capture drop AD //Column name in spreadsheet:reclaimed_
capture drop AE //Column name in spreadsheet:cost10
capture drop AF //Column name in spreadsheet:reclaimed_
capture drop AG //Column name in spreadsheet:total
capture drop AH //Column name in spreadsheet: check1
capture drop AI //Column name in spreadsheet: diff1
capture drop AJ //Column name in spreadsheet: **_fnlbgnd
capture drop AK //Column name in spreadsheet: fnlenddt
capture drop AL //Column name in spreadsheet: remark01
capture drop AM //Column name in spreadsheet: remark02
capture drop AN //Column name in spreadsheet: remark03
capture drop AO //Column name in spreadsheet: remark04
capture drop AP //Column name in spreadsheet: remark05
capture drop AQ //Column name in spreadsheet: remark06
capture drop AR //Column name in spreadsheet: remark07
capture drop AS //Column name in spreadsheet: remark08
capture drop AT //Column name in spreadsheet: remark09
capture drop AU //Column name in spreadsheet: remark10
capture drop AV //Column name in spreadsheet: remark11
capture drop AW //Column name in spreadsheet: remark12
capture drop AX //Column name in spreadsheet: ca01info
capture drop AY //Column name in spreadsheet: ca01
capture drop AZ //Column name in spreadsheet: ca02info
capture drop BA //Column name in spreadsheet: ca02
capture drop BB //Column name in spreadsheet: ca03info
capture drop BC //Column name in spreadsheet: ca03
capture drop BD //Column name in spreadsheet: ca04info
capture drop BE //Column name in spreadsheet: ca04
capture drop BF //Column name in spreadsheet: ca05info
capture drop BG //Column name in spreadsheet: ca05
capture drop BH //Column name in spreadsheet: ca06info
capture drop BI //Column name in spreadsheet: ca06
capture drop BJ //Column name in spreadsheet: ca07info
capture drop BK //Column name in spreadsheet: ca07
capture drop BL //Column name in spreadsheet: ca08info
capture drop BM //Column name in spreadsheet: ca08
capture drop BN //Column name in spreadsheet: ca09info
capture drop BO //Column name in spreadsheet: ca09
capture drop BP //Column name in spreadsheet: ca10info
capture drop BQ //Column name in spreadsheet: ca10
capture drop BR //Column name in spreadsheet: ca11info
capture drop BS //Column name in spreadsheet: ca11
capture drop BT //Column name in spreadsheet: ca12info
capture drop BU //Column name in spreadsheet: ca12
capture drop BV //Column name in spreadsheet: ca13info
capture drop BW //Column name in spreadsheet: ca13
capture drop BX //Column name in spreadsheet: ca14info
capture drop BY //Column name in spreadsheet: ca14
capture drop BZ //Column name in spreadsheet: ca15info
capture drop CA //Column name in spreadsheet: ca15
capture drop CB //Column name in spreadsheet: ca16info
capture drop CC //Column name in spreadsheet: ca16
capture drop CD //Column name in spreadsheet: ca17info
capture drop CE //Column name in spreadsheet: ca17
capture drop CF //Column name in spreadsheet: ca18info
capture drop CG //Column name in spreadsheet: ca18
capture drop CH //Column name in spreadsheet: ca19info
capture drop CI //Column name in spreadsheet: ca19
capture drop CJ //Column name in spreadsheet: ca20info
capture drop CK //Column name in spreadsheet: ca20
capture drop CL //Column name in spreadsheet: ca21info
capture drop CM //Column name in spreadsheet: ca21
capture drop CN //Column name in spreadsheet: ca22info
capture drop CO //Column name in spreadsheet: ca22
capture drop CP //Column name in spreadsheet: ca23info
capture drop CQ //Column name in spreadsheet: ca23
capture drop CR //Column name in spreadsheet: ca24info
capture drop CS //Column name in spreadsheet: ca24
capture drop CT //Column name in spreadsheet: ca25info
capture drop CU //Column name in spreadsheet: ca25'

save "$rootDir_dataBR/1935/237/237_1935_clean_B", replace
