//Cleaning script for BR spreadsheet: 237_1935. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/237"
import excel "`data_dir'/023735A0.xls", allstring sheet("023735A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indarea
capture rename K indnm
capture rename L formnm
capture rename M plntname
capture rename N ownrname
capture rename O incyn
capture rename P ctlotryn
capture rename Q a004
capture rename R state
capture rename S city
capture rename T county
capture rename U street
capture rename V othraddr
capture rename W incityyn
capture rename X sbsdryyn
capture rename Y mthrinfo
capture rename Z nmchngyn
capture rename AA lnchngyn
capture rename AB owchngyn
capture rename AC bschngyn
capture rename AD as005
capture rename AE products
capture rename AF mtlsusd1
capture rename AG mtlsusd2

//rename utilization variables
capture rename AH d001
capture rename AI d008
capture rename AJ d004
capture rename AK d006

//rename employment variables
capture rename AL proprietor
capture rename AM propwgs
capture rename AN e002t
capture rename AO e002s
capture rename AP e003ta
capture rename AQ e003tas
capture rename AR e003te
capture rename AS e003tes
capture rename AT cmar
capture rename AU cjun
capture rename AV csep
capture rename AW cdec
capture rename AX cwgs
capture rename AY nonwenm
capture rename AZ nonwewgs
capture drop BA
capture drop BB
capture drop BC //diff
capture drop BD //diff1

//rename monthly employment variables
capture rename BE wejannm
capture rename BF wemaynm
capture rename BG wesepnm
capture rename BH wefebnm
capture rename BI wejunnm
capture rename BJ weoctnm
capture rename BK wemarnm
capture rename BL wejulnm
capture rename BM wenovnm
capture drop BN
capture rename BO weaprnm
capture rename BP weaugnm
capture rename BQ wedecnm
capture rename BR wetotlnm
capture drop BS //diff2
capture rename BT e005s
capture rename BU e005sp
capture drop BV //xm1
capture drop BW //xm1wenm
capture drop BX //xm3
capture drop BY //xm3wenm
capture drop BZ //xm5
capture drop CA //xm5wenm
capture drop CB //xm2
capture drop CC //xm2wenm
capture drop CD //xm4
capture drop CE //xm4wenm
capture drop CF //xm6
capture drop CG //xm6wenm

//rename manhours variables
capture rename CH emh01
capture rename CI emh02
capture rename CJ emh03
capture rename CK emh04
capture rename CL emh05
capture rename CM emh06
capture rename CN emh07
capture rename CO emh08
capture rename CP emh09
capture rename CQ emh10
capture rename CR emh11
capture rename CS emh12
capture drop CT
capture rename CU totlmh
capture drop CV //diff3

//rename costs of input variables
capture rename CW f001
capture rename CX f002
capture rename CY f003
capture drop CZ
capture rename DA f009
capture drop DB //diff4
capture rename DC f004

//rename output variables
capture rename DD gp_q_linoleum
capture rename DE gp_v_linoleum
capture rename DF gp_q_piece_plain1
capture rename DG gp_v_piece_plain1
capture rename DH gp_q_piece_plain2
capture rename DI gp_v_piece_plain2
capture rename DJ gp_q_piece_print1
capture rename DK gp_v_piece_print1
capture rename DL gp_q_piece_print2
capture rename DM gp_v_piece_print2
capture rename DN gp_q_piece_inlaid1
capture rename DO gp_v_piece_inlaid1
capture rename DP gp_q_piece_inlaid2
capture rename DQ gp_v_piece_inlaid2
capture rename DR gp_q_piece_cork1
capture rename DS gp_v_piece_cork1
capture rename DT gp_q_linoleum_rugs
capture rename DU gp_v_linoleum_rugs
capture rename DV gp_q_piece_124_1
capture rename DW gp_v_piece_124_1
capture rename DX gp_q_piece_124_2

save "$rootDir_dataBR/1935/237/237_1935", replace

//now clean B spreadsheets
do "$rootDir_code/1935/clean_237_1935_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1935/237/237_1935", replace
merge 1:1 record using "$rootDir_dataBR/1935/237/237_1935_clean_B"
//this should really be a 1-1 mapping
drop _merge

capture drop year
gen year = 1935
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace

save "$rootDir_dataBR/1935/237/237_1935", replace
