//Cleaning script for BR "B" spreadsheet: 631_1935. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/631"
import excel "`data_dir'/063135B1.xls", allstring sheet("063135B1") clear

drop in 1 //this row is variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id+"B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""
//drop a few duplicates on record. These seem like mistakes
capture drop if record=="me0035" & AI==""
capture drop if record=="me0109" & C==""
capture drop if record=="me0225" & J==""
capture drop C //Column name in spreadsheet: plntname
capture drop D //Column name in spreadsheet: ownrname
capture drop E //Column name in spreadsheet: state
capture drop F //Column name in spreadsheet: county

//rename engine and turbine variables
capture rename G hp001gn
capture rename H hp001gh
capture rename I hp001gk
capture rename J hp001on
capture rename K hp001oh

capture rename L hp002gn
capture rename M hp002gh
capture rename N hp002gk
capture rename O hp002on
capture rename P hp002oh

capture rename Q hp005gn
capture rename R hp005gh
capture rename S hp005gk
capture rename T hp005on
capture rename U hp005oh

capture rename V hp006gn
capture rename W hp006gh
capture rename X hp006gk
capture rename Y hp006on
capture rename Z hp006oh

capture rename AA hp004gn
capture rename AB hp004gh
capture rename AC hp004gk
capture rename AD hp004on
capture rename AE hp004oh


drop AF  //standby standby_
drop AG  //Column name in spreadsheet:kw5
drop AH  //Column name in spreadsheet:horse10

capture rename AI he001n //Column name in spreadsheet: a_driven_b
capture rename AJ he001h //Column name in spreadsheet:horse11
capture rename AK he002n //Column name in spreadsheet:b_driven_b
capture rename AL he002h //Column name in spreadsheet:horse12

//rename fuel variables
capture rename AM ff001q
capture rename AN ff001v
capture rename AO ff002q
capture rename AP ff002v
capture rename AQ ff003q
capture rename AR ff003v
capture rename AS ff004q
capture rename AT ff004v
capture rename AU ff005q
capture rename AV ff005v
capture rename AW ff006q
capture rename AX ff006v
capture rename AY ff007q
capture rename AZ ff007v
capture drop BA //Column name in spreadsheet: check
capture rename BB total_fuel_cost
capture drop BC //Column name in spreadsheet: diff
capture rename BD //Column name in spreadsheet: electric_e
capture rename BE //Column name in spreadsheet: electric_e
capture rename BF //Column name in spreadsheet: electric_e
capture rename BG //Column name in spreadsheet: cost8
capture drop BH //Column name in spreadsheet:**_fnlbgnd
capture drop BI //Column name in spreadsheet: fnlenddt
capture drop BJ //Column name in spreadsheet: remark01
capture drop BK //Column name in spreadsheet: remark02
capture drop BL //Column name in spreadsheet: remark03
capture drop BM //Column name in spreadsheet: remark04
capture drop BN //Column name in spreadsheet: remark05
capture drop BO //Column name in spreadsheet: remark06
capture drop BP //Column name in spreadsheet: remark07
capture drop BQ //Column name in spreadsheet: remark08
capture drop BR //Column name in spreadsheet: remark09
capture drop BS //Column name in spreadsheet: remark10
capture drop BT //Column name in spreadsheet: remark11
capture drop BU //Column name in spreadsheet: remark12
capture drop BV //Column name in spreadsheet: remark13
capture drop BW //Column name in spreadsheet: remark14
capture drop BX //Column name in spreadsheet: remark15
capture drop BY //Column name in spreadsheet: remark16
capture drop BZ //Column name in spreadsheet: ca01info
capture drop CA //Column name in spreadsheet: ca01
capture drop CB //Column name in spreadsheet: ca02info
capture drop CC //Column name in spreadsheet: ca02
capture drop CD //Column name in spreadsheet: ca03info
capture drop CE //Column name in spreadsheet: ca03
capture drop CF //Column name in spreadsheet: ca04info
capture drop CG //Column name in spreadsheet: ca04
capture drop CH //Column name in spreadsheet: ca05info
capture drop CI //Column name in spreadsheet: ca05
capture drop CJ //Column name in spreadsheet: ca06info
capture drop CK //Column name in spreadsheet: ca06
capture drop CL //Column name in spreadsheet: ca07info
capture drop CM //Column name in spreadsheet: ca07
capture drop CN //Column name in spreadsheet: ca08info
capture drop CO //Column name in spreadsheet: ca08
capture drop CP //Column name in spreadsheet: ca09info
capture drop CQ //Column name in spreadsheet: ca09
capture drop CR //Column name in spreadsheet: ca10info
capture drop CS //Column name in spreadsheet: ca10
capture drop CT //Column name in spreadsheet: ca11info
capture drop CU //Column name in spreadsheet: ca11
capture drop CV //Column name in spreadsheet: ca12info
capture drop CW //Column name in spreadsheet: ca12
capture drop CX //Column name in spreadsheet: ca13info
capture drop CY //Column name in spreadsheet: ca13
capture drop CZ //Column name in spreadsheet: ca14info
capture drop DA //Column name in spreadsheet: ca14
capture drop DB //Column name in spreadsheet: ca15info
capture drop DC //Column name in spreadsheet: ca15
capture drop DD //Column name in spreadsheet: ca16info
capture drop DE //Column name in spreadsheet: ca16
capture drop DF //Column name in spreadsheet: ca17info
capture drop DG //Column name in spreadsheet: ca17
capture drop DH //Column name in spreadsheet: ca18info
capture drop DI //Column name in spreadsheet: ca18
capture drop DJ //Column name in spreadsheet: ca19info
capture drop DK //Column name in spreadsheet: ca19
capture drop DL //Column name in spreadsheet: ca20info
capture drop DM //Column name in spreadsheet: ca20
capture drop DN //Column name in spreadsheet: ca21info
capture drop DO //Column name in spreadsheet: ca21
capture drop DP //Column name in spreadsheet: ca22info
capture drop DQ //Column name in spreadsheet: ca22
capture drop DR //Column name in spreadsheet: ca23info
capture drop DS //Column name in spreadsheet: ca23
capture drop DT //Column name in spreadsheet: ca24info
capture drop DU //Column name in spreadsheet: ca24
capture drop DV //Column name in spreadsheet: ca25info
capture drop DW //Column name in spreadsheet: ca25'

save "$rootDir_dataBR/1935/631/631_1935_clean_B", replace
