//Cleaning script for BR spreadsheet: 803_1935. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/803"
import excel "`data_dir'/080335A0.xls", allstring sheet("080335A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indarea
capture rename K indnm
capture rename L formnm
capture rename M how_many_s
capture rename N plntname
capture rename O ownrname
capture rename P incyn
capture rename Q ctlotryn
capture rename R a004
capture rename S state
capture rename T city
capture rename U county
capture rename V street
capture rename W othraddr
capture rename X incityyn
capture rename Y sbsdryyn
capture rename Z mthrinfo
capture rename AA nmchngyn
capture rename AB as002
capture rename AC owchngyn
capture rename AD as004
capture rename AE frmrinfo
capture rename AF products
capture rename AG mtlsusd1
capture rename AH mtlsusd2

//rename utilization variables
capture rename AI d001
capture rename AJ d008
capture rename AK d004
capture rename AL d006

//rename employment variables
capture rename AM e001t
capture rename AN propwgs
capture rename AO e002t
capture rename AP e002s
capture rename AQ e003ta
capture rename AR e003tas
capture rename AS e003te
capture rename AT e003tes
capture rename AU e003tc03
capture rename AV e003tc06
capture rename AW e003tc09
capture rename AX e003tc12
capture rename AY e003tcs
capture rename AZ e004s
capture rename BA e004t
capture drop BB
capture drop BC
capture drop BD //diff
capture drop BE //diff1

//rename monthly wage earners variables
capture rename BF wejannm
capture rename BG wemaynm
capture rename BH wesepnm
capture rename BI wefebnm
capture rename BJ wejunnm
capture rename BK weoctnm
capture rename BL wemarnm
capture rename BM wejulnm
capture rename BN wenovnm
capture drop BO
capture rename BP weaprnm
capture rename BQ weaugnm
capture rename BR wedecnm
capture rename BS wetotlnm
capture drop BT 
capture rename BU e005s
capture rename BV e005sp

capture drop BW //xm1
capture drop BX //xm1wenm
capture drop BY //xm3
capture drop BZ //xm3wenm
capture drop CA //xm5
capture drop CB //xm5wenm
capture drop CC //xm2
capture drop CD //xm2wenm
capture drop CE //xm4
capture drop CF //xm4wenm
capture drop CG //xm6
capture drop CH //xm6wenm

//rename manhours variables
capture rename CI emh01
capture rename CJ emh02
capture rename CK emh03
capture rename CL emh04
capture rename CM emh05
capture rename CN emh06
capture rename CO emh07
capture rename CP emh08
capture rename CQ emh09
capture rename CR emh10
capture rename CS emh11
capture rename CT emh12
capture drop CU
capture rename CV emht
capture drop CW //diff3

//rename costs of inputs variables
capture rename CX f001
capture rename CY f002
capture rename CZ f003
capture drop DA
capture rename DB f009
capture drop DC //diff4
capture rename DD f004
//going to need to get output variables reenetered
capture drop DE-DX

save "$rootDir_dataBR/1935/803/803_1935", replace

//now clean B spreadsheets
do "$rootDir_code/1935/clean_803_1935_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1935/803/803_1935", replace
merge 1:1 record using "$rootDir_dataBR/1935/803/803_1935_clean_B"
//this should really be a 1-1 mapping
drop _merge

capture drop year
gen year = 1935
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"

//tostring all variables for consistent appending later
tostring *, replace

save "$rootDir_dataBR/1935/803/803_1935", replace
