//Cleaning script for BR spreadsheet: 1608_1935. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataB

local data_dir = "$rootDir_sheets/1935/1608"
import excel "`data_dir'/160835A0.xls", allstring sheet("160835A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indarea
capture rename K indnm
capture rename L formnm
capture rename M plntname
capture rename N ownrname
capture rename O incyn
capture rename P ctlotryn
capture rename Q a004
capture rename R state
capture rename S city
capture rename T county
capture rename U street
capture rename V othraddr
capture rename W incityyn
capture rename X sbsdryyn
capture rename Y mthrinfo
capture rename Z nmchngyn
capture rename AA lnchngyn
capture rename AB as003
capture rename AC as004
capture rename AD as005
capture rename AE products
capture rename AF mtlsusd1
capture rename AG mtlsusd2

//rename utilization variables
capture rename AH d001
capture rename AI d008
capture rename AJ d004
capture rename AK d006

//rename employment variables
capture rename AL proprietor
capture rename AM offcnm
capture rename AN soffcwgs
capture rename AO supervisor
capture rename AP e003tas
capture rename AQ technical_
capture rename AR techwgs
capture rename AS cmar
capture rename AT cjun
capture rename AU csep
capture rename AV cdec
capture rename AW cwgs
capture rename AX nonwenm
capture rename AY nonwewgs
capture drop AZ
capture drop BA
capture drop BB //diff
capture drop BC //diff1

//rename monthly wage earner variables
capture rename BD wejanuaryn
capture rename BE wemaynm
capture rename BF weseptembe
capture rename BG wefebruary
capture rename BH wejunenm
capture rename BI weoctobern
capture rename BJ wemarchnm
capture rename BK wejulynm
capture rename BL wenovember
capture rename BM weaprilnm
capture rename BN weaugustnm
capture rename BO wedecember
capture drop BP
capture rename BQ wetotalnm
capture drop BR //diff2
capture rename BS e005s
capture rename BT e005sp

capture drop BU //xm1
capture drop BV //xm1wenm
capture drop BW //xm3
capture drop BX //xm3wenm
capture drop BY //xm5
capture drop BZ //xm5wenm
capture drop CA //xm2
capture drop CB //xm2wenm
capture drop CC //xm4
capture drop CD //xm4wenm
capture drop CE //xm6
capture drop CF //xm6wenm

//rename man hours variable
capture rename CG emh01
capture rename CH emh02
capture rename CI emh03
capture rename CJ emh04
capture rename CK emh05
capture rename CL emh06
capture rename CM emh07
capture rename CN emh08
capture rename CO emh09
capture rename CP emh10
capture rename CQ emh11
capture rename CR emh12
capture drop CS
capture rename CT emht
capture drop CU //diff3

//rename costs of inputs variables
capture rename CV f001
capture rename CW f002
capture rename CX f003
capture drop CY
capture rename CZ f009
capture drop DA //diff4
capture rename DB f004

//rename output variables
capture rename DC gp_q_cigars
capture rename DD gp_q_cigars_lbs
capture rename DE gp_v_cigars
capture rename DF gp_q_cigarettes
capture rename DG gp_q_cigarettes_lbs
capture rename DH gp_v_cigarettes
capture rename DI gp_q_tobacco
capture rename DJ gp_v_tobacco
capture rename DK gp_q_snuff
capture rename DL gp_v_snuff

capture rename DM gp_s_general1
capture rename DN gp_q_general1
capture rename DO gp_v_general1
capture rename DP gp_s_general2
capture rename DQ gp_q_general2
capture rename DR gp_v_general2
capture rename DS receipts_f
capture drop DT
capture rename DU totqty
rename DV g000v
capture drop DW
capture drop DX

save "$rootDir_dataBR/1935/1608/1608_1935", replace

/*
//need some example images to rewrite the cleaning B file
//now clean B spreadsheets
do "$code_dir/1935/clean_1608_1935_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1935/1608/1608_1935_clean", replace
merge 1:1 record using "$rootDir_dataBR/1935/1608/1608_1935_clean_B"
//this should really be a 1-1 mapping
drop _merge
*/

capture drop year
gen year = 1935
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1935/1608/1608_1935", replace
