//Cleaning script for BR "B" spreadsheet: 1110_1935. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/1110"
import excel "`data_dir'/111035B0.xls", allstring sheet("111035B0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""
capture drop C //Column name in spreadsheet: id
capture drop D //Column name in spreadsheet: plntname
capture drop E //Column name in spreadsheet: ownrname
capture drop F //Column name in spreadsheet: state
capture drop G //Column name in spreadsheet:county
capture drop  H//Column name in spreadsheet: tothp
capture drop I //Column name in spreadsheet:tothp2


capture rename J hp001gn
capture rename K hp001gh
capture rename L hp001gk
capture rename M hp001on
capture rename N hp001oh

capture rename O hp002gn
capture rename P hp002gh
capture rename Q hp002gk
capture rename R hp002on
capture rename S hp002oh

capture rename T hp005gn
capture rename U hp005gh
capture rename V hp005gk
capture rename W hp005on
capture rename X hp005oh

capture rename Y hp006gn
capture rename Z hp006gh
capture rename AA hp006gk
capture rename AB hp006on
capture rename AC hp006oh

capture rename AD hp004gn
capture rename AE hp004gh
capture rename AF hp004gk
capture rename AG hp004on
capture rename AH hp004oh

capture drop AI //Column name in spreadsheet:horse10
capture drop AJ //Column name in spreadsheet:kw5
capture drop AK //Column name in spreadsheet:horse11
capture drop AL //Column name in spreadsheet:ttlnum
capture drop AM //Column name in spreadsheet:totalhp
capture drop AN //Column name in spreadsheet: chk
capture drop AO //Column name in spreadsheet: diff
capture drop AP //Column name in spreadsheet: chk1
capture drop AQ //Column name in spreadsheet: diff

rename AR he001n //Column name in spreadsheet:a_driven_b
rename AS he001h //Column name in spreadsheet:horse12
rename AT he002n //Column name in spreadsheet:b_driven_b
rename AU he002h //Column name in spreadsheet:horse13

capture drop AV //Column name in spreadsheet: remark01
capture drop AW //Column name in spreadsheet: remark02
capture drop AX //Column name in spreadsheet: remark03
capture drop AY //Column name in spreadsheet: remark04
capture drop AZ //Column name in spreadsheet: remark05
capture drop BA //Column name in spreadsheet: remark06
capture drop BB //Column name in spreadsheet: remark07
capture drop BC //Column name in spreadsheet: remark08
capture drop BD //Column name in spreadsheet: remark09
capture drop BE //Column name in spreadsheet: remark10
capture drop BF //Column name in spreadsheet: remark11

//rename fuel variables
capture rename BG ff001q
capture rename BH ff001v
capture rename BI ff002q
capture rename BJ ff002v
capture rename BK ff003q
capture rename BL ff003v
capture rename BM ff004q
capture rename BN ff004v
capture rename BO ff005q
capture rename BP ff005v
capture rename BQ ff006q
capture rename BR ff006v
capture rename BS ff007q
capture rename BT ff007v
capture drop BU //Column name in spreadsheet: check
capture rename BV total_fuel_value
capture drop BW //Column name in spreadsheet: diff2
capture drop BX //Column name in spreadsheet: electric_e
capture drop BY //Column name in spreadsheet: electric_e
capture drop BZ //Column name in spreadsheet: electric_e
capture drop CA //Column name in spreadsheet: cost8

//rename capital variables
capture rename CB z_furnace_complete_number
capture rename CC z_furnace_active_number
capture rename CD z_furnace_new_number
capture rename CE z_furnace_fuel1
capture rename CF z_furnace_fuel2
capture rename CG z_furnace_fuel3
capture rename CH z_furnace_fuel4
capture rename CI z_furnace_fuel_extra
capture rename CJ z_furnace_capacity1
capture rename CK z_furnace_capacity2
capture rename CL z_furnace_capacity3
capture rename CM z_furnace_capacity4
capture rename CN z_furnace_capacity5
capture rename CO z_furnace_capacity6
capture rename CP z_furnace_capacity7
capture rename CQ z_furnace_capacity8
capture rename CR //Column name in spreadsheet: xtracap
capture rename CS z_furnace_active_fuel1
capture rename CT z_furnace_active_number1
capture rename CU z_furnace_active_capacity1
capture rename CV z_furnace_active_fuel2
capture rename CW z_furnace_active_number2
capture rename CX z_furnace_active_capacity2
capture rename CY z_furnace_active_fuel3
capture rename CZ z_furnace_active_number3
capture rename DA z_furnace_active_capacity3
capture drop DB //Column name in spreadsheet:xtraact
capture rename DC z_furnace_idle_fuel
capture rename DD z_furnace_idle_number
capture rename DE z_furnace_idle_capacity
capture drop DF //Column name in spreadsheet: xtraidle
capture rename DG z_furnace_banked_fuel
capture rename DH z_furnace_banked_number
capture rename DI z_furnace_banked_capacity
capture drop DJ //Column name in spreadsheet: xtrabnk
capture rename DK z_furnace_new_fuel
capture rename DL z_furnace_new_number
capture rename DM z_furnace_new_capacity
capture drop DN //Column name in spreadsheet:xtranew
capture rename DO z_furnace_construction_fuel
capture rename DP z_furnace_construction_number
capture rename DQ z_furnace_construction_capacity
capture drop DR //Column name in spreadsheet: xtracons
capture rename DS z_furnace_abandoned_fuel
capture rename DT z_furnace_abandoned_number
capture rename DU z_furnace_abandoned_capacity
capture drop DV //Column name in spreadsheet: wage_earne
capture drop DW //Column name in spreadsheet: wages_paid
capture drop DX //Column name in spreadsheet: are_we_inc'

save "$rootDir_dataBR/1935/1110/1110_1935_clean_B", replace
