//rename variables for ind. 314 and year 1935

//rename output variables
 rename DD gp_q_doors_construction_pine
 rename DE gp_v_doors_construction_pine
 rename DF gp_q_doors_construction_fir
 rename DG gp_v_doors_construction_fir
 rename DH gp_q_doors_construction_hardwood
 rename DI gp_v_doors_construction_hardwood
 rename DJ gp_q_doors_construction_other
 rename DK gp_v_doors_construction_other
 rename DL gp_q_doors_garages
 rename DM gp_v_doors_garages
 rename DN gp_q_doors_other
 rename DO gp_v_doors_other
 rename DP gp_q_sash
 rename DQ gp_v_sash
 rename DR gp_q_window_door_frames
 rename DS gp_v_window_door_frames
 rename DT gp_q_window_door_screens
 rename DU gp_v_window_door_screens
 rename DV gp_q_portable_houses
 rename DW gp_v_portable_houses
 rename DX gp_q_tanks_vats
 rename DY gp_v_tanks_vats
 rename DZ gp_q_venetian_blinds
 rename EA gp_v_venetian_blinds
 rename EB gp_q_silow_stock
 rename EC gp_v_silow_stock
 rename ED gp_q_dressed_lumber
 rename EE gp_v_dressed_lumber
 rename EF gp_q_plywood_utility
 rename EG gp_v_plywood_utility
 rename EH gp_q_plywood_plain
 rename EI gp_v_plywood_plain
 rename EJ gp_v_builtIn_furniture
 rename EK gp_v_battery_separators
 rename EL gp_v_moldings
 rename EM gp_v_custom_planing 
 rename EN gp_q_box_wdn_lmbr_noWire_FV
 rename EO gp_q_box_wdn_lmbr_noWire_ind
 rename EP gp_v_box_wdn_lmbr_noWire
 rename EQ gp_q_box_wdn_lmbr_wire_FV
 rename ER gp_q_box_wdn_lmbr_wire_ind
 rename ES gp_v_box_wdn_lmbr_wire
 rename ET gp_q_box_wdn_vnr_noWire_FV
 rename EU gp_q_box_wdn_vnr_noWire_ind
 rename EV gp_v_box_wdn_vnr_noWire
 rename EW gp_q_box_wdn_vnr_wire_FV
 rename EX gp_q_box_wdn_vnr_wire_ind
 rename EY gp_v_box_wdn_vnr_wire
 rename EZ gp_q_box_wooden_combo_FV
 rename FA gp_q_box_wooden_combo_ind
 rename FB gp_v_box_wooden_combo
 rename FC gp_q_baskets_veneer_FV
 rename FD gp_q_baskets_veneer_ind
 rename FE gp_v_baskets_veneer
 rename FF gp_q_baskets_reed_FV
 rename FG gp_q_baskets_reed_ind
 rename FH gp_v_baskets_reed
 rename FI gp_q_baskets_other_FV
 rename FJ gp_q_baskets_other_ind
 rename FK gp_v_baskets_other
 rename FL gp_s_other1
 rename FM gp_q_other1
 rename FN gp_v_other1
 rename FO gp_s_other2
 rename FP gp_q_other2
 rename FQ gp_v_other2
 drop FR
 rename FS custom_work
 rename FT g000v
drop FU

