//Cleaning script for BR spreadsheet: 631_1935. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: rootDir_sheets, rootDir_dataBR

local data_dir = "$rootDir_sheets/1935/631"
import excel "`data_dir'/063135A1.xls", allstring sheet("063135A1") clear

drop in 1 //first row is variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F statenm
capture rename G cntynm
capture rename H citynm
capture rename I indarea
capture rename J indnm
capture rename K formnm
capture rename L how_many_p
capture rename M a_plntname
capture rename N b_ownrname
capture rename O incyn
capture rename P ctlotryn
capture rename Q a004
capture rename R state
capture rename S city
capture rename T f_county
capture rename U street
capture rename V h_othraddr
capture rename W i_incityyn
capture rename X j_sbsdryyn
capture rename Y mthrinfo
capture rename Z k_nmchngyn
capture rename AA lnchngyn
capture rename AB owchngyn
capture rename AC bschngyn
capture rename AD frmrinfo
capture rename AE a_products
capture rename AF b_mtlsusd1
capture rename AG mtlsusd2

//rename utilization variables
capture rename AH d001
capture rename AI d008
capture rename AJ d004
capture rename AK d006

//rename employment variables
capture rename AL a_propriet
capture rename AM b_salaried
capture rename AN offcslry
capture rename AO c_supervis
capture rename AP e003tas
capture rename AQ d_technica
capture rename AR techwgs
capture rename AS cmar
capture rename AT cjun
capture rename AU csep
capture rename AV cdec
capture rename AW e003tcs
capture drop AX
capture drop AY
capture rename AZ number
capture rename BA wages4
capture drop BB //diff
capture drop BC //diff1
capture rename BD wejannm
capture rename BE wemaynm
capture rename BF wesepnm
capture rename BG wefebnm
capture rename BH wejunnm
capture rename BI weoctnm
capture rename BJ wemarnm
capture rename BK wejulnm
capture rename BL wenovnm
capture rename BM weaprnm
capture rename BN weaugnm
capture rename BO wedecnm
capture drop BP
capture rename BQ wetotlnm
capture drop BR //diff2
capture rename BS e005s
capture rename BT e005sp

//not sure what these are
capture drop BU //xm1
capture drop BV //xm1wenm
capture drop BW //xm3
capture drop BX //xm3wenm
capture drop BY //xm5
capture drop BZ //xm5wenm
capture drop CA //xm2
capture drop CB //xm2wenm
capture drop CC //xm4
capture drop CD //xm4wenm
capture drop CE //xm6
capture drop CF //xm6wenm

//rename man hours variables
capture rename CG emh01
capture rename CH emh02
capture rename CI emh03
capture rename CJ emh04
capture rename CK emh05
capture rename CL emh06
capture rename CM emh07
capture rename CN emh08
capture rename CO emh09
capture rename CP emh10
capture rename CQ emh11
capture rename CR emh12
capture drop CS
capture rename CT emht
capture drop CU //diff3

//rename costs of inputs variables
capture rename CV f001
capture rename CW f002
capture rename CX f003
capture drop CY
capture rename CZ f009
capture rename DA diff4
capture rename DB f004

//rename output variables
capture rename DC gp_q_bar_soap1
capture rename DD gp_v_bar_soap1
capture rename DE gp_q_bar_soap2
capture rename DF gp_v_bar_soap2
capture rename DG gp_q_bar_soaps3
capture rename DH gp_v_bar_soap3
capture rename DI gp_q_bar_cleanser1
capture rename DJ gp_v_bar_cleanser1
capture rename DK gp_q_bar_cleanser2
capture rename DL gp_v_bar_cleanser2
capture rename DM gp_q_shaving_soap1
capture rename DN gp_v_shaving_soap1
capture rename DO gp_q_shaving_soap2
capture rename DP gp_v_shaving_soap2
capture rename DQ gp_q_soap_chip1
capture rename DR gp_v_soap_chip1
capture rename DS gp_q_soap_chip2
capture rename DT gp_v_soap_chip2
capture rename DU gp_q_granulated_soap
capture rename DV gp_v_granulated_soap
capture rename DW gp_q_washing_powder
capture rename DX gp_v_washing_powder

save "$rootDir_dataBR/1935/631/631_1935", replace

//now clean B spreadsheets
do "$rootDir_code/1935/clean_631_1935_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1935/631/631_1935", replace
merge 1:1 record using "$rootDir_dataBR/1935/631/631_1935_clean_B"
//this should really be a 1-1 mapping
drop _merge

capture drop year
gen year = 1935
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"

//tostring all variables for consistent appending later
tostring *, replace

save "$rootDir_dataBR/1935/631/631_1935", replace
