//rename variables for industry 626 in year 1931

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
rename AN gp_q_whiteLead_carbonateC
rename AO gp_q_whiteLead_carbonate
rename AP gp_v_whiteLead_carbonate
rename AQ gp_q_whiteLead_sulfateC
rename AR gp_q_whiteLead_sulfate
rename AS gp_v_whiteLead_sulfate
rename AT gp_q_leadOxide_lithargeC
rename AU gp_q_leadOxide_litharge
rename AV gp_v_leadOxide_litharge
rename AW gp_q_leadOxide_redLeadC
rename AX gp_q_leadOxide_redLead
rename AY gp_v_leadOxide_redLead
rename AZ gp_q_leadOxide_otherC
rename BA gp_q_leadOxide_other
rename BB gp_v_leadOxide_other
rename BC gp_s_leadOxide_other
rename BD gp_q_zincOxideC
rename BE gp_q_zincOxide
rename BF gp_v_zincOxide
rename BG gp_q_zincSulphideC
rename BH gp_q_zincSulphide
rename BI gp_v_zincSulphide
rename BJ gp_q_lithoponeC
rename BK gp_q_lithopone
rename BL gp_v_lithopone
rename BM gp_q_barytesC
rename BN gp_q_barytes
rename BO gp_v_barytes
rename BP gp_q_ironOxide_naturalC
rename BQ gp_q_ironOxide_natural
rename BR gp_v_ironOxide_natural
rename BS gp_q_ironOxide_syntheticC
rename BT gp_q_ironOxide_synthetic
rename BU gp_v_ironOxide_synthetic
rename BV gp_q_otherMineral1C
rename BW gp_q_otherMineral1
rename BX gp_v_otherMineral1
rename BY gp_s_otherMineral1C
rename BZ gp_q_otherMineral2C
rename CA gp_q_otherMineral2
rename CB gp_v_otherMineral2
rename CC gp_s_otherMineral2
rename CD gp_q_pigment_lampblackC
rename CE gp_q_pigment_lampblack
rename CF gp_v_pigment_lampblack
rename CG gp_q_pigment_carbonblackC 
rename CH gp_q_pigment_carbonblack
rename CI gp_v_pigment_carbonblack
rename CJ gp_q_chromeYellowC
rename CK gp_q_chromeYellow
rename CL gp_v_chromeYellow
rename CM gp_q_chromeOrangeC
rename CN gp_q_chromeOrange
rename CO gp_v_chromeOrange
rename CP gp_q_chromeGreenC
rename CQ gp_q_chromeGreen
rename CR gp_v_chromeGreen
rename CS gp_q_coaltarC
rename CT gp_q_coaltar
rename CU gp_v_coaltar
rename CV gp_q_prussianBlueC
rename CW gp_q_prussianBlue
rename CX gp_v_prussianBlue
rename CY gp_q_ultramarineC
rename CZ gp_q_ultramarine
rename DA gp_v_ultramarine
rename DB gp_q_vermillionC
rename DC gp_q_vermillion
rename DD gp_v_vermillion
rename DE gp_q_otherFine1C
rename DF gp_q_otherFine1
rename DG gp_v_otherFine1
rename DH gp_s_otherFine1
rename DI gp_q_otherFine2C
rename DJ gp_q_otherFine2
rename DK gp_v_otherFine2
rename DL gp_s_otherFine2
rename DM gp_q_mortarColorC
rename DN gp_q_mortarColor
rename DO gp_v_mortarColor
rename DP gp_q_whitingC
rename DQ gp_q_whiting
rename DR gp_v_whiting
rename DS gp_q_otherDry1C
rename DT gp_q_otherDry1
rename DU gp_v_otherDry1
rename DV gp_s_otherDry1
rename DW gp_q_paint_pulp
rename DX gp_v_paint_pulp
rename DY gp_q_paint_water
rename DZ gp_v_paint_water
rename EA gp_q_paint_plastic
rename EB gp_v_paint_plastic
rename EC gp_q_paint_WhiteLead
rename ED gp_v_paintPaste_WhiteLead
rename EE gp_q_paintPaste_Combo
rename EF gp_v_paintPaste_Combo
rename EG gp_q_paintPaste_RedLead
rename EH gp_v_paintPaste_RedLead
rename EI gp_q_paintPaste_ZincOxide
rename EJ gp_v_paintPaste_ZincOxide
rename EK gp_q_paintPaste_ColorsOil
rename EL gp_v_paintPaste_ColorsOIl
rename EM gp_q_paintPaste_ColorsJapan
rename EN gp_v_paintPaste_ColorsJapan
rename EO gp_q_paintPaste_Other
rename EP gp_v_paintPaste_Other
rename EQ gp_s_paintPaste_Other
rename ER gp_q_readyMixed_Oil
rename ES gp_v_readyMixed_Oil
rename ET gp_q_readyMixed_Undercoatings
rename EU gp_v_readyMixed_Undercoatings
rename EV gp_q_readyMixed_WallPaints
rename EW gp_v_readyMixed_WallPaints
rename EX gp_q_readyMixed_Staints
rename EY gp_v_readyMixed_Staints
rename EZ gp_q_readyMixed_Other
rename FA gp_v_readyMixed_Other
rename FB gp_q_varnish_OleoresinousC
rename FC gp_q_varnish_Oleoresinous
rename FD gp_v_varnish_Oleoresinous
rename FE gp_q_varnish_SpiritC
rename FF gp_q_varnish_Spirit
rename FG gp_v_varnish_Spirit
rename FH gp_q_varnish_OtherC
rename FI gp_q_varnish_Other
rename FJ gp_v_varnish_Other
rename FK gp_q_Pyroxylin_ClearC
rename FL gp_q_Pyroxylin_Clear
rename FM gp_v_Pyroxylin_Clear
rename FN gp_q_Pyroxylin_LacquerC
rename FO gp_q_Pyroxylin_Lacquer
rename FP gp_v_Pyroxylin_Lacquer
rename FQ gp_q_Pyroxylin_ThinnerC
rename FR gp_q_Pyroxylin_Thinner
rename FS gp_v_Pyroxylin_Thinner
rename FT gp_q_Pyroxylin_OtherC
rename FU gp_q_Pyroxylin_Other
rename FV gp_v_Pyroxylin_Other
rename FW gp_q_varnish_EnamelsC
rename FX gp_q_varnish_Enamels
rename FY gp_v_varnish_Enamels
rename FZ gp_q_varnish_DryingJapansC
rename GA gp_q_varnish_DryingJapans
rename GB gp_v_varnish_DryingJapans
rename GC gp_q_varnish_BakingJapansC
rename GD gp_q_varnish_BakingJapans
rename GE gp_v_varnish_BakingJapans
rename GF gp_q_varnish_OtherC
rename GG gp_q_varnish_Other
rename GH gp_v_varnish_Other
rename GI gp_s_varnish_Other
rename GJ gp_q_filler_Liquid
rename GK gp_v_filler_Liquid
rename GL gp_q_filler_Paste
rename GM gp_v_filler_Paste
rename GN gp_q_filler_Dry
rename GO gp_v_filler_Dry
rename GP gp_q_filler_Putty
rename GQ gp_v_filler_Putty
rename GR gp_q_otherPaint_Shellac
rename GS gp_v_otherPaint_Shellac
rename GT gp_q_otherPaint_LinseedOil
rename GU gp_v_otherPaint_LinseedOil
rename GV gp_q_otherPaint_Oils2
rename GW gp_v_otherPaint_Oils1
rename GX gp_s_otherPaint_Oils1
rename GY gp_q_otherPaint_Oils2
rename GZ gp_v_otherPaint_Oils2
rename HA gp_s_otherPaint_Oils2
rename HB gp_q_otherPaint_Removers
rename HC gp_v_otherPaint_Removers
rename HD gp_q_otherPaint_Insecticides
rename HE gp_v_otherPaint_Insecticides
rename HF gp_q_other1
rename HG gp_v_other1
rename HH gp_s_other1
rename HI gp_q_other2
rename HJ gp_v_other2
rename HK gp_s_other2
rename HL g000v
