//rename variables for industry 407 in year 1931

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
rename AN gp_q_newsprint_rolls_A
rename AO gp_v_newsprint_rolls_A 
rename AP gp_q_newsprint_rolls_B
rename AQ gp_v_newsprint_rolls_B 
rename AR gp_q_newsprint_rolls_C 
rename AS gp_v_newsprint_rolls_C 
rename AT gp_q_newsprint_sheets_A  
rename AU gp_v_newsprint_sheets_A   
rename AV gp_q_newsprint_sheets_B   
rename AW gp_v_newsprint_sheets_B   
rename AX gp_q_newsprint_sheets_C   
rename AY gp_v_newsprint_sheets_C   
rename AZ gp_q_paper_hanging_A   
rename BA gp_v_paper_hanging_A    
rename BB gp_q_paper_hanging_B    
rename BC gp_v_paper_hanging_B    
rename BD gp_q_paper_hanging_C    
rename BE gp_v_paper_hanging_C    
rename BF gp_q_paper_catalogue_A
rename BG gp_v_paper_catalogue_A     
rename BH gp_q_paper_catalogue_B     
rename BI gp_v_paper_catalogue_B     
rename BJ gp_q_paper_catalogue_C     
rename BK gp_v_paper_catalogue_C     
rename BL gp_q_paper_poster_A     
rename BM gp_v_paper_poster_A      
rename BN gp_q_paper_poster_B      
rename BO gp_v_paper_poster_B      
rename BP gp_q_paper_poster_C      
rename BQ gp_v_paper_poster_C      
rename BR gp_q_book_paper_A
rename BS gp_v_book_paper_A 
rename BT gp_q_book_paper_B 
rename BU gp_v_book_paper_B 
rename BV gp_q_book_paper_C 
rename BW gp_v_book_paper_C 
rename BX gp_q_body_stock_A 
rename BY gp_v_body_stock_A  
rename BZ gp_q_body_stock_B  
rename CA gp_v_body_stock_B  
rename CB gp_q_body_stock_C  
rename CC gp_v_body_stock_C  
rename CD gp_q_lithograph_A  
rename CE gp_v_lithograph_A   
rename CF gp_q_lithograph_B   
rename CG gp_v_lithograph_B   
rename CH gp_q_lithograph_C   
rename CI gp_v_lithograph_C  
rename CJ gp_q_paper_offset_A   
rename CK gp_v_paper_offset_A    
rename CL gp_q_paper_offset_B    
rename CM gp_v_paper_offset_B    
rename CN gp_q_paper_offset_C    
rename CO gp_v_paper_offset_C    
rename CP gp_q_text_paper_A    
rename CQ gp_v_text_paper_A     
rename CR gp_q_text_paper_B     
rename CS gp_v_text_paper_B     
rename CT gp_q_text_paper_C     
rename CU gp_v_text_paper_C     
rename CV gp_s_other_book_paper_1 
rename CW gp_q_other_book_paper_1_A  
rename CX gp_v_other_book_paper_1_A  
rename CY gp_q_other_book_paper_1_B  
rename CZ gp_v_other_book_paper_1_B  
rename DA gp_q_other_book_paper_1_C  
rename DB gp_v_other_book_paper_1_C  
rename DC gp_s_other_book_paper_2  
rename DD gp_q_other_book_paper_2_A  
rename DE gp_v_other_book_paper_2_A  
rename DF gp_q_other_book_paper_2_B  
rename DG gp_v_other_book_paper_2_B  
rename DH gp_q_other_book_paper_2_C  
rename DI gp_v_other_book_paper_2_C  
rename DJ gp_q_cover_paper_A
rename DK gp_v_cover_paper_A 
rename DL gp_q_cover_paper_B 
rename DM gp_v_cover_paper_B 
rename DN gp_q_cover_paper_C 
rename DO gp_v_cover_paper_C 
rename DP gp_q_writing_paper_rag_A 
rename DQ gp_v_writing_paper_rag_A  
rename DR gp_q_writing_paper_rag_B  
rename DS gp_v_writing_paper_rag_B  
rename DT gp_q_writing_paper_rag_C  
rename DU gp_v_writing_paper_rag_C  
rename DV gp_q_writing_paper_rag_less100_A 
rename DW gp_v_writing_paper_rag_less100_A  
rename DX gp_q_writing_paper_rag_less100_B  
rename DY gp_v_writing_paper_rag_less100_B  
rename DZ gp_q_writing_paper_rag_less100_C  
rename EA gp_v_writing_paper_rag_less100_C  
rename EB gp_q_writing_paper_rag_less50_A  
rename EC gp_v_writing_paper_rag_less50_A   
rename ED gp_q_writing_paper_rag_less50_B   
rename EE gp_v_writing_paper_rag_less50_B   
rename EF gp_q_writing_paper_rag_less50_C   
rename EG gp_v_writing_paper_rag_less50_C   
rename EH gp_q_paper_sulphite_A 
rename EI gp_v_paper_sulphite_A  
rename EJ gp_q_paper_sulphite_B  
rename EK gp_v_paper_sulphite_B  
rename EL gp_q_paper_sulphite_C  
rename EM gp_v_paper_sulphite_C  
rename EN gp_q_paper_other_chemical_A 
rename EO gp_v_paper_other_chemical_A  
rename EP gp_q_paper_other_chemical_B  
rename EQ gp_v_paper_other_chemical_B  
rename ER gp_q_paper_other_chemical_C  
rename ES gp_v_paper_other_chemical_C  
rename ET gp_q_wrapping_paper_unbleached_A 
rename EU gp_v_wrapping_paper_unbleached_A  
rename EV gp_q_wrapping_paper_unbleached_B  
rename EW gp_v_wrapping_paper_unbleached_B  
rename EX gp_q_wrapping_paper_unbleached_C  
rename EY gp_v_wrapping_paper_unbleached_C  
rename EZ gp_q_wrapping_paper_bleached_A  
rename FA gp_v_wrapping_paper_bleached_A   
rename FB gp_q_wrapping_paper_bleached_B   
rename FC gp_v_wrapping_paper_bleached_B   
rename FD gp_q_wrapping_paper_bleached_C   
rename FE gp_v_wrapping_paper_bleached_C   
rename FF gp_q_wrapping_paper_sulphite_A   
rename FG gp_v_wrapping_paper_sulphite_A    
rename FH gp_q_wrapping_paper_sulphite_B    
rename FI gp_v_wrapping_paper_sulphite_B    
rename FJ gp_q_wrapping_paper_sulphite_C    
rename FK gp_v_wrapping_paper_sulphite_C    
rename FL gp_q_wrapping_paper_kraft_A    
rename FM gp_v_wrapping_paper_kraft_A     
rename FN gp_q_wrapping_paper_kraft_B     
rename FO gp_v_wrapping_paper_kraft_B     
rename FP gp_q_wrapping_paper_kraft_C     
rename FQ gp_v_wrapping_paper_kraft_C     
rename FR gp_q_wrapping_paper_kraft_oth_A     
rename FS gp_v_wrapping_paper_kraft_oth_A      
rename FT gp_q_wrapping_paper_kraft_oth_B      
rename FU gp_v_wrapping_paper_kraft_oth_B      
rename FV gp_q_wrapping_paper_kraft_oth_C      
rename FW gp_v_wrapping_paper_kraft_oth_C      
rename FX gp_q_wrapping_paper_bogus_A 
rename FY gp_v_wrapping_paper_bogus_A  
rename FZ gp_q_wrapping_paper_bogus_B  
rename GA gp_v_wrapping_paper_bogus_B  
rename GB gp_q_wrapping_paper_bogus_C  
rename GC gp_v_wrapping_paper_bogus_C  
rename GD gp_q_wrapping_paper_greasepf_A  
rename GE gp_v_wrapping_paper_greasepf_A   
rename GF gp_q_wrapping_paper_greasepf_B   
rename GG gp_v_wrapping_paper_greasepf_B   
rename GH gp_q_wrapping_paper_greasepf_C   
rename GI gp_v_wrapping_paper_greasepf_C   
rename GJ gp_q_wrapping_paper_glassine_A   
rename GK gp_v_wrapping_paper_glassine_A    
rename GL gp_q_wrapping_paper_glassine_B    
rename GM gp_v_wrapping_paper_glassine_B    
rename GN gp_q_wrapping_paper_glassine_C    
rename GO gp_v_wrapping_paper_glassine_C    
rename GP gp_q_wrapping_paper_heavy_A    
rename GQ gp_v_wrapping_paper_heavy_A     
rename GR gp_q_wrapping_paper_heavy_B     
rename GS gp_v_wrapping_paper_heavy_B     
rename GT gp_q_wrapping_paper_heavy_C     
rename GU gp_v_wrapping_paper_heavy_C     
rename GV gp_q_wrapping_paper_rope_A     
rename GW gp_v_wrapping_paper_rope_A      
rename GX gp_q_wrapping_paper_rope_B      
rename GY gp_v_wrapping_paper_rope_B      
rename GZ gp_q_wrapping_paper_rope_C      
rename HA gp_v_wrapping_paper_rope_C      
rename HB gp_q_wrapping_paper_groundwood_A      
rename HC gp_v_wrapping_paper_groundwood_A       
rename HD gp_q_wrapping_paper_groundwood_B       
rename HE gp_v_wrapping_paper_groundwood_B       
rename HF gp_q_wrapping_paper_groundwood_C       
rename HG gp_v_wrapping_paper_groundwood_C       
rename HH gp_q_wrapping_paper_tag_A       
rename HI gp_v_wrapping_paper_tag_A        
rename HJ gp_q_wrapping_paper_tag_B        
rename HK gp_v_wrapping_paper_tag_B        
rename HL gp_q_wrapping_paper_tag_C        
rename HM gp_v_wrapping_paper_tag_C        
rename HN gp_q_wrapping_paper_vegetable_A        
rename HO gp_v_wrapping_paper_vegetable_A         
rename HP gp_q_wrapping_paper_vegetable_B         
rename HQ gp_v_wrapping_paper_vegetable_B         
rename HR gp_q_wrapping_paper_vegetable_C         
rename HS gp_v_wrapping_paper_vegetable_C         
rename HT gp_s_wrapping_paper_other_1 
rename HU gp_q_wrapping_paper_other_1_A  
rename HV gp_v_wrapping_paper_other_1_A  
rename HW gp_q_wrapping_paper_other_1_B  
rename HX gp_v_wrapping_paper_other_1_B  
rename HY gp_q_wrapping_paper_other_1_C  
rename HZ gp_v_wrapping_paper_other_1_C  
rename IA gp_s_wrapping_paper_other_2  
rename IB gp_q_wrapping_paper_other_2_A  
rename IC gp_v_wrapping_paper_other_2_A  
rename ID gp_q_wrapping_paper_other_2_B  
rename IE gp_v_wrapping_paper_other_2_B  
rename IF gp_q_wrapping_paper_other_2_C
rename IG gp_v_wrapping_paper_other_2_C 
rename IH gp_q_board_paper_kraft_A 
rename II gp_v_board_paper_kraft_A  
rename IJ gp_q_board_paper_kraft_B  
rename IK gp_v_board_paper_kraft_B  
rename IL gp_q_board_paper_kraft_C  
rename IM gp_v_board_paper_kraft_C  
rename IN gp_q_board_paper_other_A  
rename IO gp_v_board_paper_other_A   
rename IP gp_q_board_paper_other_B   
rename IQ gp_v_board_paper_other_B   
rename IR gp_q_board_paper_other_C   
rename IS gp_v_board_paper_other_C   
rename IT gp_q_board_paper_chip_A   
rename IU gp_v_board_paper_chip_A    
rename IV gp_q_board_paper_chip_B    
rename IW gp_v_board_paper_chip_B    
rename IX gp_q_board_paper_chip_C    
rename IY gp_v_board_paper_chip_C    
rename IZ gp_q_board_paper_straw_A    
rename JA gp_v_board_paper_straw_A     
rename JB gp_q_board_paper_straw_B     
rename JC gp_v_board_paper_straw_B     
rename JD gp_q_board_paper_straw_C     
rename JE gp_v_board_paper_straw_C     
rename JF gp_q_board_paper_folding_A     
rename JG gp_v_board_paper_folding_A      
rename JH gp_q_board_paper_folding_B      
rename JI gp_v_board_paper_folding_B      
rename JJ gp_q_board_paper_folding_C      
rename JK gp_v_board_paper_folding_C      
rename JL gp_q_board_paper_patent_A      
rename JM gp_v_board_paper_patent_A       
rename JN gp_q_board_paper_patent_B       
rename JO gp_v_board_paper_patent_B       
rename JP gp_q_board_paper_patent_C       
rename JQ gp_v_board_paper_patent_C       
rename JR gp_q_board_paper_other_folding_A       
rename JS gp_v_board_paper_other_folding_A        
rename JT gp_q_board_paper_other_folding_B        
rename JU gp_v_board_paper_other_folding_B        
rename JV gp_q_board_paper_other_folding_C        
rename JW gp_v_board_paper_other_folding_C        
rename JX gp_q_board_paper_setup_box_A        
rename JY gp_v_board_paper_setup_box_A         
rename JZ gp_q_board_paper_setup_box_B         
rename KA gp_v_board_paper_setup_box_B         
rename KB gp_q_board_paper_setup_box_C         
rename KC gp_v_board_paper_setup_box_C         
rename KD gp_q_board_paper_news_A         
rename KE gp_v_board_paper_news_A          
rename KF gp_q_board_paper_news_B          
rename KG gp_v_board_paper_news_B          
rename KH gp_q_board_paper_news_C          
rename KI gp_v_board_paper_news_C          
rename KJ gp_q_board_paper_other_D	          
rename KK gp_v_board_paper_other_D          
rename KL gp_q_board_paper_other_E           
rename KM gp_v_board_paper_other_E           
rename KN gp_q_board_paper_other_F           
rename KO gp_v_board_paper_other_F           
rename KP gp_q_board_paper_wall_A           
rename KQ gp_v_board_paper_wall_A            
rename KR gp_q_board_paper_wall_B            
rename KS gp_v_board_paper_wall_B            
rename KT gp_q_board_paper_wall_C            
rename KU gp_v_board_paper_wall_C            
rename KV gp_q_board_paper_insulating_A            
rename KW gp_v_board_paper_insulating_A             
rename KX gp_q_board_paper_insulating_B             
rename KY gp_v_board_paper_insulating_B             
rename KZ gp_q_board_paper_insulating_C             
rename LA gp_v_board_paper_insulating_C             
rename LB gp_s_board_paper_other_2             
rename LC gp_q_board_paper_other_2_A              
rename LD gp_v_board_paper_other_2_A              
rename LE gp_q_board_paper_other_2_B              
rename LF gp_v_board_paper_other_2_B              
rename LG gp_q_board_paper_other_2_C              
rename LH gp_v_board_paper_other_2_C              
rename LI gp_s_board_paper_other_3              
rename LJ gp_q_board_paper_other_3_A              
rename LK gp_v_board_paper_other_3_A              
rename LL gp_q_board_paper_other_3_B              
rename LM gp_v_board_paper_other_3_B              
rename LN gp_q_board_paper_other_3_C              
rename LO gp_v_board_paper_other_3_C              
rename LP gp_s_board_paper_other_4              
rename LQ gp_q_board_paper_other_4_A               
rename LR gp_v_board_paper_other_4_A               
rename LS gp_q_board_paper_other_4_B               
rename LT gp_v_board_paper_other_4_B              
rename LU gp_q_board_paper_other_4_C               
rename LV gp_v_board_paper_other_4_C               
rename LW gp_q_board_paper_binders_A               
rename LX gp_v_board_paper_binders_A                
rename LY gp_q_board_paper_binders_B                
rename LZ gp_v_board_paper_binders_B                
rename MA gp_q_board_paper_binders_C                
rename MB gp_v_board_paper_binders_C                
rename MC gp_q_cardboard_bristol_A
rename MD gp_v_cardboard_bristol_A 
rename ME gp_q_cardboard_bristol_B 
rename MF gp_v_cardboard_bristol_B 
rename MG gp_q_cardboard_bristol_C 
rename MH gp_v_cardboard_bristol_C 
rename MI gp_q_cardboard_other_A 
rename MJ gp_v_cardboard_other_A  
rename MK gp_q_cardboard_other_B  
rename ML gp_v_cardboard_other_B  
rename MM gp_q_cardboard_other_C  
rename MN gp_v_cardboard_other_C  
rename MO gp_q_cardboard_leather_A  
rename MP gp_v_cardboard_leather_A   
rename MQ gp_q_cardboard_leather_B   
rename MR gp_v_cardboard_leather_B   
rename MS gp_q_cardboard_leather_C   
rename MT gp_v_cardboard_leather_C   
rename MU gp_q_cardboard_press_A   
rename MV gp_v_cardboard_press_A    
rename MW gp_q_cardboard_press_B    
rename MX gp_v_cardboard_press_B    
rename MY gp_q_cardboard_press_C    
rename MZ gp_v_cardboard_press_C    
rename NA gp_s_cardboard_other_2
rename NB gp_q_cardboard_other_2_A 
rename NC gp_v_cardboard_other_2_A 
rename ND gp_q_cardboard_other_2_B 
rename NE gp_v_cardboard_other_2_B 
rename NF gp_q_cardboard_other_2_C 
rename NG gp_v_cardboard_other_2_C 
rename NH gp_s_cardboard_other_3 
rename NI gp_q_cardboard_other_3_A  
rename NJ gp_v_cardboard_other_3_A  
rename NK gp_q_cardboard_other_3_B  
rename NL gp_v_cardboard_other_3_B  
rename NM gp_q_cardboard_other_3_C  
rename NN gp_v_cardboard_other_3_C  
rename NO gp_q_cardboard_tissue_A 
rename NP gp_v_cardboard_tissue_A  
rename NQ gp_q_cardboard_tissue_B  
rename NR gp_v_cardboard_tissue_B  
rename NS gp_q_cardboard_tissue_C  
rename NT gp_v_cardboard_tissue_C  
rename NU gp_q_tissue_paper_high_A   
rename NV gp_v_tissue_paper_high_A    
rename NW gp_q_tissue_paper_high_B    
rename NX gp_v_tissue_paper_high_B    
rename NY gp_q_tissue_paper_high_C    
rename NZ gp_v_tissue_paper_high_C    
rename OA gp_q_tissue_paper_manila_A     
rename OB gp_v_tissue_paper_manila_A      
rename OC gp_q_tissue_paper_manila_B      
rename OD gp_v_tissue_paper_manila_B      
rename OE gp_q_tissue_paper_manila_C      
rename OF gp_v_tissue_paper_manila_C      
rename OG gp_q_tissue_paper_napkin_A      
rename OH gp_v_tissue_paper_napkin_A       
rename OI gp_q_tissue_paper_napkin_B       
rename OJ gp_v_tissue_paper_napkin_B       
rename OK gp_q_tissue_paper_napkin_C       
rename OL gp_v_tissue_paper_napkin_C       
rename OM gp_q_tissue_paper_toilet_A       
rename ON gp_v_tissue_paper_toilet_A        
rename OO gp_q_tissue_paper_toilet_B        
rename OP gp_v_tissue_paper_toilet_B        
rename OQ gp_q_tissue_paper_toilet_C        
rename OR gp_v_tissue_paper_toilet_C        
rename OS gp_q_tissue_paper_towel_A        
rename OT gp_v_tissue_paper_towel_A         
rename OU gp_q_tissue_paper_towel_B         
rename OV gp_v_tissue_paper_towel_B         
rename OW gp_q_tissue_paper_towel_C         
rename OX gp_v_tissue_paper_towel_C         
rename OY gp_q_tissue_paper_waxing_A         
rename OZ gp_v_tissue_paper_waxing_A          
rename PA gp_q_tissue_paper_waxing_B          
rename PB gp_v_tissue_paper_waxing_B          
rename PC gp_q_tissue_paper_waxing_C          
rename PD gp_v_tissue_paper_waxing_C          
rename PE gp_q_absorbent_paper_blotting_A          
rename PF gp_v_absorbent_paper_blotting_A           
rename PG gp_q_absorbent_paper_blotting_B           
rename PH gp_v_absorbent_paper_blotting_B           
rename PI gp_q_absorbent_paper_blotting_C           
rename PJ gp_v_absorbent_paper_blotting_C           
rename PK gp_q_absorbent_paper_filter_A           
rename PL gp_v_absorbent_paper_filter_A            
rename PM gp_q_absorbent_paper_filter_B            
rename PN gp_v_absorbent_paper_filter_B            
rename PO gp_q_absorbent_paper_filter_C            
rename PP gp_v_absorbent_paper_filter_C            
rename PQ gp_q_absorbent_paper_matrix_A            
rename PR gp_v_absorbent_paper_matrix_A             
rename PS gp_q_absorbent_paper_matrix_B             
rename PT gp_v_absorbent_paper_matrix_B             
rename PU gp_q_absorbent_paper_matrix_C             
rename PV gp_v_absorbent_paper_matrix_C             
rename PW gp_q_absrbent_ppr_vlcn_A             
rename PX gp_v_absrbent_ppr_vlcn_A              
rename PY gp_q_absrbent_ppr_vlcn_B              
rename PZ gp_v_absrbent_ppr_vlcn_B              
rename QA gp_q_absrbent_ppr_vlcn_C              
rename QB gp_v_absrbent_ppr_vlcn_C              
rename QC gp_q_absorbent_paper_celluloid_A              
rename QD gp_v_absorbent_paper_celluloid_A               
rename QE gp_q_absorbent_paper_celluloid_B               
rename QF gp_v_absorbent_paper_celluloid_B               
rename QG gp_q_absorbent_paper_celluloid_C               
rename QH gp_v_absorbent_paper_celluloid_C               
rename QI gp_q_absorbent_paper_parchment_A               
rename QJ gp_v_absorbent_paper_parchment_A                
rename QK gp_q_absorbent_paper_parchment_B                
rename QL gp_v_absorbent_paper_parchment_B                
rename QM gp_q_absorbent_paper_parchment_C                
rename QN gp_v_absorbent_paper_parchment_C                
rename QO gp_s_absorbent_paper_other_1               
rename QP gp_q_absorbent_paper_other_1_A                
rename QQ gp_v_absorbent_paper_other_1_A                
rename QR gp_q_absorbent_paper_other_1_B                
rename QS gp_v_absorbent_paper_other_1_B                
rename QT gp_q_absorbent_paper_other_1_C                
rename QU gp_v_absorbent_paper_other_1_C                
rename QV gp_s_absorbent_paper_other_2                
rename QW gp_q_absorbent_paper_other_2_A                 
rename QX gp_v_absorbent_paper_other_2_A                 
rename QY gp_q_absorbent_paper_other_2_B                 
rename QZ gp_v_absorbent_paper_other_2_B                 
rename RA gp_q_absorbent_paper_other_2_C                 
rename RB gp_v_absorbent_paper_other_2_C                 
rename RC gp_s_absorbent_paper_other_3                 
rename RD gp_q_absorbent_paper_other_3_A                  
rename RE gp_v_absorbent_paper_other_3_A                  
rename RF gp_q_absorbent_paper_other_3_B                  
rename RG gp_v_absorbent_paper_other_3_B                  
rename RH gp_q_absorbent_paper_other_3_C                  
rename RI gp_v_absorbent_paper_other_3_C                  
rename RJ gp_q_building_paper_sheathing_A 
rename RK gp_v_building_paper_sheathing_A  
rename RL gp_q_building_paper_sheathing_B  
rename RM gp_v_building_paper_sheathing_B  
rename RN gp_q_building_paper_sheathing_C  
rename RO gp_v_building_paper_sheathing_C  
rename RP gp_q_building_paper_felt_A  
rename RQ gp_v_building_paper_felt_A   
rename RR gp_q_building_paper_felt_B   
rename RS gp_v_building_paper_felt_B   
rename RT gp_q_building_paper_felt_C   
rename RU gp_v_building_paper_felt_C   
rename RV gp_q_building_paper_asbestos_A   
rename RW gp_v_building_paper_asbestos_A    
rename RX gp_q_building_paper_asbestos_B    
rename RY gp_v_building_paper_asbestos_B    
rename RZ gp_q_building_paper_asbestos_C    
rename SA gp_v_building_paper_asbestos_C    
rename SB gp_s_building_paper_other_1    
rename SC gp_q_building_paper_other_1_A     
rename SD gp_v_building_paper_other_1_A     
rename SE gp_q_building_paper_other_1_B     
rename SF gp_v_building_paper_other_1_B     
rename SG gp_q_building_paper_other_1_C     
rename SH gp_v_building_paper_other_1_C     
rename SI gp_s_building_paper_other_2     
rename SJ gp_q_building_paper_other_2_A     
rename SK gp_v_building_paper_other_2_A
rename SL gp_q_building_paper_other_2_B     
rename SM gp_v_building_paper_other_2_B     
rename SN gp_q_building_paper_other_2_C     
rename SO gp_v_building_paper_other_2_C     
rename SP gp_s_other_paper_1     
rename SQ gp_q_other_paper_1_A 
rename SR gp_v_other_paper_1_A 
rename SS gp_q_other_paper_1_B 
rename ST gp_v_other_paper_1_B 
rename SU gp_q_other_paper_1_C 
rename SV gp_v_other_paper_1_C 
rename SW gp_s_other_paper_2 
rename SX gp_q_other_paper_2_A 
rename SY gp_v_other_paper_2_A 
rename SZ gp_q_other_paper_2_B 
rename TA gp_v_other_paper_2_B 
rename TB gp_q_other_paper_2_C 
rename TC gp_v_other_paper_2_C 
rename TD gp_q_total_paper_A 
rename TE gp_v_total_paper_A  
rename TF gp_q_total_paper_B  
rename TG gp_v_total_paper_B  
rename TH gp_q_total_paper_C  
rename TI gp_v_total_paper_C  
rename TJ gp_q_converted_paper_kraft
rename TK gp_v_converted_paper_kraft 
rename TL gp_q_converted_paper_other 
rename TM gp_v_converted_paper_other 
rename TN gp_q_boxes_corregated
rename TO gp_v_boxes_corregated 
rename TP gp_q_boxes_solid 
rename TQ gp_v_boxes_solid
rename TR gp_q_cartons 
rename TS gp_v_cartons 
rename TT gp_q_setup_paper 
rename TU gp_v_setup_paper 
rename TV gp_q_paper_cans 
rename TW gp_v_paper_cans 
rename TX gp_q_decorated_paper 
rename TY gp_v_decorated_paper 
rename TZ gp_s_converted_paper_other_1 
rename UA gp_q_converted_paper_other_1 
rename UB gp_v_converted_paper_other_1 
rename UC gp_s_converted_paper_other_2 
rename UD gp_q_converted_paper_other_2 
rename UE gp_v_converted_paper_other_2 
rename UF gp_s_converted_paper_other_3 
rename UG gp_q_converted_paper_other_3 
rename UH gp_v_converted_paper_other_3 
rename UI gp_v_cardboard_paper_converted 
rename UJ gp_q_cardboard_paper_converted  
rename UK gp_q_cigarette_paper 
rename UL gp_v_cigarette_paper  
rename UM gp_q_coated_book_paper
rename UN gp_v_coated_book_paper 
rename UO gp_q_crepe_paper 
rename UP gp_v_crepe_paper
rename UQ gp_q_file_folders 
rename UR gp_v_file_folders 
rename US gp_q_glazed_paper 
rename UT gp_v_glazed_paper
rename UU gp_q_napkins 
rename UV gp_v_napkins
rename UW gp_q_papeleries 
rename UX gp_v_papeleries
rename UY gp_q_roofing_paper 
rename UZ gp_v_roofing_paper 
rename VA gp_q_tablets_book
rename VB gp_v_tablets_book 
rename VC gp_q_tablets_news 
rename VD gp_v_tablets_news 
rename VE gp_q_tablets_writing 
rename VF gp_v_tablets_writing 
rename VG gp_s_tablets_other_1 
rename VH gp_q_tablets_other_1  
rename VI gp_v_tablets_other_1  
rename VJ gp_s_tablets_other_2  
rename VK gp_q_tablets_other_2  
rename VL gp_v_tablets_other_2  
rename VM gp_q_toilet_paper 
rename VN gp_v_toilet_paper 
rename VO gp_q_towels 
rename VP gp_v_towels 
rename VQ gp_q_twisted_paper 
rename VR gp_v_twister_paper 
rename VS gp_q_waterproof_wrapping 
rename VT gp_v_waterproof_wrapping 
rename VU gp_q_waxed_paper 
rename VV gp_v_waxed_paper 
rename VW gp_s_converted_paper_other_4 
rename VX gp_q_converted_paper_other_4  
rename VY gp_v_converted_paper_other_4  
rename VZ gp_s_converted_paper_other_5  
rename WA gp_q_converted_paper_other_5  
rename WB gp_v_converted_paper_other_5  
rename WC gp_v_total_converted_paper 
rename WD gp_s_other1 
rename WE gp_v_other1  
rename WF gp_s_other2 
rename WG gp_v_other2  
rename WH g000v

//rename equipment variables
rename WI z_equipment_newsprint_fourdr_num 
rename WJ z_equipment_newsprint_fourdr_cap
rename WK z_equipment_newsprint_cyl_num 
rename WL z_equipment_newsprint_cyl_cap
rename WM z_equipment_bookpaper_fourdr_num
rename WN z_equipment_bookpaper_fourdr_cap
rename WO z_equipment_bookpaper_cyl_num  
rename WP z_equipment_bookpaper_cyl_cap  
rename WQ z_equipment_coverppr_fourdr_num  
rename WR z_equipment_coverppr_fourdr_cap  
rename WS z_equipment_coverppr_cyl_num   
rename WT z_equipment_coverppr_cyl_cap   
rename WU z_equipment_wrtngppr_fourdr_num  
rename WV z_equipment_wrtngppr_fourdr_cap
rename WW z_equipment_wrtngppr_cyl_num 
rename WX z_equipment_wrtngppr_cyl_cap
rename WY z_equipment_wrppngppr_fourdr_num 
rename WZ z_equipment_wrppngppr_fourdr_cap 
rename XA z_equipment_wrppngppr_cyl_num 
rename XB z_equipment_wrppngppr_cyl_cap 
rename XC z_equipment_boards_fourdr_num 
rename XD z_equipment_boards_fourdr_cap 
rename XE z_equipment_boards_cyl_num
rename XF z_equipment_boards_cyl_cap 
rename XG z_equipment_tissueppr_fourdr_num 
rename XH z_equipment_tissueppr_fourdr_cap 
rename XI z_equipment_tissueppr_cyl_num 
rename XJ z_equipment_tissueppr_cyl_cap 
rename XK z_equipment_absrbppr_fourdr_num
rename XL z_equipment_absrbppr_fourdr_cap 
rename XM z_equipment_absrbppr_cyl_num
rename XN z_equipment_absrbppr_cyl_cap 
rename XO z_equipment_bldppr_fourdr_numb
rename XP z_equipment_bldppr_fourdr_cap 
rename XQ z_equipment_bldppr_cyl_num 
rename XR z_equipment_bldppr_cyl_cap 
rename XS z_equipment_otherpaper
rename XT z_equipment_otherppr_fourdr_num 
rename XU z_equipment_otherppr_fourdr_cap 
rename XV z_equipment_otherppr_cyl_num
rename XW z_equipment_otherppr_cyl_cap
