//rename variables for industry 104 in year 1931

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

/* These are not renamed because not sure if actually filled in
rename AN gp_v_
rename AO gp_v_
rename AP gp_v_
rename AQ gp_v_
rename AR gp_v_
rename AS gp_v_
rename AT gp_v_
rename AU gp_v_
rename AV gp_v_
rename AW gp_v_
rename AX gp_v_
rename AY gp_v_
rename AZ gp_v_
rename BA gp_v_
rename BB gp_v_
rename BC gp_v_
rename BD gp_v_
rename BE gp_v_
rename BF gp_v_
rename BG gp_v_
rename BH gp_v_
rename BI gp_v_
rename BJ gp_v_
rename BK gp_v_
rename BL gp_v_
rename BM gp_v_
rename BN gp_v_
rename BO gp_v_
rename BP gp_v_
rename BQ gp_v_
rename BR gp_v_
rename BS gp_v_
rename BT gp_v_
rename BU gp_v_
rename BV gp_v_
rename BW gp_v_
rename BX gp_v_
rename BY gp_v_
rename BZ gp_v_
rename CA gp_v_
rename CB gp_v_
rename CC gp_v_
rename CD gp_v_
rename CE gp_v_
rename CF gp_v_
rename CG gp_v_
rename CH gp_v_
rename CI gp_v_
rename CJ gp_v_
rename CK gp_v_
rename CL gp_v_
rename CM gp_v_
rename CN gp_v_
rename CO gp_v_
rename CP gp_v_
rename CQ gp_v_
rename CR gp_v_
rename CS gp_v_
rename CT gp_v_
rename CU gp_v_
rename CV gp_v_
rename CW gp_v_
rename CX gp_v_
rename CY gp_v_
rename CZ gp_v_
rename DA gp_v_
rename DB gp_v_
rename DC gp_v_
rename DD gp_v_
rename DE gp_v_
rename DF gp_v_
rename DG gp_v_
rename DH gp_v_
rename DI gp_v_
rename DJ gp_v_
rename DK gp_v_
rename DL gp_v_
rename DM gp_v_
rename DN gp_v_
rename DO gp_v_
rename DP gp_v_
rename DQ gp_v_
rename DR gp_v_
rename DS gp_v_
rename DT gp_v_
rename DU gp_v_
rename DV gp_v_
rename DW gp_v_
rename DX gp_v_
rename DY gp_v_
rename DZ gp_v_
rename EA gp_v_
rename EB gp_v_
rename EC gp_v_
rename ED gp_v_
rename EE gp_v_
rename EF gp_v_
rename EG gp_v_
rename EH gp_v_
rename EI gp_v_
rename EJ gp_v_
rename EK gp_v_
rename EL gp_v_
rename EM gp_v_
rename EN gp_v_
rename EO gp_v_
rename EP gp_v_
rename EQ gp_v_
rename ER gp_v_
rename ES gp_v_
rename ET gp_v_
rename EU gp_v_
rename EV gp_v_
rename EW gp_v_
rename EX gp_v_
rename EY gp_v_
rename EZ gp_v_
rename FA gp_v_
rename FB gp_v_
rename FC gp_v_
rename FD gp_v_
rename FE gp_v_
rename FF gp_v_
rename FG gp_v_
rename FH gp_v_
rename FI gp_v_
rename FJ gp_v_
rename FK gp_v_
rename FL gp_v_
rename FM gp_v_
rename FN gp_v_
rename FO gp_v_
rename FP gp_v_
rename FQ gp_v_
rename FR gp_v_
rename FS gp_v_
*/
//once rename should take this line out
drop AN-FS

//rename output variables
rename FT gp_q_smokedFish_Finnan
rename FU gp_v_smokedFish_Finnan
rename FV gp_q_smokedFish_Herring
rename FW gp_v_smokedFish_Herring
rename FX gp_q_smokedFish_Salmon
rename FY gp_v_smokedFish_Salmon
rename FZ gp_s_smokedFish_Other
rename GA gp_q_smokedFish_Other
rename GB gp_v_smokedFish_Other
rename GC gp_q_driedFish_Cod
rename GD gp_v_driedFish_Cod
rename GE gp_q_driedFish_Herring
rename GF gp_v_driedFish_Herring
rename GG gp_s_driedFish_Other
rename GH gp_q_driedFish_Other
rename GI gp_v_driedFish_Other
rename GJ gp_q_saltedFish_Cod
rename GK gp_v_saltedFish_Cod
rename GL gp_q_saltedFish_Haddock
rename GM gp_v_saltedFish_Haddock
rename GN gp_q_saltedFish_Herring
rename GO gp_v_saltedFish_Herring
rename GP gp_q_saltedFish_Mackerel
rename GQ gp_v_saltedFish_Mackerel
rename GR gp_q_saltedFish_Salmon
rename GS gp_v_saltedFish_Salmon
rename GT gp_s_saltedFish_Other1
rename GU gp_q_saltedFish_Other1
rename GV gp_v_saltedFish_Other1
rename GW gp_s_saltedFish_Other2
rename GX gp_q_saltedFish_Other2
rename GY gp_v_saltedFish_Other2
rename GZ gp_s_saltedFish_Other3
rename HA gp_q_saltedFish_Other3
rename HB gp_v_saltedFish_Other3
rename HC gp_s_saltedFish_Other4
rename HD gp_q_saltedFish_Other4
rename HE gp_v_saltedFish_Other4
rename HF gp_s_saltedFish_Other5
rename HG gp_q_saltedFish_Other5
rename HH gp_v_saltedFish_Other5
rename HI gp_q_bonelessFish_Cod
rename HJ gp_v_bonelessFish_Cod
rename HK gp_q_bonelessFish_Haddock
rename HL gp_v_bonelessFish_Haddock
rename HM gp_s_bonelessFish_Other1
rename HN gp_q_bonelessFish_Other1
rename HO gp_v_bonelessFish_Other1
rename HP gp_s_bonelessFish_Other2
rename HQ gp_q_bonelessFish_Other2
rename HR gp_v_bonelessFish_Other2
rename HS gp_s_bonelessFish_Other3
rename HT gp_q_bonelessFish_Other3
rename HU gp_v_bonelessFish_Other3
rename HV gp_s_bonelessFish_Other4
rename HW gp_q_bonelessFish_Other4
rename HX gp_v_bonelessFish_Other4
rename HY gp_s_bonelessFish_Other5
rename HZ gp_q_bonelessFish_Other5
rename IA gp_v_bonelessFish_Other5
rename IB gp_s_bonelessFish_Other6
rename IC gp_q_bonelessFish_Other6
rename ID gp_v_bonelessFish_Other6
rename IE gp_q_fishOil
rename IF gp_v_fishOil
rename IG gp_q_fishScrap_dried
rename IH gp_v_fishScrap_dried
rename II gp_q_fishScrap_green
rename IJ gp_v_fishScrap_green
rename IK gp_q_fertilizer
rename IL gp_v_fertilizer
rename IM gp_q_liquidGlue
rename IN gp_v_liquidGlue
rename IO gp_q_crushedOysterShells
rename IP gp_v_crushedOysterShells
rename IQ gp_q_oysterShellLine
rename IR gp_v_oysterShellLine
rename IS gp_s_other1
rename IT gp_q_other1
rename IU gp_v_other1
rename IV gp_s_other2
rename IW gp_q_other2
rename IX gp_v_other2
rename IY gp_s_other3
rename IZ gp_q_other3
rename JA gp_v_other3
rename JB gp_s_other4
rename JC gp_q_other4
rename JD gp_v_other4
rename JE g000v
