//Cleaning script for BR spreadsheet: 631_1931. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1931/631"
import excel "`data_dir'/063131A0.xls", allstring sheet("063131A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture replace record = lower(record)
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F statenm
capture rename G cntynm
capture rename H citynm
capture rename I indnm
capture rename J formnm
capture rename K plntname
capture rename L ownrname
capture rename M incyn
capture rename N a004
capture rename O state
capture rename P city
capture rename Q county
capture rename R street
capture rename S othraddr
capture rename T incityyn
capture rename U othrcity
capture rename V sbsdryyn
capture rename W mthrinfo
capture rename X nmchngyn
capture rename Y lnchngyn
capture rename Z owchngyn
capture rename AA as004
capture rename AB frmrinfo
capture rename AC products
capture rename AD mtlsusd1
capture rename AE mtlsusd2
capture rename AF bgndt3
capture rename AG enddt3

//rename utilization variables
capture rename AH d001
capture rename AI d005
capture rename AJ d006
capture drop AK

//rename employment variables
capture rename AL wetotal
capture rename AM diff
capture rename AN wejanuary
capture rename AO wefebruary
capture rename AP wemarch
capture rename AQ weapril
capture rename AR wemay
capture rename AS wejune
capture rename AT wejuly
capture rename AU weaugust
capture rename AV weseptembe
capture rename AW weoctober
capture rename AX wenovember
capture rename AY wedecember
capture rename AZ wages_paid

//rename costs of inputs variables
capture rename BA f009
capture rename BB f004
capture drop BC
capture rename BD f008
capture rename BE diff1

//rename output variables
capture rename BF gp_q_toilet_soap
capture rename BG gp_v_toilet_soap
capture rename BH gp_q_shaving_soap
capture rename BI gp_v_shaving_soap
capture rename BJ gp_q_laundry_soap_white
capture rename BK gp_v_laundry_soap_white
capture rename BL gp_q_laundry_soap_yellow
capture rename BM gp_v_laundry_soap_yellow
capture rename BN gp_q_foot_soap
capture rename BO gp_v_foot_soap
capture rename BP gp_q_soap_chip
capture rename BQ gp_v_soap_chip
capture rename BR gp_q_granulated_soap
capture rename BS gp_v_granulated_soap
capture rename BT gp_s_other_hard_soap1
capture rename BU gp_q_other_hard_soap1
capture rename BV gp_v_other_hard_soap1
capture rename BW gp_s_other_hard_soap2
capture rename BX gp_q_other_hard_soap2
capture rename BY gp_v_other_hard_soap2
capture rename BZ gp_s_other_hard_soap3
capture rename CA gp_q_other_hard_soap3
capture rename CB gp_v_other_hard_soap3
capture rename CC gp_s_other_hard_soap4
capture rename CD gp_q_other_hard_soap4
capture rename CE gp_v_other_hard_soap4
capture rename CF gp_q_shaving_cream
capture rename CG gp_v_shaving_cream
capture rename CH gp_q_shaving_powder
capture rename CI gp_v_shaving_powder
capture rename CJ gp_q_soap_powder
capture rename CK gp_v_soap_powder
capture rename CL gp_q_cleansers_soap
capture rename CM gp_v_cleansers_soap
capture rename CN gp_q_cleansers_no_soap
capture rename CO gp_v_cleansers_no_soap
capture rename CP gp_q_liquid_soap
capture rename CQ gp_v_liquid_soap
capture rename CR gp_q_paste_soap
capture rename CS gp_v_paste_soap
capture rename CT gp_q_soft_soap
capture rename CU gp_v_soft_soap
capture rename CV gp_s_other_soap1
capture rename CW gp_q_other_soap1
capture rename CX gp_v_other_soap1
capture rename CY gp_s_other_soap2
capture rename CZ gp_q_other_soap2
capture rename DA gp_v_other_soap2
capture rename DB gp_q_soap_stock
capture rename DC gp_v_soap_stock
capture rename DD gp_q_glycerin_crude
capture rename DE gp_v_glycerin_crude
capture rename DF gp_q_glycerin_refined
capture rename DG gp_v_glycerin_refined
capture rename DH gp_q_stearin
capture rename DI gp_v_stearin
capture rename DJ gp_q_steraic_acid
capture rename DK gp_v_steraic_acid
capture rename DL gp_q_red_oil
capture rename DM gp_v_red_oil
capture rename DN gp_q_candles
capture rename DO gp_v_candles
capture rename DP gp_q_insecticide
capture rename DQ gp_v_insecticide
capture rename DR gp_q_sodium_sil1
capture rename DS gp_v_sodium_sil1
capture rename DT gp_v_sodium_sil2
capture rename DU gp_v_perfume
capture rename DV gp_v_toilet_water
capture rename DW gp_v_cream
capture rename DX gp_v_rouge
//missing some other products as well as total value of output

capture drop year
capture gen year = 1931
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1931/631/631_1931", replace
