//Cleaning script for BR spreadsheet: 312_1931. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals reference.
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1931/312"
import excel "`data_dir'/031231A0.xls", allstring sheet("031231A0") clear

drop in 1 // this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture replace record = lower(record)
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L plntname
capture rename M ownrname
capture rename N incyn
capture rename O a004
capture rename P state
capture rename Q city
capture rename R county
capture rename S street
capture rename T othraddr
capture rename U incityyn
capture rename V othrcity
capture rename W sbsdryyn
capture rename X mthrinfo
capture rename Y nmchngyn
capture rename Z as002
capture rename AA as003
capture rename AB as004
capture rename AC frmrinfo
capture rename AD products
capture rename AE mtlsusd1
capture rename AF mtlsusd2
capture rename AG bgndt3
capture rename AH enddt3

//rename utilization variables
capture rename AI d001
capture rename AJ d005
capture rename AK d006
capture drop AL

//rename employment variables
capture rename AM wetotal
capture drop AN //column name: diff
capture rename AO wejanuary
capture rename AP wefebruary
capture rename AQ wemarch
capture rename AR weapril
capture rename AS wemay
capture rename AT wejune
capture rename AU wejuly
capture rename AV weaugust
capture rename AW weseptembe
capture rename AX weoctober
capture rename AY wenovember
capture rename AZ wedecember
capture rename BA e005s

//rename costs of input variables
capture rename BB f009
capture rename BC f004
capture drop BD
capture rename BE f008
capture drop BF //column name: diff1

//rename output variable
capture rename BG gp_u_match_strikeAnywhere
capture rename BH gp_ave_match_strikeAnywhere
capture rename BI gp_q_match_strikeAnywhere
capture rename BJ gp_v_match_strikeAnywhere
capture rename BK gp_s_match_strikeAnywhere_other
capture rename BL gp_u_match_strikeAnywhere_other
capture rename BM gp_ave_match_strikeAnywhere_other
capture rename BN gp_q_match_strikeAnywhere_other
capture rename BO gp_v_match_strikeAnywhere_other
capture rename BP gp_u_match_safety_inBox
capture rename BQ gp_ave_match_safety_inBox
capture rename BR gp_q_match_safety_inBox
capture rename BS gp_v_match_safety_inBox
capture rename BT gp_u_match_safety_inBook
capture rename BU gp_ave_match_safety_inBook
capture rename BV gp_q_match_safety_inBook
capture rename BW gp_v_match_safety_inBook
capture rename BX gp_s_match_safety_other
capture rename BY gp_u_match_safety_other
capture rename BZ gp_ave_match_safety_other
capture rename CA gp_q_match_safety_other
capture rename CB gp_v_match_safety_other
capture rename CC gp_allOther
capture drop CD 
capture drop CE
capture rename CF totalval
//these shoudl probably be sorted out eventually
capture drop CG - DX


capture drop year
gen year = 1931
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1931/312/312_1931", replace
