//Cleaning script for BR spreadsheet: 237_1931. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals 
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code .

local data_dir = "$rootDir_sheets/1931/237"
import excel "`data_dir'/023731A0.xls", allstring sheet("023731A0") clear

drop in 1 // this row has variable names in it
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture replace record = lower(record)
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I indnm
capture rename J formnm
capture rename K plntname
capture rename L ownrname
capture rename M incyn
capture rename N a004
capture rename O state
capture rename P city
capture rename Q county
capture rename R street
capture rename S othraddr
capture rename T incityyn
capture rename U othrcity
capture rename V sbsdryyn
capture rename W mthrinfo
capture rename X as001
capture rename Y as002
capture rename Z as003
capture rename AA as004
capture rename AB as005
capture rename AC products
capture rename AD mtlsusd1
capture rename AE mtlsusd2
capture rename AF bgndt3
capture rename AG enddt3
capture rename AH d001
capture rename AI d005
capture rename AJ d006
capture drop AK

//rename employment variables
capture rename AL wetotal
capture drop AM //column name: diff
capture rename AN wejan
capture rename AO wefeb
capture rename AP wemar
capture rename AQ weapr
capture rename AR wemay
capture rename AS wejun
capture rename AT wejul
capture rename AU weaug
capture rename AV wesep
capture rename AW weoct
capture rename AX wenov
capture rename AY wedec
capture rename AZ e005s
capture rename BA f009
capture rename BB f004
capture drop BC
capture rename BD f008
capture drop BE //column name: diff1

//rename output variables
capture rename BF gp_q_general1
capture rename BG gp_v_general1
capture rename BH gp_q_general2
capture rename BI gp_v_general2
capture rename BJ gp_q_general3
capture rename BK gp_v_general3
capture rename BL gp_q_general4
capture rename BM gp_v_general4
capture rename BN gp_q_general5
capture rename BO gp_v_general5
capture rename BP gp_q_general6
capture rename BQ gp_v_general6
capture rename BR gp_q_general7
capture rename BS gp_v_general7
capture rename BT gp_q_general8
capture rename BU gp_v_general8
capture rename BV gp_q_general9
capture rename BW gp_v_general9
capture rename BX gp_q_general10
capture rename BY gp_v_general10
capture rename BZ gp_q_general11
capture rename CA gp_v_general11

//this is a stub
capture drop CB-DX
/*_(8/4)_l
capture rename CC 11val
capture rename CD 12_(8/4)_>
capture rename CE 12val
capture rename CF 13qty
capture rename CG 13val
capture rename CH 14qty
capture rename CI 14val
capture rename CJ 15_ls_.050
capture rename CK 15val
capture rename CL 16_>=_.050
capture rename CM 16val
capture rename CN 17_enamele
capture rename CO 17val
capture rename CP 18_table_a
capture rename CQ 18val
capture rename CR 19_wall_..
capture rename CS 19val
capture rename CT 20_light_g
capture rename CU 20val
capture rename CV 21_heavy_g
capture rename CW 21val
capture rename CX 22_olr
capture rename CY 22qty
capture rename CZ 22val
capture rename DA 23_olr
capture rename DB 23qty
capture rename DC 23val
capture rename DD 24_olr
capture rename DE 24qty
capture rename DF 24val
capture rename DG 25_op01
capture rename DH 25qty
capture rename DI 25val
capture rename DJ 26_op02
capture rename DK 26qty
capture rename DL 26val
capture rename DM 27_op03
capture rename DN 27qty
capture rename DO 27val
capture rename DP 28_op04
capture rename DQ 28qty
capture rename DR 28val
capture rename DS 29_op05
capture rename DT 29qty
capture rename DU 29val
capture rename DV 30_op06
capture rename DW 30qty
capture rename DX 30val
*/

capture drop year
gen year =  1931
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace

save "$rootDir_dataBR/1931/237/237_1931", replace
