//Cleaning script for BR spreadsheet: 705_1931. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced.
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1931/705"
import excel "`data_dir'/070531A0_PDSPL.xls", allstring sheet("070531A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
replace record=lower(record)
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I indnm
capture rename J formnm
capture rename K plntname
capture rename L ownrname
capture rename M incyn
capture rename N gopoaddr
capture rename O state
capture rename P city
capture rename Q county
capture rename R street
capture rename S a004
capture rename T incityyn
capture rename U othrcity
capture rename V sbsdryyn
capture rename W mthrinfo
capture rename X nmchngyn
capture rename Y lnchngyn
capture rename Z owchngyn
capture rename AA as004
capture rename AB frmrinfo
capture rename AC products
capture rename AD mtlsusd1
capture rename AE mtlsusd2
capture rename AF bgndt3
capture rename AG enddt3

//rename utilization variables
capture rename AH d001
capture rename AI d005
capture rename AJ d006
capture drop AK

//rename employment variables
capture rename AL wetotal
capture rename AM wejan
capture rename AN wefeb
capture rename AO wemar
capture rename AP weapr
capture rename AQ wemay
capture rename AR wejun
capture rename AS wejul
capture rename AT weaug
capture rename AU wesep
capture rename AV weoct
capture rename AW wenov
capture rename AX wedec
capture rename AY e005s

//rename input cost variables
capture rename AZ f009
capture rename BA f004
capture drop BB
capture rename BC f008

//rename output variables
capture rename BD gp_q_gasoline
capture rename BE gp_v_gasoline
capture rename BF gp_q_napththa
capture rename BG gp_v_napththa
capture rename BH gp_q_benzine
capture rename BI gp_v_benzine
capture rename BJ gp_q_tops
capture rename BK gp_v_tops
capture rename BL gp_q_illuminating_oil
capture rename BM gp_v_illuminating_oil
capture rename BN gp_q_distillate
capture rename BO gp_v_distillate
capture rename BP gp_q_gas_oils
capture rename BQ gp_v_gas_oils
capture rename BR gp_q_residual_fuel_oils
capture rename BS gp_v_residual_fuel_oils
capture rename BT gp_q_above_fuel_oil
capture rename BU gp_v_above_fuel_oil
capture rename BV gp_q_at_fuel_oil
capture rename BW gp_v_at_fuel_oil
capture rename BX gp_q_below_fuel_oil
capture rename BY gp_v_below_fuel_oil
capture rename BZ gp_q_pale_or_paraffin
capture rename CA gp_v_pale_or_paraffin
capture rename CB gp_q_red_or_neutral
capture rename CC gp_v_red_or_neutral
capture rename CD gp_q_cylinder_oil
capture rename CE gp_v_cylinder_oil
capture rename CF gp_q_all_other_lubricating_oil
capture rename CG gp_v_all_other_lubricating_oil
capture rename CH gp_q_liquid_asphalt
capture rename CI gp_v_liquid_asphalt
capture rename CJ gp_q_residuum_or_tar
capture rename CK gp_v_residuum_or_tar
capture rename CL gp_q_petrolatum
capture rename CM gp_v_petrolatum
capture rename CN gp_q_petrolatum_lubricating
capture rename CO gp_v_petrolatum_lubricating
capture rename CP gp_q_axle_grease
capture rename CQ gp_v_axle_grease
capture rename CR gp_q_paraffin_wax
capture rename CS gp_v_paraffin_wax
capture rename CT gp_q_acid_oil
capture rename CU gp_v_acid_oil
capture rename CV gp_q_liquefied_petroleum_gas
capture rename CW gp_v_liquefied_petroleum_gas
capture rename CX gp_q_asphalt_other
capture rename CY gp_v_asphalt_other
capture rename CZ gp_q_coke
capture rename DA gp_v_coke
capture rename DB gp_q_insecticides
capture rename DC gp_v_insecticides
capture rename DD gp_s_otherRefinery1
capture rename DE gp_q_otherRefinery1
capture rename DF gp_v_otherRefinery1
capture rename DG gp_s_other1
capture rename DH gp_q_other1
capture rename DI gp_v_other1
capture rename DJ receipts_for_contract_work
capture drop DK
capture rename DL total_value_output

//rename input variables
capture rename DM j_q_crude_petroleum
capture rename DN j_q_partly_refined_oils
capture rename DO j_q_purchased_natural_gas
capture rename DP j_q_extracted_natural_gas
capture rename DQ j_q_soda_ash
capture rename DR j_q_purchased_caustic_soda
capture rename DS j_q_made_caustic_soda
capture rename DT j_purchased_sufluric_acid
capture rename DU j_str_made_sufluric_acid
capture rename DV j_q_made_sufluric_acid
capture rename DW j_str_reclaimed_sufluric_acid
capture rename DX j_q_reclaimed_sufluric_acid
capture drop DY 

//rename man hours variables
capture rename DZ emh01
capture rename EA emh02
capture rename EB emh03
capture rename EC emh04
capture rename ED emh05
capture rename EE emh06
capture rename EF emh07
capture rename EG emh08
capture rename EH emh09
capture rename EI emh10
capture rename EJ emh11
capture rename EK emh12
capture rename EL emht

capture drop year
gen year = 1931
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1931/705/705_1931", replace
