//Cleaning script for BR spreadsheet: 1112_1931. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR.

local data_dir = "$rootDir_sheets/1931/1112"
import excel "`data_dir'/111231A0.xls", allstring sheet("111231A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture replace record = lower(record)
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F com
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L firm_code
capture rename M plntname
capture rename N ownrname
capture rename O incyn
capture rename P a004
capture rename Q state
capture rename R city
capture rename S county
capture rename T street
capture rename U othraddr
capture rename V incityyn
capture rename W othrcity
capture rename X sbsdryyn
capture rename Y mthrinfo
capture rename Z nmchngyn
capture rename AA lnchngyn
capture rename AB owchngyn
capture rename AC as004
capture rename AD frmrinfo
capture rename AE products
capture rename AF mtlsusd1
capture rename AG mtlsusd2
capture rename AH bgndt3
capture rename AI enddt3

//rename utilization variables
capture rename AJ d001
capture rename AK d005
capture rename AL d006
capture drop AM //column name: comment
capture drop AN

//rename employment variables
capture rename AO wetotal
capture drop AP //column name: diff
capture rename AQ wejan
capture rename AR wefeb
capture rename AS wemar
capture rename AT weapr
capture rename AU wemay
capture rename AV wejun
capture rename AW wejul
capture rename AX weaug
capture rename AY wesep
capture rename AZ weoct
capture rename BA wenov
capture rename BB wedec
capture rename BC e005s

//rename cost of inputs variables
capture rename BD f009
capture rename BE f005f
capture rename BF f004
capture drop BG
capture rename BH f008
capture rename BI //column name: diff1

//not sure why all of these variables are being dropped
capture drop BJ
capture drop BK
capture drop BL
capture drop BM
capture drop BN
capture drop BO
capture drop BP
capture drop BQ
capture drop BR
capture drop BS
capture drop BT
capture drop BU
capture drop BV
capture drop BW
capture drop BX
capture drop BY
capture drop BZ
capture drop CA
capture drop CB
capture drop CC
capture drop CD
capture drop CE
capture drop CF
capture drop CG
capture drop CH
capture drop CI
capture drop CJ
capture drop CK
capture drop CL
capture drop CM

save "$rootDir_dataBR/1931/1112/1112_1931_clean", replace

//now clean B spreadsheets
do "$rootDir_code/1931/clean_1112_1931_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1931/1112/1112_1931_clean", replace
merge 1:1 record using "$rootDir_dataBR/1931/1112/1112_1931_clean_B"
//this should really be a 1-1 mapping
drop _merge

capture drop year
gen year = 1931
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1931/1112/1112_1931_clean", replace
