//Cleaning script for BR "B" spreadsheet: 1112_1931. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referneced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1931/1112"
import excel "`data_dir'/111231B0.xls", allstring sheet("111231B0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

//rename identifying information variables
capture drop A //Column name in spreadsheet: *start
capture rename B record
capture replace record = lower(record)
//don't need these because will merge on record with A sheet
capture drop C //plntname
capture drop D //ownrname
capture drop E //state
capture drop F //county

//rename output variables
capture rename G gp_q_cons_ingots_oh_basic
capture rename H gp_q_trans_ingots_oh_basic
capture rename I gp_q_FS_ingots_oh_basic
capture rename J gp_v_trans_ingots_oh_basic
capture rename K gp_v_FS_ingots_oh_basic
capture rename L gp_q_cons_ingots_oh_acid
capture rename M gp_q_trans_ingots_oh_acid
capture rename N gp_q_FS_ingots_oh_acid
capture rename O gp_v_trans_ingots_oh_acid
capture rename P gp_v_FS_ingots_oh_acid
capture rename Q gp_q_cons_ingots_bessemer
capture rename R gp_q_trans_ingots_bessemer
capture rename S gp_q_FS_ingots_bessemer
capture rename T gp_v_trans_ingots_bessemer
capture rename U gp_v_FS_ingots_bessemer
capture rename V gp_q_cons_ingots_electric
capture rename W gp_q_trans_ingots_electric
capture rename X gp_q_FS_ingots_electric
capture rename Y gp_v_trans_ingots_electric
capture rename Z gp_v_FS_ingots_electric
capture rename AA gp_q_cons_ingots_crucible
capture rename AB gp_q_trans_ingots_crucible
capture rename AC gp_q_FS_ingots_crucible
capture rename AD gp_v_trans_ingots_crucible
capture rename AE gp_v_FS_ingots_crucible
capture rename AF gp_q_cons_castings_oh_basic
capture rename AG gp_q_trans_castings_oh_basic
capture rename AH gp_q_FS_castings_oh_basic
capture rename AI gp_v_trans_castings_oh_basic
capture rename AJ gp_v_FS_castings_oh_basic
capture rename AK gp_q_cons_castings_oh_acid
capture rename AL gp_q_trans_castings_oh_acid
capture rename AM gp_q_FS_castings_oh_acid
capture rename AN gp_v_trans_castings_oh_acid
capture rename AO gp_v_FS_castings_oh_acid
capture rename AP gp_q_cons_castings_bessemer
capture rename AQ gp_q_trans_castings_bessemer
capture rename AR gp_q_FS_castings_bessemer
capture rename AS gp_v_trans_castings_bessemer
capture rename AT gp_v_FS_castings_bessemer
capture rename AU gp_q_cons_castings_electric
capture rename AV gp_q_trans_castings_electric
capture rename AW gp_q_FS_castings_electric
capture rename AX gp_v_trans_castings_electric
capture rename AY gp_v_FS_castings_electric
capture rename AZ gp_q_cons_castings_crucible
capture rename BA gp_q_trans_castings_crucible
capture rename BB gp_q_FS_castings_crucible
capture rename BC gp_v_trans_castings_crucible
capture rename BD gp_v_FS_castings_crucible
capture rename BE gp_q_cons_blooms_billets
capture rename BF gp_q_trans_blooms_billets
capture rename BG gp_q_FS_blooms_billets
capture rename BH gp_v_trans_blooms_billets
capture rename BI gp_v_FS_blooms_billets
capture rename BJ gp_q_cons_rolled_blooms
capture rename BK gp_q_trans_rolled_blooms
capture rename BL gp_q_FS_rolled_blooms
capture rename BM gp_v_trans_rolled_blooms
capture rename BN gp_v_FS_rolled_blooms
capture rename BO gp_q_cons_hammered_blooms
capture rename BP gp_q_trans_hammered_blooms
capture rename BQ gp_q_FS_hammered_blooms
capture rename BR gp_v_trans_hammered_blooms
capture rename BS gp_v_FS_hammered_blooms
capture rename BT gp_q_cons_sheet_tp_bars
capture rename BU gp_q_trans_sheet_tp_bars
capture rename BV gp_q_FS_sheet_tp_bars
capture rename BW gp_v_trans_sheet_tp_bars
capture rename BX gp_v_FS_sheet_tp_bars
capture rename BY gp_q_cons_muck_scrap
capture rename BZ gp_q_trans_muck_scrap
capture rename CA gp_q_FS_muck_scrap
capture rename CB gp_v_trans_muck_scrap
capture rename CC gp_v_FS_muck_scrap
capture rename CD gp_q_cons_plates_thick_crucible
capture rename CE gp_q_trans_plates_thick_crucible
capture rename CF gp_q_FS_plates_thick_crucible
capture rename CG gp_v_trans_plates_thick_crucible
capture rename CH gp_v_FS_plates_thick_crucible
capture rename CI gp_q_cons_plates_thick_saw
capture rename CJ gp_q_trans_plates_thick_saw
capture rename CK gp_q_FS_plates_thick_saw
capture rename CL gp_v_trans_plates_thick_saw
capture rename CM gp_v_FS_plates_thick_saw
capture rename CN gp_q_cons_plates_thick_boiler
capture rename CO gp_q_trans_plates_thick_boiler
capture rename CP gp_q_FS_plates_thick_boiler
capture rename CQ gp_v_trans_plates_thick_boiler
capture rename CR gp_v_FS_plates_thick_boiler
capture rename CS gp_q_cons_plates_thin_autobody
capture rename CT gp_q_trans_plates_thin_autobody
capture rename CU gp_q_FS_plates_thin_autobody
capture rename CV gp_v_trans_plates_thin_autobody
capture rename CW gp_v_FS_plates_thin_autobody
capture rename CX gp_q_cons_plates_thin_black
capture rename CY gp_q_trans_plates_thin_black
capture rename CZ gp_q_FS_plates_thin_black
capture rename DA gp_v_trans_plates_thin_black
capture rename DB gp_v_FS_plates_thin_black
capture rename DC gp_q_cons_plates_thin_plain
capture rename DD gp_q_trans_plates_thin_plain
capture rename DE gp_q_FS_plates_thin_plain
capture rename DF gp_v_trans_plates_thin_plain
capture rename DG gp_v_FS_plates_thin_plain
capture rename DH gp_q_cons_skelp
capture rename DI gp_q_trans_skelp
capture rename DJ gp_q_FS_skelp
capture rename DK gp_v_trans_skelp
capture rename DL gp_v_FS_skelp
capture rename DM gp_q_cons_cotton_ties
capture rename DN gp_q_trans_cotton_ties
capture rename DO gp_q_FS_cotton_ties
capture rename DP gp_v_trans_cotton_ties
capture rename DQ gp_v_FS_cotton_ties
capture rename DR gp_q_cons_strips_black_hot_roll
capture rename DS gp_q_trans_strips_black_hot_roll
capture rename DT gp_q_FS_strips_black_hot_roll
capture rename DU gp_v_trans_strips_black_hot_roll
capture rename DV gp_v_FS_strips_black_hot_roll
capture rename DW gp_q_cons_strips_black_hoop
capture rename DX gp_q_trans_strips_black_hoop

//not all output variables are in the spreadsheet

save "$rootDir_dataBR/1931/1112/1112_1931_clean_B", replace
