//Cleaning script for BR spreadsheet: 1110_1931. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced.
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1931/1110"
import excel "`data_dir'/111031A0_PDSPL.xls", allstring sheet("111031A0") clear

drop in 1 / 2 //first row is blank, 2nd row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture replace record=lower(record)
capture rename C fileno1
capture rename D fileno2
capture rename E id
capture rename F tempid
capture rename G comment
capture rename H statenm
capture rename I cntynm
capture rename J citynm
capture rename K indnm
capture rename L merchant
capture rename M formnm
capture rename N plntname
capture rename O ownrname
capture rename P incyn
capture rename Q a004
capture rename R state
capture rename S city
capture rename T county
capture rename U street
capture rename V othraddr
capture rename W incityyn
capture rename X othrcity
capture rename Y sbsdryyn
capture rename Z mthrinfo
capture rename AA nmchngyn
capture rename AB as002
capture rename AC owchngyn
capture rename AD as004
capture rename AE frmrinfo
capture rename AF products
capture rename AG mtlsusd1
capture rename AH mtlsusd2
capture rename AI bgndt3
capture rename AJ enddt3

//rename utilization variables
capture rename AK d001
capture rename AL d005
capture rename AM d006
capture drop AN

//rename employment variables
capture rename AO wetotal
capture drop AP //column name: diff
capture rename AQ wejan
capture rename AR wefeb
capture rename AS wemar
capture rename AT weapr
capture rename AU wemay
capture rename AV wejun
capture rename AW wejul
capture rename AX weaug
capture rename AY wesep
capture rename AZ weoct
capture rename BA wenov
capture rename BB wedec
capture rename BC e005s
capture rename BD f009
capture rename BE f005f

//rename output variables
capture rename BF gp_q_coke_ip
capture rename BG gp_v_coke_ip
capture rename BH gp_q_coke_fs
capture rename BI gp_v_coke_fs
capture rename BJ gp_v_coke
capture rename BK gp_q_charcoal_ip
capture rename BL gp_v_charcoal_ip
capture rename BM gp_q_charcoal_fs
capture rename BN gp_v_charcoal_fs
capture rename BO gp_v_charcoal
capture rename BP gp_s_otherfuel1
capture rename BQ gp_q_otherfuel1_ip
capture rename BR gp_v_otherfuel1_ip
capture rename BS gp_q_otherfuel1_fs
capture rename BT gp_v_otherfuel1_fs
capture rename BU gp_v_otherfuel1
capture rename BV gp_s_otherfuel2
capture rename BW gp_q_otherfuel2_ip
capture rename BX gp_v_otherfuel2_ip
capture rename BY gp_q_otherfuel2_fs
capture rename BZ gp_v_otherfuel2_fs
capture rename CA gp_v_otherfuel2
capture rename CB gp_q_blastfurnacegas
capture rename CC gp_q_blastfurnacegas_other
capture rename CD gp_v_blastfurnacegas_other
capture rename CE gp_v_slag
capture rename CF gp_s_general1
capture rename CG gp_v_general1
capture drop CH
capture rename CI g000v
capture drop CJ - DX //Why?
capture rename DZ gp_q_pigiron_foundry_ip
capture rename EA gp_q_pigiron_foundry_fs
capture rename EB gp_q_pigiron_basic_ip
capture rename EC gp_q_pigiron_basic_fs
capture rename ED gp_q_pigiron_bessemer_ip
capture rename EE gp_q_pigiron_bessemer_fs
capture rename EF gp_q_pigiron_lowPhosphorus_ip
capture rename EG gp_q_pigiron_lowPhosphorus_fs
capture rename EH gp_q_pigiron_malleable_ip
capture rename EI gp_q_pigiron_malleable_fs
capture rename EJ gp_q_pigiron_forge_ip
capture rename EK gp_q_pigiron_forge_fs
capture rename EL gp_q_pigiron_white_ip
capture rename EM gp_q_pigiron_white_fs
capture rename EN gp_q_directCasting_pipe_ip
capture rename EO gp_q_directCasting_pipe_fs
capture rename EP gp_q_directCasting_other_ip
capture rename EQ gp_q_directCasting_other_fs
capture rename ER gp_q_spiegeleisen_consumption_ip
capture rename ES gp_q_spiegeleisen_fs
capture rename ET gp_v_spiegeleisen
capture rename EU gp_q_ferromanganese_ip
capture rename EV gp_q_ferromanganese_fs
capture rename EW gp_v_ferromanganese
capture rename EX gp_q_ferrophosphorus_ip
capture rename EY gp_q_ferrophosphorus_fs
capture rename EZ gp_v_ferrophosphorus
capture rename FA gp_q_ferrosillicon_ip
capture rename FB gp_q_ferrosillicon_fs
capture rename FC gp_v_ferrosillicon
capture rename FD gp_q_ferroalloy_other_ip
capture rename FE gp_q_ferroalloy_other_fs
capture rename FF gp_v_ferroalloy_other
capture rename FJ gp_q_machine_cast
capture rename FK gp_q_sand_cast
capture rename FL gp_q_chill_cast
capture rename FM gp_q_delivered_molton

//rename capital variables
capture rename FN z_stack
capture rename FO z_stack_fuel
capture rename FP z_stack_capacity
capture rename FQ z_stack_volume
capture rename FR z_stack_active1_fuel
capture rename FS z_stack_active1_number
capture rename FT z_stack_active1_capacity
capture rename FU z_stack_active2_fuel
capture rename FV z_stack_active2_number
capture rename FW z_stack_active2_capacity
capture rename FX z_stack_idle_fuel
capture rename FY z_stack_idle_number
capture rename FZ z_stack_idle_capacity
capture rename GA z_stack_banked_fuel
capture rename GB z_stack_banked_number
capture rename GC z_stack_banked_capacity
capture rename GD z_stack_new_fuel
capture rename GE z_stack_new_number
capture rename GF z_stack_new_capacity
capture rename GG z_stack_inConstruction_fuel
capture rename GH z_stack_inConstruction_number
capture rename GI z_stack_inConstruction_capacity
capture rename GJ z_stack_abandoned_fuel
capture rename GK z_stack_abandoned_number
capture rename GL z_stack_abandoned_capacity

//rename manhours variables
capture rename GM emh01
capture rename GN emh02
capture rename GO emh03
capture rename GP emh04
capture rename GQ emh05
capture rename GR emh06
capture rename GS emh07
capture rename GT emh08
capture rename GU emh09
capture rename GV emh10
capture rename GW emh11
capture rename GX emh12

gen year = 1931
//rename "common" set of variables
do "$rootDir_code/General/basic_rename"

//tostring all variables for consistent appending later
tostring *, replace force

do "$rootDir_code/1931/fix_estabids_1110_1931"

save "$rootDir_dataBR/1931/1110/1110_1931_clean", replace
