//rename variables for industry 907 in 1931

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
rename AN	 gp_q_sole_leather_oak
rename AO 	 gp_v_sole_leather_oak
rename AP 	 gp_q_sole_leather_chrome
rename AQ 	 gp_v_sole_leather_chrome
rename AR 	 gp_q_sole_leather_horse
rename AS 	 gp_v_sole_leather_horse
rename AT 	 gp_q_sole_leather_butts_rough
rename AU 	 gp_v_sole_leather_butts_rough
rename AV 	 gp_q_sole_leather_butts_curried
rename AW 	 gp_v_sole_leather_butts_curried
rename AX 	 gp_q_sole_leather_offal
rename AY 	 gp_v_sole_leather_offal
rename AZ	 gp_q_harness_leather_union
rename BA	gp_v_harness_leather_union
rename BB	 gp_q_harness_leather_oak
rename BC	 gp_v_harness_leather_oak
rename BD	 gp_q_harness_leather_bag
rename BE	 gp_v_harness_leather_bag
rename BF	 gp_q_harness_leather_skirting
rename BG	 gp_v_harness_leather_skirting
rename BH	 gp_q_harness_leather_collar
rename BI	 gp_v_harness_leather_collar
rename BJ	 gp_q_harness_leather
rename BK	 gp_v_harness_leather
rename BL	 gp_q_harness_leather_latigo
rename BM	 gp_v_harness_leather_latigo
rename BN	 gp_q_harness_leather_lace
rename BO	 gp_v_harness_leather_lace
rename BP	 gp_q_welting_cattle_sides
rename BQ	 gp_v_welting_cattle_sides
rename BR	 gp_q_welting_cattle_shoulders
rename BS	 gp_v_welting_cattle_shoulders
rename BT	 gp_q_welting_pigskin
rename BU	 gp_v_welting_pigskin
rename BV	 gp_q_upholstery_leather_hide
rename BW	 gp_v_upholstery_leather_hide
rename BX	 gp_q_upholstery_leather_buffings
rename BY	 gp_v_upholstery_leather_buffings
rename BZ	 gp_q_upholstery_leather_splits
rename CA	 gp_v_upholstery_leather_splits
rename CB	 gp_q_upper_leather_cattle
rename CC	 gp_v_upper_leather_cattle
rename CD	 gp_q_upper_leather_calf
rename CE	 gp_v_upper_leather_calf
rename CF	 gp_q_upper_leather_kip
rename CG	 gp_v_upper_leather_kip
rename CH	 gp_q_upper_leather_goat
rename CI	 gp_v_upper_leather_goat
rename CJ	 gp_q_upper_leather_cabretta
rename CK	 gp_v_upper_leather_cabretta
rename CL	 gp_q_upper_leather_sheep
rename CM	 gp_v_upper_leather_sheep
rename CN	 gp_q_upper_leather_deer
rename CO	 gp_v_upper_leather_deer
rename CP	 gp_q_upper_leather_kangaroo
rename CQ	 gp_v_upper_leather_kangaroo
rename CR	 gp_q_upper_leather_horse_half
rename CS	 gp_v_upper_leather_horse_half
rename CT	 gp_q_upper_leather_horse_butts
rename CU	 gp_v_upper_leather_horse_butts
rename CV	 gp_q_upper_leather_horse_shanks
rename CW	 gp_v_upper_leather_horse_shanks
rename CX	 gp_s_upper_leather_other_1
rename CY	 gp_q_upper_leather_other_1
rename CZ	 gp_v_upper_leather_other_1
rename DA	 gp_s_upper_leather_other_2
rename DB	 gp_q_upper_leather_other_2
rename DC	 gp_v_upper_leather_other_2
rename DD	 gp_q_patent_leather_cattle
rename DE	 gp_v_patent_leather_cattle
rename DF	 gp_q_patent_leather_calf
rename DG	 gp_v_patent_leather_calf
rename DH	 gp_q_patent_leather_goat
rename DI	 gp_v_patent_leather_goat
rename DJ	 gp_q_patent_leather_sheep
rename DK	 gp_v_patent_leather_sheep
rename DL	 gp_q_patent_leather_horse
rename DM	 gp_v_patent_leather_horse
rename DN	 gp_q_glove_leather_cattle
rename DO	 gp_v_glove_leather_cattle
rename DP	 gp_q_glove_leather_calf
rename DQ	 gp_v_glove_leather_calf
rename DR	 gp_q_glove_leather_cowhide
rename DS	 gp_v_glove_leather_cowhide
rename DT	 gp_q_glove_leather_horse_half
rename DU	 gp_v_glove_leather_horse_half
rename DV	 gp_q_glove_leather_horse_butts
rename DW	 gp_v_glove_leather_horse_butts
rename DX	 gp_q_glove_leather_horse_shanks
rename DY	 gp_v_glove_leather_horse_shanks
rename DZ	 gp_q_glove_leather_pig
rename EA 	 gp_v_glove_leather_pig
rename EB	 gp_q_glove_leather_goat
rename EC	 gp_v_glove_leather_goat
rename ED	 gp_q_glove_leather_cabretta
rename EE	 gp_v_glove_leather_cabretta
rename EF	 gp_q_glove_leather_sheep
rename EG	 gp_v_glove_leather_sheep
rename EH	 gp_q_glove_leather_shearlings
rename EI	 gp_v_glove_leather_shearlings
rename EJ	 gp_q_glove_leather_deer
rename EK  	gp_v_glove_leather_deer
rename EL 	gp_q_fancy_leather_cowhide
rename EM	 gp_v_fancy_leather_cowhide
rename EN	 gp_q_fancy_leather_buffings
rename EO	 gp_v_fancy_leather_buffings
rename EP	 gp_q_fancy_leather_goat
rename EQ	 gp_v_fancy_leather_goat
rename ER gp_q_fancy_leather_cabretta
rename ES gp_v_fancy_leather_cabretta
rename ET	gp_q_fancy_leather_sheep
rename EU	 gp_v_fancy_leather_sheep
rename EV	 gp_q_fancy_leather_calf
rename EW	 gp_v_fancy_leather_calf
rename EX	 gp_q_fancy_leather_pig
rename EY	 gp_v_fancy_leather_pig
rename EZ	 gp_q_fancy_leather_pigskin
rename FA	 gp_v_fancy_leather_pigskin
rename FB	 gp_q_fancy_leather_reptile
rename FC	 gp_v_fancy_leather_reptile
rename FD	 gp_q_fancy_leather_seal
rename FE	 gp_v_fancy_leather_seal
rename FF	 gp_s_fancy_leather_other
rename FG	 gp_q_fancy_leather_other
rename FH	 gp_v_fancy_leather_other
rename FI	 gp_q_splits_not_upholstery
rename FJ	 gp_v_splits_not_upholstery
rename FK	 gp_q_roller_leather
rename FL	 gp_v_roller_leather
rename FM	 gp_q_half_sweat_skivers
rename FN	 gp_v_half_sweat_skivers
rename FO 	 gp_q_skivers
rename FP	 gp_v_skivers
rename FQ	 gp_q_chamola
rename FR	 gp_v_chamola
rename FS	 gp_q_fleshers
rename FT	 gp_v_fleshers
rename FU	 gp_q_rough_unsplit
rename FV	 gp_v_rough_unsplit
rename FW	 gp_q_rough_splits
rename FX	 gp_v_rough_splits
rename FY	 gp_s_all_other_leather
rename FZ	 gp_v_all_other_leather
rename GA	 gp_v_byproducts
rename GB	 gp_s_other1
rename GC	 gp_v_other1
rename GD	 gp_s_other2
rename GE	 gp_v_other2
rename GF	 gp_s_other3
rename GG	 gp_v_other3
rename GH	 gp_s_other4
rename GI	 gp_v_other4
rename GJ	 gp_s_other5
rename GK	 gp_v_other5
rename GL	 gp_s_other6
rename GM	 gp_v_other6
rename GN 	gp_v_all_other_products
rename GO gp_v_contract_work
rename GP gp_v_custom_work
rename GQ g000v
