//regularizes firm names before running reclink. 

//Other possible fixes
//1. Replace Letters for Cardinal Directions
//2. Replace all \d{2}Th with String

//Args: vars_to_match - list of fuzzy variables to match on, required_vars - list of variables to exactly match on
args owner_name establishment_name

tempvar establishment_name_virtual
gen `establishment_name_virtual' = `establishment_name'
 
//do some basic regularization of names
foreach regularize_var in owner_name establishment_name_virtual {
	replace ``regularize_var'' = upper(``regularize_var'')
	replace ``regularize_var'' = regexr(``regularize_var'', "INC.$", "INCORPORATED")
	replace ``regularize_var'' = regexr(``regularize_var'', "CORP.$", "CORPORATION")
	replace ``regularize_var'' = regexr(``regularize_var'', "CO.$", "CORPORATION")
	replace ``regularize_var'' = regexr(``regularize_var'', "^THE", "")
	replace ``regularize_var'' = subinstr(``regularize_var'', "&", "AND", .)

	replace ``regularize_var'' = subinstr(``regularize_var'', "COMPANY", "CORPORATION", .)
	replace ``regularize_var'' = subinstr(``regularize_var'', "MANAGER", "", .)
	replace ``regularize_var'' = subinstr(``regularize_var'', "PRESIDENT", "", .)
	replace ``regularize_var'' = subinstr(``regularize_var'', "OWNER", "", .)

	replace ``regularize_var'' = subinstr(``regularize_var'', ",", "", .)
	replace ``regularize_var'' = subinstr(``regularize_var'', "?", "", .)
}

//if name is just CORPORATION, then make name blank. 
replace `owner_name' = "" if `owner_name' == "CORPORATION"

//if owner_name=="SAME", then this means it's actually the establishment_name
replace `owner_name' = `establishment_name_virtual' if `owner_name' == "SAME"

//try filling in some more values of `owner_name'
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & (regexm(`establishment_name_virtual', "INCORPORATED") | regexm(`establishment_name_virtual', "CORPORATION"))

//final trim
replace `owner_name' = trim(`owner_name')
replace `owner_name' = ustrtrim(`owner_name')

//addsome additional fixes here
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GENERAL ICE CREAM CORPORATIION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PANGBURN CO. INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="OAKLAND DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HUBERT CORENS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ARDIE ICE CREAM CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PANGBURN CO. INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CAMBRIDGE DAIRY CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="E. N. MCCONNELL"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MCCARTHY BROS."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DARIGLEN CREAMERIES LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PETER G. FULTON"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DILLINGHAM AND ALEXANDER"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MID WEST DAIRY PROD. CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BERKELEY ICE CREAM CO. LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ARORA CREAMERY LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="H. P. HOOD AND SON"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HOOKER BROS."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BEEHIVE CANDY SHOP"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DAVISON DAIRY AND ICE CREAM CO. B. N."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="OHIO FARMERS CO-OPERATIVE MILK"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="JACK M. TERZIS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="R. J. CASEY AND CO. ESTATE"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CRAWFORD CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CARUSO BROS."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DARIGOLD MILK CO. LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GOOD HUMOR ICE CREAM CO. INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ADOLPH SCHILLING"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HARDIE SALES CO. INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CARNATION CO. OF CALIF. FRESH MILK AND ICE CREAM DIVISION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BACHMAN CONFECTIONERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FOSTER AND O'REAR"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BELLAMNY ICE CREAM CO INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DAIRY PRODUCTS LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WOOD BROS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WINDSOR FARM DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="RIVERVIEW DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LYNDONVILLE CREAMERY ASS'N ."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ALGONA ICE CREAM AND CANDY FACTORY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ICE CREAM"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FLYNN DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BROWN VELVET ICE CREAM CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GLOVER LEAF DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="VAGTO ICE CREAM INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WASCO CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="KINNETT ICE CREAM CO. COLUMBUS GEORGIA"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FREEMAN DAIRY CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ROLF SAMSONS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="OKLAHOMA DAIRY PRODUCERS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MCLAGAN BROS. CRY."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FREEMAN DAIRY CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="KROLL BROS. ICE CREAM PRODUCTS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SCHWEN'S ICE CREAM AND CANDY CO. BLUE EARTH MINN."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SPARTANBURG CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LYNDONVILLE CREAMERY ASS'N."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="JOHN HARKINSON"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ROLLINS CANDY SHOP"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CURLESS ICE CREAM INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ALAMO MANUFACTURING CORPORATION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HUYLER'S"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WILCOXSON'S CONF."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LYNDONVILLE CREAMERY ASS'N ."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="H. P. HOOD AND SON"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LOGOMASCUS GRUPE CO OF IOWA"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GOOD HUMOR ICE CREAM CO. INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LAURAWADE ICE CREAM CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="L. J. MCELROY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MELROSE CREAMERY CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GENERAL ICE CREAM CORP. BING. DIV."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PERRY CREAMERY CO. INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BELL ICE CREAM CO. OF AUSTIN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BOYER ICE CREAM AND DAIRY CORPORATION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ROSS DAIRY CORP"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FISHER ICE CREAM CO. INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="TRI CLOVER DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FOSTER AND OREAR"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CARDOSI AND CARDOSI"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="A. W. PARTRIDGE"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="OAK PARK ICE CREAM SHOP"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FARMERS CO-OPERATIVE DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="KOKOMO GROCER'S DAIRY PRODUCTS CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PERRY CREAMERY CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BELLDEL  CREAM CO. OF AUSTIN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ESTATE CHARLES BECKMANN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LYNDONVILLE CREAMERY ASSN."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="UNIVERSITY CREAMERIES LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="S. C.  HOOKSTRATTEN INC. LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GOOD HUMOR ICE CREAM CO. INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="J. C. PARRENS CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ARROWHEAD CO-OP CRY. ASS'N"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="A. HOLT INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GREY'S INC. (ICE CREAM)"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="JACOB J. MURRAY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ALASKA FROZEN PRODUCTS INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HERMAN DE RONNER"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LAGOMARCINO GRUPE CO OF IOWA"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="W. F. ELLSWORTH"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BROADWAY CREAMERIES LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WOMEN'S EDUCATIONAL AND INDUSTRIAL UNION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MARTINSVILLE CREAMERY AND COLD STORAGE CORP"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BRIERDENE ICE CREAM CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SUNBEAM CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WEISER ICE AND COLD STORAGE"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DEMONETS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MODEL DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LYNDONVILLE CREAMERY ASS'N ."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PURE ICE CREAM CO. INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MID WEST DAIRY PROD. CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WASCO CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BERKELY ICE CREAM CO. LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="YAKIMA DAIRYMEN'S ASSOCIATION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="VINCENTS CANDY STORE"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ALGONA ICE CREAM AND CANDY FACTORY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SNOWHITE CREAMERIES"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BIGGIN AND SONS CO. J. D."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SEALE-LILY ICE CREAM"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="L. ESPERANCE"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="MODEL DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FRED F. FIELD HOLSTEIN DUTCHLAND FARMS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="NEW YORK ESKIMO PIE CORP"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LORD BALTIMORE ICE CREAM"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GOOD HUMOR ICE CREAM CO. OF TULSA"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="TURNER CENTER SYSTEM INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="OHIO FARMERS COOPERATIVE MILK ASSOCIATION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BECHTEL BROS."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CHAPMANS PRODUCTS INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="-PARTNERS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="TOWNSEND CALIFORNIA GLACE FRUITS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="(REAL) ICE CREAM SERVICE INC. (JESSEY MAID I.E. LISTED AS)"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HYGEIA ICE CREAM"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BORDEN'S FARM PRODUCTS CO. OF MICHIGAN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="F. W. BERGENDAHL INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FRANK DOLANSKY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HANCOCK  COUNTY COOPERATIVE CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CALLAHAN'S INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WILLOW BROOK CREAMERY LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SOUTH WEST DAIRY PRODUCTS CO (FORMERLY BROWN AND BILLINGS)"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BY. PRODUCTS PLANT"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="EXCERTO ICE CREAM CO. INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PURE GOLD DAIRY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="B. F. BEALOR"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DAYLIGHT CONFECTIONERY CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LOUISVILLE ICE CREAM CO INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CLIFTON FROGE ICE AND BOTTLING WORKS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CROCKERY CITY ICE AND PRODUCTS CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SANBORN'S C-LECT ICE CREAM"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ESTATE OF CHARLES BECKMANN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LONGHORN CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="COBB'S CONFECTIONERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="C. D. EMANUEL"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BETTY BALTON"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WILLOW BROOK CREAMERY LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GREENVILLE DAIRY CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LEWISBURG ICE CREAM CO. MABSCOTT"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="JAMES VERAS DUNMORE CANDY KITCHEN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ADOHR CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PEP CREAMERIES LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="COLONIAL ICE CREAM CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GENERAL ICE CREAM CORP. ALBANY N. Y."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HICKS AND COLLINS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WOOD BROS."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HENRY THODE"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="WOMEN'S EDUCATIONAL AND INDUSTRIAL UNION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HORACE M. WEAVER"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PURITY ICE CREAM CO. LTD."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="NORTH AMERICAN OREAMERIES INC."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FRED SANDERS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="JOHN M. DETJEN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="PFLAUMER CHRISTIAN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="SERVICE DAIRY AND ICE CREAM COP."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="TELL CITY CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FREEMAN DAIRY CO."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DAIRYLEA ICE CREAM PLANT"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="DEMONETS' INC"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="OELGES CONFECTIONERS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GEORGE F. KEMPEN"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ALGONA ICE CREAM AND CANDY FACTORY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="HANCOCK COUNTY COOPERATIVE CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FRED SANDERS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LOWER COLUMBIA COOP. DAIRY ASSN."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="BRIGGS CREAMERY CO"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="FRED SANDERS"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="CLIFTON FORGE ICE BOTTLING OPERATING AS PEERLESS CREAMERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="LUCAS CONFECTIONERY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="GENERAL ICE CREAM CORP. ONEONTA DIV."
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="" & `establishment_name_virtual'=="ELITE CONFECTIONERY STORE"

 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="A CORPORATION" 
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="A. CORPORATION"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="CO-OPERATIVE"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="CO-OPERATIVELY"
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="CORP" 
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="CORP." 
 replace `owner_name' = `establishment_name_virtual' if `owner_name'=="CORPORATION"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="INCORPORATED"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="INCORPORATED CORPORATION"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="INCORPORATION"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="PARTNERSHIP"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="PARTERSHIP"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="STOCK CORPORATION"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="STOCK-CORPORATION"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="STOCKHOLDERS"
replace `owner_name' = `establishment_name_virtual' if `owner_name'=="STOOK CORPORATION"
replace `owner_name' = `establishment_name_virtual' if `owner_name'==""
