//Clean firm names
//Based on code generously shared by Sarah Quincy
gen a002_update = a002

replace a002_update = subinstr(a002_update, " Lum."," Lumber ",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "'s","s",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "'S","s",1) //standardize basic structure
replace a002_update = subinstr(a002_update, ",","",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Co.","Co",1) //standardize basic structure
replace a002_update = subinstr(a002_update, ".","",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "-"," ",.) //sta ndardize basic structure
replace a002_update = subinstr(a002_update, "&"," and ",.) //standardize basic structure
replace a002_update =proper(a002_update) //standardize basic structure
replace a002_update = regexr(a002_update, "`","") //get rid of quotes
replace a002_update = regexr(a002_update, "\'","") //get rid of quotes
replace a002_update = subinstr(a002_update, `"""',  "", .) //get rid of quotes
replace a002_update = regexr(a002_update, "\([A-Z a-z \ \-]+\)","") //get rid of parentheticals
replace a002_update = trim(a002_update) //standardize basic structure
replace a002_update = subinstr(a002_update, "  "," ",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Ltd","",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Incroporated","Incorporated",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Incorporated","",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Products","Product",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Product","Prod",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Limited","",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Corportion","Corporation",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Corporated","Corporation",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "A Public Corporation","",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Public Corporation","",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Corpn","Corp",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Corporation","Corp",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Cooperation","Corp",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Compnay","Company",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Company","Co",.) //standardize basic structure
replace a002_update = subinstr(a002_update, "Manufacturing","Mfg",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Manuf","Mfg",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "#","No ",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "  "," ",.) //just in case
replace a002_update = subinstr(a002_update, "Confectionery","Conf",1) //typo
replace a002_update = subinstr(a002_update, "Bros","Brothers",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Macaroni Mfg","Macaroni",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "MacaroniMfg","Macaroni",1) //standardize basic structure
replace a002_update = regexr(a002_update, "(Corp)+ [A-Z a-z \ ]*Branch+$","Corp") if regexm(a002_update, "Branch+$")
replace a002_update = regexr(a002_update, "(Co)+ [A-Z a-z \ ]*Branch+$","Co") if regexm(a002_update, "Branch+$")
replace a002_update = regexr(a002_update, "(Inc)+$","") //get rid of Corp at end of name
replace a002_update = regexr(a002_update, "(Corp)+$","") //get rid of Corp at end of name
replace a002_update = regexr(a002_update, "(Co)+$","") //get rid of Co at end of name
replace a002_update = regexr(a002_update, "[A-Za-z \ 0-9]+ Branch","") if regexm(a002_update, "Branch")==1 & regexm(a002_update, "Branch$")==0 //get rid of branch location because it's in ag003
replace a002_update = subinstr(a002_update, "And Son","Son",1) //typo
replace a002_update = subinstr(a002_update, "Sons","Son",1) //typo
replace a002_update = subinstr(a002_update, "Fcty","Factory",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "()","",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "BotG","Bottling",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Wks","Works",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Mldg","Moulding",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Deverage","Beverage",1) //typo
replace a002_update = subinstr(a002_update, "Co Planing","Planing",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Cremery","Creamery",1) //typo
replace a002_update = subinstr(a002_update, "Aircrft","Aircraft",1) //typo
replace a002_update = subinstr(a002_update, "Decoratine","Decorative",1) //typo
replace a002_update = subinstr(a002_update, "Hongkong","Hong Kong",1) //typo
replace a002_update = subinstr(a002_update, "Insto Plant","Insto",1) //typo
replace a002_update = subinstr(a002_update, " Bros"," Brothers",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Candy Stone","Candy Store",1) //typo
replace a002_update = subinstr(a002_update, "Aurcraft","Aircraft",1) //typo
replace a002_update = subinstr(a002_update, "Cement Cement","Cement",1) //typo
replace a002_update = subinstr(a002_update, "The ","",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Aricraft","Aircraft",1) //typo
replace a002_update = subinstr(a002_update, "A Corporation","",1) //standardize basic structure
replace a002_update = regexr(a002_update, "Co [A-Za-z \ ]+ Division","Co")
replace a002_update = regexr(a002_update, "Prod [A-Za-z \ ]+ Division","Prod")
replace a002_update = subinstr(a002_update, "Macaron ","Macaroni",1) //typo
replace a002_update = subinstr(a002_update, "Macroni ","Macaroni",1) //typo
replace a002_update = subinstr(a002_update, "Gerorge","George",1) //typo
replace a002_update = subinstr(a002_update, "Geo ","George ",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Wm ","William ",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Florance","Florence",1) //typo
replace a002_update = subinstr(a002_update, "Fibre","Fiber",1) //typo
replace a002_update = subinstr(a002_update, "Furniturre","Furniture",1) //typo
replace a002_update = subinstr(a002_update, "Confictionary","Confectionery",1) //typo
replace a002_update = "Coca Cola Bottling" if regexm(a002_update, "Cola") //standardize basic structure
replace a002_update = subinstr(a002_update, "Parrafine","Paraffine",1) //typo
replace a002_update = subinstr(a002_update, "Paraffine","Paraffin",1) //typo
replace a002_update = subinstr(a002_update, "Beverages","Beverage",1) //typo
replace a002_update = subinstr(a002_update, "Beverage","Bev",1) //typo
replace a002_update = subinstr(a002_update, "Cabinet","Cab",1) //typo
replace a002_update = subinstr(a002_update, "Glss","Glass",1) //typo
replace a002_update = subinstr(a002_update, "Steel Castings","Steel Casting",1) //typo
replace a002_update = subinstr(a002_update, "Planning Mill","Planing Mill",1) //typo
replace a002_update = subinstr(a002_update, "Partiton","Partition",1) //typo
replace a002_update = subinstr(a002_update, "Co Partnership","",1) //name TMI
replace a002_update = subinstr(a002_update, " Lbr"," Lumber ",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Mfgr","Mfg",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Cold Storage","C S",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Cold Stg","C S",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Bottling Works","Bottling",1) //standardize basic structure
replace a002_update = subinstr(a002_update, "Builders Supply","Building Supply",1) //typo
replace a002_update = subinstr(a002_update, "Candy Store","",1) if regexm(a002_update, "OBriens") //standardize name across incorp forms
replace a002_update = subinstr(a002_update, "Creamery","Creameries",1) //typo
replace a002_update = subinstr(a002_update, "Brrewery","Brewery",1)  //typo
replace a002_update = subinstr(a002_update, "Confectionery","Conf",1) //typo
replace a002_update = subinstr(a002_update, "Monarchs","Monarch",1)  //typo
replace a002_update = subinstr(a002_update, "Chocalate","Chocolate",1)  //typo
replace a002_update = subinstr(a002_update, "Cola Works","Cola Bottling",1)  //typo
replace a002_update = regexr(a002_update, "Avenue","Ave") //standardize basic structure
replace a002_update = regexr(a002_update, "Street","St") //standardize basic structure
replace a002_update = regexr(a002_update, "Murry","Murray") //typo
replace a002_update = regexr(a002_update, "Cament","Cement") //typo
replace a002_update = regexr(a002_update, "Bottling Works","Bottling") //typo
replace a002_update = regexr(a002_update, "Planing Mix","Planing Mill") //typo
replace a002_update = regexr(a002_update, "(One Plant)+$","") //standardize basic structure
replace a002_update = regexr(a002_update,"Lumbe+$", "Lumber") if regexm(a002_update,"Lumbe+$")==1 & regexm(a002_update,"Lumber+$")==0
replace a002_update = subinstr(a002_update, "  "," ",.) //just in case
replace a002_update = trim(a002_update)

replace a002 = a002_update
drop a002_update
