//label variables for industry 126

//label output variables
capture label var gp_u_Chickens "Output: Chickens, unit"
capture label var gp_q_Chickens "Output: Chickens, qt."
capture label var gp_v_Chickens "Output: Chickens, value"
capture label var gp_u_Ducks "Output: Ducks, unit"
capture label var gp_q_Ducks "Output: Ducks, qt."
capture label var gp_v_Ducks "Output: Ducks, value"
capture label var gp_u_Geese "Output: Geese, unit"			
capture label var gp_q_Geese "Output: Ducks, qt."		
capture label var gp_v_Geese "Output: Ducks, value"			
capture label var gp_u_Turkeys "Output: Turkeys, unit"
capture label var gp_q_Turkeys "Output: Turkeys, qt."
capture label var gp_v_Turkeys "Output: Turkeys, value"
capture label var gp_s_Dressed_Other "Output: Other dressed poultry, specify"
capture label var gp_u_Dressed_Other "Output: Other dressed poultry, unit"
capture label var gp_q_Dressed_Other "Output: Other dressed poultry, qt."
capture label var gp_v_Dressed_Other "Output: Other dressed poultry, value"
capture label var gp_s_Poultry_canned_whole "Output: Poultry canned whole, specify"
capture label var gp_u_Poultry_canned_whole "Output: Poultry canned whole, unit"
capture label var gp_q_Poultry_canned_whole "Output: Poultry canned whole, qt."
capture label var gp_v_Poultry_canned_whole "Output: Poultry canned whole, value"
capture label var gp_u_Poultry_canned_parts "Output: Poultry canned parts, specify"
capture label var gp_s_Poultry_canned_parts "Output: Poultry canned parts, unit"
capture label var gp_q_Poultry_canned_parts "Output: Poultry canned parts, qt."
capture label var gp_v_Poultry_canned_parts "Output: Poultry canned parts, value"
capture label var gp_u_Chicken_potted "Output: Chicken potted and deviled, unit"
capture label var gp_q_Chicken_potted "Output: Chicken potted and deviled, qt."
capture label var gp_v_Chicken_potted "Output: Chicken potted and deviled, value"
capture label var gp_u_Chicken_broth "Output: Broth and soup, unit"
capture label var gp_q_Chicken_broth "Output: Broth and soup, qt."
capture label var gp_v_Chicken_broth "Output: Broth and soup, value"
capture label var gp_u_Feathers "Output: Feathers, unit"
capture label var gp_q_Feathers "Output: Feathers, qt."
capture label var gp_v_Feathers "Output: Feathers, value"
capture label var gp_s_Rabbits "Output: Rabbits, specify"
capture label var gp_u_Rabbits "Output: Rabbits, unit"
capture label var gp_q_Rabbits "Output: Rabbits, quantity"
capture label var gp_v_Rabbits "Output: Rabbits, value"
capture label var gp_s_Poultry_Other1 "Output: Other poultry product 1, specify"
capture label var gp_v_Poultry_Other1 "Output: Other poultry product 1, value"
capture label var gp_q_Poultry_Other1 "Output: Other poultry product 1, qt."
capture label var gp_s_Poultry_Other2 "Output: Other poultry product 2, specify"
capture label var gp_v_Poultry_Other2 "Output: Other poultry product 2, value"
capture label var gp_q_Poultry_Other2 "Output: Other poultry product 2, qt."
capture label var gp_s_Poultry_Other3 "Output: Other poultry product 3, specify"
capture label var gp_v_Poultry_Other3 "Output: Other poultry product 3, value"
capture label var gp_q_Poultry_Other3 "Output: Other poultry product 3, qt."
