//label ag. imps. specific variables

//output variables
capture label var gp_v_attachment "Output: attachments, value"
capture label var gp_s_attachment "Output: attachments, specify"
capture label var gp_q_cultivators "Output: Cultivators, qt"
capture label var gp_v_cultivators "Output: Cultivators, value"
capture label var gp_q_harrows "Output: Harrows, qt"
capture label var gp_v_harrows "Output: Harrows, value"
capture label var gp_q_harvesting "Output: Harvesting equipment, qt"
capture label var gp_v_harvesting "Output: Harvesting equipment, value"
capture label var gp_q_haying "Output: Haying equipment, qt"
capture label var gp_v_haying "Output: Haying equipment, value"
capture label var gp_q_planting "Output: Planting equipment, qt"
capture label var gp_v_planting "Output: Planting equipment, value"
capture label var gp_q_plows "Output: Plows, qt"
capture label var gp_v_plows "Output: Plows, value"
capture label var gp_v_preparing "Output: Preparing equipment, value"
capture label var gp_q_preparing "Output: Preparing equipment, qt"

//input variables
capture label var j_q_pig_iron "Input: Pig Iron, qt"
capture label var j_v_pig_iron "Input: Pig Iron, value"
capture label var j_q_scrap_iron "Input: Scrap Iron, qt"
capture label var j_v_scrap_iron "Input: Scrap Iron, value"
capture label var j_q_iron_steel "Input: Steel, qt"
capture label var j_v_iron_steel "Input: Steel, value"
capture label var j_q_hardwood  "Input: hardwood"
capture label var j_v_hardwood  "Input: hardwood"
capture label var j_q_softwood "Input: softwood"
capture label var j_v_softwood  "Input: softwood"
