//label vars for industry 129

//output variables
capture label var gp_q_sugar_granulated "Output: granulated sugar, qt"
capture label var gp_v_sugar_granualted "Output: granulated sugar, value"
capture label var gp_q_sugar_unfinished "Output: unfinished sugar, qt"
capture label var gp_v_sugar_unfinished "Output: unfinished sugar, value"
capture label var gp_q_molasses_sold "Output: molasses sold, qt"
capture label var gp_v_molasses_sold "Output: molasses sold, value"
capture label var gp_q_molasses_discarded "Output: molasses discarded, qt"
capture label var gp_v_molasses_discarded "Output: molasses discarded, value"
capture label var gp_q_molasses_other "Output: molasses (other), qt"
capture label var gp_v_molasses_other "Output: molasses (other), value"
capture label var gp_q_syrup "Output: syrup, qt"
capture label var gp_v_syrup "Output: syrup, value"
capture label var gp_q_beet_pulp_dried "Output: dried beet pulp, qt"
capture label var gp_v_beet_pulp_dried "Output: dried beet pulp, value"
capture label var gp_q_beet_pulp_moist "Output: moist beet pulp, qt"
capture label var gp_v_beet_pulp_moist "Output: moist beet pulp, value"
capture label var gp_q_beet_pulp_molasses "Output: molasses beet pulp, qt"
capture label var gp_v_beet_pulp_molasses "Output: molasses beet pulp, value"

//input variables
capture label var j_factory_planted "Acres planted (grown directly by factory)"
capture label var j_factory_harvested "Acres harvested (grown directly by factory)"
capture label var j_factory_beets_received "Beets received, tons (grown directly by factory"
capture label var j_factory_beets_sliced "Beets sliced, tons (grown directly by factory)"
capture label var j_factory_cost_beets_received "Cost of beets received (grown directly by factory)"
capture label var j_tenants_planted "Acres planted (grown by tenants of factory)"
capture label var j_tenants_harvested "Acres harvested (grown by tenants of factory)"
capture label var j_tenants_beets_received "Beets received, tons (grown by tenants of factory)"
capture label var j_tenants_beets_sliced "Beets sliced, tons (grown by tenants of factory)"
capture label var j_tenants_cost_beets_received "Cost of beets received, tons (grown by tenants of factory)"
capture label var j_contract_planted "Acres planted (grown on contract by others than tenants of factory)"
capture label var j_contract_harvested "Acres harvested (grown on contract by others than tenants of factory)"
capture label var j_contract_beets_received "Beets received, tons (grown on contract by others than tenants of factory)"
capture label var j_contract_beets_sliced "Beets sliced, tons (grown on contract by others than tenants of factory)"
capture label var j_contract_cost_beets_received "Cost of beets received (grown on contract by others than tenants of factory)"
capture label var j_purchased_beets_received "Beets received, tons (purchased, not on contract)"
capture label var j_purchased_beets_sliced "Beets sliced, tons (purchased, not on contract)"
capture label var j_purchased_cost_beets_received "Cost of beets received (purchased, not on contract)"
capture label var j_other_beets_received "Beets received, tons (beets received from other factories)"
capture label var j_other_beets_sliced "Beets sliced, tons (beets received from other factories)"
capture label var j_other_cost_beets_received "Cost of beets received (beets received from other factories)"
capture label var j_q_transferred "Beets transferred to other factories, tons"
capture label var j_v_transferred "Beets transferred to other factories, value"
capture label var j_location_received "Location of factories from which this factor received beets"
capture label var j_location_transferred "Location of factories to which this factory transferred beets"
capture label var j_sucrose_percent "Quality of beets used: Average percent of sucrose"
capture label var j_purity_coefficient "Quality of beets used: Average coefficient of purity"
capture label var j_recovery_specify "Specify the process, if any, used for recovery of sugar from molasses"
