//label variables for industry 626

//label output variables
capture label var gp_q_whiteLead_carbonateC "Output: Pigment White Lead, basic carbonate consumed, qt."
capture label var gp_q_whiteLead_sulfateC "Output: Pigment White Lead, sulfate consumed, qt."
capture label var gp_q_whiteLeadC "Output: Pigment White Lead, consumed, qt."
capture label var gp_v_whiteLead_carbonate "Output: Pigment White Lead, basic carbonate, value"
capture label var gp_v_whiteLead_sulfate "Output: Pigment White Lead, sulfate, value"
capture label var gp_v_whiteLead "Output: Pigment White Lead, value"
capture label var gp_q_whiteLead_carbonate "Output: Pigment White Lead, basic carbonate, qt."
capture label var gp_q_whiteLead_sulfate "Output: Pigment White Lead, sulfate, qt."
capture label var gp_q_whiteLead "Output: Pigment White Lead, qt."
capture label var gp_q_leadOxide_lithargeC "Output: Pigment Lead oxides, litharge, consumed, qt."
capture label var gp_q_leadOxide_redLeadC "Output: Pigment Lead oxide, red lead minimum, qt."
capture label var gp_q_leadOxide_otherC "Output: Pigment Lead oxide other, consumed, qt."
capture label var gp_v_leadOxide_litharge "Output: Pigment Lead oxides, litharge, value"
capture label var gp_v_leadOxide_redLead "Output: Pigment Lead oxide, red lead minimum, value"
capture label var gp_v_leadOxide_other "Output: Pigment Lead oxide other, value"
capture label var gp_q_leadOxide_litharge "Output: Pigment Lead oxides, litharge, qt."
capture label var gp_q_leadOxide_redLead "Output: Pigment Lead oxide, red lead minimum, qt."
capture label var gp_q_leadOxide_other "Output: Pigment White Lead, qt."
capture label var gp_s_leadOxide_other "Output: Pigment Lead oxide other, specify"
capture label var gp_q_zincOxideC "Output: Pigment Zinc Oxide consumed, qt."
capture label var gp_q_zincOxide "Output: Pigment Zinc Oxide, qt."
capture label var gp_v_zincOxide "Output: Pigment Zinc Oxide, value"
capture label var gp_q_zincSulphideC "Output: Pigment Zinc Sulphide consumed, qt."
capture label var gp_q_zincSulphide "Output: Pigment Zinc Sulphide, qt."
capture label var gp_v_zincSulphide "Output: Pigment Zinc Sulphide, value"
capture label var gp_q_lithoponeC "Output: Pigment lithopone consumed, qt."
capture label var gp_q_lithopone "Output: Pigment lithopone, qt."
capture label var gp_v_lithopone "Output: Pigment lithopone, value"
capture label var gp_q_barytesC "Output: Pigment barytes consumed, qt."
capture label var gp_q_barytes "Output: Pigment barytes, qt."
capture label var gp_v_barytes "Output: Pigment barytes, value"
capture label var gp_q_ironOxide_naturalC "Output: Pigment Iron Oxide Natural consumed, qt."
capture label var gp_q_ironOxide_natural "Output: Pigment Iron Oxide Natural, qt."
capture label var gp_v_ironOxide_natural "Output: Pigment Iron Oxide Natural, value"
capture label var gp_q_ironOxide_syntheticC "Output: Pigment Iron Oxide Synthetic consumed, qt."
capture label var gp_q_ironOxide_synthetic "Output: Pigment Iron Oxide Synthetic, qt."
capture label var gp_v_ironOxide_synthetic "Output: Pigment Iron Oxide Synthetic, value"
capture label var gp_q_ironOxide "Output: Pigment Iron Oxide, qt."
capture label var gp_v_ironOxide "Output: Pigment Iron Oxide, value"
capture label var gp_q_otherMineral1C "Output: Pigment Other Mineral Colors 1 consumed, qt."
capture label var gp_q_otherMineral1 "Output: Pigment Other Mineral Colors 1, qt."
capture label var gp_v_otherMineral1 "Output: Pigment Other Mineral Colors 1, value"
capture label var gp_s_otherMineral1 "Output: Pigment Other Mineral Colors 1, specify"
capture label var gp_q_otherMineral2C "Output: Pigment Other Mineral Colors 2 consumed, qt."
capture label var gp_q_otherMineral2 "Output: Pigment Other Mineral Colors 2, qt."
capture label var gp_v_otherMineral2 "Output: Pigment Other Mineral Colors 2, value"
capture label var gp_s_otherMineral2 "Output: Pigment Other Mineral Colors 2, specify"
capture label var gp_q_pigment_lampblackC "Output: Pigment lamp black consumed, qt."
capture label var gp_q_pigment_lampblack "Output: Pigment lamp black, qt."
capture label var gp_v_pigment_lampblack "Output: Pigment lamp black, value"
capture label var gp_q_pigment_carbonblackC "Output: Pigment carbon black consumed, qt."
capture label var gp_q_pigment_carbonblack "Output: Pigment carbon black, qt."
capture label var gp_v_pigment_carbonblack "Output: Pigment carbon black, value"
capture label var gp_q_chromeYellowC "Output: Pigment chrome yellow consumed, qt."
capture label var gp_q_chromeYellow "Output: Pigment chrome yellow, qt."
capture label var gp_v_chromeYellow "Output: Pigment chrome yellow, value"
capture label var gp_q_chromeOrangeC "Output: Pigment chrome orange consumed, qt."
capture label var gp_q_chromeOrange "Output: Pigment chrome orange, qt."
capture label var gp_v_chromeOrange "Output: Pigment chrome orange, value"
capture label var gp_q_chromeGreenC "Output: Pigment chrome green consumed, qt."
capture label var gp_q_chromeGreen "Output: Pigment chrome green, qt."
capture label var gp_v_chromeGreen "Output: Pigment chrome green, value"
capture label var gp_q_chrome "Output: Pigment chrome yellow, orange, and green, qt."
capture label var gp_v_chrome "Output: Pigment chrome yellow, orange, and green, value"
capture label var gp_q_coaltarC "Output: Pigment coal-tar color lakes consumed, qt."
capture label var gp_q_coaltar "Output: Pigment coal-tar color lakes, qt."
capture label var gp_v_coaltar "Output: Pigment coal-tar color lakes, value"
capture label var gp_q_prussianBlueC "Output: Pigment Prussian Blue consumed, qt."
capture label var gp_q_prussianBlue "Output: Pigment Prussian Blue, qt."
capture label var gp_v_prussianBlue "Output: Pigment Prussian Blue, value"
capture label var gp_q_ultramarineC "Output: Pigment ultramarine consumed, qt."
capture label var gp_q_ultramarine "Output: Pigment ultramarine, qt."
capture label var gp_v_ultramarine "Output: Pigment ultramarine, value"
capture label var gp_q_vermillionC "Output: Pigment vermillion consumed, qt."
capture label var gp_q_vermillion "Output: Pigment vermillion, qt."
capture label var gp_v_vermillion "Output: Pigment vermillion, value"
capture label var gp_q_whitingC "Output: Pigment whiting consumed, qt."
capture label var gp_q_whiting "Output: Pigment whiting, qt."
capture label var gp_v_whiting "Output: Pigment whiting, value"
capture label var gp_q_otherFine1C "Output: Pigment other fine color 1 consumed, qt."
capture label var gp_q_otherFine1 "Output: Pigment other fine color 1, qt."
capture label var gp_v_otherFine1 "Output: Pigment other fine color 1, value"
capture label var gp_s_otherFine1 "Output: Pigment other fine color 1, specify"
capture label var gp_q_otherFine2C "Output: Pigment other fine color 2 consumed, qt."
capture label var gp_q_otherFine2 "Output: Pigment other fine color 2, qt."
capture label var gp_v_otherFine2 "Output: Pigment other fine color 2, value"
capture label var gp_s_otherFine2 "Output: Pigment other fine color 2, specify"
capture label var gp_q_otherFine3C "Output: Pigment other fine color 3 consumed, qt."
capture label var gp_q_otherFine3 "Output: Pigment other fine color 3, qt."
capture label var gp_v_otherFine3 "Output: Pigment other fine color 3, value"
capture label var gp_s_otherFine3 "Output: Pigment other fine color 3, specify"
capture label var gp_q_otherDry1C "Output: Pigment other dry color 1 consumed, qt."
capture label var gp_q_otherDry1 "Output: Pigment other dry color 1, qt."
capture label var gp_v_otherDry1 "Output: Pigment other dry color 1, value"
capture label var gp_s_otherDry1 "Output: Pigment other dry color 1, specify"
capture label var gp_q_otherDry2C "Output: Pigment other dry color 2 consumed, qt."
capture label var gp_q_otherDry2 "Output: Pigment other dry color 2, qt."
capture label var gp_v_otherDry2 "Output: Pigment other dry color 2, value"
capture label var gp_s_otherDry2 "Output: Pigment other dry color 2, specify"
capture label var gp_q_mortarColorC "Output: Pigment mortar colors consumed, qt."
capture label var gp_q_mortarColor "Output: Pigment mortar colors, qt."
capture label var gp_v_mortarColor "Output: Pigment mortar colors, value"
capture label var gp_q_paint_pulp "Output: Paint pulp color sold moist, qt."
capture label var gp_v_paint_pulp "Output: Paint pulp color sold moist, value"
capture label var gp_q_paint_water "Output: Paint water, qt."
capture label var gp_v_paint_water "Output: Paint water, value"
capture label var gp_q_paint_plastic "Output: Paint plastic, qt."
capture label var gp_v_paint_plastic "Output: Paint plastic, value"

foreach paint_paste of "White lead" Combo "Red Lead" "Zinc Oxide" "Colors Oil" "Colors Japan" "Other"{
    local squeeze = substr("`paint_paste'", " ","")
    capture label var gp_s_paintPaste_`squeeze' "Output: Paint in paste `paint_paste', specify"
    capture label var gp_q_paintPaste_`squeeze' "Output: Paint in paste `paint_paste', qt."
    capture label var gp_v_paintPaste_`squeeze' "Output: Paint in paste `paint_paste', value"
}

foreach readyMixed_paste of "Oil" "Undercoatings" "Wall Paints" "Stains" "Other"
    local squeeze = substr("`readyMixed_paste'", " ","")
    capture label var gp_s_readyMixed_`squeeze' "Output: Paint ready-mixed `readyMixed_paste', specify"
    capture label var gp_q_readyMixed_`squeeze' "Output: Paint ready-mixed `readyMixed_paste', qt."
    capture label var gp_v_readyMixed_`squeeze' "Output: Paint ready-mixed `readyMixed_paste', value"
}

foreach varnish_prod of "Oleoresinous" "Spirit" "Other" "Stains" "Enamels" "Drying Japans" "Baking Japans"{
    local squeeze = substr("`varnish_prod'", " ","")
    capture label var gp_s_varnish_`squeeze' "Output: Varnishes `varnish_prod', specify"
    capture label var gp_q_varnish_`squeeze'C "Output: Varnishes `varnish_prod' consumed, qt."
    capture label var gp_q_varnish_`squeeze' "Output: Varnishes `varnish_prod', qt."
    capture label var gp_v_varnish_`squeeze' "Output: Varnishes `varnish_prod', value"
}

foreach Pyroxylin_prod of "Clear" "Lacquer" "Thinner" "Other"{
    local squeeze = substr("`Pyroxylin_prod'", " ","")
    capture label var gp_q_Pyroxylin_`squeeze'C "Output: Pyroxylin `Pyroxylin_prod' consumed, qt."
    capture label var gp_q_Pyroxylin_`squeeze' "Output: Pyroxylin `Pyroxylin_prod', qt."
    capture label var gp_v_Pyroxylin_`squeeze' "Output: Pyroxylin `Pyroxylin_prod', value"
}

foreach filler_prod of "Liquid" "Paste" "Putty" "Dry"{
    local squeeze = substr("`filler_prod'", " ","")
    capture label var gp_q_filler_`squeeze' "Output: Filler `filler_prod', qt."
    capture label var gp_v_filler_`squeeze' "Output: Filler `filler_prod', value"
}

foreach prod of "Shellac" "Removers" "Oils1" "Oils2" "Insecticides" "Linseed Oil"{
    local squeeze = substr("`prod'", " ","")
    capture label var gp_s_otherPaint_`squeeze' "Output: Other paint product `prod', specify"
    capture label var gp_q_otherPaint_`squeeze' "Output: Other paint product `prod', qt."
    capture label var gp_v_otherPaint_`squeeze' "Output: Other paint product `prod', value"
}
