//label variables for industry 1502

//label output variables
capture label var gp_q_Locomotives_steam "Output: Locomotives steam, qt."		
capture label var gp_v_Locomotives_steam "Output: Locomotives steam, value"		
capture label var gp_q_Locomotives_electric	"Output: Locomotives electric, qt."		
capture label var gp_q_Locomotives_electric "Output: Locomotives electric, value"		
capture label var gp_v_Repairs_locomotives "Output: Locomotives repair, value"		
capture label var gp_v_otherCorps_locomotives "Output: Locomotives for other corps., value"		
capture label var gp_v_all_other_locomotives "Output: Locomotives all others, value"		
capture label var gp_v_Locomotive_dept_Total "Output: Locomotives dept. total, value"		
capture label var gp_q_passenger_steam_wood	 "Output: Passenger car steam wood, qt."		
capture label var gp_q_passenger_steam_steelUF "Output: Passenger car steam steel underframe, qt."		
capture label var gp_q_passenger_steam_steelBody "Output: Passenger car steam steel body, qt."		
capture label var gp_q_passenger_steam_steelAll "Output: Passenger car steam steel all, qt."		
capture label var gp_v_passenger_steam "Output: Passenger car steam, value"		
capture label var gp_q_passenger_electric_wood "Output: Passenger car electric wood, qt."		
capture label var gp_q_passenger_electric_steelUF "Output: Passenger car electric steel underframe, qt."		
capture label var gp_q_passenger_electric_steelBody "Output: Passenger car electric steel body, qt."		
capture label var gp_q_passenger_electric_steelAll "Output: Passenger car steam steel all, qt."		
capture label var gp_v_passenger_electric "Output: Passenger car electric, value"
capture label var gp_q_freight_steam_wood	 "Output: Freight car steam wood, qt."
capture label var gp_q_freight_steam_steelUF "Output: Freight car steam	steel underframe, qt."
capture label var gp_q_freight_steam_steelBody "Output: Freight car steam steel body, qt."
capture label var gp_q_freight_steam_steelAll "Output: Freight car steam steel all, qt."
capture label var gp_v_freight_steam "Output: Freight car steam, value"
capture label var gp_q_freight_electric_wood "Output: Freight car electric wood, qt."
capture label var gp_q_freight_electric_steelUF "Output: Freight car electric steel underframe, qt."
capture label var gp_q_freight_electric_steelBody "Output: Freight car electric	steel body, qt."
capture label var gp_q_freight_electric_steelAll "Output: Freight car electric steel all, qt."
capture label var gp_v_freight_electric_cost "Output: Freight car electric, value"
capture label var gp_q_other_steam_wood	 "Output: Other train car steam wood, qt."
capture label var gp_q_other_steam_steelUF	"Output: Other train car steam steel underframe, qt." 	 
capture label var gp_q_other_steam_steelBody "Output: Other train car steam steel body, qt."
capture label var gp_q_other_steam_steelAll	"Output: Other train car steam steel all, qt."
capture label var gp_v_other_steam	"Output: Other train car steam, value"
capture label var gp_q_other_electric_wood "Output: Other train car electric wood, qt."
capture label var gp_q_other_electric_steelUF "Output: Other train car electric steel underframe, qt."
capture label var gp_q_other_electric_steelBody "Output: Other train car electric steel body, qt."
capture label var gp_q_other_electric_steelAll "Output: Other train car electric steel all, qt."
capture label var gp_v_other_electric "Output: Other train car electric, value"
capture label var gp_v_trainCar_Repairs "Output: Train car repairs"
capture label var gp_v_trainCar_Repairs_other_corps "Output: Train car other corps."
capture label var gp_v_trainCar_Repairs_All_other "Output: Train car reports all other"
capture label var gp_v_trainCar_Repairs_Total "Output: Train car repairs total"
capture label var gp_v_bridges_Repairs "Output: Bridge repairs"
capture label var gp_v_bridges_other_corps "Output: Other corp bridge work"
capture label var gp_v_bridges_other_work "Output: Other bridge work"
capture label var gp_v_bridges_Total "Output: Total bridge work"
capture label var gp_v_All_other "Output: Shop other revenue, value"
capture label var gp_v_shop_Total "Output: Shop total, value"
capture label var gp_q_Locomotives_electric "Output: Locomotives electric, qt."
capture label var gp_v_Locomotives_electric "Output: Locomotives electric, value"
capture label var gp_q_passenger_electric_steelBod "Output: Passenger car steel body, qt."
capture label var gp_v_trainCar_Repairs_other_corp "Output: Car department, work for other corporations, value"
