//label variables for industry 311
//Globals referenced: rootDir_code

//label output variables
capture label var gp_q_logs_produced "Output: Logs produced, qt."
capture label var gp_q_logs_used "Output: Logs used in the mill, qt."
capture label var gp_q_logs_sold "Output: Logs produced and sold, qt."
capture label var gp_v_logs_sold "Output: Logs produced and sold, value"
capture label var gp_v_all_other_timber "Output: All other timber products, value"
capture label var gp_v_contract_logging "Output: Contract logging, value"
capture label var gp_q_balsam_fir "Output: Balsam fir, qt"
capture label var gp_v_balsam_fir "Output: Balsam fir, value"
capture label var gp_q_cedar "Output: Cedar, qt"
capture label var gp_v_cedar "Output: Cedar, value"
capture label var gp_q_douglas_fir "Output: Douglas fir, qt"
capture label var gp_v_douglas_fir "Output: Douglas fir, value"
capture label var gp_q_cypress "Output: Cypress, qt"
capture label var gp_v_cypress "Output: Cypress, value"
capture label var gp_q_hemlock "Output: Hemlock, qt"
capture label var gp_v_hemlock "Output: Hemlock, value"
capture label var gp_q_southern_pine "Output: Southern pine, qt"
capture label var gp_v_southern_pine "Output: Southern pine, value"
capture label var gp_q_spruce "Output: Spruce, qt"
capture label var gp_v_spruce "Output: Spruce, value"
capture label var gp_q_spruce2 "Output: Spruce 2, qt"
capture label var gp_v_spruce2 "Output: Spruce 2, value" 
capture label var gp_q_white_pine "Output: White pine, qt"
capture label var gp_v_white_pine "Output: White pine, value"
capture label var gp_q_idaho_white_pine "Output: Idaho white pine, qt"
capture label var gp_v_idaho_white_pine "Output: Idaho white pine, value" 
capture label var gp_q_tamarack "Output: Tamarack, qt"
capture label var gp_v_tamarack "Output: Tamarack, value"
capture label var gp_q_larch "Output: Larch, qt"
capture label var gp_v_larch "Output: Larch, value"
capture label var gp_q_lodgepole_pine "Output: Lodgepole pine, qt"
capture label var gp_v_lodgepole_pine "Output: Lodgepole pine, value"
capture label var gp_q_port_orford_cedar "Output: Port orford cedar, qt"
capture label var gp_v_port_orford_cedar "Output: Port orford cedar, value"
capture label var gp_q_sugar_pine "Output: Sugar pine, qt"
capture label var gp_v_sugar_pine "Output: Sugar pine, value"
capture label var gp_q_western_pine "Output: Western pine, qt"
capture label var gp_v_western_pine "Output: Western pine, value"
capture label var gp_q_white_fir "Output: White fir, qt"
capture label var gp_v_white_fir "Output: White fir, value"
capture label var gp_q_alder "Output: Alder, qt"
capture label var gp_v_alder "Output: Alder, value"
capture label var gp_q_ash "Output: Ash, qt"
capture label var gp_v_ash "Output: Ash, value"
capture label var gp_q_basswood "Output: Basswood, qt"
capture label var gp_v_basswood "Output: Basswood, value"
capture label var gp_q_beech "Output: Beech, qt"
capture label var gp_v_beech "Output: Beech, value"
capture label var gp_q_birch "Output: Birch, qt"
capture label var gp_v_birch "Output: Birch, value"
capture label var gp_q_chestnut "Output: Chestnut, qt"
capture label var gp_v_chestnut "Output: Chestnut, value"
capture label var gp_q_cottonwood "Output: Cottonwood, qt"
capture label var gp_v_cottonwood "Output: Cottonwood, value"
capture label var gp_q_elm "Output: Elm, qt"
capture label var gp_v_elm "Output: Elm, value"
capture label var gp_q_gum "Output: Gum, qt"
capture label var gp_v_gum "Output: Gum, value"
capture label var gp_q_hickory "Output: Hickory, qt"
capture label var gp_v_hickory "Output: Hickory, value"
capture label var gp_q_maple "Output: Maple, qt"
capture label var gp_v_maple "Output: Maple, value"
capture label var gp_q_oak "Output: Oak, qt"
capture label var gp_v_oak "Output: Oak, value"
capture label var gp_q_sycamore "Output: Sycamore, qt"
capture label var gp_v_sycamore "Output: Sycamore, value"
capture label var gp_q_tupelo "Output: Tupelo, qt"
capture label var gp_v_tupelo "Output: Tupelo, value"
capture label var gp_q_walnut "Output: Walnut, qt"
capture label var gp_v_walnut "Output: Walnut, value"
capture label var gp_q_yellow_poplar "Output: Yellow poplar, qt"
capture label var gp_v_yellow_poplar "Output: Yellow poplar, value"
capture label var  gp_q_shingles "Output: Shingles, qt"
capture label var  gp_v_shingles "Output: Shingles, value"
capture label var  gp_q_lath "Output: Lath, qt"
capture label var  gp_v_lath "Output: Lath, value"
capture label var  gp_v_slack_cooperage "Output: Slack cooperage, value"
capture label var  gp_v_tight_cooperage "Output: Tight cooperage, value"
capture label var  gp_v_other_sawmill_products  "Output: Other sawmill products, value"
capture label var  gp_q_rough_lumber_produced "Output: Rough lumber products, qt."
capture label var  gp_q_rough_lumber_used "Output: Rough lumber used, qt."
capture label var  gp_q_rough_lumber_sold "Output: Rough lumber sold, qt."
capture label var  gp_v_rough_lumber_sold "Output: Rough lumber sold, value"
capture label var  gp_v_custom_sawing "Output: Custom sawing, value"
//these are actually from label industry 314 which applies to 1935
do "${rootDir_code}/Label/label_314_vars"

//label other variables
capture label var z_n_sawmills "Number of saw mills"
capture label var z_q_sawmills  "Capacity of saw mills"
capture label var z_inventory_lumber_beginning "Lumber on hand on Jan. 1, 1935"
capture label var z_inventory_lumber_end "Lumber on hand on Dec. 31, 1935"
