//label variables for industry 610

//label output variables
capture label var gp_q_carbonDioxide_Liquified "Output: Carbon Dioxide, Liquified, qt."
capture label var gp_v_carbonDioxide_Liquified "Output: Carbon Dioxide, Liquified, value"
capture label var gp_q_carbonDioxide_Made "Output: Carbon Dioxide, Made and consumed, qt."
capture label var gp_q_carbonDioxide_solid "Output: Carbon Dioxide, solid, qt."
capture label var gp_v_carbonDioxide_solid "Output: Carbon Dioxide, solid, value"
capture label var gp_q_Acetylene "Output: Acetylene, qt."
capture label var gp_v_Acetylene "Output: Acetylene, value"
capture label var gp_q_Pintsch "Output: Pintsch, qt."
capture label var gp_v_Pintsch "Output: Pintsch, value"
capture label var gp_q_hydrocarbonGas_Other "Output: Hydrocarbon Gas, Other, qt."
capture label var gp_v_hydrocarbonGas_Other "Output: Hydrocarbon Gas, Other, value"
capture label var gp_s_hydrocarbonGas_Other "Output: Hydrocarbon Gas, Other, specify"
capture label var gp_q_Hydrogen "Output: Hydrogen, qt."
capture label var gp_v_Hydrogen "Output: Hydrogen, value"
capture label var gp_q_Nitrogen "Output: Nitrogen, qt."
capture label var gp_v_Nitrogen "Output: Nitrogen, value"
capture label var gp_q_NitrousOxide "Output: Nitrous Oxide, qt."
capture label var gp_v_NitrousOxide "Output: Nitrous Oxide, value"
capture label var gp_q_Oxygen_liquefaction "Output: Oxygen, liquefaction, qt."
capture label var gp_v_Oxygen_liquefaction "Output: Oxygen, liquefaction, value"
capture label var gp_q_Oxygen_Electrolytic "Output: Oxygen, electrolytic, qt."
capture label var gp_v_Oxygen_Electrolytic "Output: Oxygen, electrolytic, value"
capture label var gp_q_Sulphur_Dioxide "Output: Sulphur_Dioxide, qt."
capture label var gp_v_Sulphur_Dioxide "Output: Sulphur_Dioxide, value"
capture label var gp_q_manufacturedGas_Other "Output: Manufactured Gas, Other, qt."
capture label var gp_v_manufacturedGas_Other "Output: Manufactured Gas, Other, value"
capture label var gp_s_manufacturedGas_Other "Output: Manufactured Gas, Other, specify"
			 																							
