//Label automobile variables

//Label output variables
capture label var gp_q_coupe "Output: Passenger Vehicles, closed, coupes, qt."
capture label var gp_v_coupe "Output: Passenger Vehicles, closed, coupes, value"
capture label var gp_q_pvc2d "Output: Passenger Vechicles, closed, 2-door sedans, qt."
capture label var gp_v_pvc2d "Output: Passenger Vechicles, closed, 2-door sedans, value"
capture label var gp_q_pvc4d "Output: Passenger Vechicles, closed, 4-door sedans, qt."
capture label var gp_v_pvc4d "Output: Passenger Vechicles, closed, 4-door sedans, value"
capture label var gp_q_pvo2d "Output: Passenger Vechicles, open, 2-door sedans, qt."
capture label var gp_v_pvo2d "Output: Passenger Vechicles, open, 2-door sedans, value"
capture label var gp_q_pvo4d "Output: Passenger Vechicles, open, 4-door sedans, qt."
capture label var gp_v_pvo4d "Output: Passenger Vechicles, open, 4-door sedans, value"
capture label var gp_q_pvcotr "Output: Passenger Vechicles, closed, other, qt."
capture label var gp_v_pvcotr "Output: Passenger Vechicles, closed, other, value"
capture label var gp_s_pvootr "Output: Passenger Vehicles, open, other, specify"
capture label var gp_q_rdstr "Output: Passenger Vechicles, open, roadster, qt."
capture label var gp_v_rdstr "Output: Passenger Vechicles, open, roadster, value"
capture label var gp_q_pvootr "Output: Passenger Vechicles, open, other, qt."
capture label var gp_v_pvootr "Output: Passenger Vechicles, open, other, value"
capture label var gp_q_bus20 "Output: Public conveyances, buses under 21 passengers, qt."
capture label var gp_v_bus20 "Output: Public conveyances, buses under 21 passengers, value"
capture label var gp_q_bus25 "Output: Public conveyances, buses from 21 to 32 passengers, qt."
capture label var gp_v_bus25 "Output: Public conveyances, buses from 21 to 32 passengers, value"
capture label var gp_q_bus35 "Output: Public conveyances, buses over 33 passengers, qt."
capture label var gp_v_bus35 "Output: Public conveyances, buses over 33 passengers, value"
capture label var gp_q_taxi "Output: Public conveyances, taxis, qt."
capture label var gp_v_taxi "Output: Public conveyances, taxis, value"
capture label var gp_q_opb "Output: Public conveyances, other, qt."
capture label var gp_v_opb "Output: Public conveyances, other, value"
capture label var gp_s_opb "Output: Public conveyances, other, specify"
capture label var gp_q_trklt "Output: Commerical vehicles, truck light, qt."
capture label var gp_v_trklt "Output: Commerical vehicles, truck light, value"
capture label var gp_q_trk1t "Output: Commerical vehicles, truck 1 ton, qt."
capture label var gp_v_trk1t "Output: Commerical vehicles, truck 1 ton, value"
capture label var gp_q_trk3t "Output: Commerical vehicles, truck 3 ton, qt."
capture label var gp_v_trk3t "Output: Commerical vehicles, truck 3 ton, value"
capture label var gp_q_trk5t "Output: Commerical vehicles, truck 5 ton, qt."
capture label var gp_v_trk5t "Output: Commerical vehicles, truck 5 ton, value"
capture label var gp_q_trktrc "Output: Commerical vehicles, truck tractors, qt."
capture label var gp_v_trktrc "Output: Commerical vehicles, truck tractors, value"
capture label var gp_q_trkhvy "Output: Commerical vehicles, truck heavy, qt."
capture label var gp_v_trkhvy "Output: Commerical vehicles, truck heavy, value"
capture label var gp_q_hearse "Output: Commerical vehicles, hearses, qt."
capture label var gp_v_hearse "Output: Commerical vehicles, hearses, value"
capture label var gp_q_othrcm "Output: Commercial vehicles, other, qt."
capture label var gp_v_othrcm "Output: Commercial vehicles, other, value"
capture label var gp_s_othrcm "Output: Commercial vehicles, other, specify"
capture label var gp_q_amb "Output: Public conveyances, ambulances, qt."
capture label var gp_v_amb "Output: Public conveyances, ambulances, value"
capture label var gp_q_fyren "Output: Government vehicles, fire engines, qt."
capture label var gp_v_fyren "Output: Government vehicles, fire engines, value"
capture label var gp_q_fyrhl  "Output: Government vehicles, fire hook and ladder trucks, qt."
capture label var gp_v_fyrhl  "Output: Government vehicles, fire hook and ladder trucks, value"
capture label var gp_q_fyrchm "Output: Government vehicles, fire chemical wagons, qt."
capture label var gp_v_fyrchm "Output: Government vehicles, fire chemical wagons, value"
capture label var gp_q_amb "Output: Public conveyances, ambulances, qt."
capture label var gp_v_amb "Output: Public conveyances, ambulances, value"
capture label var gp_q_fyrotr "Output: Government vehicles, fire other, qt."
capture label var gp_v_fyrotr "Output: Government vehicles, fire other, value"
capture label var gp_s_fyrotr "Output: Government vehicles, fire other, specify"
capture label var gp_q_ptlwgn "Output: Government vehicles, patrol wagons, qt."
capture label var gp_v_ptlwgn "Output: Government vehicles, patrol wagons, value"
capture label var gp_q_strcln "Output: Government vehicles, street cleaners, qt."
capture label var gp_v_strcln "Output: Government vehicles, street cleaners, value"
capture label var gp_q_othrmv "Output: Other vehicles, qt."
capture label var gp_v_othrmv "Output: Other vehicles, value"
capture label var gp_s_othrmv "Output: Other vehicles, specify"
capture label var gp_q_trl "Output: Trailers, qt."
capture label var gp_v_trl "Output: Trailers, value"
capture label var gp_q_trcrd "Output: Tractor, road, qt."
capture label var gp_v_trcrd "Output: Tractor, road, value"
capture label var gp_q_trcfrm "Output: Tractor, farm, qt."
capture label var gp_v_trcfrm "Output: Tractor, farm, value"
capture label var gp_q_otrgvt "Output: Government vehicles, other, qt."
capture label var gp_v_otrgvt "Output: Government vehicles, other, value"
capture label var gp_s_otrgvt "Output: Government vehicles, other, specify"
capture label var gp_q_trl "Output: Trailers, qt."
capture label var gp_v_trl "Output: Trailers, value"
capture label var gp_q_trcind "Output: Tractor, industrial, qt."
capture label var gp_v_trcind "Output: Tractor, industrial, value"
capture label var gp_q_chspv "Output: Chassis, passenger, qt."
capture label var gp_v_chspv "Output: Chassis, passenger, value"
capture label var gp_q_chscom "Output: Chassis, commercial, qt."
capture label var gp_v_chscom "Output: Chassis, commercial, value"
capture label var gp_q_chsbus  "Output: Chassis, bus, qt."
capture label var gp_v_chsbus "Output: Chassis, bus, value"
capture label var gp_q_body "Output: Bodies, qt."
capture label var gp_v_body "Output: Bodies, value"
