//label variables for industry 104

//label output variables
capture label var	gp_u1_canned_clams	"Output: Canned clams, unit"
capture label var	gp_u2_canned_clams	"Output: Canned clams, unit"
capture label var	gp_u3_canned_clams	"Output: Canned clams, unit"
capture label var	gp_u4_canned_clams	"Output: Canned clams, unit"
capture label var	gp_u5_canned_clams	"Output: Canned clams, unit"
capture label var	gp_u6_canned_clams	"Output: Canned clams, unit"
capture label var	gp_v_canned_clams	"Output: Canned clams, value"
capture label var	gp_u1_canned_oysters	"Output: Canned oysters, unit"
capture label var	gp_u2_canned_oysters	"Output: Canned oysters, unit"
capture label var	gp_u3_canned_oysters	"Output: Canned oysters, unit"
capture label var	gp_u4_canned_oysters	"Output: Canned oysters, unit"
capture label var	gp_u5_canned_oysters	"Output: Canned oysters, unit"
capture label var	gp_u6_canned_oysters	"Output: Canned oysters, unit"
capture label var	gp_v_canned_oysters	"Output: Canned oysters, value"
capture label var	gp_u1_canned_shrimp	"Output: Canned shrimp, unit"
capture label var	gp_u2_canned_shrimp	"Output: Canned shrimp, unit"
capture label var	gp_u3_canned_shrimp	"Output: Canned shrimp, unit"
capture label var	gp_u4_canned_shrimp	"Output: Canned shrimp, unit"
capture label var	gp_u5_canned_shrimp	"Output: Canned shrimp, unit"
capture label var	gp_u6_canned_shrimp	"Output: Canned shrimp, unit"
capture label var	gp_v_canned_shrimp	"Output: Canned shrimp, value"
capture label var	gp_u1_canned_mackarel	"Output: Canned mackarel, unit"
capture label var	gp_u2_canned_mackarel	"Output: Canned mackarel, unit"
capture label var	gp_u3_canned_mackarel	"Output: Canned mackarel, unit"
capture label var	gp_u4_canned_mackarel	"Output: Canned mackarel, unit"
capture label var	gp_u5_canned_mackarel	"Output: Canned mackarel, unit"
capture label var	gp_u6_canned_mackarel	"Output: Canned mackarel, unit"
capture label var	gp_v_canned_mackarel	"Output: Canned mackarel, value"
capture label var	gp_u1_canned_salmon	"Output: Canned salmon, unit"
capture label var	gp_u2_canned_salmon	"Output: Canned salmon, unit"
capture label var	gp_u3_canned_salmon	"Output: Canned salmon, unit"
capture label var	gp_u4_canned_salmon	"Output: Canned salmon, unit"
capture label var	gp_u5_canned_salmon	"Output: Canned salmon, unit"
capture label var	gp_u6_canned_salmon	"Output: Canned salmon, unit"
capture label var	gp_v_canned_salmon	"Output: Canned salmon, value"
capture label var	gp_u1_canned_sardines	"Output: Canned sardines, unit"
capture label var	gp_u2_canned_sardines	"Output: Canned sardines, unit"
capture label var	gp_u3_canned_sardines	"Output: Canned sardines, unit"
capture label var	gp_u4_canned_sardines	"Output: Canned sardines, unit"
capture label var	gp_u5_canned_sardines	"Output: Canned sardines, unit"
capture label var	gp_u6_canned_sardines	"Output: Canned sardines, unit"
capture label var	gp_v_canned_sardines	"Output: Canned sardines, value"
capture label var	gp_u1_canned_tuna	"Output: Canned tuna, unit"
capture label var	gp_u2_canned_tuna	"Output: Canned tuna, unit"
capture label var	gp_u3_canned_tuna	"Output: Canned tuna, unit"
capture label var	gp_u4_canned_tuna	"Output: Canned tuna, unit"
capture label var	gp_u5_canned_tuna	"Output: Canned tuna, unit"
capture label var	gp_u6_canned_tuna	"Output: Canned tuna, unit"
capture label var	gp_v_canned_tuna	"Output: Canned tuna, value"
capture label var	gp_s_canned_otherFish1	"Output: Canned other fish 1, specify"
capture label var	gp_u1_canned_otherFish1	"Output: Canned other fish 1, unit"
capture label var	gp_u2_canned_otherFish1	"Output: Canned other fish 1, unit"
capture label var	gp_u3_canned_otherFish1	"Output: Canned other fish 1, unit"
capture label var	gp_u4_canned_otherFish1	"Output: Canned other fish 1, unit"
capture label var	gp_u5_canned_otherFish1	"Output: Canned other fish 1, unit"
capture label var	gp_u6_canned_otherFish1	"Output: Canned other fish 1, unit"
capture label var	gp_v_canned_otherFish1	"Output: Canned other fish 1, value"
capture label var	gp_s_canned_otherFish2	"Output: Canned other fish 1, specify"
capture label var	gp_u1_canned_otherFish2	"Output: Canned other fish 2, unit"
capture label var	gp_u2_canned_otherFish2	"Output: Canned other fish 2, unit"
capture label var	gp_u3_canned_otherFish2	"Output: Canned other fish 2, unit"
capture label var	gp_u4_canned_otherFish2	"Output: Canned other fish 2, unit"
capture label var	gp_u5_canned_otherFish2	"Output: Canned other fish 2, unit"
capture label var	gp_u6_canned_otherFish2	"Output: Canned other fish 2, unit"
capture label var	gp_v_canned_otherFish2	"Output: Canned other fish 2, value"
capture label var	gp_u1_clamBroth	"Output: Clam broth, unit"
capture label var	gp_u2_clamBroth	"Output: Clam broth, unit"
capture label var	gp_u3_clamBroth	"Output: Clam broth, unit"
capture label var	gp_u4_clamBroth	"Output: Clam broth, unit"
capture label var	gp_u5_clamBroth	"Output: Clam broth, unit"
capture label var	gp_u6_clamBroth	"Output: Clam broth, unit"
capture label var	gp_v_clamBroth	"Output: Clam broth, value"
capture label var	gp_u1_crabMeat	"Output: Crab meat, unit"
capture label var	gp_u2_crabMeat	"Output: Crab meat, unit"
capture label var	gp_u3_crabMeat	"Output: Crab meat, unit"
capture label var	gp_u4_crabMeat	"Output: Crab meat, unit"
capture label var	gp_u5_crabMeat	"Output: Crab meat, unit"
capture label var	gp_u6_crabMeat	"Output: Crab meat, unit"
capture label var	gp_v_crabMeat	"Output: Crab meat, value"
capture label var	gp_u1_fishCakes	"Output: Fish cakes, unit"
capture label var	gp_u2_fishCakes	"Output: Fish cakes, unit"
capture label var	gp_u3_fishCakes	"Output: Fish cakes, unit"
capture label var	gp_u4_fishCakes	"Output: Fish cakes, unit"
capture label var	gp_u5_fishCakes	"Output: Fish cakes, unit"
capture label var	gp_u6_fishCakes	"Output: Fish cakes, unit"
capture label var	gp_v_fishCakes	"Output: Fish roe, value"
capture label var	gp_u1_fishRoe	"Output: Fish roe, unit"
capture label var	gp_u2_fishRoe	"Output: Fish roe, unit"
capture label var	gp_u3_fishRoe	"Output: Fish roe, unit"
capture label var	gp_u4_fishRoe	"Output: Fish roe, unit"
capture label var	gp_u5_fishRoe	"Output: Fish roe, unit"
capture label var	gp_u6_fishRoe	"Output: Fish roe, unit"
capture label var	gp_v_fishRoe	"Output: Fish roe, value"
capture label var	gp_s_cannedFished_other1	"Output: Canned fish other 1, specify"
capture label var	gp_u1_cannedFished_other1	"Output: Canned fish other 1, unit"
capture label var	gp_u2_cannedFished_other1	"Output: Canned fish other 1, unit"
capture label var	gp_u3_cannedFished_other1	"Output: Canned fish other 1, unit"
capture label var	gp_u4_cannedFished_other1	"Output: Canned fish other 1, unit"
capture label var	gp_u5_cannedFished_other1	"Output: Canned fish other 1, unit"
capture label var	gp_u6_cannedFished_other1	"Output: Canned fish other 1, unit"
capture label var	gp_v_cannedFished_other1	"Output: Canned fish other 1, value"
capture label var	gp_s_cannedFished_other2	"Output: Canned fish other 2, specify"
capture label var	gp_u1_cannedFished_other2	"Output: Canned fish other 2, unit"
capture label var	gp_u2_cannedFished_other2	"Output: Canned fish other 2, unit"
capture label var	gp_u3_cannedFished_other2	"Output: Canned fish other 2, unit"
capture label var	gp_u4_cannedFished_other2	"Output: Canned fish other 2, unit"
capture label var	gp_u5_cannedFished_other2	"Output: Canned fish other 2, unit"
capture label var	gp_u6_cannedFished_other2	"Output: Canned fish other 2, unit"
capture label var	gp_v_cannedFished_other2	"Output: Canned fish other 2, value"
capture label var	gp_q_smokedFish_finnan	"Output: Smoked fish finnan haddie,  qt."
capture label var	gp_v_smokedFish_finnan	"Output: Smoked fish finnan haddie, value"
capture label var	gp_q_smokedFish_herring	"Output: Smoked fish herring,  qt."
capture label var	gp_v_smokedFish_herring	"Output: Smoked fish herring, value"
capture label var	gp_q_smokedFish_salmon	"Output: Smoked fish salmon,  qt."
capture label var	gp_v_smokedFish_salmon	"Output: Smoked fish salmon, value"
capture label var	gp_s_smokedFish_other1	"Output: Smoked fish other 1, specify"
capture label var	gp_q_smokedFish_other1	"Output: Smoked fish other 1,  qt."
capture label var	gp_v_smokedFish_other1	"Output: Smoked fish other 1, value"
capture label var	gp_s_smokedFish_other2	"Output: Smoked fish other 2, specify"
capture label var	gp_q_smokedFish_other2	"Output: Smoked fish other 2,  qt."
capture label var	gp_v_smokedFish_other2	"Output: Smoked fish other 2, value"
capture label var	gp_q_driedFish_cod	"Output: Dried fish cod,  qt."
capture label var	gp_v_driedFish_cod	"Output: Dried fish cod, value"
capture label var	gp_q_driedFish_herring	"Output: Dried fish herring,  qt."
capture label var	gp_v_driedFish_herring	"Output: Dried fish herring, value"
capture label var	gp_s_driedFish_other1	"Output: Dried fish other 1, specify"
capture label var	gp_q_driedFish_other1	"Output: Dried fish other 1,  qt."
capture label var	gp_v_driedFish_other1	"Output: Dried fish other 1, value"
capture label var	gp_s_driedFish_other2	"Output: Dried fish other 2, specify"
capture label var	gp_q_driedFish_other2	"Output: Dried fish other 2,  qt."
capture label var	gp_v_driedFish_other2	"Output: Dried fish other 2, value"
capture label var	gp_q_saltedFish_cod	"Output: Salted fish cod,  qt."
capture label var	gp_v_saltedFish_cod	"Output: Salted fish cod, value"
capture label var	gp_q_saltedFish_haddock	"Output: Salted fish haddock,  qt."
capture label var	gp_v_saltedFish_haddock	"Output: Salted fish haddock, value"
capture label var	gp_q_saltedFish_herring	"Output: Salted fish herring,  qt."
capture label var	gp_v_saltedFish_herring	"Output: Salted fish herring, value"
capture label var	gp_q_saltedFish_mackarel	"Output: Salted fish mackarel,  qt."
capture label var	gp_v_saltedFish_mackarel	"Output: Salted fish mackarel, value"
capture label var	gp_s_saltedFish_other1	"Output: Salted fish other 1, specify"
capture label var	gp_q_saltedFish_other1	"Output: Salted fish other 1,  qt."
capture label var	gp_v_saltedFish_other1	"Output: Salted fish other 1, value"
capture label var	gp_s_saltedFish_other2	"Output: Salted fish other 2, specify"
capture label var	gp_q_saltedFish_other2	"Output: Salted fish other 2,  qt."
capture label var	gp_v_saltedFish_other2	"Output: Salted fish other 2, value"
capture label var	gp_q_bonelessFish_cod	"Output: Boneless fish cod,  qt."
capture label var	gp_v_bonelessFish_cod	"Output: Boneless fish cod, value"
capture label var	gp_q_bonelessFish_haddock	"Output: Boneless fish haddock,  qt."
capture label var	gp_v_bonelessFish_haddock	"Output: Boneless fish haddock, value"
capture label var	gp_s_bonelessFish_other1	"Output: Boneless fish other 1, specify"
capture label var	gp_q_bonelessFish_other1	"Output: Boneless fish other 1,  qt."
capture label var	gp_v_bonelessFish_other1	"Output: Boneless fish other 1, value"
capture label var	gp_s_bonelessFish_other2	"Output: Boneless fish other 2, specify"
capture label var	gp_q_bonelessFish_other2	"Output: Boneless fish other 2,  qt."
capture label var	gp_v_bonelessFish_other2	"Output: Boneless fish other 2, value"
capture label var	gp_s_bonelessFish_other3	"Output: Boneless fish other 3, specify"
capture label var	gp_q_bonelessFish_other3	"Output: Boneless fish other 3,  qt."
capture label var	gp_v_bonelessFish_other3	"Output: Boneless fish other 3, value"
capture label var	gp_q_fishOil	"Output: Fish oil,  qt."
capture label var	gp_v_fishOil	"Output: Fish oil, value"
capture label var	gp_q_fishScrap_dried	"Output: Fish scrap dried,  qt."
capture label var	gp_v_fishScrap_dried	"Output: Fish scrap dried, value"
capture label var	gp_q_fishScrap_green	"Output: Fish scrap green,  qt."
capture label var	gp_v_fishScrap_green	"Output: Fish scrap green, value"
capture label var	gp_q_fertilizerMaterial	"Output: Fertilizer Material,  qt."
capture label var	gp_v_fertilizerMaterial	"Output: Fertilizer Material, value"
capture label var	gp_q_liquidGlue	"Output: Liquid glue,  qt."
capture label var	gp_v_liquidGlue	"Output: Liquid glue, value"
capture label var	gp_q_oysterShells	"Output: Oyster shells,  qt."
capture label var	gp_v_oysterShells	"Output: Oyster shells, value"
capture label var	gp_q_oysterShell_lime	"Output: Oyster shell lime,  qt."
capture label var	gp_v_oysterShell_lime	"Output: Oyster shell lime, value"

//label input variables
capture label var	j_v_fishConsumption	"Input:	Fresh fish consumption, value"
