//rename variables for ind 311 in 1933

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//missing renames for AT-DG

//rename output variables
capture rename DH gp_q_balsam_fir
capture rename DI gp_v_balsam_fir
capture rename DJ gp_q_cedar
capture rename DK gp_v_cedar
capture rename DL gp_q_douglas_fir
capture rename DM gp_v_douglas_fir
capture rename DN gp_q_cypress
capture rename DO gp_v_cypress
capture rename DP gp_q_hemlock
capture rename DQ gp_v_hemlock
capture rename DR gp_q_larch
capture rename DS gp_v_larch
capture rename DT gp_q_lodgepole_pine
capture rename DU gp_v_lodgepole_pine
capture rename DV gp_q_ponderosa_pine
capture rename DW gp_v_ponderosa_pine
capture rename DX gp_q_port_orford_cedar
capture rename DY gp_v_port_orford_cedar
capture rename DZ gp_q_redwood
capture rename EA gp_v_redwood
capture rename EB gp_q_southern_pine
capture rename EC gp_v_southern_pine
capture rename ED gp_q_spruce
capture rename EE gp_v_spruce
capture rename EF gp_q_spruce2
capture rename EG gp_v_spruce2
capture rename EH gp_q_sugar_pine
capture rename EI gp_v_sugar_pine
capture rename EJ gp_q_white_fir
capture rename EK gp_v_white_fir
capture rename EL gp_q_white_pine
capture rename EM gp_v_white_pine
capture rename EN gp_q_tamarack
capture rename EO gp_v_tamarack
capture rename EP gp_q_western_pine
capture rename EQ gp_v_western_pine
capture rename ER gp_q_alder
capture rename ES gp_v_alder
capture rename ET gp_s_lumber_other1
capture rename EU gp_q_lumber_other1
capture rename EV gp_v_lumber_other1
capture rename EW gp_s_lumber_other2
capture rename EX gp_q_lumber_other2
capture rename EY gp_v_lumber_other2
capture rename EZ gp_s_lumber_other3
capture rename FA gp_q_lumber_other3
capture rename FB gp_v_lumber_other3
capture rename FC gp_s_lumber_other3
capture rename FD gp_q_lumber_other3
capture rename FE gp_v_lumber_other4
capture rename FF gp_q_ash
capture rename FG gp_v_ash
capture rename FH gp_q_basswood
capture rename FI gp_v_basswood
capture rename FJ gp_q_beech
capture rename FK gp_v_beech
capture rename FL gp_q_birch
capture rename FM gp_v_birch
capture rename FN gp_q_chestnut
capture rename FO gp_v_chestnut
capture rename FP gp_q_cottonwood
capture rename FQ gp_v_cottonwood
capture rename FR gp_q_elm
capture rename FS gp_v_elm
capture rename FT gp_q_gum
capture rename FU gp_v_gum
capture rename FV gp_q_hickory
capture rename FW gp_v_hickory
capture rename FX gp_q_maple
capture rename FY gp_v_maple
capture rename FZ gp_q_oak
capture rename GA gp_v_oak
capture rename GB gp_q_sycamore
capture rename GC gp_v_sycamore
capture rename GD gp_q_tupelo
capture rename GE gp_v_tupelo
capture rename GF gp_q_walnut
capture rename GG gp_v_walnut
capture rename GH gp_q_yellow_poplar
capture rename GI gp_v_yellow_poplar
//missing labels from GJ-IV
