//Cleaning script for BR spreadsheet: 237_1933. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1933/237"
import excel "`data_dir'/023733A0.xls", allstring sheet("023733A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L plntname
capture rename M ownrname
capture rename N incyn
capture rename O a004
capture rename P state
capture rename Q city
capture rename R county
capture rename S street
capture rename T othraddr
capture rename U incityyn
capture rename V othrcity
capture rename W sbsdryyn
capture rename X mthrinfo
capture rename Y as001
capture rename Z as002
capture rename AA as003
capture rename AB as004
capture rename AC as005
capture rename AD products
capture rename AE mtlsusd1
capture rename AF mtlsusd2
capture rename AG d001
capture rename AH d008
capture rename AI xtraln1
capture rename AJ xtraln2
capture rename AK xtraln3
capture rename AL xtraln4

//rename employment variables
capture rename AM empldate
capture rename AN propnm
capture rename AO offcnm
capture rename AP mngrnm
capture rename AQ clrknm
capture rename AR wagenm
capture drop AS
capture rename AT wetotal
capture drop AU //column name: diff
capture rename AV wejan
capture rename AW wefeb
capture rename AX wemar
capture rename AY weapr
capture rename AZ wemay
capture rename BA wejun
capture rename BB wejul
capture rename BC weaug
capture rename BD wesep
capture rename BE weoct
capture rename BF wenov
capture rename BG wedec
capture rename BH offcslry
capture rename BI e003tas
capture rename BJ clrkslry
capture rename BK weslry
capture drop BL
capture rename BM totlslry
capture drop BN //column name: diff1

capture rename BO f009
capture rename BP f004
capture rename BQ f007
capture drop BR
capture drop BS //column name: diff2

//rename output variables
capture rename BT gp_s_general1
capture rename BU gp_q_general1
capture rename BV gp_v_general1
capture rename BW gp_s_general2
capture rename BX gp_q_general2
capture rename BY gp_v_general2
capture rename BZ gp_s_general3
capture rename CA gp_q_general3
capture rename CB gp_v_general3
capture rename CC gp_s_general4
capture rename CD gp_q_general4
capture rename CE gp_v_general4
capture rename CF gp_s_general5
capture rename CG gp_q_general5
capture rename CH gp_v_general5
capture rename CI gp_s_general6
capture rename CJ gp_q_general6
capture rename CK gp_v_general6
capture drop CL
capture drop CM
capture drop CN
capture drop CO
capture rename CP g000q
capture rename CQ g000v

//not sure why these are being dropped (CZV they look to be blank on the spreadsheets)
capture drop CR
capture drop CS
capture drop CT
capture drop CU
capture drop CV
capture drop CW
capture drop CX
capture drop CY
capture drop CZ
capture drop DA
capture drop DB
capture drop DC
capture drop DD
capture drop DE
capture drop DF
capture drop DG
capture drop DH
capture drop DI
capture drop DJ
capture drop DK
capture drop DL
capture drop DM
capture drop DN
capture drop DO
capture drop DP
capture drop DQ
capture drop DR
capture drop DS
capture drop DT
capture drop DU
capture drop DV
capture drop DW
capture drop DX

capture drop year
gen year =  1933
//rename "common" set of variables for labeling 
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistency
tostring *, replace force

save "$rootDir_dataBR/1933/237/237_1933", replace
