//Cleaning script for BR spreadsheet: 705_1933. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1933/705"
import excel "`data_dir'/070533A0.xls", allstring sheet("070533A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L a_plntname
capture rename M b_ownrname
capture rename N incyn
capture rename O a004
capture rename P state
capture rename Q city
capture rename R f_county
capture rename S street
capture rename T h_othraddr
capture rename U i_incityyn
capture rename V othrcity
capture rename W j_sbsdryyn
capture rename X mthrinfo
capture rename Y k_nmchngyn
capture rename Z lnchngyn
capture rename AA owchngyn
capture rename AB bschngyn
capture rename AC frmrinfo
capture rename AD a_products
capture rename AE b_mtlsusd1
capture rename AF mtlsusd2

//rename utilization variables
capture rename AG d001
capture rename AH d008
capture rename AI comments
capture rename AJ inq4date

//rename employment variables
capture rename AK e001t
capture rename AL e002t
capture rename AM e003ta
capture rename AN e003tc
capture rename AO 
capture drop AP
capture rename AQ wetotlnm
capture rename AR ewemt01
capture rename AS ewemt02
capture rename AT ewemt03
capture rename AU ewemt04
capture rename AV ewemt05
capture rename AW ewemt06
capture rename AX ewemt07
capture rename AY ewemt08
capture rename AZ ewemt09
capture rename BA ewemt10
capture rename BB ewemt11
capture rename BC ewemt12
capture rename BD e002s
capture rename BE e003tas
capture rename BF e003tcs
capture rename BG e005s
capture drop BH
capture rename BI e009s

//rename costs of inputs variables
capture rename BJ f009
capture rename BK f004
capture drop BL
capture rename BM f007

//rename output variables
capture rename BN gp_q_gasoline
capture rename BO gp_v_gasoline
capture rename BP gp_q_napththa
capture rename BQ gp_v_napththa
capture rename BR gp_q_benzine
capture rename BS gp_v_benzine
capture rename BT gp_q_tops
capture rename BU gp_v_tops
capture rename BV gp_q_illuminating_oil
capture rename BW gp_v_illuminating_oil
capture rename BX gp_q_distillate
capture rename BY gp_v_distillate
capture rename BZ gp_q_gas_oils
capture rename CA gp_v_gas_oils
capture rename CB gp_q_residual_fuel_oils
capture rename CC gp_v_residual_fuel_oils
capture rename CD gp_q_above_fuel_oil
capture rename CE gp_v_above_fuel_oil
capture rename CF gp_q_at_fuel_oil
capture rename CG gp_v_at_fuel_oil
capture rename CH gp_q_below_fuel_oil
capture rename CI gp_v_below_fuel_oil
capture rename CJ gp_q_red_neutral_pale_parrafin
capture rename CK gp_v_red_neutral_pale_parrafin
capture rename CL gp_q_black_lubricating_oil
capture rename CM gp_v_black_lubricating_oil
capture rename CN gp_q_all_other_lubricating_oil
capture rename CO gp_v_all_other_lubricating_oil
capture rename CP gp_q_liquid_asphalt
capture rename CQ gp_v_liquid_asphalt
capture rename CR gp_q_residuum_or_tar
capture rename CS gp_v_residuum_or_tar
capture rename CT gp_q_petrolatum
capture rename CU gp_v_petrolatum
capture rename CV gp_q_axle_grease
capture rename CW gp_v_axle_grease
capture rename CX gp_q_paraffin_wax
capture rename CY gp_v_paraffin_wax
capture rename CZ gp_q_acid_oil
capture rename DA gp_v_acid_oil
capture rename DB gp_q_liquefied_petroleum_gas
capture rename DC gp_v_liquefied_petroleum_gas
capture rename DD gp_q_asphalt_other
capture rename DE gp_v_asphalt_other
capture rename DF gp_q_coke
capture rename DG gp_v_coke
capture rename DH gp_q_reclaimed_acid
capture rename DI gp_v_reclaimed_acid
capture rename DJ gp_q_insecticides
capture rename DK gp_v_insecticides
capture rename DL gp_s_otherRefinery1
capture rename DM gp_s_otherRefinery1
capture rename DN gp_s_otherRefinery1
capture rename DO gp_s_otherRefinery2
capture rename DP gp_q_otherRefinery2
capture rename DQ gp_v_otherRefinery2
capture rename DR gp_s_other1
capture rename DS gp_q_other1
capture rename DT gp_v_other1
capture rename DU receipts_for_contract_work
capture drop DV //value28 not sure what this is
capture drop DW
capture rename DX total_output_value

capture drop year
gen year =  1933
//rename "common" set of variables for labeling 
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending
tostring *, replace force

save "$rootDir_dataBR/1933/705/705_1933", replace
