//Cleaning script for BR spreadsheet: 1112_1933. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1933/1112"
import excel "`data_dir'/111233A0.xls", allstring sheet("111233A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F com
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L firm_code
capture rename M how_many_p
capture rename N plntname
capture rename O ownrname
capture rename P incyn
capture rename Q a004
capture rename R state
capture rename S city
capture rename T county
capture rename U street
capture rename V othraddr
capture rename W incityyn
capture rename X othrcity
capture rename Y sbsdryyn
capture rename Z mthrinfo
capture rename AA nmchngyn
capture rename AB lnchngyn
capture rename AC owchngyn
capture rename AD bschngyn
capture rename AE frmrinfo
capture rename AF products
capture rename AG mtlsusd1
capture rename AH mtlsusd2
capture rename AI d001
capture rename AJ d008
capture rename AK inq3cmt1
capture rename AL inq3cmt2
capture rename AM inq4date

//rename employment variables
capture rename AN e001t
capture rename AO e002t
capture rename AP e003ta
capture rename AQ e003tc
capture rename AR wage_earne
capture drop AS
capture rename AT wetotlnm
capture drop AU //column name: diff
capture rename AV wejan
capture rename AW wefeb
capture rename AX wemar
capture rename AY weapr
capture rename AZ wemay
capture rename BA wejun
capture rename BB wejul
capture rename BC weaug
capture rename BD wesep
capture rename BE weoct
capture rename BF wenov
capture rename BG wedec
capture rename BH e002s
capture rename BI e003tas
capture rename BJ e003tcs
capture rename BK e005s
capture drop BL
capture rename BM e009s
capture drop BN //column name: diff1

//rename costs of inputs variables
capture rename BO f009
capture rename BP f005f
capture rename BQ f004
capture drop BR
capture rename BS f007
capture drop BT //column name: diff2
//drop some useless variables
capture drop BU
capture drop BV
capture drop BW
capture drop BX
capture drop BY
capture drop BZ
capture drop CA
capture drop CB
capture drop CC
capture drop CD
capture drop CE
capture drop CF
capture drop CG
capture drop CH
capture drop CI
capture drop CJ
drop inq3cmt1 inq3cmt2 inq4date

save "$rootDir_dataBR/1933/1112/1112_1933_clean", replace

//now clean B spreadsheets
do "$rootDir_code/1933/clean_1112_1933_B"
//merge with existing dataset
use "$rootDir_dataBR/1933/1112/1112_1933_clean", clear
merge 1:1 record using "$rootDir_dataBR/1933/1112/1112_1933_clean_B"
//this should really be a 1-1 mapping
drop _merge

capture drop year
gen year =  1933
//rename "common" set of variables for labeling 
do "$rootDir_code/General/basic_rename"
//tpstring all variables for consistent appending
tostring *, replace force

save "$rootDir_dataBR/1933/1112/1112_1933_clean", replace
