//Cleaning script for BR spreadsheet: 631_1933. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1933/631"
import excel "`data_dir'/063133A1.xls", allstring sheet("063133A1") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F statenm
capture rename G cntynm
capture rename H citynm
capture rename I indnm
capture rename J formnm
capture rename K a_plntname
capture rename L b_ownrname
capture rename M incyn
capture rename N a004
capture rename O state
capture rename P city
capture rename Q f_county
capture rename R street
capture rename S h_othraddr
capture rename T i_incityyn
capture rename U othrcity
capture rename V j_sbsdryyn
capture rename W mthrinfo
capture rename X k_nmchngyn
capture rename Y lnchngyn
capture rename Z owchngyn
capture rename AA bschngyn
capture rename AB frmrinfo
capture rename AC a_products
capture rename AD b_mtlsusd1
capture rename AE mtlsusd2

//rename utilization variables
capture rename AF d001
capture rename AG d008
capture rename AH inq4date

//rename employment variables
capture rename AI a_propriet
capture rename AJ b_officers
capture rename AK c_managers
capture rename AL d_clerical
capture rename AM e_wage_ear
capture drop AN
capture rename AO wetotlnm
capture drop AP //column name: diff
capture rename AQ ewemt01
capture rename AR ewemt02
capture rename AS ewemt03
capture rename AT ewemt04
capture rename AU ewemt05
capture rename AV ewemt06
capture rename AW ewemt07
capture rename AX ewemt08
capture rename AY ewemt09
capture rename AZ ewemt10
capture rename BA ewemt11
capture rename BB ewemt12
capture rename BC a_total_am
capture rename BD b_total_am
capture rename BE c_total_am
capture rename BF d_total_am
capture drop BG //column name: diff1
capture drop BH
capture rename BI totlwgs

//rename costs of input variables
capture rename BJ f009
capture rename BK f004
capture drop BL
capture rename BM f007
capture drop BN //column name: diff2

//rename output variables
capture rename BO gp_q_toilet_soap
capture rename BP gp_v_toilet_soap
capture rename BQ gp_q_shaving_soap
capture rename BR gp_v_shaving_soap
capture rename BS gp_q_laundry_soap
capture rename BT gp_v_laundry_soap
capture rename BU gp_q_foot_soap
capture rename BV gp_v_foot_soap
capture rename BW gp_q_soap_chip
capture rename BX gp_v_soap_chip
capture rename BY gp_q_granulated_soap
capture rename BZ gp_v_granulated_soap
capture rename CA gp_s_other_hard_soap1
capture rename CB gp_q_other_hard_soap1
capture rename CC gp_v_other_hard_soap1
capture rename CD gp_s_other_hard_soap2
capture rename CE gp_q_other_hard_soap2
capture rename CF gp_v_other_hard_soap2
capture rename CG gp_s_other_hard_soap3
capture rename CH gp_q_other_hard_soap3
capture rename CI gp_v_other_hard_soap1
capture rename CJ gp_s_other_hard_soap4
capture rename CK gp_q_other_hard_soap4
capture rename CL gp_v_other_hard_soap4
capture rename CM gp_q_shaving_cream
capture rename CN gp_v_shaving_cream
capture rename CO gp_q_soap_powder
capture rename CP gp_v_soap_powder
capture rename CQ gp_q_cleanser_soap
capture rename CR gp_v_cleanser_soap
capture rename CS gp_q_cleanser_no_soap
capture rename CT gp_v_cleanser_no_soap
capture rename CU gp_q_liquid_soap
capture rename CV gp_v_liquid_soap
capture rename CW gp_q_paste_soap
capture rename CX gp_v_paste_soap
capture rename CY gp_q_soft_soap
capture rename CZ gp_v_soft_soap
capture rename DA gp_q_soap_stock
capture rename DB gp_v_soap_stock
capture rename DC gp_q_glycerin_crude
capture rename DD gp_v_glycerin_crude
capture rename DE gp_q_glycerin_refined
capture rename DF gp_v_glycerin_refined
capture rename DG gp_q_steraic_acid
capture rename DH gp_v_steraic_acid
capture rename DI gp_q_glycerin_refined
capture rename DJ gp_v_glycerin_refined
capture rename DK gp_q_stearic_acid
capture rename DL gp_v_stearic_acid
capture rename DM gp_q_red_oil
capture rename DN gp_v_red_oil
capture rename DO gp_q_insecticide
capture rename DP gp_v_insecticide
capture rename DQ gp_q_sodium_sil1
capture rename DR gp_v_sodium_sil1
capture rename DS gp_v_sodium_sil2
capture rename DT gp_v_perfume
capture rename DU gp_v_toilet_water
capture rename DV gp_v_cream
capture rename DX gp_v_rouge
capture rename DY gp_v_dentrifices
capture rename DZ gp_v_shampoo
capture rename EA gp_v_hair_dyes
capture rename EB gp_v_hair_tonics
capture rename EC gp_v_hair_dressings

capture drop year
gen year =  1933
//rename "common" set of variables for labeling 
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending
tostring *, replace force

save "$rootDir_dataBR/1933/631/631_1933", replace
