//rename variable for industry 106 in 1833

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
rename AR gp_q_flour_white
rename AS gp_v_flour_white
rename AT gp_q_flour_graham
rename AU gp_v_flour_graham
rename AV gp_q_flour_semolina
rename AW gp_v_flour_semolina
rename AX gp_q_flour_rye
rename AY gp_v_flour_rye
rename AZ gp_q_flour_corn_meal
rename BA gp_v_flour_corn_meal
rename BB gp_q_flour_buckwheat
rename BC gp_v_flour_buckwheat
rename BD gp_s_flour_other_1
rename BE gp_q_flour_other_1
rename BF gp_v_flour_other_1
rename BG gp_s_flour_other_2
rename BH gp_q_flour_other_2
rename BI gp_v_flour_other_2
rename BJ gp_q_bran
rename BK gp_v_bran
rename BL gp_q_feed
rename BM gp_v_feed
rename BN gp_q_prepared_flour
rename BO gp_v_prepared_flour
rename BP gp_q_cereal_corn
rename BQ gp_v_cereal_corn
rename BR gp_q_cereal_wheat
rename BS gp_v_cereal_wheat
rename BT gp_q_cereal_oats
rename BU gp_v_cereal_oats
rename BV gp_q_cereal_other_grains
rename BW gp_v_cereal_other_grains
rename BX gp_q_cereal_coffee_sub
rename BY gp_v_cereal_coffee_sub
rename BZ gp_s_other_cereal_1
rename CA gp_v_other_cereal_1
rename CB gp_s_all_other_cereal
rename CC gp_u_all_other_cereal
rename CD gp_q_all_other_cereal
rename CE gp_v_all_other_cereal
rename CF gp_q_alfalfa_meal
rename CG gp_v_alfalfa_meal
rename CH gp_q_prepared_feed
rename CI gp_v_prepared_feed
rename CJ gp_s_other_prepared_feed_1
rename CK gp_v_other_prepared_feed_1
rename CL gp_q_malt_barley
rename CM gp_v_malt_barley
rename CN gp_q_malt_rye
rename CO gp_v_malt_rye
rename CP gp_q_sprouts
rename CQ gp_v_sprouts
rename CR gp_q_screenings
rename CS gp_v_screenings
rename CT gp_s_other_by_products
rename CU gp_v_other_by_products
rename CV gp_s_other1
rename CW gp_v_other1
rename CX gp_s_other2
rename CY gp_v_other2
rename CZ gp_s_other3
rename DA gp_v_other3
rename DB gp_v_all_other_products
rename DC gp_v_custom_work 
rename DD g000v

//rename input variables
rename DE jp_q_wheat
rename DF jp_v_wheat
rename DG jp_q_corn
rename DH jp_v_corn
rename DI jp_q_rye
rename DJ jp_v_rye
rename DK jp_q_barley
rename DL jp_v_barley
rename DM jp_q_buckwheat
rename DN jp_v_buckwheat
rename DO jp_q_oats
rename DP jp_v_oats
rename DQ jp_s_other
rename DR jp_q_other
rename DS jp_v_other
rename DT jp_q_soybean_whole
rename DU jp_q_soybean_beanoil
rename DV jp_q_soybean
rename DW jp_v_soybean

rename DX z_capacity_flour_mill

//rename man hours variables
rename DY emh01
rename DZ emh02
rename EA emh03
rename EB emh04
rename EC emh05
rename ED emh06
rename EE emh07
rename EF emh08
rename EG emh09
rename EH emh10
rename EI emh11
rename EJ emh12
rename EK emht
rename EL ewemt
