//rename variables for industry 118 in year 1933

//rename output variables
capture rename AR gp_q_creamery_butter
capture rename AS gp_v_creamery_butter
capture rename AT gp_q_cheese_whole_milk
capture rename AU gp_v_cheese_whole_milk
capture rename AV gp_q_cheese_part_skim
capture rename AW gp_v_cheese_part_skim
capture rename AX gp_q_cheese_full_skim
capture rename AY gp_v_cheese_full_skim
capture rename AZ gp_q_swiss
capture rename BA gp_v_swiss
capture rename BB gp_q_brick
capture rename BC gp_v_brick
capture rename BD gp_q_munster
capture rename BE gp_v_munster
capture rename BF gp_q_limburger
capture rename BG gp_v_limburger
capture rename BH gp_q_cottage
capture rename BI gp_v_cottage
capture rename BJ gp_q_cream
capture rename BK gp_v_cream
capture rename BL gp_q_neufchatel
capture rename BM gp_v_neufchatel
capture rename BN gp_s_italian_varieties
capture rename BO gp_q_italian_varieties
capture rename BP gp_v_italian_varieties
capture rename BQ gp_s_other1 
capture rename BR gp_q_other1
capture rename BS gp_v_other1
capture rename BT gp_q_whey_butter
capture rename BU gp_v_whey_butter
capture rename BV gp_q_dried_casein
capture rename BW gp_v_dried_casein
capture rename BX gp_q_wet_casein
capture rename BY gp_v_wet_casein
capture rename BZ gp_q_condensed_milk
capture rename CA gp_v_condensed_milk
capture rename CB gp_q_whole_case_goods
capture rename CC gp_v_whole_case_goods
capture rename CD gp_q_whole_bulk_goods
capture rename CE gp_v_whole_bulk_goods
capture rename CF gp_q_skim_case_goods
capture rename CG gp_v_skim_case_goods
capture rename CH gp_q_skim_bulk_goods
capture rename CI gp_v_skim_bulk_goods
capture rename CJ gp_q_evaporated_case_goods
capture rename CK gp_v_evaporated_case_goods
capture rename CL gp_q_evaporated_bulk_goods
capture rename CM gp_v_evaporated_bulk_goods
capture rename CN gp_q_concentrated_skim
capture rename CO gp_v_concentrated_skim
capture rename CP gp_q_condensed_evaporated
capture rename CQ gp_v_condensed_evaporated
capture rename CR gp_q_dried_buttermilk
capture rename CS gp_v_dried_buttermilk
capture rename CT gp_q_dried_cream
capture rename CU gp_v_dried_cream
capture rename CV gp_q_dried_skim
capture rename CW gp_v_dried_skim
capture rename CX gp_q_dried_whole
capture rename CY gp_v_dried_whole
capture rename CZ gp_q_milk_sugar_crude
capture rename DA gp_v_milk_sugar_crude
capture rename DB gp_q_milk_sugar_refined
capture rename DC gp_v_milk_sugar_refined
capture rename DD gp_q_ice_cream
capture rename DE gp_v_ice_cream
capture rename DF gp_q_ices_sherbets
capture rename DG gp_v_ices_sherbets
capture rename DH gp_q_specialties
capture rename DI gp_v_specialties
capture rename DJ gp_q_ice_cream_mix
capture rename DK gp_v_ice_cream_mix
capture rename DL gp_q_ice_sale
capture rename DM gp_v_ice_sale
capture rename DN gp_q_ice_consumed
capture rename DO gp_v_ice_consumed
capture rename DP gp_q_confectionery
capture rename DQ gp_v_confectionery
capture rename DR gp_q_beverages
capture rename DS gp_v_beverages
capture rename DT gp_q_bakery
capture rename DU gp_v_bakery
capture rename DV gp_q_malted_milk
capture rename DW gp_v_malted_milk
capture rename DX gp_q_skim_sold
capture rename DY gp_v_skim_sold
capture rename DZ gp_q_buttermilk_sold
capture rename EA gp_v_buttermilk_sold
capture rename EB gp_q_whey_sold
capture rename EC gp_v_whey_sold
capture rename ED gp_q_milk_sold
capture rename EE gp_v_milk_sold
capture rename EF gp_q_cream_sold
capture rename EG gp_v_cream_sold
capture rename EH gp_s_other2
capture rename EI gp_q_other2
capture rename EJ gp_v_other2
capture rename EK g000v

//rename man hours variables
capture rename EL emh01
capture rename EM emh02
capture rename EN emh03
capture rename EO emh04
capture rename EP emh05
capture rename EQ emh06
capture rename ER emh07
capture rename ES emh08
capture rename ET emh09
capture rename EU emh10
capture rename EV emh11
capture rename EW emh12
drop EX-IR

//These aren't actually *on* the ice form
drop f004 f009
