//Cleaning script for BR spreadsheet: 803_1933. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1933/803"
import excel "`data_dir'/080333A0.xls", allstring sheet("080333A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L how_many_p
capture rename M plntname
capture rename N ownrname
capture rename O incyn
capture rename P a004
capture rename Q state
capture rename R city
capture rename S county
capture rename T street
capture rename U othraddr
capture rename V incityyn
capture rename W othrcity
capture rename X sbsdryyn
capture rename Y mthrinfo
capture rename Z nmchngyn
capture rename AA as002
capture rename AB as003
capture rename AC as004
capture rename AD as005
capture rename AE products
capture rename AF mtlsusd1

//rename utilization variables
capture rename AG d001
capture rename AH d008
capture rename AI inq3cmt1
capture rename AJ inq3cmt2
capture rename AK fnlbgndt
capture rename AL fnlenddt
capture rename AM inq4date

//rename employment variables
capture rename AN e001t
capture rename AO e002t
capture rename AP e003ta
capture rename AQ e003tc
capture rename AR wage_earne
capture drop AS
capture rename AT wetotlnm
capture drop AU //column name: diff
capture rename AV wejan
capture rename AW wefeb
capture rename AX wemar
capture rename AY weapr
capture rename AZ wemay
capture rename BA wejun
capture rename BB wejul
capture rename BC weaug
capture rename BD wesep
capture rename BE weoct
capture rename BF wenov
capture rename BG wedec
capture drop BH
capture rename BI e002s
capture rename BJ e003tas
capture rename BK e003tcs
capture rename BL e005s
capture drop BM
capture rename BN e009s
capture drop BO //column name: diff1
capture rename BP f009
capture rename BQ f004
capture drop BR
capture rename BS f007
capture drop BT //column name: diff2

//rename output (and input) variables
capture rename BU gp_q_pneumatic_mv_casing_balloon
capture rename BV gp_v_pneumatic_mv_casing_balloon
capture rename BW gp_q_pneumatic_mv_casing_HP
capture rename BX gp_v_pneumatic_mv_casing_HP
capture rename BY j_q_rubber_pneumatic_mv_casing
capture rename BZ gp_q_pneumatic_mv_innerTube_balloon
capture rename CA gp_v_pneumatic_mv_innerTube_balloon
capture rename CB gp_q_pneumatic_mv_innerTube_HP
capture rename CC gp_v_pneumatic_mv_innerTube_HP
capture rename CD j_q_rubber_pneumatic_mv_innerTube
capture rename CE gp_q_pneumatic_motorCycle_casing
capture rename CF gp_v_pneumatic_motorCycle_casing
capture rename CG gp_q_pneumatic_motorCycle_innerTube
capture rename CH gp_v_pneumatic_motorCycle_innerTube
capture rename CI j_q_rubber_motorCycle
capture rename CJ gp_q_bicycle_singleTube
capture rename CK gp_v_bicycle_singleTube
capture rename CL gp_q_bicycle_innerTube
capture rename CM gp_v_bicycle_innerTube
capture rename CN j_q_rubber_bicycle
capture rename CO gp_q_tractor_tire
capture rename CP gp_v_tractor_tire
capture drop CQ //column name: rub4. don't know what this is to be?
capture rename CR gp_v_rubber_otherCasing
capture drop CS //column name: rub5. don't know what this is to be?
capture rename CT gp_q_solidRubber_truck
capture rename CU gp_v_solidRubber_truck
capture rename CV gp_q_solidRubber_tractor
capture rename CW gp_v_solidRubber_tractor
capture rename CX gp_v_solidRubber_other
capture rename CY j_q_rubber_solid_cushion
capture rename CZ gp_q_rubber_canvas
capture rename DA gp_v_rubber_canvas
capture rename DB gp_q_rubber_boot
capture rename DC gp_v_rubber_boot
capture rename DD gp_q_lumbermen_boot
capture rename DE gp_v_lumbermen_boot
capture rename DF gp_q_artics_boot
capture rename DG gp_v_artics_boot
capture rename DH gp_q_other_shoe
capture rename DI gp_v_other_shoe
capture rename DJ gp_q_other_shoe_notRubber
capture rename DK gp_v_other_shoe_notRubber
capture rename DL j_q_rubber_shoe
capture rename DM gp_q_heel
capture rename DN gp_v_heel
capture rename DO gp_q_soles
capture rename DP gp_v_soles
capture rename DQ gp_q_soling_strip
capture rename DR gp_v_soling_strip
capture rename DS j_q_rubber_soles
capture rename DT gp_q_rubber_auto
capture rename DU gp_v_rubber_auto
capture rename DV gp_q_rubber_raincoat
capture rename DW gp_v_rubber_raincoat
capture rename DX gp_q_rubber_hospital

capture drop year
gen year =  1933
//rename "common" set of variables for labeling 
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending
tostring *, replace force

save "$rootDir_dataBR/1933/803/803_1933", replace
