//Cleaning script for BR spreadsheet: 1110_1933. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1933/1110"
import excel "`data_dir'/111033A1_PDSPL.xls", allstring sheet("111033A1") clear

drop in 1/2 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E id
capture rename F tempid
capture rename G comment
capture rename H statenm
capture rename I cntynm
capture rename J citynm
capture rename K indnm
capture rename L formnm
capture rename M merchant
capture rename N how_many_p
capture rename O plntname
capture rename P ownrname
capture rename Q incyn
capture rename R a004
capture rename S state
capture rename T city
capture rename U county
capture rename V street
capture rename W othraddr
capture rename X incityyn
capture rename Y othrcity
capture rename Z sbsdryyn
capture rename AA mthrinfo
capture rename AB nmchngyn
capture rename AC as002
capture rename AD owchngyn
capture rename AE as004
capture rename AF frmrinfo
capture rename AG products
capture rename AH mtlsusd1
capture rename AI mtlsusd2

//rename utilization variables
capture rename AJ d001
capture rename AK d008
capture rename AL inq3cmt1
capture rename AM inq3cmt2
capture rename AN inq4date

//rename employment variables
capture rename AO e001t
capture rename AP e002t
capture rename AQ e003ta
capture rename AR e003tc
capture rename AS wage_earne
capture drop AT
capture rename AU wetotlnm
capture drop AV //column name: diff
capture rename AW ewemt01
capture rename AX ewemt02
capture rename AY ewemt03
capture rename AZ ewemt04
capture rename BA ewemt05
capture rename BB ewemt06
capture rename BC ewemt07
capture rename BD ewemt08
capture rename BE ewemt09
capture rename BF ewemt10
capture rename BG ewemt11
capture rename BH ewemt12
capture rename BI e002s
capture rename BJ e003tas
capture rename BK e003tcs
capture rename BL e005s
capture drop BM
capture rename BN e009s
capture drop BO //column name: diff1

//rename costs of inputs variables
capture rename BP f009
capture rename BQ f005f
capture drop BR
capture rename BS f007
capture drop BT //column name: diff2

//rename output variables
capture rename BU gp_q_coke_ip
capture rename BV gp_v_coke_ip
capture rename BW gp_q_coke_fs
capture rename BX gp_v_coke_fs
capture rename BY gp_v_coke
capture rename BZ gp_q_charcoal_ip
capture rename CA gp_v_charcoal_ip
capture rename CB gp_q_charcoal_fs
capture rename CC gp_v_charcoal_fs
capture rename CD gp_v_charcoal
capture rename CE gp_n_otherfuel1
capture rename CF gp_q_otherfuel1_ip
capture rename CG gp_v_otherfuel1_ip
capture rename CH gp_q_otherfuel1_fs
capture rename CI gp_v_otherfuel1_fs
capture rename CJ gp_v_otherfuel2
capture rename CK gp_n_otherfuel2
capture rename CL gp_q_otherfuel2_ip
capture rename CM gp_v_otherfuel2_ip
capture rename CN gp_q_otherfuel2_fs
capture rename CO gp_v_otherfuel2_fs
capture rename CP gp_v_otherfuel2
capture rename CQ gp_q_blastfurnacegas
capture rename CR gp_q_blastfurnacegas_other
capture rename CS gp_v_blastfurnacegas_other
capture rename CT gp_v_slag
capture rename CU gp_n_general1
capture rename CV gp_v_general1
capture drop CW
capture rename CX g000v
capture drop CY-DY //why are these being dropped?
capture rename DZ gp_q_pigiron_foundry_ip
capture rename EA gp_q_pigiron_foundry_fs
capture rename EB gp_q_pigiron_basic_ip
capture rename EC gp_q_pigiron_basic_fs
capture rename ED gp_q_pigiron_bessemer_ip
capture rename EE gp_q_pigiron_bessemer_fs
capture rename EF gp_q_pigiron_lowPhosphorus_ip
capture rename EG gp_q_pigiron_lowPhosphorus_fs
capture rename EH gp_q_pigiron_malleable_ip
capture rename EI gp_q_pigiron_malleable_fs
capture rename EJ gp_q_pigiron_forge_ip
capture rename EK gp_q_pigiron_forge_fs
capture rename EL gp_q_pigiron_white_ip
capture rename EM gp_q_pigiron_white_fs
capture rename EN gp_q_directCasting_pipe_ip
capture rename EO gp_q_directCasting_pipe_fs
capture rename EP gp_q_directCasting_other_ip
capture rename EQ gp_q_directCasting_other_fs
capture rename ER gp_q_spiegeleisen_consumption_ip
capture rename ES gp_q_spiegeleisen_fs
capture rename ET gp_v_spiegeleisen
capture rename EU gp_q_ferromanganese_ip
capture rename EV gp_q_ferromanganese_fs
capture rename EW gp_v_ferromanganese
capture rename EX gp_q_ferrophosphorus_ip
capture rename EY gp_q_ferrophosphorus_fs
capture rename EZ gp_v_ferrophosphorus
capture rename FA gp_q_ferrosillicon_ip
capture rename FB gp_q_ferrosillicon_fs
capture rename FC gp_v_ferrosillicon
capture rename FD gp_q_ferroalloy_other_ip
capture rename FE gp_q_ferroalloy_other_fs
capture rename FF gp_v_ferroalloy_other
capture rename FJ gp_q_machine_cast
capture rename FK gp_q_sand_cast
capture rename FL gp_q_chill_cast
capture rename FM gp_q_delivered_molton

//rename capital variables
capture rename FN z_stack
capture rename FO z_stack_fuel
capture rename FP z_stack_capacity
capture rename FQ z_stack_volume
capture rename FR z_stack_active1_fuel
capture rename FS z_stack_active1_number
capture rename FT z_stack_active1_capacity
capture rename FU z_stack_active2_fuel
capture rename FV z_stack_active2_number
capture rename FW z_stack_active2_capacity
capture rename FX z_stack_idle_fuel
capture rename FY z_stack_idle_number
capture rename FZ z_stack_idle_capacity
capture rename GA z_stack_banked_fuel
capture rename GB z_stack_banked_number
capture rename GC z_stack_banked_capacity
capture rename GD z_stack_new_fuel
capture rename GE z_stack_new_number
capture rename GF z_stack_new_capacity
capture rename GG z_stack_inConstruction_fuel
capture rename GH z_stack_inConstruction_number
capture rename GI z_stack_inConstruction_capacity
capture rename GJ z_stack_abandoned_fuel
capture rename GK z_stack_abandoned_number
capture rename GL z_stack_abandoned_capacity
capture rename GM z_sintering_employees
capture rename GN z_sintering_employees_wages
capture rename GO z_sintering_employees_yesno

//rename man hours variables
capture rename GP emh01
capture rename GQ emh02
capture rename GR emh03
capture rename GS emh04
capture rename GT emh05
capture rename GU emh06
capture rename GV emh07
capture rename GW emh08
capture rename GX emh09
capture rename GY emh10
capture rename GZ emh11
capture rename HA emh12

capture drop year
gen year =  1933
//rename "common" set of variables for labeling 
do "$rootDir_code/General/basic_rename"
//fix a few id mistakes
do "$rootDir_code/1933/fix_estabids_1110_1933"
//tostring all variables for consistency
tostring *, replace force

save "$rootDir_dataBR/1933/1110/1110_1933_clean", replace
