//rename variables for industries 1215, 1216, and 1217 in year 1933
//These 3 industries share the same form in 1933.
//It is also substantially based on the 1931 form

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
rename AR gp_q_unrefinedS_CopperP
rename AS gp_v_unrefinedS_CopperP
rename AT gp_q_unrefinedS_CopperS
rename AU gp_v_unrefinedS_CopperS
rename AV gp_q_unrefinedS_CopperPT
rename AW gp_q_unrefinedS_CopperST
rename AX gp_v_unrefinedS_CopperT
rename AY gp_q_unrefinedS_BullionP
rename AZ gp_v_unrefinedS_BullionP
rename BA gp_q_unrefinedS_BullionS
rename BB gp_v_unrefinedS_BullionS
rename BC gp_q_unrefinedS_BullionPT
rename BD gp_q_unrefinedS_BullionST
rename BE gp_v_unrefinedS_BullionT
rename BF gp_s_unrefinedS_Other1
rename BG gp_q_unrefinedS_Other1P
rename BH gp_v_unrefinedS_Other1P
rename BI gp_q_unrefinedS_Other1S
rename BJ gp_v_unrefinedS_Other1S
rename BK gp_q_unrefinedS_Other1PT
rename BL gp_q_unrefinedS_Other1ST
rename BM gp_v_unrefinedS_Other1T
rename BN gp_s_unrefinedS_Other2
rename BO gp_q_unrefinedS_Other2P
rename BP gp_v_unrefinedS_Other2P
rename BQ gp_q_unrefinedS_Other2S
rename BR gp_v_unrefinedS_Other2S
rename BS gp_q_unrefinedS_Other2PT
rename BT gp_q_unrefinedS_Other2ST
rename BU gp_v_unrefinedS_Other2T
rename BV gp_q_refinedS_CopperP
rename BW gp_v_refinedS_CopperP
rename BX gp_q_refinedS_CopperS
rename BY gp_v_refinedS_CopperS
rename BZ gp_q_refinedS_CopperPT
rename CA gp_q_refinedS_CopperST
rename CB gp_v_refinedS_CopperT
rename CC gp_q_refinedS_LeadP
rename CD gp_v_refinedS_LeadP
rename CE gp_q_refinedS_LeadS
rename CF gp_v_refinedS_LeadS
rename CG gp_q_refinedS_LeadPT
rename CH gp_q_refinedS_LeadST
rename CI gp_v_refinedS_LeadT
rename CJ gp_q_refinedS_AntimonialLeadP
rename CK gp_v_refinedS_AntimonialLeadP
rename CL gp_q_refinedS_AntimonialLeadS
rename CM gp_v_refinedS_AntimonialLeadS
rename CN gp_q_refinedS_AntimonialLeadPT
rename CO gp_q_refinedS_AntimonialLeadST
rename CP gp_v_refinedS_AntimonialLeadT
rename CQ gp_q_refinedS_ZincP
rename CR gp_v_refinedS_ZincP
rename CS gp_q_refinedS_ZincS
rename CT gp_v_refinedS_ZincS
rename CU gp_q_refinedS_ZincPT
rename CV gp_q_refinedS_ZincST
rename CW gp_v_refinedS_ZincT
rename CX gp_q_refinedS_AluminumS
rename CY gp_v_refinedS_AluminumS
rename CZ gp_q_refinedS_AluminumPT
rename DA gp_q_refinedS_AluminumST
rename DB gp_v_refinedS_AluminumT
rename DC gp_q_refinedS_TinS
rename DD gp_v_refinedS_TinS
rename DE gp_q_refinedS_TinPT
rename DF gp_q_refinedS_TinST
rename DG gp_v_refinedS_TinT
rename DH gp_q_alloyReclaimed_Brass 
rename DI gp_v_alloyReclaimed_Brass 
rename DJ gp_q_alloyReclaimed_Antifriction 
rename DK gp_v_alloyReclaimed_Antifriction 
rename DL gp_q_alloyReclaimed_Solders 
rename DM gp_v_alloyReclaimed_Solders 
rename DN gp_q_alloyReclaimed_TypeMetal
rename DO gp_v_alloyReclaimed_TypeMetal
rename DP gp_s_alloyReclaimed_Other1 
rename DQ gp_q_alloyReclaimed_Other1
rename DR gp_v_alloyReclaimed_Other1
rename DS gp_s_alloyReclaimed_Other2
rename DT gp_q_alloyReclaimed_Other2
rename DU gp_v_alloyReclaimed_Other2
rename DV gp_q_preciousMetal_Gold
rename DW gp_v_preciousMetal_Gold
rename DX gp_q_preciousMetal_Silver
rename DY gp_v_preciousMetal_Silver
rename DX gp_s_preciousMetal_Other1
rename EA gp_q_preciousMetal_Other1
rename EB gp_v_preciousMetal_Other1
rename EC gp_s_pigments
rename ED gp_v_pigments
drop EE //total value of group 1 products
rename EF gp_q_plates_BrassT
rename EG gp_q_plates_BrassC
rename EH gp_q_plates_BrassFS
rename EI gp_v_plates_BrassFS
rename EJ gp_v_plates_BrassT
rename EK gp_q_plates_CopperT
rename EL gp_q_plates_CopperC
rename EM gp_q_plates_CopperFS
rename EN gp_v_plates_CopperFS
rename EO gp_v_plates_CopperT
rename EP gp_q_plates_LeadT
rename EQ gp_q_plates_LeadC
rename ER gp_q_plates_LeadFS
rename ES gp_v_plates_LeadFS
rename ET gp_v_plates_LeadT
rename EU gp_q_plates_ZincT
rename EV gp_q_plates_ZincC
rename EW gp_q_plates_ZincFS
rename EX gp_v_plates_ZincFS
rename EY gp_v_plates_ZincT
rename EZ gp_s_plates_Nickel
rename FA gp_q_plates_NickelT
rename FB gp_q_plates_NickelC
rename FC gp_q_plates_NickelFS
rename FD gp_v_plates_NickelFS
rename FE gp_v_plates_NickelT
rename FF gp_s_plates_Other1
rename FG gp_q_plates_Other1T
rename FH gp_q_plates_Other1C
rename FI gp_q_plates_Other1FS
rename FJ gp_v_plates_Other1FS
rename FK gp_v_plates_Other1T
rename FL gp_q_rods_BrassT
rename FM gp_q_rods_BrassC
rename FM gp_q_rods_BrassFS
rename FO gp_v_rods_BrassFS
rename FP gp_v_rods_BrassT
rename FQ gp_q_rods_CopperT
rename FR gp_q_rods_CopperC
rename FS gp_q_rods_CopperFS
rename FT gp_v_rods_CopperFS
rename FU gp_v_rods_CopperT
rename FV gp_s_rods_Nickel
rename FW gp_q_rods_NickelT
rename FX gp_q_rods_NickelC
rename FY gp_q_rods_NickelFS
rename FZ gp_v_rods_NickelFS
rename GA gp_v_rods_NickelT
rename GB gp_s_rods_Other1
rename GC gp_q_rods_Other1T
rename GD gp_q_rods_Other1C
rename GE gp_q_rods_Other1FS
rename GF gp_v_rods_Other1FS
rename GG gp_v_rods_Other1T
rename GH gp_q_extrudedShapes_BrassT
rename GI gp_q_extrudedShapes_BrassC
rename GJ gp_q_extrudedShapes_BrassFS
rename GK gp_v_extrudedShapes_BrassFS
rename GL gp_v_extrudedShapes_BrassT
rename GM gp_s_extrudedShapes_Other1
rename GN gp_q_extrudedShapes_Other1T
rename GO gp_q_extrudedShapes_Other1C
rename GP gp_q_extrudedShapes_Other1FS
rename GQ gp_v_extrudedShapes_Other1FS
rename GR gp_v_extrudedShapes_Other1T
rename GS gp_q_tubing_BrassT
rename GT gp_q_tubing_BrassC
rename GU gp_q_tubing_BrassFS
rename GV gp_v_tubing_BrassFS
rename GW gp_v_tubing_BrassT
rename GX gp_q_tubing_CopperT
rename GY gp_q_tubing_CopperC
rename GZ gp_q_tubing_CopperFS
rename HA gp_v_tubing_CopperFS
rename HB gp_v_tubing_CopperT
rename HC gp_q_tubing_LeadT
rename HD gp_q_tubing_LeadC
rename HE gp_q_tubing_LeadFS
rename HF gp_v_tubing_LeadFS
rename HG gp_v_tubing_LeadT
rename HH gp_s_tubing_Nickel
rename HI gp_q_tubing_NickelT
rename HJ gp_q_tubing_NickelFS
rename HK gp_q_tubing_NickelFS
rename HL gp_v_tubing_NickelT
rename HM gp_v_tubing_NickelC
rename HN gp_s_tubing_Other1
rename HO gp_q_tubing_Other1T
rename HP gp_q_tubing_Other1C
rename HQ gp_q_tubing_Other1FS
rename HR gp_v_tubing_Other1FS
rename HS gp_v_tubing_Other1T
rename HT gp_s_otherTubing_Other1
rename HU gp_q_otherTubing_Other1T
rename HV gp_q_otherTubing_Other1C
rename HW gp_q_otherTubing_Other1FS
rename HX gp_v_otherTubing_Other1FS
rename HY gp_v_otherTubing_Other1T
rename HZ gp_s_otherTubing_Other2
rename IA gp_q_otherTubing_Other2T
rename IB gp_q_otherTubing_Other2C
rename IC gp_q_otherTubing_Other2FS
rename ID gp_v_otherTubing_Other2FS
rename IE gp_v_otherTubing_Other2T
rename IF gp_v_wire
drop IG //total value for group 2 of products
rename IH gp_q_castings_Brass
rename II gp_v_castings_Brass
rename IJ gp_q_castings_Copper
rename IK gp_v_castings_Copper
rename IL gp_q_castings_Aluminum
rename IM gp_v_castings_Aluminum
rename IN gp_q_castings_ResistantAlloy
rename IO gp_v_castings_ResistantAlloy
rename IP gp_q_castings_Nickel
rename IQ gp_v_castings_Nickel
rename IR gp_s_castings_Other1
rename IS gp_q_castings_Other1
rename IT gp_v_castings_Other1
rename IU gp_s_castings_Other2
rename IV gp_q_castings_Other2
rename IW gp_v_castings_Other2
rename IX gp_v_bearings_Total
rename IY gp_v_electricalSupplies_Total
rename IZ gp_v_hardware_Total
rename JA gp_v_architecturalWork_Total
rename JB gp_v_ornamentalGrilles_Total
rename JC gp_v_valves_Total
rename JD gp_v_faucets_Total
rename JE gp_v_fittings_Total
rename JF gp_v_screwmachProducts_Total
rename JG gp_v_bells_Total
rename JH gp_v_dieCastings_Total
rename JI gp_v_finishedCastings_Total
rename JJ gp_v_forgings_Total
rename JK gp_v_spunWare_Total
rename JL gp_s_foundryOther1
rename JM gp_v_foundryOther1_Total
rename JN gp_s_foundryOther2
rename JO gp_v_foundryOther2_Total
rename JP gp_s_foundryOther3
rename JQ gp_v_foundryOther3_Total
rename JR gp_s_other1
rename JS gp_v_other1
rename JT gp_s_other2
rename JU gp_v_other2
rename JV gp_s_other3
rename JW gp_v_other3
rename JX gp_custom_work
drop JY //total value for group 3 products
rename JZ g000v
