//rename variables for industry 1113 in year 1933

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
/* The following are not renamed because they are not nail products but from a different form
rename AR gp_v_
rename AS gp_v_
rename AT gp_v_
rename AU gp_v_
rename AV gp_v_
rename AW gp_v_
rename AX gp_v_
rename AY gp_v_
rename AZ gp_v_
rename BA gp_v_
rename BB gp_v_
rename BC gp_v_
rename BD gp_v_
rename BE gp_v_
rename BF gp_v_
rename BG gp_v_
rename BH gp_v_
rename BI gp_v_
rename BJ gp_v_
rename BK gp_v_
rename BL gp_v_
rename BM gp_v_
rename BN gp_v_
rename BO gp_v_
rename BP gp_v_
rename BQ gp_v_
rename BR gp_v_
rename BS gp_v_
rename BT gp_v_
rename BU gp_v_
rename BV gp_v_
rename BW gp_v_
rename BX gp_v_
rename BY gp_v_
rename BZ gp_v_
rename CA gp_v_
rename CB gp_v_
rename CC gp_v_
rename CD gp_v_
rename CE gp_v_
rename CF gp_v_
rename CG gp_v_
rename CH gp_v_
rename CI gp_v_
rename CJ gp_v_
rename CK gp_v_
rename CL gp_v_
rename CM gp_v_
rename CN gp_v_
rename CO gp_v_
rename CP gp_v_
*/
drop AN-CP
rename CQ gp_q_wireNails_bright
rename CR gp_v_wireNails_bright
rename CS gp_q_wireNails_galvanized
rename CT gp_v_wireNails_galvanized
rename CU gp_s_wireNails_other
rename CV gp_q_wireNails_other
rename CW gp_v_wireNails_other
rename CX gp_q_cutTacks
rename CY gp_v_cutTacks
rename CZ gp_q_staples
rename DA gp_v_staples

/* The following variables are really for wire producers not nail producers
rename DB gp_v_
rename DC gp_v_
rename DD gp_v_
rename DE gp_v_
rename DF gp_v_
rename DG gp_v_
rename DH gp_v_
rename DI gp_v_
rename DJ gp_v_
rename DK gp_v_
rename DL gp_v_
rename DM gp_v_
rename DN gp_v_
rename DO gp_v_
rename DP gp_v_
rename DQ gp_v_
rename DR gp_v_
rename DS gp_v_
rename DT gp_v_
rename DU gp_v_
rename DV gp_v_
rename DW gp_v_
rename DX gp_v_
rename DY gp_v_
rename DZ gp_v_
rename EA gp_v_
rename EB gp_v_
rename EC gp_v_
rename ED gp_v_
rename EE gp_v_
rename EF gp_v_
rename EG gp_v_
rename EH gp_v_
rename EI gp_v_
rename EJ gp_v_
rename EK gp_v_
rename EL gp_v_
rename EM gp_v_
rename EN gp_v_
rename EO gp_v_
rename EP gp_v_
rename EQ gp_v_
rename ER gp_v_
rename ES gp_v_
rename ET gp_v_
rename EU gp_v_
rename EV gp_v_
rename EW gp_v_
rename EX gp_v_
rename EY gp_v_
rename EZ gp_v_
rename FA gp_v_
rename FB gp_v_
rename FC gp_v_
rename FD gp_v_
rename FE gp_v_
rename FF gp_v_
rename FG gp_v_
rename FH gp_v_
rename FI gp_v_
rename FJ gp_v_
rename FK gp_v_
rename FL gp_v_
rename FM gp_v_
rename FN gp_v_
rename FO gp_v_
rename FP gp_v_
rename FQ gp_v_
rename FR gp_v_
rename FS gp_v_
rename FT gp_v_
rename FU gp_v_
rename FV gp_v_
rename FW gp_v_
rename FX gp_v_
rename FY gp_v_
rename FZ gp_v_
rename GA gp_v_
rename GB gp_v_
rename GC gp_v_
rename GD gp_v_
rename GE gp_v_
rename GF gp_v_
rename GG gp_v_
rename GH gp_v_
rename GI gp_v_
rename GJ gp_v_
rename GK gp_v_
rename GL gp_v_
rename GM gp_v_
rename GN gp_v_
rename GO gp_v_
rename GP gp_v_
rename GQ gp_v_
rename GR gp_v_
rename GS gp_v_
rename GT gp_v_
rename GU gp_v_
rename GV gp_v_
rename GW gp_v_
rename GX gp_v_
rename GY gp_v_
*/
drop DB-GY
rename GZ gp_q_other1
rename HA gp_v_other1
rename HB gp_s_other1
rename HC g000v
