//rename variables industry 314  for 1933
 
 //rename output variables
capture rename AR gp_q_doors_dwellings
capture rename AS gp_v_doors_dwellings
capture rename AT gp_q_doors_other
capture rename AU gp_v_doors_other
capture rename AV gp_q_sash
capture rename AW gp_v_sash
capture rename AX gp_q_window_door_frames
capture rename AY gp_v_window_door_frames
capture rename AZ gp_q_window_door_screens
capture rename BA gp_v_window_door_screens
capture rename BB gp_q_portable_houses
capture rename BC gp_v_portable_houses
capture rename BD gp_q_tanks_vats
capture rename BE gp_v_tanks_vats
capture rename BF gp_q_venetian_blinds
capture rename BG gp_v_venetian_blinds
capture rename BH gp_q_silow_stock
capture rename BI gp_v_silow_stock
capture rename BJ gp_q_dressed_lumber
capture rename BK gp_v_dressed_lumber
capture rename BL gp_q_plywood
capture rename BM gp_v_plywood
capture rename BN gp_v_moldings
capture rename BO gp_v_builtIn_furniture
capture rename BP gp_v_battery_separators
capture rename BQ gp_v_custom_planing 
capture rename BR gp_v_box_wooden_lumber_noWire
capture rename BS gp_v_box_wooden_veneer_noWire
capture rename BT gp_v_box_wooden_lumber_wire
capture rename BU gp_s_other1
capture rename BV gp_v_other1
capture rename BW gp_s_other2
capture rename BX gp_v_other2
capture rename BY gp_s_other3
capture rename BZ gp_v_other3
capture rename CA gp_s_other4
capture rename CB gp_v_other4
capture rename CC gp_s_other5
capture rename CD gp_v_other5
capture rename CE g000v
drop CG CH CF
