//rename variables for industry 626 in year 1931

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
rename AR gp_q_whiteLead
rename AS gp_q_whiteLead
rename AT gp_v_whiteLead
rename AU gp_q_leadOxide_lithargeC
rename AV gp_q_leadOxide_litharge
rename AW gp_v_leadOxide_litharge
rename AX gp_q_leadOxide_otherC
rename AY gp_q_leadOxide_other
rename AZ gp_v_leadOxide_other
rename BA gp_s_leadOxide_other
rename BB gp_q_zincOxideC
rename BC gp_q_zincOxide
rename BD gp_v_zincOxide
rename BE gp_q_lithoponeC
rename BF gp_q_lithopone
rename BG gp_v_lithopone
rename BH gp_q_ironOxide
rename BI gp_q_ironOxide
rename BJ gp_v_ironOxide
rename BK gp_q_otherMineral1C
rename BL gp_q_otherMineral1
rename BM gp_v_otherMineral1
rename BN gp_s_otherMineral1C
rename BO gp_q_chromeC
rename BP gp_q_chrome
rename BQ gp_v_chrome
rename BR gp_q_coaltarC
rename BS gp_q_coaltar
rename BT gp_v_coaltar
rename BU gp_q_otherFine1C
rename BV gp_q_otherFine1
rename BW gp_v_otherFine1
rename BX gp_s_otherFine1
rename BY gp_q_otherFine2C
rename BZ gp_q_otherFine2
rename CA gp_v_otherFine2
rename CB gp_s_otherFine2
rename CC gp_q_otherDry1C
rename CD gp_q_otherDry1
rename CE gp_v_otherDry1
rename CF gp_s_otherDry1
rename CG gp_q_paint_pulp
rename CH gp_v_paint_pulp
rename CI gp_q_paint_water
rename CJ gp_v_paint_water
rename CK gp_q_paint_plastic
rename CL gp_v_paint_plastic
rename CM gp_q_paint_WhiteLead
rename CN gp_v_paintPaste_WhiteLead
rename CO gp_q_paintPaste_ColorsOil
rename CP gp_v_paintPaste_ColorsOIl
rename CQ gp_q_paintPaste_Other
rename CR gp_v_paintPaste_Other
rename CS gp_s_paintPaste_Other
rename CT gp_q_readyMixed_Oil
rename CU gp_v_readyMixed_Oil
rename CV gp_q_readyMixed_Other
rename CW gp_v_readyMixed_Other
rename CX gp_q_varnish_OleoresinousC
rename CY gp_q_varnish_Oleoresinous
rename CZ gp_v_varnish_Oleoresinous
rename DA gp_q_varnish_SpiritC
rename DB gp_q_varnish_Spirit
rename DC gp_v_varnish_Spirit
rename DD gp_q_varnish_OtherC
rename DE gp_q_varnish_Other
rename DF gp_v_varnish_Other
rename DG gp_q_varnish_stainC
rename DH gp_q_varnish_stain
rename DI gp_v_varnish_stain
rename DJ gp_q_Pyroxylin_ClearC
rename DK gp_q_Pyroxylin_Clear
rename DL gp_v_Pyroxylin_Clear
rename DM gp_q_Pyroxylin_LacquerC
rename DN gp_q_Pyroxylin_Lacquer
rename DO gp_v_Pyroxylin_Lacquer
rename DP gp_q_Pyroxylin_OtherC
rename DQ gp_q_Pyroxylin_Other
rename DR gp_v_Pyroxylin_Other
rename DS gp_q_varnish_EnamelsC
rename DT gp_q_varnish_Enamels
rename DU gp_v_varnish_Enamels
rename DV gp_q_varnish_DryingJapansC
rename DW gp_q_varnish_DryingJapans
rename DX gp_v_varnish_DryingJapans
rename DY gp_q_varnish_BakingJapansC
rename DZ gp_q_varnish_BakingJapans
rename EA gp_v_varnish_BakingJapans
rename EB gp_q_varnish_OtherC
rename EC gp_q_varnish_Other
rename ED gp_v_varnish_Other
rename EE gp_s_varnish_Other
rename EF gp_q_filler_Liquid
rename EG gp_v_filler_Liquid
rename EH gp_q_filler_Paste
rename EI gp_v_filler_Paste
rename EJ gp_q_filler_Putty
rename EK gp_v_filler_Putty
rename EL gp_q_otherPaint_Shellac
rename EM gp_v_otherPaint_Shellac
rename EN gp_q_otherPaint_Removers
rename EO gp_v_otherPaint_Removers
rename EP gp_q_other1
rename EQ gp_v_other1
rename ER gp_s_other1
rename ES gp_q_other2
rename ET gp_v_other2
rename EU gp_s_other2
rename EV g000v
