//rename variables for industry 907 in year 1933

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename output variables
rename AR	 gp_q_sole_leather_oak
rename AS 	 gp_v_sole_leather_oak
rename AT 	 gp_q_sole_leather_chrome
rename AU 	 gp_v_sole_leather_chrome
rename AV 	 gp_q_sole_leather_butts_rough
rename AW 	 gp_v_sole_leather_butts_rough
rename AX 	 gp_q_sole_leather_offal
rename AY 	 gp_v_sole_leather_offal
rename AZ	 gp_q_harness_leather_union
rename BA	 gp_v_harness_leather_union
rename BB	 gp_q_harness_leather_oak
rename BC	 gp_v_harness_leather_oak
rename BD	 gp_q_harness_leather_bag
rename BE	 gp_v_harness_leather_bag
rename BF	 gp_q_harness_leather_skirting
rename BG	 gp_v_harness_leather_skirting
rename BH	 gp_q_harness_leather_collar
rename BI	 gp_v_harness_leather_collar
rename BJ	 gp_q_harness_leather_lace
rename BK	 gp_v_harness_leather_lace
rename BL	 gp_q_welting_cattle_sides
rename BM	 gp_v_welting_cattle_sides
rename BN	 gp_q_welting_pigskin
rename BO	 gp_v_welting_pigskin
rename BP	 gp_q_upholstery_leather_hide
rename BQ	 gp_v_upholstery_leather_hide
rename BR	 gp_q_upholstery_leather_buffings
rename BS	 gp_v_upholstery_leather_buffings
rename BT	 gp_q_upholstery_leather_splits
rename BU	 gp_v_upholstery_leather_splits
rename BV	 gp_q_upper_leather_cattle
rename BW	 gp_v_upper_leather_cattle
rename BX	 gp_q_upper_leather_calf
rename BY	 gp_v_upper_leather_calf
rename BZ	 gp_q_upper_leather_kip
rename CA	 gp_v_upper_leather_kip
rename CB	 gp_q_upper_leather_goat
rename CC	 gp_v_upper_leather_goat
rename CD	 gp_q_upper_leather_cabretta
rename CE	 gp_v_upper_leather_cabretta
rename CF	 gp_q_upper_leather_sheep
rename CG	 gp_v_upper_leather_sheep
rename CH	 gp_q_upper_leather_horse_half
rename CI	 gp_v_upper_leather_horse_half
rename CJ	 gp_q_upper_leather_horse_butts
rename CK	 gp_v_upper_leather_horse_butts
rename CL	 gp_q_upper_leather_horse_shanks
rename CM	 gp_v_upper_leather_horse_shanks
rename CN	 gp_s_upper_leather_other_1
rename CO	 gp_q_upper_leather_other_1
rename CP	 gp_v_upper_leather_other_1
rename CQ	 gp_s_upper_leather_other_2
rename CR	 gp_q_upper_leather_other_2
rename CS	 gp_v_upper_leather_other_2
rename CT	 gp_q_patent_leather_cattle
rename CU	 gp_v_patent_leather_cattle
rename CV	 gp_q_patent_leather_calf
rename CW	 gp_v_patent_leather_calf
rename CX	 gp_q_patent_leather_goat
rename CY	 gp_v_patent_leather_goat
rename CZ	 gp_q_patent_leather_sheep
rename DA	 gp_v_patent_leather_sheep
rename DB	 gp_q_patent_leather_horse
rename DC	 gp_v_patent_leather_horse
rename DD	 gp_q_glove_leather_cattle
rename DE	 gp_v_glove_leather_cattle
rename DF	 gp_q_glove_leather_calf
rename DG	 gp_v_glove_leather_calf
rename DH	 gp_q_glove_leather_cowhide
rename DI	 gp_v_glove_leather_cowhide
rename DJ	 gp_q_glove_leather_horse_half
rename DK	 gp_v_glove_leather_horse_half
rename DL	 gp_q_glove_leather_horse_butts
rename DM	 gp_v_glove_leather_horse_butts
rename DN	 gp_q_glove_leather_horse_shanks
rename DO	 gp_v_glove_leather_horse_shanks
rename DP	 gp_q_glove_leather_pig
rename DQ 	 gp_v_glove_leather_pig
rename DR	 gp_q_glove_leather_goat
rename DS	 gp_v_glove_leather_goat
rename DT	 gp_q_glove_leather_cabretta
rename DU	 gp_v_glove_leather_cabretta
rename DV	 gp_q_glove_leather_sheep
rename DW	 gp_v_glove_leather_sheep
rename DX	 gp_q_glove_leather_shearlings
rename DY	 gp_v_glove_leather_shearlings
rename DZ 	 gp_q_fancy_leather_cowhide
rename EA	 gp_v_fancy_leather_cowhide
rename EB	 gp_q_fancy_leather_buffings
rename EC	 gp_v_fancy_leather_buffings
rename ED	 gp_q_fancy_leather_goat
rename EE	 gp_v_fancy_leather_goat
rename EF  	 gp_q_fancy_leather_cabretta
rename EG	 gp_v_fancy_leather_cabretta
rename EH	 gp_q_fancy_leather_sheep
rename EI	 gp_v_fancy_leather_sheep
rename EJ	 gp_q_fancy_leather_calf
rename EK	 gp_v_fancy_leather_calf
rename EL	 gp_q_fancy_leather_pig
rename EM	 gp_v_fancy_leather_pig
rename EN	 gp_q_fancy_leather_pigskin
rename EO	 gp_v_fancy_leather_pigskin
rename EP	 gp_s_fancy_leather_other
rename EQ	 gp_q_fancy_leather_other
rename ER	 gp_v_fancy_leather_other
rename ES	 gp_q_splits_not_upholstery
rename ET	 gp_v_splits_not_upholstery
rename EU	 gp_q_miscellaneous
rename EV	 gp_v_miscellaneous
rename EW	 gp_s_all_other_leather
rename EX	 gp_v_all_other_leather
rename EY	 gp_v_byproducts
rename EZ	 gp_s_other_product_1
rename FA	 gp_v_other_product_1
rename FB	 gp_s_other_product_2
rename FC	 gp_v_other_product_2
rename FD	 gp_s_other_product_3
rename FE	 gp_v_other_product_3
rename FF  	 gp_q_all_other_products
rename FG 	 receipts_contract
rename FH 	 receipts_custom
rename FI 	 g000v

//rename man hour varibables
rename FJ emh01
rename FK emh02
rename FL emh03
rename FM emh04
rename FN emh05
rename FO emh06
rename FP emh07
rename FQ emh08
rename FR emh09
rename FS emh10
rename FT emh11
rename FU emh12
rename FV ewemt
