//Cleaning script for BR spreadsheet: 1608_1933. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals referenced
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1933/1608"
import excel "`data_dir'/160833A0.xls", allstring sheet("160833A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C filenm1
capture rename D filenm2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I big3
capture rename J nex2
capture rename K tencen
capture rename L citynm
capture rename M indnm
capture rename N formnm
capture rename O plntname
capture rename P ownrname
capture rename Q incyn
capture rename R a004
capture rename S state
capture rename T city
capture rename U county
capture rename V street
capture rename W othraddr
capture rename X incityyn
capture rename Y ag007
capture rename Z sbsdryyn
capture rename AA mthrinfo
capture rename AB nmchngyn
capture rename AC as002
capture rename AD as003
capture rename AE as004
capture rename AF frmrinfo
capture rename AG products
capture rename AH mtlsusd1
capture rename AI mtlsusd2

//rename utilization variables
capture rename AJ d001
capture rename AK d008
capture rename AL inq3cmt1
capture rename AM inq3cmt2
capture rename AN inq4date

//rename employment variables
capture rename AO proprietor
capture rename AP officers_o
capture rename AQ e003ta
capture rename AR clerical_e
capture rename AS wage_earne
capture drop AT
capture rename AU wetotlnm
capture rename AV diff
capture rename AW wejan
capture rename AX wefeb
capture rename AY wemar
capture rename AZ weapr
capture rename BA wemay
capture rename BB wejun
capture rename BC wejul
capture rename BD weaug
capture rename BE wesep
capture rename BF weoct
capture rename BG wenov
capture rename BH wedec
capture rename BI e002s
capture rename BJ e003tas
capture rename BK e003tcs
capture rename BL total_wages_salaries
capture drop BM
capture rename BN totlwgs
capture drop BO //column name: diff1

//rename costs of inputs variables
capture rename BP f009
capture rename BQ f005i
capture rename BR f004
capture drop BS
capture rename BT f007
capture drop BU //column name: diff2

//rename output variables
capture rename BV gp_q_cigars
capture rename BW gp_v_cigars
capture rename BX gp_q_cigarettes
capture rename BY gp_v_cigarettes
capture rename BZ gp_q_tobacco
capture rename CA gp_v_tobacco
capture rename CB gp_q_snuff
capture rename CC gp_v_snuff
capture rename CD gp_s_general1
capture rename CE gp_q_general1
capture rename CF gp_v_general1
capture rename CG gp_s_general2
capture rename CH gp_q_general2
capture rename CI gp_v_general2
capture rename CJ gp_s_general3
capture rename CK gp_q_general3
capture rename CL gp_v_general3
capture rename CM gp_s_general4
capture rename CN gp_q_general4
capture rename CO gp_v_general4
capture rename CP ttlqty
capture rename CQ totval
capture drop CR
capture drop CS
capture drop CT //column name: diff3
capture drop CU //column name: diff4

//rename man hours variables
capture rename CV emh01
capture rename CW emh02
capture rename CX emh03
capture rename CY emh04
capture rename CZ emh05
capture rename DA emh06
capture rename DB emh07
capture rename DC emh08
capture rename DD emh09
capture rename DE emh10
capture rename DF emh11
capture rename DG emh12
capture drop DH-DX

capture drop year
gen year =  1933
//rename "common" set of variables for labeling 
do "$rootDir_code/General/basic_rename"
//tostring all variables for consistent appending
tostring *, replace force

save "$rootDir_dataBR/1933/1608/1608_1933", replace

