//Rename common variables for year: 1933 on General Schedule Form B. Generated by write_rename_common.py and ind_cols_years.txt.
//note that data will start on line 3 of these files versus line 4 in "regular" schedules
capture rename A z_imagenumber
capture rename B z_indCode
capture rename C nameofplant
capture rename D nameofowner
capture rename E incorporated
capture rename F ag008
capture rename G state
capture rename H citytownorvillage
capture rename I county
capture rename J streetandnumber
capture rename K poaddressifdifferent
capture rename L subsidiaryofanother
capture rename M am002
capture drop N //located within present corporate boundaries question
capture rename O proprietors
capture rename P e004t
capture rename Q e004s
capture rename R ewemt03
capture rename S ewemt06
capture rename T ewemt09
capture rename U ewemt12
capture rename V total_wages
capture rename W f009
capture rename X g000v
capture drop Y
