//Cleaning script for BR spreadsheet: 312_1929. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $rootDir_code .
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1929/312"
import excel "`data_dir'/031229A0.xls", allstring sheet("031229A0") clear

drop in 1 //this row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I indnm
capture rename J formnm
capture rename K plntname
capture rename L ownrname
capture rename M incyn
capture rename N state
capture rename O city
capture rename P county
capture rename Q street
capture rename R ag008
capture rename S incityyn
capture rename T ag007
capture rename U nwplntyn
capture rename V nmchngyn
capture rename W lnchngyn
capture rename X as003
capture rename Y as004
capture rename Z frmrinfo
capture rename AA sbsdryyn
capture rename AB mthrinfo
capture rename AC products
capture rename AD mtlsusd1
capture rename AE mtlsusd2
capture rename AF bgndt3
capture rename AG enddt3

//rename utilization variables
capture rename AH d001
capture rename AI d002
capture rename AJ d003
capture rename AK d004
capture rename AL d005
capture rename AM d006
capture rename AN d007
capture rename AO pttminf2

//rename employment variables
capture rename AP empldate
capture rename AQ e001m
capture rename AR e001f
capture rename AS e002m
capture rename AT e002f
capture rename AU e003m
capture rename AV e003f
capture drop AW
capture drop AX
capture rename AY mnnwenm
capture rename AZ fnnwenm
capture drop BA
capture drop BB
capture drop BC
capture rename BD wage_earne
capture rename BE 
capture rename BF
capture rename BG
capture drop BH
capture rename BI
capture drop BJ
capture rename BK wejannm
capture rename BL wefebnm
capture rename BM wemarnm
capture rename BN weaprnm
capture rename BO wemaynm
capture rename BP wejunnm
capture rename BQ wejulnm
capture rename BR weaugnm
capture rename BS wesepnm
capture rename BT weoctnm
capture rename BU wenovnm
capture rename BV wedecnm
capture rename BW e004s
capture rename BX e002s
capture rename BY e003s
capture rename BZ total_wages
capture drop CA
capture rename CB e009s
capture drop CC




//make the ff00up variable consistent with ours
gen f00up = ""
replace f00up = "Used" if CD == "yes"
replace f00up = "Purchased" if CE == "yes"
drop CD CE

//rename fuel variables
capture rename CF f001
capture rename CG f002
capture rename CH f003
capture drop CI
capture rename CJ f009
capture drop CK

//rename output variables
capture rename CL gp_u_match_strikeAnywhere
capture rename CM gp_ave_match_strikeAnywhere
capture rename CN gp_q_match_strikeAnywhere
capture rename CO gp_v_match_strikeAnywhere
capture rename CP gp_s_match_strikeAnywhere_other
capture rename CQ gp_u_match_strikeAnywhere_other
capture rename CR gp_ave_match_strikeAnywhere_other
capture rename CS gp_q_match_strikeAnywhere_other
capture rename CT gp_v_match_strikeAnywhere_other
capture rename CU gp_u_match_safety_inBox
capture rename CV gp_ave_match_safety_inBox
capture rename CW gp_q_match_safety_inBox
capture rename CX gp_v_match_safety_inBox
capture rename CY gp_u_match_safety_inBook
capture rename CZ gp_ave_match_safety_inBook
capture rename DA gp_q_match_safety_inBook
capture rename DB gp_v_match_safety_inBook
capture rename DC gp_s_match_safety_other
capture rename DD gp_u_match_safety_other
capture rename DE gp_ave_match_safety_other
capture rename DF gp_q_match_safety_other
capture rename DG gp_v_match_safety_other
capture drop DH //is this all other products? 
capture drop DI
capture drop DJ
capture drop DK
capture rename DL total_output_value
capture drop DM

//rename engine and turbine variables
capture rename DN total_hp
rename DO hp001n
rename DP hp001h
rename DQ hp002n
rename DR hp002h
rename DS hp003n
rename DT hp003h
rename DU hp004n
rename DV hp004h
capture drop DW
capture drop DX

capture drop year
gen year = 1929
//rename variables consistent with CK naming convention
do "$rootDir_code/General/basic_rename"
//tostring all variables to make sure consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1929/312/312_1929", replace
