//rename variables for industry 104 in 1929

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//output variables
rename	CK	gp_u1_canned_clams
rename	CL	gp_u2_canned_clams
rename	CM	gp_u3_canned_clams
rename	CN	gp_u4_canned_clams
rename	CO	gp_u5_canned_clams
rename	CP	gp_u6_canned_clams
rename	CQ	gp_v_canned_clams
rename	CR	gp_u1_canned_oysters
rename	CS	gp_u2_canned_oysters
rename	CT	gp_u3_canned_oysters
rename	CU	gp_u4_canned_oysters
rename	CV	gp_u5_canned_oysters
rename	CW	gp_u6_canned_oysters
rename	CX	gp_v_canned_oysters
rename	CY	gp_u1_canned_shrimp
rename	CZ	gp_u2_canned_shrimp
rename	DA	gp_u3_canned_shrimp
rename	DB	gp_u4_canned_shrimp
rename	DC	gp_u5_canned_shrimp
rename	DD	gp_u6_canned_shrimp
rename	DE	gp_v_canned_shrimp
rename	DF	gp_u1_canned_mackarel
rename	DG	gp_u2_canned_mackarel
rename	DH	gp_u3_canned_mackarel
rename	DI	gp_u4_canned_mackarel
rename	DJ	gp_u5_canned_mackarel
rename	DK	gp_u6_canned_mackarel
rename	DL	gp_v_canned_mackarel
rename	DM	gp_u1_canned_salmon
rename	DN	gp_u2_canned_salmon
rename	DO	gp_u3_canned_salmon
rename	DP	gp_u4_canned_salmon
rename	DQ	gp_u5_canned_salmon
rename	DR	gp_u6_canned_salmon
rename	DS	gp_v_canned_salmon
rename	DT	gp_u1_canned_sardines
rename	DU	gp_u2_canned_sardines
rename	DV	gp_u3_canned_sardines
rename	DW	gp_u4_canned_sardines
rename	DX	gp_u5_canned_sardines
rename	DY	gp_u6_canned_sardines
rename	DZ	gp_v_canned_sardines
rename	EA	gp_u1_canned_tuna
rename	EB	gp_u2_canned_tuna
rename	EC	gp_u3_canned_tuna
rename	ED	gp_u4_canned_tuna
rename	EE	gp_u5_canned_tuna
rename	EF	gp_u6_canned_tuna
rename	EG	gp_v_canned_tuna
rename	EH	gp_s_canned_otherFish1
rename	EI	gp_u1_canned_otherFish1
rename	EJ	gp_u2_canned_otherFish1
rename	EK	gp_u3_canned_otherFish1
rename	EL	gp_u4_canned_otherFish1
rename	EM	gp_u5_canned_otherFish1
rename	EN	gp_u6_canned_otherFish1
rename	EO	gp_v_canned_otherFish1
rename	EP	gp_s_canned_otherFish2
rename	EQ	gp_u1_canned_otherFish2
rename	ER	gp_u2_canned_otherFish2
rename	ES	gp_u3_canned_otherFish2
rename	ET	gp_u4_canned_otherFish2
rename	EU	gp_u5_canned_otherFish2
rename	EV	gp_u6_canned_otherFish2
rename	EW	gp_v_canned_otherFish2
rename	EX	gp_u1_clamBroth
rename	EY	gp_u2_clamBroth
rename	EZ	gp_u3_clamBroth
rename	FA	gp_u4_clamBroth
rename	FB	gp_u5_clamBroth
rename	FC	gp_u6_clamBroth
rename	FD	gp_v_clamBroth
rename	FE	gp_u1_crabMeat
rename	FF	gp_u2_crabMeat
rename	FG	gp_u3_crabMeat
rename	FH	gp_u4_crabMeat
rename	FI	gp_u5_crabMeat
rename	FJ	gp_u6_crabMeat
rename	FK	gp_v_crabMeat
rename	FL	gp_u1_fishCakes
rename	FM	gp_u2_fishCakes
rename	FN	gp_u3_fishCakes
rename	FO	gp_u4_fishCakes
rename	FP	gp_u5_fishCakes
rename	FQ	gp_u6_fishCakes
rename	FR	gp_v_fishCakes
rename	FS	gp_u1_fishRoe
rename	FT	gp_u2_fishRoe
rename	FU	gp_u3_fishRoe
rename	FV	gp_u4_fishRoe
rename	FW	gp_u5_fishRoe
rename	FX	gp_u6_fishRoe
rename	FY	gp_v_fishRoe
rename	FZ	gp_s_cannedFished_other1
rename	GA	gp_u1_cannedFished_other1
rename	GB	gp_u2_cannedFished_other1
rename	GC	gp_u3_cannedFished_other1
rename	GD	gp_u4_cannedFished_other1
rename	GE	gp_u5_cannedFished_other1
rename	GF	gp_u6_cannedFished_other1
rename	GG	gp_v_cannedFished_other1
rename	GH	gp_s_cannedFished_other2
rename	GI	gp_u1_cannedFished_other2
rename	GJ	gp_u2_cannedFished_other2
rename	GK	gp_u3_cannedFished_other2
rename	GL	gp_u4_cannedFished_other2
rename	GM	gp_u5_cannedFished_other2
rename	GN	gp_u6_cannedFished_other2
rename	GO	gp_v_cannedFished_other2
rename	GP	gp_q_smokedFish_finnan
rename	GQ	gp_v_smokedFish_finnan
rename	GR	gp_q_smokedFish_herring
rename	GS	gp_v_smokedFish_herring
rename	GT	gp_q_smokedFish_salmon
rename	GU	gp_v_smokedFish_salmon
rename	GV	gp_s_smokedFish_other1
rename	GW	gp_q_smokedFish_other1
rename	GX	gp_v_smokedFish_other1
rename	GY	gp_s_smokedFish_other2
rename	GZ	gp_q_smokedFish_other2
rename	HA	gp_v_smokedFish_other2
rename	HB	gp_q_driedFish_cod
rename	HC	gp_v_driedFish_cod
rename	HD	gp_q_driedFish_herring
rename	HE	gp_v_driedFish_herring
rename	HF	gp_s_driedFish_other1
rename	HG	gp_q_driedFish_other1
rename	HH	gp_v_driedFish_other1
rename	HI	gp_s_driedFish_other2
rename	HJ	gp_q_driedFish_other2
rename	HK	gp_v_driedFish_other2
rename	HL	gp_q_saltedFish_cod
rename	HM	gp_v_saltedFish_cod
rename	HN	gp_q_saltedFish_haddock
rename	HO	gp_v_saltedFish_haddock
rename	HP	gp_q_saltedFish_herring
rename	HQ	gp_v_saltedFish_herring
rename	HR	gp_q_saltedFish_mackarel
rename	HS	gp_v_saltedFish_mackarel
rename	HT	gp_s_saltedFish_other1
rename	HU	gp_q_saltedFish_other1
rename	HV	gp_v_saltedFish_other1
rename	HW	gp_s_saltedFish_other2
rename	HX	gp_q_saltedFish_other2
rename	HY	gp_v_saltedFish_other2
rename	HZ	gp_q_bonelessFish_cod
rename	IA	gp_v_bonelessFish_cod
rename	IB	gp_q_bonelessFish_haddock
rename	IC	gp_v_bonelessFish_haddock
rename	ID 	gp_s_bonelessFish_other1
rename	IE	gp_q_bonelessFish_other1
rename	IF	gp_v_bonelessFish_other1
rename	IG	gp_s_bonelessFish_other2
rename	IH	gp_q_bonelessFish_other2
rename	II	gp_v_bonelessFish_other2
rename	IJ	gp_s_bonelessFish_other3
rename	IK	gp_q_bonelessFish_other3
rename	IL	gp_v_bonelessFish_other3
rename	IM	gp_q_fishOil
rename	IN	gp_v_fishOil
rename	IO	gp_q_fishScrap_dried
rename	IP	gp_v_fishScrap_dried
rename	IQ	gp_q_fishScrap_green
rename	IR 	gp_v_fishScrap_green
rename	IS	gp_q_fertilizerMaterial
rename	IT	gp_v_fertilizerMaterial
rename	IU	gp_q_liquidGlue
rename	IV	gp_v_liquidGlue
rename	IW	gp_q_oysterShells
rename	IX	gp_v_oysterShells
rename	IY	gp_q_oysterShell_lime
rename	IZ	gp_v_oysterShell_lime
rename	JA	gp_s_other1
rename	JB	gp_q_other1
rename	JC	gp_v_other1
rename	JD	gp_s_other2
rename	JE	gp_q_other2
rename	JF	gp_v_other2
rename	JG	gp_s_other3
rename	JH	gp_q_other3
rename	JI	gp_v_other3

//input variables
rename	JJ	j_v_fishConsumption
