//Cleaning script for BR spreadsheet: 1112_1929. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $rootDir_code .
//Globals referenced: $rootDir_sheets, $rootDir_dataBR, $rootDir_code

local data_dir = "$rootDir_sheets/1929/1112"
import excel "`data_dir'/111229A0.xls", allstring sheet("111229A0") clear

drop in 1 //first row is just variable names

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
drop if record==""
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F com
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L firm_code
capture rename M plntname
capture rename N ownrname
capture rename O incyn
capture rename P state
capture rename Q city
capture rename R county
capture rename S street
capture rename T ag008
capture rename U incityyn
capture rename V othrcity
capture rename W nwplntyn
capture rename X nmchngyn
capture rename Y lnchngyn
capture rename Z owchngyn
capture rename AA as004
capture rename AB frmrinfo
capture rename AC sbsdryyn
capture rename AD mthrinfo
capture rename AE products
capture rename AF mtlsusd1
capture rename AG mtlsusd2
capture rename AH bgndt3
capture rename AI enddt3

//rename utilization variables
capture rename AJ d001
capture rename AK d002
capture rename AL d003
capture rename AM d004
capture rename AN d005
capture rename AO d006
capture rename AP d007
capture rename AQ pttminf2

//rename employment variables
capture rename AR empldate
capture rename AS e001m
capture rename AT e001f
capture rename AU e002m
capture rename AV e002f
capture rename AW e003m
capture rename AX e003f
capture rename AY total_of_b
capture rename AZ fnnwenm
capture drop BA
capture drop BB
capture drop BC //Column name:  diffm
capture drop BD //Column name: difff
capture rename BE e005m
capture rename BF e005f

//rename monthly wage earner variables
capture rename BG wetotal
capture rename BH wejanuary
capture rename BI wefebruary
capture rename BJ wemarch
capture rename BK weapril
capture rename BL wemay
capture rename BM wejune
capture rename BN wejuly
capture rename BO weaugust
capture rename BP weseptembe
capture rename BQ weoctober
capture rename BR wenovember
capture rename BS wedecember
capture drop BT
capture drop BU //Column name: diff
capture rename BV e002s
capture rename BW e003s
capture rename BX e005s
capture drop BY
capture rename BZ e009s
capture drop CA //Column name: diff1
capture rename CB mtlusdyn
capture rename CC mtlpcdyn

//make the ff00up variable consistent with ours
gen f00up = ""
replace f00up = "Used" if mtlusdyn == "Yes"
replace f00up = "Purchased" if mtlpcdyn == "Yes"
drop mtlusdyn mtlpcdyn

//rename fuel variables
capture rename CD f001
capture rename CE f002
capture rename CF f003
capture drop CG
capture rename CH f009
capture drop CI //Column name: diff2

//dropping variables that were generated by BR for data checking purposes
capture drop CJ
capture drop CK
capture drop CL
capture drop CM
capture drop CN
capture drop CO
capture drop CP
capture drop CQ
capture drop CR
capture drop CS
capture drop CT
capture drop CU
capture drop CV
capture drop CW
capture drop CX
capture drop CY
capture drop CZ
capture drop DA
capture drop DB
capture drop DC
capture drop DD
capture drop DE
capture drop DF
capture drop DG

save "$rootDir_dataBR/1929/1112/1112_1929_clean", replace

//clean B and C spreadsheets and merge with existing dataset
foreach letter in B C {
	//now clean `letter' spreadsheet
	do "$rootDir_code/1929/clean_1112_1929_`letter'"

	//merge with existing dataset
	use "$rootDir_dataBR/1929/1112/1112_1929_clean", clear
	merge 1:1 record using "$rootDir_dataBR/1929/1112/1112_1929_clean_`letter'"
	//this should really be a 1-1 mapping
	drop _merge

	save "$rootDir_dataBR/1929/1112/1112_1929_clean", replace
}

capture drop year
gen year = 1929
//this will translate to CK convention if necessary
do "$rootDir_code/General/basic_rename.do"
//tostring all variables to make sure consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1929/1112/1112_1929_clean", replace
