//Cleaning script for BR "B" spreadsheet: 705_1929. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $dir_cleaning .
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1929/705"
import excel "`data_dir'/070529B0.xls", allstring sheet("070529B0") clear

drop in 1 //this row has variable names that we do not need
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""

//don't need these because will merge on record with A sheet
capture drop C //plntname
capture drop D //ownrname
capture drop E //state
capture drop F //county

//rename engine and turbine variables
capture rename G hp001n
capture rename H hp001h
capture rename I hp002n
capture rename J hp002h
capture rename K hp003n
capture rename L hp003h
capture rename M hp004n
capture rename N hp004h
capture drop O //What is this?
capture drop P //Column name in spreadsheet: diffhp
capture rename Q totalnm
capture rename R totalhp
capture rename S abovestndb
capture rename T stndbyhp
capture rename U he001n
capture rename V he001h
capture rename W he002n
capture rename X he002h
capture rename Y he003n
capture rename Z he003h
capture rename AA stndbygen
capture rename AB stndbykw

//rename fuel variables
capture rename AC ff001q
capture rename AD ff001v
capture rename AE ff002q
capture rename AF ff002v
capture rename AG ff003q
capture rename AH ff003v
capture rename AI ff004q
capture rename AJ ff004v
capture rename AK ff005q
capture rename AL ff005v
capture rename AM ff006q
capture rename AN ff006v
capture rename AO ff007q
capture rename AP ff007v
capture rename AQ ff008q
capture rename AR ff008v
capture drop AS //Column name in spreadsheet: chk
capture rename AT ff000c
capture rename AU fe001k
capture rename AV fe002k
capture rename AW fe002c

//rename input variables
capture rename AX j_q_crude_petroleum
capture rename AY j_v_crude_petroleum
capture rename AZ j_q_partly_refined_oils
capture rename BA j_v_partly_refined_oils
capture rename BB j_q_natural_gas_purchased
capture rename BC j_v_natural_gas_purchased
capture rename BD j_q_natural_gas_extracted
capture rename BE j_v_natural_gas_extracted
capture rename BF j_q_soda_ash
capture rename BG j_v_soda_ash
capture rename BH j_q_caustic_soda_purchased
capture rename BI j_v_caustic_soda_purchased
capture rename BJ j_q_caustic_soda_made
capture rename BK j_v_caustic_soda_made
capture rename BL j_q_sulphuric_soda_purchased
capture rename BM j_v_sulphuric_soda_purchased
capture rename BN j_q_sulphuric_soda_made
capture rename BO j_v_sulphuric_soda_made
capture rename BP j_q_sulphuric_soda_reclaimed
capture rename BQ j_v_sulphuric_soda_reclaimed
capture rename BR j_q_lumber
capture rename BS j_v_lumber
capture rename BT j_q_wooden_container
capture rename BU j_v_wooden_container
capture rename BV j_q_fullers_earth
capture rename BW j_v_fullers_earth
capture rename BX z_sulphur_process
capture rename BY z_contact_process

//rename monthly manhours variable
capture rename BZ emh01
capture rename CA emh02
capture rename CB emh03
capture rename CC emh04
capture rename CD emh05
capture rename CE emh06
capture rename CF emh07
capture rename CG emh08
capture rename CH emh09
capture rename CI emh10
capture rename CJ emh11
capture rename CK emh12

//rename distribution variables
capture rename CL k001
capture rename CM k002
capture rename CN k003
capture rename CO k004
capture rename CP k005
capture rename CQ k006
capture rename CR k007
capture rename CS k008

//drop all of these useless variables
capture drop CT //Column name in spreadsheet: **_fnlbgnd
capture drop CU //Column name in spreadsheet: fnlenddt
capture drop CV //Column name in spreadsheet: remark01
capture drop CW //Column name in spreadsheet: remark02
capture drop CX //Column name in spreadsheet: remark03
capture drop CY //Column name in spreadsheet: remark04
capture drop CZ //Column name in spreadsheet: remark05
capture drop DA //Column name in spreadsheet: remark06
capture drop DB //Column name in spreadsheet: remark07
capture drop DC //Column name in spreadsheet: remark08
capture drop DD //Column name in spreadsheet: remark09
capture drop DE //Column name in spreadsheet: remark10
capture drop DF //Column name in spreadsheet: remark11
capture drop DG //Column name in spreadsheet: remark12
capture drop DH //Column name in spreadsheet: remark13
capture drop DI //Column name in spreadsheet: remark14
capture drop DJ //Column name in spreadsheet: remark15
capture drop DK //Column name in spreadsheet: remark16
capture drop DL //Column name in spreadsheet: remark17
capture drop DM //Column name in spreadsheet: remark18
capture drop DN //Column name in spreadsheet: remark19
capture drop DO //Column name in spreadsheet: remark20
capture drop DP //Column name in spreadsheet: remark21
capture drop DQ //Column name in spreadsheet: remark22
capture drop DR //Column name in spreadsheet: remark23
capture drop DS //Column name in spreadsheet: remark24
capture drop DT //Column name in spreadsheet: remark25
capture drop DU //Column name in spreadsheet: remark26
capture drop DV //Column name in spreadsheet: remark27'

save "$rootDir_dataBR/1929/705/705_1929_clean_B", replace
