//rename variables for industry 116 in year 1929

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//output variables
rename	CN	gp_q_wheat_flour_white
rename	CO	gp_v_wheat_flour_white
rename	CP	gp_q_wheat_flour_graham
rename	CQ	gp_v_wheat_flour_graham
rename	CR	gp_q_wheat_flour_whole
rename	CS	gp_v_wheat_flour_whole
rename	CT	gp_q_wheat_flour_semolina
rename	CU	gp_v_wheat_flour_semolina
rename	CV	gp_q_rye_flour
rename	CW	gp_v_rye_flour
rename	CX	gp_q_corn_flour
rename	CY	gp_v_corn_flour
rename	CZ	gp_q_buckwheat_flour
rename	DA	gp_v_buckwheat_flour
rename	DB	gp_s_flour_other1
rename	DC	gp_q_flour_other1
rename	DD	gp_v_flour_other1
rename	DE	gp_s_flour_other2
rename	DF	gp_q_flour_other2
rename	DG	gp_v_flour_other2
rename	DH	gp_q_corn_meal
rename	DI	gp_v_corn_meal
rename	DJ	gp_q_bran
rename	DK	gp_v_bran
rename	DL	gp_q_feed
rename	DM	gp_v_feed
rename	DN	gp_q_alfalfa_meal
rename	DO	gp_v_alfalfa_meal
rename	DP	gp_q_prepared_flour
rename	DQ	gp_v_prepared_flour
rename	DR	gp_q_cereal_breakfast_corn
rename	DS	gp_v_cereal_breakfast_corn
rename	DT	gp_q_cereal_breakfast_wheat
rename	DU	gp_v_cereal_breakfast_wheat
rename	DV	gp_q_cereal_breakfast_oats
rename	DW	gp_v_cereal_breakfast_oats
rename	DX	gp_q_cereal_breakfast_otherGrains
rename	DY	gp_v_cereal_breakfast_otherGrains
rename	DZ	gp_q_cerealCoffee_substitutes
rename	EA	gp_v_cerealCoffee_substitutes
rename	EB	gp_s_otherCereal_products1
rename	EC	gp_q_otherCereal_products1
rename	ED	gp_v_otherCereal_products1
rename	EE	gp_s_otherCereal_products2
rename	EF	gp_q_otherCereal_products2
rename	EG	gp_v_otherCereal_products2
rename	EH	gp_s_otherFood_products2
rename	EI	gp_q_otherFood_products2
rename	EJ	gp_v_otherFood_products2
rename	EK	gp_s_otherFood_products2
rename	EL	gp_q_otherFood_products2
rename	EM	gp_v_otherFood_products2
rename	EN	gp_q_preparedFeed
rename	EO	gp_v_preparedFeed
rename	EP	gp_s_otherPreparedFeed1
rename	EQ	gp_q_otherPreparedFeed1
rename	ER	gp_v_otherPreparedFeed1
rename	ES	gp_s_otherPreparedFeed2
rename	ET	gp_q_otherPreparedFeed2
rename	EU	gp_v_otherPreparedFeed2
rename	EV	gp_q_malt_barley
rename	EW	gp_v_malt_barley
rename	EX	gp_q_malt_rye
rename	EY	gp_v_malt_rye
rename	EZ	gp_q_sprouts
rename	FA	gp_v_sprouts
rename	FB	gp_q_screenings
rename	FC	gp_v_screenings
rename	FD	gp_s_otherMaltByproducts1
rename	FE	gp_q_otherMaltByproducts1
rename	FF	gp_v_otherMaltByproducts1
rename	FG	gp_s_otherMaltByproducts2
rename	FH	gp_q_otherMaltByproducts2
rename	FI	gp_v_otherMaltByproducts2
rename	FJ	gp_s_otherProducts1
rename	FK	gp_q_otherProducts1
rename	FL	gp_v_otherProducts1
rename	FM	gp_s_otherProducts2
rename	FN	gp_q_otherProducts2
rename	FO	gp_v_otherProducts2
rename 	FP 	g000v
