//Cleaning script for BR spreadsheet: 237_1929. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $rootDir_code .
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1929/237"
import excel "`data_dir'/023729A0.xls", allstring sheet("023729A0") clear

drop in 1 //first row has variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L plntname
capture rename M ownrname
capture rename N incyn
capture rename O state
capture rename P city
capture rename Q county
capture rename R street
capture rename S ag008
capture rename T incityyn
rename U ag007
capture rename V nwplntyn
capture rename W nmchngyn
capture rename X lnchngyn
capture rename Y owchngyn
capture rename Z bschngyn
capture rename AA frmrinfo
capture rename AB sbsdryyn
capture rename AC mthrinfo
capture rename AD products
capture rename AE mtlsusd1
capture rename AF mtlsusd2
capture rename AG bgndt3
capture rename AH enddt3

//rename utilization variables
capture rename AI d001
capture rename AJ d002
capture rename AK d003
capture rename AL d004
capture rename AM d005
capture rename AN d006
capture rename AO d007
capture rename AP pttminf2

//rename employment variables
capture rename AQ empldate
capture rename AR e001m
capture rename AS e001f
capture rename AT e002m
capture rename AU e002f
capture rename AV e003m
capture rename AW e003f
capture rename AX mnnwenm
capture rename AY fnnwenm
capture drop AZ
capture drop BA
capture drop BB //column name: diffm
capture drop BC //column name: difff
capture rename BD mwenm
capture rename BE fwenm
capture drop BF
capture rename BG wetotal
capture drop BH //column name: diff
capture rename BI wejanuary
capture rename BJ wefebruary
capture rename BK wemarch
capture rename BL weapril
capture rename BM wemay
capture rename BN wejune
capture rename BO wejuly
capture rename BP weaugust
capture rename BQ weseptembe
capture rename BR weoctober
capture rename BS wenovember
capture rename BT wedecember
capture rename BU e002s
capture rename BV e003s
capture rename BW wages_paid
capture drop BX
capture rename BY e009s
capture drop BZ //column name: diff1
capture rename CA mtlusdyn
capture rename CB mtlpcdyn

//make the ff00up variable consistent with ours
gen f00up = ""
replace f00up = "Used" if mtlusdyn == "Yes"
replace f00up = "Purchased" if mtlpcdyn == "Yes"
drop mtlusdyn mtlpcdyn


//rename fuel variables
capture rename CC f001
capture rename CD f002
capture rename CE f003
capture drop CF
capture rename CG f009
capture drop CH //column name: diff2

//rename output variables
capture rename CI gp_q_general1
capture rename CJ gp_v_general1
capture rename CK gp_q_general2
capture rename CL gp_v_general2
capture rename CM gp_q_general3
capture rename CN gp_v_general3
capture rename CO gp_q_general4
capture rename CP gp_v_general4
capture rename CQ gp_q_general5
capture rename CR gp_v_general5
capture rename CS gp_q_general6
capture rename CT gp_v_general6
capture rename CU gp_q_general7
capture rename CV gp_v_general7
capture rename CW gp_q_general8
capture rename CX gp_v_general8
capture rename CY gp_q_general9
capture rename CZ gp_v_general9
capture rename DA gp_q_general10
capture rename DB gp_v_general10
capture rename DC gp_q_general11
capture rename DD gp_v_general11
capture rename DE gp_q_general12
capture rename DF gp_v_general12
capture rename DG gp_q_general13
capture rename DH gp_v_general13
capture rename DI gp_q_general14
capture rename DJ gp_v_general14
capture rename DK gp_q_general15
capture rename DL gp_v_general15
capture rename DM gp_q_general16
capture rename DN gp_v_general16
capture rename DO gp_q_general17
capture rename DP gp_v_general17
capture rename DQ gp_q_general18
capture rename DR gp_v_general18
capture rename DS gp_q_general19
capture rename DT gp_v_general19
capture rename DU gp_q_general20
capture rename DV gp_v_general20
capture rename DW gp_q_general21
capture rename DX gp_v_general21
capture rename DY g000v

save "$rootDir_dataBR/1929/237/237_1929", replace

//now clean B spreadsheets
do "$rootDir_code/1929/clean_237_1929_B"

//merge with existing dataset
use "$rootDir_dataBR/1929/237/237_1929", clear
merge 1:1 record using "$rootDir_dataBR/1929/237/237_1929_clean_B"
drop _merge

capture drop year
gen year = 1929
//this will translate to CK convention if necessary
do "$rootDir_code/General/basic_rename.do"
//tostring all variables to make sure consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1929/237/237_1929", replace


