//Cleaning script for BR "B" spreadsheet: 1008_1929. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $dir_cleaning .
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1929/1008"
import excel "`data_dir'/100829B1.xls", allstring sheet("100829B1") clear

drop in 1 //this row has variable names

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""
//don't need these because will merge on record with A sheet
capture drop C //plntname
capture drop D //ownrname
capture drop E //state
capture drop F //county

//rename engine and turbine variables
capture rename G hp001n
capture rename H hp001h
capture rename I hp002n
capture rename J hp002h
capture rename K hp003n
capture rename L hp003h
capture rename M hp004n
capture rename N hp004h
capture drop O //Column name in spreadsheet: chknm
capture drop P //Column name in spreadsheet: chkhp
capture drop Q //Column name in spreadsheet: diff
capture drop R //Column name in spreadsheet: diff1
capture rename S totlpmnm
capture rename T totlpmhp
capture rename U standby_ho
capture rename V sum_of_b_a
capture rename W he001n
capture rename X he001h
capture rename Y he002n
capture rename Z he002h
capture rename AA he003n
capture rename AB he003h
capture rename AC standby_ge
capture rename AD sum_of_b_a

//rename fuel variables
capture rename AE ff001q
capture rename AF ff001v
capture rename AG ff002q
capture rename AH ff002v
capture rename AI ff003q
capture rename AJ ff003v
capture rename AK ff004q
capture rename AL ff004v
capture rename AM ff005q
capture rename AN ff005v
capture rename AO ff006q
capture rename AP ff006v
capture rename AQ ff007q
capture rename AR ff007v
capture drop AS 
capture rename AT ff000c
capture drop AU //Column name in spreadsheet: diff2
capture rename AV fe001k
capture rename AW fe002k
capture rename AX fe002c
capture rename AY fueleleccs

//rename input variables
capture rename AZ j_q_silica_sand
capture rename BA j_q_soda_ash
capture rename BB j_q_salt_cake
capture rename BC j_q_lime
capture rename BD j_q_limestone
capture rename BE j_q_grinding_sand

//rename capital variables
capture rename BF z_furnace_continuous_operated_number
capture rename BG z_furnace_continuous_operated_fuel
capture rename BH z_furnace_continuous_operated_capacity
capture rename BI z_furnace_continuous_idle_number
capture rename BJ z_furnace_continuous_idle_fuel
capture rename BK z_furnace_continuous_idle_capacity
capture rename BL z_furnace_intermittent_operated_number
capture rename BM z_furnace_intermittent_operated_fuel
capture rename BN z_furnace_intermittent_operated_capacity
capture rename BO z_furnace_intermittent_idled_number
capture rename BP z_furnace_intermittent_idled_fuel
capture rename BQ z_furnace_intermittent_idled_capacity
capture rename BR z_furnace_pot_operated_number
capture rename BS z_furnace_pot_operated_fueld
capture rename BT z_furnace_pot_operated_capacity
capture rename BU z_furnace_pot_idled_number
capture rename BV z_furnace_pot_idled_fuel
capture rename BW z_furnace_pot_idled_capacity
capture rename BX z_glass_window_cylinder_number
capture rename BY z_glass_window_cylinder_capacity
capture rename BZ z_glass_window_libbey_number
capture rename CA z_glass_window_libbey_capacity
capture rename CB z_glass_window_fourcault_number
capture rename CC z_glass_window_fourcault_capacity
capture rename CD z_glass_plate_rough_continuous_number
capture rename CE z_glass_plate_rough_continuous_capacity
capture rename CF z_glass_plate_rough_other_number
capture rename CG z_glass_plate_rough_other_capacity
capture rename CH z_glass_plate_polished_continuous_number
capture rename CI z_glass_plate_polished_continuous_capacity
capture rename CJ z_glass_plate_polished_other_number
capture rename CK z_glass_plate_polished_other_capacity
capture rename CL z_automatic_full_number
capture rename CM z_automatic_full_fuel
capture rename CN z_automatic_full_capacity
capture rename CO z_automatic_partial_number
capture rename CP z_automatic_partial_fuel
capture rename CQ z_automatic_partial_capacity
capture rename CR z_pressed_hand_automatic_number
capture rename CS z_pressed_hand_automatic_fuel
capture rename CT z_pressed_hand_automatic_capacity
capture rename CU z_pressed_hand_partial_number
capture rename CV z_pressed_hand_partial_fuel
capture rename CW z_pressed_hand_partial_capacity

//rename distribution variables
capture rename CX k001
capture rename CY k002
capture rename CZ k003
capture rename DA k004
capture rename DB k005
capture rename DC k006
capture rename DD k007

//drop a number of useless variables
capture drop DE 
capture drop DF //Column name in spreadsheet: diff3
capture rename DG k008
capture drop DH 
capture drop DI 
capture drop DJ //Column name in spreadsheet: remark01
capture drop DK //Column name in spreadsheet: remark02
capture drop DL //Column name in spreadsheet: remark03
capture drop DM //Column name in spreadsheet: remark04
capture drop DN //Column name in spreadsheet: remark05
capture drop DO //Column name in spreadsheet: remark06
capture drop DP //Column name in spreadsheet: remark07
capture drop DQ //Column name in spreadsheet: remark08
capture drop DR //Column name in spreadsheet: remark09
capture drop DS //Column name in spreadsheet: remark10
capture drop DT //Column name in spreadsheet: remark11
capture drop DU //Column name in spreadsheet: remark12
capture drop DV //Column name in spreadsheet: remark13
capture drop DW //Column name in spreadsheet: remark14
capture drop DX //Column name in spreadsheet: remark15'

//fix a problematic identifier
replace record = "me0190_a" if hp001h=="190" & record=="me0190"

save "$rootDir_dataBR/1929/1008/1008_1929_clean_B", replace
