//Cleaning script for BR "B" spreadsheet: 237_1929. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $dir_cleaning .
*Globals referenced: $rootDir_dataBR, $rootDir_sheets

local data_dir = "$rootDir_sheets/1929/237"
import excel "`data_dir'/023729B0.xls", allstring sheet("023729B0") clear

drop in 1 //first column is variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""
//don't need these because will merge on record with A sheet
capture drop C //plntname
capture drop D //ownrname
capture drop E //state
capture drop F //county
capture rename G tothp
capture rename H hp001n
capture rename I hp001h
capture rename J hp002n
capture rename K hp002h
capture rename L hp003n
capture rename M hp003h
capture rename N hp004n
capture rename O hp004h
capture rename P hp000n
capture rename Q hp000h
capture drop R //Column name in spreadsheet: checkn
capture drop S //Column name in spreadsheet: diffn
capture drop T //Column name in spreadsheet: checkh
capture drop U //Column name in spreadsheet: diffh
capture drop V //Column name in spreadsheet:abovestndb
capture drop W //Column name in spreadsheet:stndbyhp
capture rename X he001n
capture rename Y he001h
capture rename Z he002n
capture rename AA he002h
capture rename AB he003n
capture rename AC h3003h
capture drop AD //Column name in spreadsheet:stndbygen
capture drop AE //Column name in spreadsheet:stndbykw
capture rename AF ff001q
capture rename AG ff001v
capture rename AH ff002q
capture rename AI ff002v
capture rename AJ ff003q
capture rename AK ff003v
capture rename AL ff004q
capture rename AM ff004v
capture rename AN ff005q
capture rename AO ff005v
capture rename AP ff006q
capture rename AQ ff006v
capture rename AR ff007q
capture rename AS ff007v
capture rename AT ff000c
capture drop AU //Column name in spreadsheet: check
capture drop AV //Column name in spreadsheet: diff
capture rename AW fe001k
capture rename AX fe002k
capture rename AY fe002c
capture rename AZ j_q_cotton_fabric
capture rename BA j_v_cotton_fabric
capture rename BB j_q_jute_fabric
capture rename BC j_v_jute_fabric
capture rename BD j_q_castor
capture rename BE j_v_castor
capture rename BF j_q_pyroxylin
capture rename BG j_v_pyroxylin
capture rename BH j_q_alcohol
capture rename BI j_v_alcohol
capture rename BJ j_q_pigments
capture rename BK j_v_pigments
capture rename BL total_cost_inputs
capture drop BM //Column name in spreadsheet: check1
capture drop BN //Column name in spreadsheet: diff1
capture rename BO k001
capture rename BP k002
capture rename BQ k003
capture rename BR k004
capture rename BS k005
capture rename BT k006
capture rename BU k007
capture drop BV //Column name in spreadsheet: check2
capture drop BW //Column name in spreadsheet: diff2
capture rename BX k008
capture drop BY //**_fnlbgnd
capture drop BZ //fnlenddt
capture drop CA //Column name in spreadsheet: remark01
capture drop CB //Column name in spreadsheet: remark02
capture drop CC //Column name in spreadsheet: remark03
capture drop CD //Column name in spreadsheet: remark04
capture drop CE //Column name in spreadsheet: remark05
capture drop CF //Column name in spreadsheet: remark06
capture drop CG //Column name in spreadsheet: remark07
capture drop CH //Column name in spreadsheet: remark08
capture drop CI //Column name in spreadsheet: remark09
capture drop CJ //Column name in spreadsheet: remark10
capture drop CK //Column name in spreadsheet: remark11
capture drop CL //Column name in spreadsheet: remark12
capture drop CM //Column name in spreadsheet: remark13
capture drop CN //Column name in spreadsheet: remark14
capture drop CO //Column name in spreadsheet: remark15
capture drop CP //Column name in spreadsheet: cc01info
capture drop CQ //Column name in spreadsheet: cc01
capture drop CR //Column name in spreadsheet: cc02info
capture drop CS //Column name in spreadsheet: cc02
capture drop CT //Column name in spreadsheet: cc03info
capture drop CU //Column name in spreadsheet: cc03
capture drop CV //Column name in spreadsheet: cc04info
capture drop CW //Column name in spreadsheet: cc04
capture drop CX //Column name in spreadsheet: cc05info
capture drop CY //Column name in spreadsheet: cc05
capture drop CZ //Column name in spreadsheet: cc06info
capture drop DA //Column name in spreadsheet: cc06
capture drop DB //Column name in spreadsheet: cc07info
capture drop DC //Column name in spreadsheet: cc07
capture drop DD //Column name in spreadsheet: cc08info
capture drop DE //Column name in spreadsheet: cc08
capture drop DF //Column name in spreadsheet: cc09info
capture drop DG //Column name in spreadsheet: cc09
capture drop DH //Column name in spreadsheet: cc10info
capture drop DI //Column name in spreadsheet: cc10
capture drop DJ //Column name in spreadsheet: cc11info
capture drop DK //Column name in spreadsheet: cc11
capture drop DL //Column name in spreadsheet: cc12info
capture drop DM //Column name in spreadsheet: cc12
capture drop DN //Column name in spreadsheet: cc13info
capture drop DO //Column name in spreadsheet: cc13
capture drop DP //Column name in spreadsheet: cc14info
capture drop DQ //Column name in spreadsheet: cc14
capture drop DR //Column name in spreadsheet: cc15info
capture drop DS //Column name in spreadsheet: cc15
capture drop DT //Column name in spreadsheet: cc16info
capture drop DU //Column name in spreadsheet: cc16
capture drop DV //Column name in spreadsheet: cc17info
capture drop DW //Column name in spreadsheet: cc17
capture drop DX //Column name in spreadsheet: cc18info

save "$rootDir_dataBR/1929/237/237_1929_clean_B", replace
