//Cleaning script for BR "B" spreadsheet: 631_1929. Generated by write_renamingFiles_B.py and ind_cols_B.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $dir_cleaning .
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1929/631"
import excel "`data_dir'/063129B0.xls", allstring sheet("063129B0") clear

drop in 1 // this is row with variable names
//Create obs_id
do "$rootDir_code/General/gen_obsID.do"
replace obs_id = obs_id + "B"

capture drop A //Column name in spreadsheet: start
capture rename B record
capture drop if record==""
//don't need these because will merge on record with A sheet
capture drop C //plntname
capture drop D //ownrname
capture drop E //state
capture drop F //county
capture drop G //Column name in spreadsheet: diffn
capture drop H //Column name in spreadsheet: diffhp

//rename engine and turbine variables
capture rename I hp001n
capture rename J hp001h
capture rename K hp002n
capture rename L hp002h
capture rename M hp003n
capture rename N hp003h
capture rename O hp004n
capture rename P hp004h
capture rename Q totalnm
capture rename R totalhp

//rename electricty variables
capture rename S abovestndb
capture rename T stndbyhp
capture rename U he001n
capture rename V he001h
capture rename W he002n
capture rename X he002h
capture rename Y he003n
capture rename Z he003h
capture rename AA stndbygen
capture d AB stndbykw

//rename fuel variables
capture rename AC ff001q
capture rename AD ff001v
capture rename AE ff002q
capture rename AF ff002v
capture rename AG ff003q
capture rename AH ff003v
capture rename AI ff004q
capture rename AJ ff004v
capture rename AK ff005q
capture rename AL ff005v
capture rename AM ff006q
capture rename AN ff006v
capture rename AO ff007q
capture rename AP ff007v
capture drop AQ //Column name in spreadsheet: chk
capture rename AR ff000c
capture drop AS //Column name in spreadsheet: diff
capture rename AT fe001k
capture rename AU fe002k
capture rename AV fe002c

//rename input variables
capture rename AW j_q_animal_fat
capture rename AX j_v_animal_fat
capture rename AY j_q_vegatable_fat
capture rename AZ j_v_vegatable_fat
capture rename BA j_q_alk
capture rename BB j_v_alk
capture rename BC j_q_abm
capture rename BD j_v_abm
capture rename BE j_q_per
capture rename BF j_v_per
capture rename BG j_q_col
capture rename BH j_v_col
capture rename BI j_v_red_oil
capture rename BJ j_v_sodium_sil
capture rename BK j_v_glycerin
capture drop BL

capture rename BM k001
capture rename BN k002
capture rename BO k003
capture rename BP k004
capture rename BQ k005
capture rename BR k006
capture rename BS k007
capture rename BT k008

//drop useless variables
capture drop BU-DX

replace record = "me0092" if record == "ME0092"

save "$rootDir_dataBR/1929/631/631_1929_clean_B", replace
