//Cleaning script for BR spreadsheet: 1110_1929. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $rootDir_code .
//Globals referenced: $rootDir_sheets

local data_dir = "$rootDir_sheets/1929/1110"
import excel "`data_dir'/111029A0_PDSPL.xls", allstring sheet("111029A0") clear

drop in 1/2 //variable names are on row 2, row 1 is totally blank


//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C fileno1
capture rename D fileno2
capture rename E id
capture rename F tempid
capture rename G comment
capture rename H statenm
capture rename I cntynm
capture rename J citynm
capture rename K indnm
capture rename L merchant
capture rename M formnm
capture rename N plntname
capture rename O ownrname
capture rename P incyn
capture rename Q state
capture rename R city
capture rename S county
capture rename T street
capture rename U ag008
capture rename V incityyn
capture rename W othrcity
capture rename X nwplntyn
capture rename Y nmchngyn
capture rename Z as002
capture rename AA owchngyn
capture rename AB as004
capture rename AC frmrinfo
capture rename AD sbsdryyn
capture rename AE mthrinfo
capture rename AF products
capture rename AG mtlsusd1
capture rename AH mtlsusd2
capture rename AI bgndt3
capture rename AJ enddt3

//rename utilization variables
capture rename AK d001
capture rename AL d002
capture rename AM d003
capture rename AN d004
capture rename AO d005
capture rename AP d006
capture rename AQ d007
capture rename AR pttminf2
capture rename AS empldate

//rename employment variables
capture rename AT e001m
capture rename AU e001f
capture rename AV e002m
capture rename AW e002f
capture rename AX e003m
capture rename AY e003f
capture rename AZ nonwenm
capture rename BA fnnwenm
capture drop BB
capture drop BC
capture drop BD //Column name: diffm
capture drop BE //Column name: difff
capture rename BF e005m
capture rename BG e005f
capture drop BH
capture rename BI wetotal
capture rename BJ diff
capture rename BK wejanuary
capture rename BL wefebruary
capture rename BM wemarch
capture rename BN weapril
capture rename BO wemay
capture rename BP wejune
capture rename BQ wejuly
capture rename BR weaugust
capture rename BS weseptembe
capture rename BT weoctober
capture rename BU wenovember
capture rename BV wedecember
capture rename BW e004s
capture rename BX e002s
capture rename BY e003s
capture rename BZ e005s
capture drop CA
capture rename CB e009s
capture drop CC //Column name: diff1

//rename fuel variables
capture rename CD mtlusdyn
capture rename CE mtlpcdyn

//make the ff00up variable consistent with ours
gen f00up = ""
replace f00up = "Used" if mtlusdyn == "Yes"
replace f00up = "Purchased" if mtlpcdyn == "Yes"
drop mtlusdyn mtlpcdyn

capture rename CF f001
capture rename CG f002
capture rename CH f003
capture drop CI
capture rename CJ f009
capture drop CK //Column name: diff2

//rename output variables
capture rename CL gp_q_coke_ip
capture rename CM gp_v_coke_ip
capture rename CN gp_q_coke_fs
capture rename CO gp_v_coke_fs
capture rename CP gp_v_coke
capture rename CQ gp_q_charcoal_ip
capture rename CR gp_v_charcoal_ip
capture rename CS gp_q_charcoal_fs
capture rename CT gp_v_charcoal_fs
capture rename CU gp_v_charcoal
capture rename CV gp_s_otherfuel1
capture rename CW gp_q_otherfuel1_ip
capture rename CX gp_v_otherfuel1_ip
capture rename CY gp_q_otherfuel1_fs
capture rename CZ gp_v_otherfuel1_fs
capture rename DA gp_v_otherfuel1
capture rename DB gp_s_otherfuel2
capture rename DC gp_q_otherfuel2_ip
capture rename DD gp_v_otherfuel2_ip
capture rename DE gp_q_otherfuel2_fs
capture rename DF gp_v_otherfuel2_fs
capture rename DG gp_v_otherfuel2
capture rename DH gp_q_blastfurnace_gas
capture rename DI gp_q_blastfurnacegas_other
capture rename DJ gp_v_blastfurnacegas_other
capture rename DK gp_v_slag
capture rename DL gp_s_general1
capture rename DM gp_v_general1
capture drop DN
capture rename DO g000v		//CZV 8/4/2022 Named "total value" before but I think this was in error
capture drop DP-DY
capture rename DZ gp_q_pigiron_foundry_ip
capture rename EA gp_q_pigiron_foundry_fs
capture rename EB gp_q_pigiron_basic_ip
capture rename EC gp_q_pigiron_basic_fs
capture rename ED gp_q_pigiron_bessemer_ip
capture rename EE gp_q_pigiron_bessemer_fs
capture rename EF gp_q_pigiron_lowPhosphorus_ip
capture rename EG gp_q_pigiron_lowPhosphorus_fs
capture rename EH gp_q_pigiron_malleable_ip
capture rename EI gp_q_pigiron_malleable_fs
capture rename EJ gp_q_pigiron_forge_ip
capture rename EK gp_q_pigiron_forge_fs
capture rename EL gp_q_pigiron_white_ip
capture rename EM gp_q_pigiron_white_fs
capture rename EN gp_q_directCasting_pipe_ip
capture rename EO gp_q_directCasting_pipe_fs
capture rename EP gp_q_directCasting_other_ip
capture rename EQ gp_q_directCasting_other_fs
capture rename ER gp_q_spiegeleisen_consumption_ip
capture rename ES gp_q_spiegeleisen_fs
capture rename ET gp_v_spiegeleisen
capture rename EU gp_q_ferromanganese_ip
capture rename EV gp_q_ferromanganese_fs
capture rename EW gp_v_ferromanganese
capture rename EX gp_q_ferrophosphorus_ip
capture rename EY gp_q_ferrophosphorus_fs
capture rename EZ gp_v_ferrophosphorus
capture rename FA gp_q_ferrosillicon_ip
capture rename FB gp_q_ferrosillicon_fs
capture rename FC gp_v_ferrosillicon
capture rename FD gp_q_ferroalloy_other_ip
capture rename FE gp_q_ferroalloy_other_fs
capture rename FF gp_v_ferroalloy_other
capture drop FG FH FI
capture rename FJ gp_q_machine_cast
capture rename FK gp_q_sand_cast
capture rename FL gp_q_chill_cast
capture rename FM gp_q_delivered_molton


save "$rootDir_dataBR/1929/1110/1110_1929_clean", replace

//now clean B spreadsheets
do "$rootDir_code/1929/clean_1110_1929_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1929/1110/1110_1929_clean", replace
merge 1:1 record using "$rootDir_dataBR/1929/1110/1110_1929_clean_B"
drop _merge

capture drop year
gen year = 1929
//this will translate to CK convention if necessary
do "$rootDir_code/General/basic_rename.do"
//tostring all variables to make sure consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1929/1110/1110_1929_clean", replace
