//Cleaning script for BR spreadsheet: 1656_1929. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $rootDir_code .
//Globals referenced: $rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1929/1656"
import excel "`data_dir'/165629A1.xls", allstring sheet("165629A1") clear

drop in 1 //this row has variable names

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
drop if record==""
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K big3
capture rename L nex2
capture rename M tencen
capture rename N formnm
capture rename O plntname
capture rename P ownrname
capture rename Q incyn
capture rename R state
capture rename S city
capture rename T county
capture rename U street
capture rename V ag008
capture rename W incityyn
capture rename X ag007
capture rename Y nwplntyn
capture rename Z nmchngyn
capture rename AA lnchngyn
capture rename AB owchngyn
capture rename AC as004
capture rename AD as005
capture rename AE sbsdryyn
capture rename AF mthrinfo
capture rename AG products
capture rename AH mtlsusd1
capture rename AI mtlsusd2
capture rename AJ bgndt3
capture rename AK enddt3

//rename utilization variables
capture rename AL d001
capture rename AM d002
capture rename AN d003
capture rename AO d004
capture rename AP d005
capture rename AQ d006
capture rename AR d007
capture rename AS pttminf2

//rename employment variables
capture rename AT empldate
capture rename AU mpropnm
capture rename AV fpropnm
capture rename AW moffcnm
capture rename AX foffcnm
capture rename AY mmngrnm
capture rename AZ fmngrnm
capture rename BA mnnwenm
capture rename BB fnnwenm
capture drop BC
capture drop BD
capture drop BE 
capture drop BF 
capture rename BG mwenm
capture rename BH fwenm
capture drop BI
capture rename BJ wetotal
capture drop BK //column name: diff
capture rename BL wejanuary
capture rename BM wefebruary
capture rename BN wemarch
capture rename BO weapril
capture rename BP wemay
capture rename BQ wejune
capture rename BR wejuly
capture rename BS weaugust
capture rename BT weseptembe
capture rename BU weoctober
capture rename BV wenovember
capture rename BW wedecember
capture rename BX offcslry
capture rename BY mngrslry
capture rename BZ e005s
capture drop CA
capture rename CB totlslry
capture drop CC //column name: diff1

//rename fuel variables
capture rename CD mtlusdyn
capture rename CE mtlpcdyn

//make the ff00up variable consistent with ours
gen f00up = ""
replace f00up = "Used" if mtlusdyn == "Yes"
replace f00up = "Purchased" if mtlpcdyn == "Yes"
drop mtlusdyn mtlpcdyn

capture rename CF f001
capture rename CG f002
capture rename CH f003
capture drop CI
capture rename CJ f009
capture drop CK //column name: diff2

//rename output variables
capture rename CL gp_q_cigars
capture rename CM gp_v_cigars
capture rename CN gp_q_cigarettes
capture rename CO gp_v_cigarettes
capture rename CP gp_q_tobacco
capture rename CQ gp_v_tobacco
capture rename CR gp_s_general1
capture rename CS gp_q_general1
capture rename CT gp_v_general1
capture rename CU gp_s_general2
capture rename CV gp_q_general2
capture rename CW gp_v_general2
capture rename CX gp_s_general3
capture rename CY gp_q_general3
capture rename CZ gp_v_general3
capture rename DA g000q
capture rename DB total_output_value
capture drop DC
capture drop DD
capture drop DE //column name: diff3
capture drop DF //column name: diff4
capture rename DG tax
capture rename DH totmn

//dropping useless variables
capture drop DI
capture drop DJ
capture drop DK
capture drop DL
capture drop DM
capture drop DN
capture drop DO
capture drop DP
capture drop DQ
capture drop DR
capture drop DS
capture drop DT
capture drop DU
capture drop DV
capture drop DW
capture drop DX

capture drop year
gen year = 1929
//this will translate to CK variable naming convention if necessary
do "$rootDir_code/General/basic_rename.do"
//tostring all variables for consistency in appending later
tostring *, replace force

save "$rootDir_dataBR/1929/1656/1656_1929", replace
