//Cleaning script for BR spreadsheet: 803_1929. Generated by write_renamingFiles.py and ind_cols.txt, which has NLZ's renaming of BR variables.
//Note that variable `home_dir' is set outside the script and setup to be run from build_BR_legacy.do.
//If you want to run this file directly, change data_dir and globals $rootDir_sheetsLegacy, $rootDir_code .
//Globals referenced: "$rootDir_sheets, $rootDir_dataBR

local data_dir = "$rootDir_sheets/1929/803"
import excel "`data_dir'/080329A0.xls", allstring sheet("080329A0") clear

drop in 1 //this is row with variable names

//Create obs_id
do "$rootDir_code/General/gen_obsID.do"

//rename identifying information variables
capture rename A start
capture rename B record
capture drop if record==""
capture rename C fileno1
capture rename D fileno2
capture rename E tempid
capture rename F comment
capture rename G statenm
capture rename H cntynm
capture rename I citynm
capture rename J indnm
capture rename K formnm
capture rename L plntname
capture rename M ownrname
capture rename N incyn
capture rename O state
capture rename P city
capture rename Q county
capture rename R street
capture rename S ag008
capture rename T incityyn
capture rename U othrcity
capture rename V nwplntyn
capture rename W nmchngyn
capture rename X lnchngyn
capture rename Y owchngyn
capture rename Z bschngyn
capture rename AA frmrinfo
capture rename AB sbsdryyn
capture rename AC mthrinfo
capture rename AD products
capture rename AE mtlsusd1
capture rename AF mtlsusd2
capture rename AG bgndt3
capture rename AH enddt3

//rename utilization variables
capture rename AI d001
capture rename AJ d002
capture rename AK d003
capture rename AL d004
capture rename AM d005
capture rename AN d006
capture rename AO d007
capture rename AP pttminf2

//rename employment variables
capture rename AQ empldate
capture rename AR e001m
capture rename AS e001f
capture rename AT e002m
capture rename AU e002f
capture rename AV e003m
capture rename AW e003f
capture rename AX total_of_b
capture rename AY fnnwenm
capture drop AZ
capture drop BA
capture drop BB //column name: diffm
capture drop BC //column name: difff
capture rename BD e005m
capture rename BE e005f
capture drop BF
capture rename BG wetotal
capture drop BH //column name: diff
capture rename BI wejanuary
capture rename BJ wefebruary
capture rename BK wemarch
capture rename BL weapril
capture rename BM wemay
capture rename BN wejune
capture rename BO wejuly
capture rename BP weaugust
capture rename BQ weseptembe
capture rename BR weoctober
capture rename BS wenovember
capture rename BT wedecember
capture rename BU we5/we6
capture rename BV e002s
capture rename BW e003s
capture rename BX e005s
capture rename BY e004s
capture rename BZ totlslry
capture drop CA //column name: diff1
capture rename CB mtlusdyn
capture rename CC mtlpcdyn

//make the ff00up variable consistent with ours
gen f00up = ""
replace f00up = "Used" if mtlusdyn == "yes"
replace f00up = "Purchased" if mtlpcdyn == "yes"
drop mtlusdyn mtlpcdyn

//rename fuel variables
capture rename CD f001
capture rename CE f002
capture rename CF f003
capture drop CG
capture rename CH f009
capture drop CI //column name: diff2

//rename output variables
//this is guesing that form for 1929 is the same as 1931
capture rename CJ gp_q_pneumatic_mv_casing_balloon
capture rename CK gp_v_pneumatic_mv_casing_balloon
capture rename CL gp_q_pneumatic_mv_casing_HP-pres
capture rename CM gp_v_pneumatic_mv_casing_HP
capture rename CN j_q_rubber_pneumatic_mv_casing
capture rename CO gp_q_pneumatic_mv_innerTube_balloon
capture rename CP gp_v_pneumatic_mv_innerTube_balloon
capture rename CQ gp_q_pneumatic_mv_innerTube_HP
capture rename CR gp_v_pneumatic_mv_innerTube_HP
capture rename CS j_q_rubber_pneumatic_mv_innerTube
capture rename CT gp_q_pneumatic_motorCycle_casing
capture rename CU gp_v_pneumatic_motorCycle_casing
capture rename CV gp_q_pneumatic_motorCycle_innerTube
capture rename CW gp_v_pneumatic_motorCycle_innerTube
capture rename CX j_q_rubber_motorCycle
capture rename CY gp_q_bicycle_singleTube
capture rename CZ gp_v_bicycle_singleTube
capture rename DA gp_q_bicycle_casing
capture rename DB gp_v_bicycle_casing
capture rename DC gp_q_bicycle_innerTube
capture rename DD gp_v_bicycle_innerTube
capture rename DE j_q_rubber_bicycle
capture rename DF gp_q_rubber_otherCasing
capture rename DG gp_v_rubber_otherCasing
capture drop DH //rub4 //not sure what this is?
capture rename DI gp_q_solidRubber_truck
capture rename DJ gp_v_solidRubber_truck
capture rename DK gp_q_solidRubber_tractor
capture rename DL gp_v_solidRubber_tractor
capture rename DM gp_q_solidRubber_other
capture rename DN gp_b_solidRubber_other
capture drop DO //rub5 //not sure what this is?
capture rename DP gp_q_rubber_canvas
capture rename DQ gp_v_rubber_canvas
capture rename DR gp_q_rubber_boot
capture rename DS gp_v_rubber_boot
capture rename DT gp_q_lumbermen_boot
capture rename DU gp_v_lumbermen_boot
capture rename DV gp_q_artics_boot
capture rename DW gp_v_artics_boot
capture rename DX gp_q_gaiter

save "$rootDir_dataBR/1929/803/803_1929", replace

//now clean B spreadsheets
do "$rootDir_code/1929/clean_803_1929_B"

//merge with existing dataset
clear
use "$rootDir_dataBR/1929/803/803_1929", replace
merge 1:1 record using "$rootDir_dataBR/1929/803/803_1929_clean_B"
//this should really be a 1-1 mapping
drop _merge

capture drop year
gen year = 1929
//rename variables for consistency with CK naming convention
do "$rootDir_code/General/basic_rename"
//tostring all variables to make sure consistent appending later
tostring *, replace force

save "$rootDir_dataBR/1929/803/803_1929", replace
