//Rename common variables for year: 1929. Generated by write_rename_common.py and ind_cols_years.txt
//Missing e005m and e005f

//identifyig information
capture rename A z_imagenumber
capture rename B z_indCode
capture rename C nameofplant
capture rename D nameofowner
capture rename E incorporated
capture rename F state
capture rename G citytownorvillage
capture rename H county
capture rename I streetandnumber
capture rename J poaddressifdifferent
capture rename K newplant
capture rename L change_location
capture rename M change_name
capture rename N as003
capture rename O subsidiary
capture rename P am002
capture rename Q began
capture rename R end

//shift length and hours in operation
capture rename S d001
capture rename T d002
capture rename U d003
capture rename V d004
capture rename W d005
capture rename X d006

//employment variables
capture rename Y e001m
capture rename Z e001f
capture rename AA e002m
capture rename AB e002f
capture rename AC e003m
capture rename AD e003f
capture rename AE ewemt01
capture rename AF ewemt02
capture rename AG ewemt03
capture rename AH ewemt04
capture rename AI ewemt05
capture rename AJ ewemt06
capture rename AK ewemt07
capture rename AL ewemt08
capture rename AM ewemt09
capture rename AN ewemt10
capture rename AO ewemt11
capture rename AP ewemt12
capture rename AQ e002s
capture rename AR e003s
capture rename AS total_wages
capture rename AT f00up

//Cost variables
capture rename AU f001
capture rename AV f002
capture rename AW f003
capture rename AX f009

//engines and turbines
capture rename AY hp001n
capture rename AZ hp001h
capture rename BA hp002n
capture rename BB hp002h
capture rename BC hp003n
capture rename BD hp003h
capture rename BE hp004n
capture rename BF hp004h

//electrical motor variables
capture rename BG he001n
capture rename BH he001h
capture rename BI he002n
capture rename BJ he002h
rename BK he003n
rename BL he003h

//fuels used
capture rename BM ff001q
capture rename BN ff001v
capture rename BO ff002q
capture rename BP ff002v
capture rename BQ ff003q
capture rename BR ff003v
capture rename BS ff004q
capture rename BT ff004v
capture rename BU ff005q
capture rename BV ff005v
capture rename BW ff006q
capture rename BX ff006v
capture rename BY ff007q
capture rename BZ ff007v
capture rename CA ff000c	

//electricity use
capture rename CB fe001k
capture rename CC fe002k
capture rename CD fe002c

//distribution of products
capture rename CE k001
capture rename CF k002
capture rename CG k003
capture rename CH k004
capture rename CI k005
capture rename CJ k006
capture rename CK k007
capture rename CL k008

