//Renaming for "form B" from 1929. Note that the form B is the Census of Mines schedule.
//It is required that schedules of this form be in a separate B0 spreadsheet. 

capture rename A z_imagenumber
capture rename B z_indcode
capture rename C nameofplant
capture rename D nameofowner
capture rename E state
capture rename F citytownorvillage
capture rename G county
capture rename H streetandnumber
capture rename I poaddressifdifferent
capture rename J character_products
capture rename K materials_used
capture rename L schedule_mailed
capture rename M schedule_returned
capture rename N total_employees
capture rename O total_male_employees
capture rename P total_female_employees
capture rename Q e009s
capture rename R amount_development
capture rename S f009 
capture rename T total_value_output
capture rename U lumber_bf
capture rename V lath_thousands
capture rename W coal_tons
capture rename X shingles_thousands
capture rename Y staves_number
capture rename Z ore_tons
capture rename AA heading_sets
capture rename AB other_value
capture rename AC other_specify
capture rename AD stone_slate_etx
capture rename AE g000v
capture rename AF prime_movers_number 
capture rename AG prime_movers_hp
capture rename AH he001n
capture rename AI he001h
capture rename AJ merchandising
capture rename AK merchandising_character
capture rename AL value_merchandising_sales
capture rename AM began
capture rename AN end
