	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Arkansas" & `clean_county'=="Arkansas"
	replace `countyfips' ="003" if `clean_state'=="Arkansas" & `clean_county'=="Ashley"
	replace `countyfips' ="005" if `clean_state'=="Arkansas" & `clean_county'=="Baxter"
	replace `countyfips' ="007" if `clean_state'=="Arkansas" & `clean_county'=="Benton"
	replace `countyfips' ="009" if `clean_state'=="Arkansas" & `clean_county'=="Boone"
	replace `countyfips' ="011" if `clean_state'=="Arkansas" & `clean_county'=="Bradley"
	replace `countyfips' ="013" if `clean_state'=="Arkansas" & `clean_county'=="Calhoun"
	replace `countyfips' ="015" if `clean_state'=="Arkansas" & `clean_county'=="Carroll"
	replace `countyfips' ="017" if `clean_state'=="Arkansas" & `clean_county'=="Chicot"
	replace `countyfips' ="019" if `clean_state'=="Arkansas" & `clean_county'=="Clark"
	replace `countyfips' ="021" if `clean_state'=="Arkansas" & `clean_county'=="Clay"
	replace `countyfips' ="023" if `clean_state'=="Arkansas" & `clean_county'=="Cleburne"
	replace `countyfips' ="025" if `clean_state'=="Arkansas" & `clean_county'=="Cleveland"
	replace `countyfips' ="027" if `clean_state'=="Arkansas" & `clean_county'=="Columbia"
	replace `countyfips' ="029" if `clean_state'=="Arkansas" & `clean_county'=="Conway"
	replace `countyfips' ="031" if `clean_state'=="Arkansas" & `clean_county'=="Craighead"
	replace `countyfips' ="033" if `clean_state'=="Arkansas" & `clean_county'=="Crawford"
	replace `countyfips' ="035" if `clean_state'=="Arkansas" & `clean_county'=="Crittenden"
	replace `countyfips' ="037" if `clean_state'=="Arkansas" & `clean_county'=="Cross"
	replace `countyfips' ="039" if `clean_state'=="Arkansas" & `clean_county'=="Dallas"
	replace `countyfips' ="041" if `clean_state'=="Arkansas" & `clean_county'=="Desha"
	replace `countyfips' ="043" if `clean_state'=="Arkansas" & `clean_county'=="Drew"
	replace `countyfips' ="045" if `clean_state'=="Arkansas" & `clean_county'=="Faulkner"
	replace `countyfips' ="047" if `clean_state'=="Arkansas" & `clean_county'=="Franklin"
	replace `countyfips' ="049" if `clean_state'=="Arkansas" & `clean_county'=="Fulton"
	replace `countyfips' ="051" if `clean_state'=="Arkansas" & `clean_county'=="Garland"
	replace `countyfips' ="053" if `clean_state'=="Arkansas" & `clean_county'=="Grant"
	replace `countyfips' ="055" if `clean_state'=="Arkansas" & `clean_county'=="Greene"
	replace `countyfips' ="057" if `clean_state'=="Arkansas" & `clean_county'=="Hempstead"
	replace `countyfips' ="059" if `clean_state'=="Arkansas" & `clean_county'=="Hot Spring"
	replace `countyfips' ="061" if `clean_state'=="Arkansas" & `clean_county'=="Howard"
	replace `countyfips' ="063" if `clean_state'=="Arkansas" & `clean_county'=="Independence"
	replace `countyfips' ="065" if `clean_state'=="Arkansas" & `clean_county'=="Izard"
	replace `countyfips' ="067" if `clean_state'=="Arkansas" & `clean_county'=="Jackson"
	replace `countyfips' ="069" if `clean_state'=="Arkansas" & `clean_county'=="Jefferson"
	replace `countyfips' ="071" if `clean_state'=="Arkansas" & `clean_county'=="Johnson"
	replace `countyfips' ="073" if `clean_state'=="Arkansas" & `clean_county'=="Lafayette"
	replace `countyfips' ="075" if `clean_state'=="Arkansas" & `clean_county'=="Lawrence"
	replace `countyfips' ="077" if `clean_state'=="Arkansas" & `clean_county'=="Lee"
	replace `countyfips' ="079" if `clean_state'=="Arkansas" & `clean_county'=="Lincoln"
	replace `countyfips' ="081" if `clean_state'=="Arkansas" & `clean_county'=="Little River"
	replace `countyfips' ="083" if `clean_state'=="Arkansas" & `clean_county'=="Logan"
	replace `countyfips' ="085" if `clean_state'=="Arkansas" & `clean_county'=="Lonoke"
	replace `countyfips' ="087" if `clean_state'=="Arkansas" & `clean_county'=="Madison"
	replace `countyfips' ="089" if `clean_state'=="Arkansas" & `clean_county'=="Marion"
	replace `countyfips' ="091" if `clean_state'=="Arkansas" & `clean_county'=="Miller"
	replace `countyfips' ="093" if `clean_state'=="Arkansas" & `clean_county'=="Mississippi"
	replace `countyfips' ="095" if `clean_state'=="Arkansas" & `clean_county'=="Monroe"
	replace `countyfips' ="099" if `clean_state'=="Arkansas" & `clean_county'=="Nevada"
	replace `countyfips' ="101" if `clean_state'=="Arkansas" & `clean_county'=="Newton"
	replace `countyfips' ="103" if `clean_state'=="Arkansas" & `clean_county'=="Ouachita"
	replace `countyfips' ="105" if `clean_state'=="Arkansas" & `clean_county'=="Perry"
	replace `countyfips' ="107" if `clean_state'=="Arkansas" & `clean_county'=="Phillips"
	replace `countyfips' ="109" if `clean_state'=="Arkansas" & `clean_county'=="Pike"
	replace `countyfips' ="111" if `clean_state'=="Arkansas" & `clean_county'=="Poinsett"
	replace `countyfips' ="113" if `clean_state'=="Arkansas" & `clean_county'=="Polk"
	replace `countyfips' ="115" if `clean_state'=="Arkansas" & `clean_county'=="Pope"
	replace `countyfips' ="117" if `clean_state'=="Arkansas" & `clean_county'=="Prairie"
	replace `countyfips' ="119" if `clean_state'=="Arkansas" & `clean_county'=="Pulaski"
	replace `countyfips' ="121" if `clean_state'=="Arkansas" & `clean_county'=="Randolph"
	replace `countyfips' ="123" if `clean_state'=="Arkansas" & `clean_county'=="St Francis"
	replace `countyfips' ="123" if `clean_state'=="Arkansas" & `clean_county'=="St. Francis"
	replace `countyfips' ="125" if `clean_state'=="Arkansas" & `clean_county'=="Saline"
	replace `countyfips' ="127" if `clean_state'=="Arkansas" & `clean_county'=="Scott"
	replace `countyfips' ="129" if `clean_state'=="Arkansas" & `clean_county'=="Searcy"
	replace `countyfips' ="131" if `clean_state'=="Arkansas" & `clean_county'=="Sebastian"
	replace `countyfips' ="133" if `clean_state'=="Arkansas" & `clean_county'=="Sevier"
	replace `countyfips' ="135" if `clean_state'=="Arkansas" & `clean_county'=="Sharp"
	replace `countyfips' ="137" if `clean_state'=="Arkansas" & `clean_county'=="Stone"
	replace `countyfips' ="139" if `clean_state'=="Arkansas" & `clean_county'=="Union"
	replace `countyfips' ="141" if `clean_state'=="Arkansas" & `clean_county'=="Van Buren"
	replace `countyfips' ="143" if `clean_state'=="Arkansas" & `clean_county'=="Washington"
	replace `countyfips' ="145" if `clean_state'=="Arkansas" & `clean_county'=="White"
	replace `countyfips' ="147" if `clean_state'=="Arkansas" & `clean_county'=="Woodruff"
	replace `countyfips' ="149" if `clean_state'=="Arkansas" & `clean_county'=="Yell"
	