	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Iowa" & `clean_county'=="Adair"
	replace `countyfips' ="003" if `clean_state'=="Iowa" & `clean_county'=="Adams"
	replace `countyfips' ="005" if `clean_state'=="Iowa" & `clean_county'=="Allamakee"
	replace `countyfips' ="007" if `clean_state'=="Iowa" & `clean_county'=="Appanoose"
	replace `countyfips' ="009" if `clean_state'=="Iowa" & `clean_county'=="Audubon"
	replace `countyfips' ="011" if `clean_state'=="Iowa" & `clean_county'=="Benton"
	replace `countyfips' ="013" if `clean_state'=="Iowa" & `clean_county'=="Black Hawk"
	replace `countyfips' ="015" if `clean_state'=="Iowa" & `clean_county'=="Boone"
	replace `countyfips' ="017" if `clean_state'=="Iowa" & `clean_county'=="Bremer"
	replace `countyfips' ="019" if `clean_state'=="Iowa" & `clean_county'=="Buchanan"
	replace `countyfips' ="021" if `clean_state'=="Iowa" & `clean_county'=="Buena Vista"
	replace `countyfips' ="023" if `clean_state'=="Iowa" & `clean_county'=="Butler"
	replace `countyfips' ="025" if `clean_state'=="Iowa" & `clean_county'=="Calhoun"
	replace `countyfips' ="027" if `clean_state'=="Iowa" & `clean_county'=="Carroll"
	replace `countyfips' ="029" if `clean_state'=="Iowa" & `clean_county'=="Cass"
	replace `countyfips' ="031" if `clean_state'=="Iowa" & `clean_county'=="Cedar"
	replace `countyfips' ="033" if `clean_state'=="Iowa" & `clean_county'=="Cerro Gordo"
	replace `countyfips' ="035" if `clean_state'=="Iowa" & `clean_county'=="Cherokee"
	replace `countyfips' ="037" if `clean_state'=="Iowa" & `clean_county'=="Chickasaw"
	replace `countyfips' ="039" if `clean_state'=="Iowa" & `clean_county'=="Clarke"
	replace `countyfips' ="041" if `clean_state'=="Iowa" & `clean_county'=="Clay"
	replace `countyfips' ="043" if `clean_state'=="Iowa" & `clean_county'=="Clayton"
	replace `countyfips' ="045" if `clean_state'=="Iowa" & `clean_county'=="Clinton"
	replace `countyfips' ="047" if `clean_state'=="Iowa" & `clean_county'=="Crawford"
	replace `countyfips' ="049" if `clean_state'=="Iowa" & `clean_county'=="Dallas"
	replace `countyfips' ="051" if `clean_state'=="Iowa" & `clean_county'=="Davis"
	replace `countyfips' ="053" if `clean_state'=="Iowa" & `clean_county'=="Decatur"
	replace `countyfips' ="055" if `clean_state'=="Iowa" & `clean_county'=="Delaware"
	replace `countyfips' ="057" if `clean_state'=="Iowa" & `clean_county'=="Des Moines"
	replace `countyfips' ="059" if `clean_state'=="Iowa" & `clean_county'=="Dickinson"
	replace `countyfips' ="061" if `clean_state'=="Iowa" & `clean_county'=="Dubuque"
	replace `countyfips' ="063" if `clean_state'=="Iowa" & `clean_county'=="Emmet"
	replace `countyfips' ="065" if `clean_state'=="Iowa" & `clean_county'=="Fayette"
	replace `countyfips' ="067" if `clean_state'=="Iowa" & `clean_county'=="Floyd"
	replace `countyfips' ="069" if `clean_state'=="Iowa" & `clean_county'=="Franklin"
	replace `countyfips' ="071" if `clean_state'=="Iowa" & `clean_county'=="Fremont"
	replace `countyfips' ="073" if `clean_state'=="Iowa" & `clean_county'=="Greene"
	replace `countyfips' ="075" if `clean_state'=="Iowa" & `clean_county'=="Grundy"
	replace `countyfips' ="077" if `clean_state'=="Iowa" & `clean_county'=="Guthrie"
	replace `countyfips' ="079" if `clean_state'=="Iowa" & `clean_county'=="Hamilton"
	replace `countyfips' ="081" if `clean_state'=="Iowa" & `clean_county'=="Hancock"
	replace `countyfips' ="083" if `clean_state'=="Iowa" & `clean_county'=="Hardin"
	replace `countyfips' ="085" if `clean_state'=="Iowa" & `clean_county'=="Harrison"
	replace `countyfips' ="087" if `clean_state'=="Iowa" & `clean_county'=="Henry"
	replace `countyfips' ="089" if `clean_state'=="Iowa" & `clean_county'=="Howard"
	replace `countyfips' ="091" if `clean_state'=="Iowa" & `clean_county'=="Humboldt"
	replace `countyfips' ="093" if `clean_state'=="Iowa" & `clean_county'=="Ida"
	replace `countyfips' ="095" if `clean_state'=="Iowa" & `clean_county'=="Iowa"
	replace `countyfips' ="097" if `clean_state'=="Iowa" & `clean_county'=="Jackson"
	replace `countyfips' ="099" if `clean_state'=="Iowa" & `clean_county'=="Jasper"
	replace `countyfips' ="101" if `clean_state'=="Iowa" & `clean_county'=="Jefferson"
	replace `countyfips' ="103" if `clean_state'=="Iowa" & `clean_county'=="Johnson"
	replace `countyfips' ="105" if `clean_state'=="Iowa" & `clean_county'=="Jones"
	replace `countyfips' ="107" if `clean_state'=="Iowa" & `clean_county'=="Keokuk"
	replace `countyfips' ="109" if `clean_state'=="Iowa" & `clean_county'=="Kossuth"
	replace `countyfips' ="111" if `clean_state'=="Iowa" & `clean_county'=="Lee"
	replace `countyfips' ="113" if `clean_state'=="Iowa" & `clean_county'=="Linn"
	replace `countyfips' ="115" if `clean_state'=="Iowa" & `clean_county'=="Louisa"
	replace `countyfips' ="117" if `clean_state'=="Iowa" & `clean_county'=="Lucas"
	replace `countyfips' ="119" if `clean_state'=="Iowa" & `clean_county'=="Lyon"
	replace `countyfips' ="121" if `clean_state'=="Iowa" & `clean_county'=="Madison"
	replace `countyfips' ="123" if `clean_state'=="Iowa" & `clean_county'=="Mahaska"
	replace `countyfips' ="125" if `clean_state'=="Iowa" & `clean_county'=="Marion"
	replace `countyfips' ="127" if `clean_state'=="Iowa" & `clean_county'=="Marshall"
	replace `countyfips' ="129" if `clean_state'=="Iowa" & `clean_county'=="Mills"
	replace `countyfips' ="131" if `clean_state'=="Iowa" & `clean_county'=="Mitchell"
	replace `countyfips' ="133" if `clean_state'=="Iowa" & `clean_county'=="Monona"
	replace `countyfips' ="135" if `clean_state'=="Iowa" & `clean_county'=="Monroe"
	replace `countyfips' ="137" if `clean_state'=="Iowa" & `clean_county'=="Montgomery"
	replace `countyfips' ="139" if `clean_state'=="Iowa" & `clean_county'=="Muscatine"
	replace `countyfips' ="141" if `clean_state'=="Iowa" & `clean_county'=="Obrien"
	replace `countyfips' ="143" if `clean_state'=="Iowa" & `clean_county'=="Osceola"
	replace `countyfips' ="145" if `clean_state'=="Iowa" & `clean_county'=="Page"
	replace `countyfips' ="147" if `clean_state'=="Iowa" & `clean_county'=="Palo Alto"
	replace `countyfips' ="149" if `clean_state'=="Iowa" & `clean_county'=="Plymouth"
	replace `countyfips' ="151" if `clean_state'=="Iowa" & `clean_county'=="Pocahontas"
	replace `countyfips' ="153" if `clean_state'=="Iowa" & `clean_county'=="Polk"
	replace `countyfips' ="155" if `clean_state'=="Iowa" & `clean_county'=="Pottawattamie"
	replace `countyfips' ="157" if `clean_state'=="Iowa" & `clean_county'=="Poweshiek"
	replace `countyfips' ="159" if `clean_state'=="Iowa" & `clean_county'=="Ringgold"
	replace `countyfips' ="161" if `clean_state'=="Iowa" & `clean_county'=="Sac"
	replace `countyfips' ="163" if `clean_state'=="Iowa" & `clean_county'=="Scott"
	replace `countyfips' ="165" if `clean_state'=="Iowa" & `clean_county'=="Shelby"
	replace `countyfips' ="167" if `clean_state'=="Iowa" & `clean_county'=="Sioux"
	replace `countyfips' ="169" if `clean_state'=="Iowa" & `clean_county'=="Story"
	replace `countyfips' ="171" if `clean_state'=="Iowa" & `clean_county'=="Tama"
	replace `countyfips' ="173" if `clean_state'=="Iowa" & `clean_county'=="Taylor"
	replace `countyfips' ="175" if `clean_state'=="Iowa" & `clean_county'=="Union"
	replace `countyfips' ="177" if `clean_state'=="Iowa" & `clean_county'=="Van Buren"
	replace `countyfips' ="179" if `clean_state'=="Iowa" & `clean_county'=="Wapello"
	replace `countyfips' ="181" if `clean_state'=="Iowa" & `clean_county'=="Warren"
	replace `countyfips' ="183" if `clean_state'=="Iowa" & `clean_county'=="Washington"
	replace `countyfips' ="185" if `clean_state'=="Iowa" & `clean_county'=="Wayne"
	replace `countyfips' ="187" if `clean_state'=="Iowa" & `clean_county'=="Webster"
	replace `countyfips' ="189" if `clean_state'=="Iowa" & `clean_county'=="Winnebago"
	replace `countyfips' ="191" if `clean_state'=="Iowa" & `clean_county'=="Winneshiek"
	replace `countyfips' ="193" if `clean_state'=="Iowa" & `clean_county'=="Woodbury"
	replace `countyfips' ="195" if `clean_state'=="Iowa" & `clean_county'=="Worth"
	replace `countyfips' ="197" if `clean_state'=="Iowa" & `clean_county'=="Wright"
	