	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Virginia" & `clean_county'=="Accomack"
	replace `countyfips' ="003" if `clean_state'=="Virginia" & `clean_county'=="Albemarle"
	replace `countyfips' ="005" if `clean_state'=="Virginia" & `clean_county'=="Alleghany"
	replace `countyfips' ="007" if `clean_state'=="Virginia" & `clean_county'=="Amelia"
	replace `countyfips' ="009" if `clean_state'=="Virginia" & `clean_county'=="Amherst"
	replace `countyfips' ="011" if `clean_state'=="Virginia" & `clean_county'=="Appomattox"
	replace `countyfips' ="013" if `clean_state'=="Virginia" & `clean_county'=="Arlington"
	replace `countyfips' ="015" if `clean_state'=="Virginia" & `clean_county'=="Augusta"
	replace `countyfips' ="017" if `clean_state'=="Virginia" & `clean_county'=="Bath"
	replace `countyfips' ="019" if `clean_state'=="Virginia" & `clean_county'=="Bedford"
	replace `countyfips' ="021" if `clean_state'=="Virginia" & `clean_county'=="Bland"
	replace `countyfips' ="023" if `clean_state'=="Virginia" & `clean_county'=="Botetourt"
	replace `countyfips' ="025" if `clean_state'=="Virginia" & `clean_county'=="Brunswick"
	replace `countyfips' ="027" if `clean_state'=="Virginia" & `clean_county'=="Buchanan"
	replace `countyfips' ="029" if `clean_state'=="Virginia" & `clean_county'=="Buckingham"
	replace `countyfips' ="031" if `clean_state'=="Virginia" & `clean_county'=="Campbell"
	replace `countyfips' ="033" if `clean_state'=="Virginia" & `clean_county'=="Caroline"
	replace `countyfips' ="035" if `clean_state'=="Virginia" & `clean_county'=="Carroll"
	replace `countyfips' ="036" if `clean_state'=="Virginia" & `clean_county'=="Charles City"
	replace `countyfips' ="037" if `clean_state'=="Virginia" & `clean_county'=="Charlotte"
	replace `countyfips' ="041" if `clean_state'=="Virginia" & `clean_county'=="Chesterfield"
	replace `countyfips' ="043" if `clean_state'=="Virginia" & `clean_county'=="Clarke"
	replace `countyfips' ="045" if `clean_state'=="Virginia" & `clean_county'=="Craig"
	replace `countyfips' ="047" if `clean_state'=="Virginia" & `clean_county'=="Culpeper"
	replace `countyfips' ="049" if `clean_state'=="Virginia" & `clean_county'=="Cumberland"
	replace `countyfips' ="051" if `clean_state'=="Virginia" & `clean_county'=="Dickenson"
	replace `countyfips' ="053" if `clean_state'=="Virginia" & `clean_county'=="Dinwiddie"
	replace `countyfips' ="057" if `clean_state'=="Virginia" & `clean_county'=="Essex"
	replace `countyfips' ="059" if `clean_state'=="Virginia" & `clean_county'=="Fairfax"
	replace `countyfips' ="061" if `clean_state'=="Virginia" & `clean_county'=="Fauquier"
	replace `countyfips' ="063" if `clean_state'=="Virginia" & `clean_county'=="Floyd"
	replace `countyfips' ="065" if `clean_state'=="Virginia" & `clean_county'=="Fluvanna"
	replace `countyfips' ="067" if `clean_state'=="Virginia" & `clean_county'=="Franklin"
	replace `countyfips' ="069" if `clean_state'=="Virginia" & `clean_county'=="Frederick"
	replace `countyfips' ="071" if `clean_state'=="Virginia" & `clean_county'=="Giles"
	replace `countyfips' ="073" if `clean_state'=="Virginia" & `clean_county'=="Gloucester"
	replace `countyfips' ="075" if `clean_state'=="Virginia" & `clean_county'=="Goochland"
	replace `countyfips' ="077" if `clean_state'=="Virginia" & `clean_county'=="Grayson"
	replace `countyfips' ="079" if `clean_state'=="Virginia" & `clean_county'=="Greene"
	replace `countyfips' ="081" if `clean_state'=="Virginia" & `clean_county'=="Greensville"
	replace `countyfips' ="083" if `clean_state'=="Virginia" & `clean_county'=="Halifax"
	replace `countyfips' ="085" if `clean_state'=="Virginia" & `clean_county'=="Hanover"
	replace `countyfips' ="087" if `clean_state'=="Virginia" & `clean_county'=="Henrico"
	replace `countyfips' ="089" if `clean_state'=="Virginia" & `clean_county'=="Henry"
	replace `countyfips' ="091" if `clean_state'=="Virginia" & `clean_county'=="Highland"
	replace `countyfips' ="093" if `clean_state'=="Virginia" & `clean_county'=="Isle of Wight"
	replace `countyfips' ="095" if `clean_state'=="Virginia" & `clean_county'=="James City"
	replace `countyfips' ="097" if `clean_state'=="Virginia" & `clean_county'=="King and Queen"
	replace `countyfips' ="099" if `clean_state'=="Virginia" & `clean_county'=="King George"
	replace `countyfips' ="101" if `clean_state'=="Virginia" & `clean_county'=="King William"
	replace `countyfips' ="103" if `clean_state'=="Virginia" & `clean_county'=="Lancaster"
	replace `countyfips' ="105" if `clean_state'=="Virginia" & `clean_county'=="Lee"
	replace `countyfips' ="107" if `clean_state'=="Virginia" & `clean_county'=="Loudoun"
	replace `countyfips' ="109" if `clean_state'=="Virginia" & `clean_county'=="Louisa"
	replace `countyfips' ="111" if `clean_state'=="Virginia" & `clean_county'=="Lunenburg"
	replace `countyfips' ="113" if `clean_state'=="Virginia" & `clean_county'=="Madison"
	replace `countyfips' ="115" if `clean_state'=="Virginia" & `clean_county'=="Mathews"
	replace `countyfips' ="117" if `clean_state'=="Virginia" & `clean_county'=="Mecklenburg"
	replace `countyfips' ="119" if `clean_state'=="Virginia" & `clean_county'=="Middlesex"
	replace `countyfips' ="121" if `clean_state'=="Virginia" & `clean_county'=="Montgomery"
	replace `countyfips' ="125" if `clean_state'=="Virginia" & `clean_county'=="Nelson"
	replace `countyfips' ="127" if `clean_state'=="Virginia" & `clean_county'=="New Kent"
	replace `countyfips' ="131" if `clean_state'=="Virginia" & `clean_county'=="Northampton"
	replace `countyfips' ="133" if `clean_state'=="Virginia" & `clean_county'=="Northumberland"
	replace `countyfips' ="135" if `clean_state'=="Virginia" & `clean_county'=="Nottoway"
	replace `countyfips' ="137" if `clean_state'=="Virginia" & `clean_county'=="Orange"
	replace `countyfips' ="139" if `clean_state'=="Virginia" & `clean_county'=="Page"
	replace `countyfips' ="141" if `clean_state'=="Virginia" & `clean_county'=="Patrick"
	replace `countyfips' ="143" if `clean_state'=="Virginia" & `clean_county'=="Pittsylvania"
	replace `countyfips' ="145" if `clean_state'=="Virginia" & `clean_county'=="Powhatan"
	replace `countyfips' ="147" if `clean_state'=="Virginia" & `clean_county'=="Prince Edward"
	replace `countyfips' ="149" if `clean_state'=="Virginia" & `clean_county'=="Prince George"
	replace `countyfips' ="153" if `clean_state'=="Virginia" & `clean_county'=="Prince William"
	replace `countyfips' ="155" if `clean_state'=="Virginia" & `clean_county'=="Pulaski"
	replace `countyfips' ="157" if `clean_state'=="Virginia" & `clean_county'=="Rappahannock"
	replace `countyfips' ="159" if `clean_state'=="Virginia" & `clean_county'=="Richmond"
	replace `countyfips' ="161" if `clean_state'=="Virginia" & `clean_county'=="Roanoke"
	replace `countyfips' ="163" if `clean_state'=="Virginia" & `clean_county'=="Rockbridge"
	replace `countyfips' ="165" if `clean_state'=="Virginia" & `clean_county'=="Rockingham"
	replace `countyfips' ="167" if `clean_state'=="Virginia" & `clean_county'=="Russell"
	replace `countyfips' ="169" if `clean_state'=="Virginia" & `clean_county'=="Scott"
	replace `countyfips' ="171" if `clean_state'=="Virginia" & `clean_county'=="Shenandoah"
	replace `countyfips' ="173" if `clean_state'=="Virginia" & `clean_county'=="Smyth"
	replace `countyfips' ="175" if `clean_state'=="Virginia" & `clean_county'=="Southampton"
	replace `countyfips' ="177" if `clean_state'=="Virginia" & `clean_county'=="Spotsylvania"
	replace `countyfips' ="179" if `clean_state'=="Virginia" & `clean_county'=="Stafford"
	replace `countyfips' ="181" if `clean_state'=="Virginia" & `clean_county'=="Surry"
	replace `countyfips' ="183" if `clean_state'=="Virginia" & `clean_county'=="Sussex"
	replace `countyfips' ="185" if `clean_state'=="Virginia" & `clean_county'=="Tazewell"
	replace `countyfips' ="187" if `clean_state'=="Virginia" & `clean_county'=="Warren"
	replace `countyfips' ="191" if `clean_state'=="Virginia" & `clean_county'=="Washington"
	replace `countyfips' ="193" if `clean_state'=="Virginia" & `clean_county'=="Westmoreland"
	replace `countyfips' ="195" if `clean_state'=="Virginia" & `clean_county'=="Wise"
	replace `countyfips' ="197" if `clean_state'=="Virginia" & `clean_county'=="Wythe"
	replace `countyfips' ="199" if `clean_state'=="Virginia" & `clean_county'=="York"
	replace `countyfips' ="510" if `clean_state'=="Virginia" & `clean_county'=="Alexandria City"
	replace `countyfips' ="515" if `clean_state'=="Virginia" & `clean_county'=="Bedford City"
	replace `countyfips' ="520" if `clean_state'=="Virginia" & `clean_county'=="Bristol City"
	replace `countyfips' ="530" if `clean_state'=="Virginia" & `clean_county'=="Buena Vista City"
	replace `countyfips' ="540" if `clean_state'=="Virginia" & `clean_county'=="Charlottesville City"
	replace `countyfips' ="550" if `clean_state'=="Virginia" & `clean_county'=="Chesapeake City"
	replace `countyfips' ="560" if `clean_state'=="Virginia" & `clean_county'=="Clifton Forge City"
	replace `countyfips' ="570" if `clean_state'=="Virginia" & `clean_county'=="Colonial Heights City"
	replace `countyfips' ="580" if `clean_state'=="Virginia" & `clean_county'=="Covington City"
	replace `countyfips' ="590" if `clean_state'=="Virginia" & `clean_county'=="Danville City"
	replace `countyfips' ="595" if `clean_state'=="Virginia" & `clean_county'=="Emporia City"
	replace `countyfips' ="600" if `clean_state'=="Virginia" & `clean_county'=="Fairfax City"
	replace `countyfips' ="610" if `clean_state'=="Virginia" & `clean_county'=="Falls Church City"
	replace `countyfips' ="620" if `clean_state'=="Virginia" & `clean_county'=="Franklin City"
	replace `countyfips' ="630" if `clean_state'=="Virginia" & `clean_county'=="Fredericksburg City"
	replace `countyfips' ="640" if `clean_state'=="Virginia" & `clean_county'=="Galax City"
	replace `countyfips' ="650" if `clean_state'=="Virginia" & `clean_county'=="Hampton City"
	replace `countyfips' ="660" if `clean_state'=="Virginia" & `clean_county'=="Harrisonburg City"
	replace `countyfips' ="670" if `clean_state'=="Virginia" & `clean_county'=="Hopewell City"
	replace `countyfips' ="678" if `clean_state'=="Virginia" & `clean_county'=="Lexington City"
	replace `countyfips' ="680" if `clean_state'=="Virginia" & `clean_county'=="Lynchburg City"
	replace `countyfips' ="683" if `clean_state'=="Virginia" & `clean_county'=="Manassas City"
	replace `countyfips' ="685" if `clean_state'=="Virginia" & `clean_county'=="Manassas Park City"
	replace `countyfips' ="690" if `clean_state'=="Virginia" & `clean_county'=="Martinsville City"
	replace `countyfips' ="700" if `clean_state'=="Virginia" & `clean_county'=="Newport News City"
	replace `countyfips' ="710" if `clean_state'=="Virginia" & `clean_county'=="Norfolk City"
	replace `countyfips' ="710" if `clean_state'=="Virginia" & `clean_county'=="Norfolk"
	replace `countyfips' ="720" if `clean_state'=="Virginia" & `clean_county'=="Norton City"
	replace `countyfips' ="730" if `clean_state'=="Virginia" & `clean_county'=="Petersburg City"
	replace `countyfips' ="735" if `clean_state'=="Virginia" & `clean_county'=="Poquoson City"
	replace `countyfips' ="740" if `clean_state'=="Virginia" & `clean_county'=="Portsmouth City"
	replace `countyfips' ="750" if `clean_state'=="Virginia" & `clean_county'=="Radford"
	replace `countyfips' ="760" if `clean_state'=="Virginia" & `clean_county'=="Richmond City"
	replace `countyfips' ="770" if `clean_state'=="Virginia" & `clean_county'=="Roanoke City"
	replace `countyfips' ="775" if `clean_state'=="Virginia" & `clean_county'=="Salem City"
	replace `countyfips' ="780" if `clean_state'=="Virginia" & `clean_county'=="South Boston City"
	replace `countyfips' ="790" if `clean_state'=="Virginia" & `clean_county'=="Staunton City"
	replace `countyfips' ="800" if `clean_state'=="Virginia" & `clean_county'=="Suffolk City"
	replace `countyfips' ="810" if `clean_state'=="Virginia" & `clean_county'=="Virginia Beach City"
	replace `countyfips' ="820" if `clean_state'=="Virginia" & `clean_county'=="Waynesboro City"
	replace `countyfips' ="830" if `clean_state'=="Virginia" & `clean_county'=="Williamsburg City"
	replace `countyfips' ="840" if `clean_state'=="Virginia" & `clean_county'=="Winchester City"
	
	//These counties are no longer extant, not sure what to do with their FIPS codes
	replace `countyfips' ="999" if `clean_state'=="Virginia" & `clean_county'=="Elizabeth City"
	replace `countyfips' ="999" if `clean_state'=="Virginia" & `clean_county'=="Nansemond"
	replace `countyfips' ="999" if `clean_state'=="Virginia" & `clean_county'=="Warwick"
	replace `countyfips' ="999" if `clean_state'=="Virginia" & `clean_county'=="Elizabeth City"

	
	