	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Montana" & `clean_county'=="Beaverhead"
	replace `countyfips' ="003" if `clean_state'=="Montana" & `clean_county'=="Big Horn"
	replace `countyfips' ="005" if `clean_state'=="Montana" & `clean_county'=="Blaine"
	replace `countyfips' ="007" if `clean_state'=="Montana" & `clean_county'=="Broadwater"
	replace `countyfips' ="009" if `clean_state'=="Montana" & `clean_county'=="Carbon"
	replace `countyfips' ="011" if `clean_state'=="Montana" & `clean_county'=="Carter"
	replace `countyfips' ="013" if `clean_state'=="Montana" & `clean_county'=="Cascade"
	replace `countyfips' ="015" if `clean_state'=="Montana" & `clean_county'=="Chouteau"
	replace `countyfips' ="017" if `clean_state'=="Montana" & `clean_county'=="Custer"
	replace `countyfips' ="019" if `clean_state'=="Montana" & `clean_county'=="Daniels"
	replace `countyfips' ="021" if `clean_state'=="Montana" & `clean_county'=="Dawson"
	replace `countyfips' ="023" if `clean_state'=="Montana" & `clean_county'=="Deer Lodge"
	replace `countyfips' ="025" if `clean_state'=="Montana" & `clean_county'=="Fallon"
	replace `countyfips' ="027" if `clean_state'=="Montana" & `clean_county'=="Fergus"
	replace `countyfips' ="029" if `clean_state'=="Montana" & `clean_county'=="Flathead"
	replace `countyfips' ="031" if `clean_state'=="Montana" & `clean_county'=="Gallatin"
	replace `countyfips' ="033" if `clean_state'=="Montana" & `clean_county'=="Garfield"
	replace `countyfips' ="035" if `clean_state'=="Montana" & `clean_county'=="Glacier"
	replace `countyfips' ="037" if `clean_state'=="Montana" & `clean_county'=="Golden Valley"
	replace `countyfips' ="039" if `clean_state'=="Montana" & `clean_county'=="Granite"
	replace `countyfips' ="041" if `clean_state'=="Montana" & `clean_county'=="Hill"
	replace `countyfips' ="043" if `clean_state'=="Montana" & `clean_county'=="Jefferson"
	replace `countyfips' ="045" if `clean_state'=="Montana" & `clean_county'=="Judith Basin"
	replace `countyfips' ="047" if `clean_state'=="Montana" & `clean_county'=="Lake"
	replace `countyfips' ="049" if `clean_state'=="Montana" & `clean_county'=="Lewis and Clark"
	replace `countyfips' ="051" if `clean_state'=="Montana" & `clean_county'=="Liberty"
	replace `countyfips' ="053" if `clean_state'=="Montana" & `clean_county'=="Lincoln"
	replace `countyfips' ="055" if `clean_state'=="Montana" & `clean_county'=="McCone"
	replace `countyfips' ="057" if `clean_state'=="Montana" & `clean_county'=="Madison"
	replace `countyfips' ="059" if `clean_state'=="Montana" & `clean_county'=="Meagher"
	replace `countyfips' ="061" if `clean_state'=="Montana" & `clean_county'=="Mineral"
	replace `countyfips' ="063" if `clean_state'=="Montana" & `clean_county'=="Missoula"
	replace `countyfips' ="065" if `clean_state'=="Montana" & `clean_county'=="Musselshell"
	replace `countyfips' ="067" if `clean_state'=="Montana" & `clean_county'=="Park"
	replace `countyfips' ="069" if `clean_state'=="Montana" & `clean_county'=="Petroleum"
	replace `countyfips' ="071" if `clean_state'=="Montana" & `clean_county'=="Phillips"
	replace `countyfips' ="073" if `clean_state'=="Montana" & `clean_county'=="Pondera"
	replace `countyfips' ="075" if `clean_state'=="Montana" & `clean_county'=="Powder River"
	replace `countyfips' ="077" if `clean_state'=="Montana" & `clean_county'=="Powell"
	replace `countyfips' ="079" if `clean_state'=="Montana" & `clean_county'=="Prairie"
	replace `countyfips' ="081" if `clean_state'=="Montana" & `clean_county'=="Ravalli"
	replace `countyfips' ="083" if `clean_state'=="Montana" & `clean_county'=="Richland"
	replace `countyfips' ="085" if `clean_state'=="Montana" & `clean_county'=="Roosevelt"
	replace `countyfips' ="087" if `clean_state'=="Montana" & `clean_county'=="Rosebud"
	replace `countyfips' ="089" if `clean_state'=="Montana" & `clean_county'=="Sanders"
	replace `countyfips' ="091" if `clean_state'=="Montana" & `clean_county'=="Sheridan"
	replace `countyfips' ="093" if `clean_state'=="Montana" & `clean_county'=="Silver Bow"
	replace `countyfips' ="095" if `clean_state'=="Montana" & `clean_county'=="Stillwater"
	replace `countyfips' ="097" if `clean_state'=="Montana" & `clean_county'=="Sweet Grass"
	replace `countyfips' ="099" if `clean_state'=="Montana" & `clean_county'=="Teton"
	replace `countyfips' ="101" if `clean_state'=="Montana" & `clean_county'=="Toole"
	replace `countyfips' ="103" if `clean_state'=="Montana" & `clean_county'=="Treasure"
	replace `countyfips' ="105" if `clean_state'=="Montana" & `clean_county'=="Valley"
	replace `countyfips' ="107" if `clean_state'=="Montana" & `clean_county'=="Wheatland"
	replace `countyfips' ="109" if `clean_state'=="Montana" & `clean_county'=="Wibaux"
	replace `countyfips' ="111" if `clean_state'=="Montana" & `clean_county'=="Yellowstone"
	