	args countyfips clean_county clean_state

	replace `countyfips' ="001" if `clean_state'=="Illinois" & `clean_county'=="Adams"
	replace `countyfips' ="003" if `clean_state'=="Illinois" & `clean_county'=="Alexander"
	replace `countyfips' ="005" if `clean_state'=="Illinois" & `clean_county'=="Bond"
	replace `countyfips' ="007" if `clean_state'=="Illinois" & `clean_county'=="Boone"
	replace `countyfips' ="009" if `clean_state'=="Illinois" & `clean_county'=="Brown"
	replace `countyfips' ="011" if `clean_state'=="Illinois" & `clean_county'=="Bureau"
	replace `countyfips' ="013" if `clean_state'=="Illinois" & `clean_county'=="Calhoun"
	replace `countyfips' ="015" if `clean_state'=="Illinois" & `clean_county'=="Carroll"
	replace `countyfips' ="017" if `clean_state'=="Illinois" & `clean_county'=="Cass"
	replace `countyfips' ="019" if `clean_state'=="Illinois" & `clean_county'=="Champaign"
	replace `countyfips' ="021" if `clean_state'=="Illinois" & `clean_county'=="Christian"
	replace `countyfips' ="023" if `clean_state'=="Illinois" & `clean_county'=="Clark"
	replace `countyfips' ="025" if `clean_state'=="Illinois" & `clean_county'=="Clay"
	replace `countyfips' ="027" if `clean_state'=="Illinois" & `clean_county'=="Clinton"
	replace `countyfips' ="029" if `clean_state'=="Illinois" & `clean_county'=="Coles"
	replace `countyfips' ="031" if `clean_state'=="Illinois" & `clean_county'=="Cook"
	replace `countyfips' ="033" if `clean_state'=="Illinois" & `clean_county'=="Crawford"
	replace `countyfips' ="035" if `clean_state'=="Illinois" & `clean_county'=="Cumberland"
	replace `countyfips' ="037" if `clean_state'=="Illinois" & `clean_county'=="De Kalb"
	replace `countyfips' ="039" if `clean_state'=="Illinois" & `clean_county'=="Dewitt"
	replace `countyfips' ="041" if `clean_state'=="Illinois" & `clean_county'=="Douglas"
	replace `countyfips' ="043" if `clean_state'=="Illinois" & `clean_county'=="Du Page"
	replace `countyfips' ="045" if `clean_state'=="Illinois" & `clean_county'=="Edgar"
	replace `countyfips' ="047" if `clean_state'=="Illinois" & `clean_county'=="Edwards"
	replace `countyfips' ="049" if `clean_state'=="Illinois" & `clean_county'=="Effingham"
	replace `countyfips' ="051" if `clean_state'=="Illinois" & `clean_county'=="Fayette"
	replace `countyfips' ="053" if `clean_state'=="Illinois" & `clean_county'=="Ford"
	replace `countyfips' ="055" if `clean_state'=="Illinois" & `clean_county'=="Franklin"
	replace `countyfips' ="057" if `clean_state'=="Illinois" & `clean_county'=="Fulton"
	replace `countyfips' ="059" if `clean_state'=="Illinois" & `clean_county'=="Gallatin"
	replace `countyfips' ="061" if `clean_state'=="Illinois" & `clean_county'=="Greene"
	replace `countyfips' ="063" if `clean_state'=="Illinois" & `clean_county'=="Grundy"
	replace `countyfips' ="065" if `clean_state'=="Illinois" & `clean_county'=="Hamilton"
	replace `countyfips' ="067" if `clean_state'=="Illinois" & `clean_county'=="Hancock"
	replace `countyfips' ="069" if `clean_state'=="Illinois" & `clean_county'=="Hardin"
	replace `countyfips' ="071" if `clean_state'=="Illinois" & `clean_county'=="Henderson"
	replace `countyfips' ="073" if `clean_state'=="Illinois" & `clean_county'=="Henry"
	replace `countyfips' ="075" if `clean_state'=="Illinois" & `clean_county'=="Iroquois"
	replace `countyfips' ="077" if `clean_state'=="Illinois" & `clean_county'=="Jackson"
	replace `countyfips' ="079" if `clean_state'=="Illinois" & `clean_county'=="Jasper"
	replace `countyfips' ="081" if `clean_state'=="Illinois" & `clean_county'=="Jefferson"
	replace `countyfips' ="083" if `clean_state'=="Illinois" & `clean_county'=="Jersey"
	replace `countyfips' ="085" if `clean_state'=="Illinois" & `clean_county'=="Jo Daviess"
	replace `countyfips' ="087" if `clean_state'=="Illinois" & `clean_county'=="Johnson"
	replace `countyfips' ="089" if `clean_state'=="Illinois" & `clean_county'=="Kane"
	replace `countyfips' ="091" if `clean_state'=="Illinois" & `clean_county'=="Kankakee"
	replace `countyfips' ="093" if `clean_state'=="Illinois" & `clean_county'=="Kendall"
	replace `countyfips' ="095" if `clean_state'=="Illinois" & `clean_county'=="Knox"
	replace `countyfips' ="097" if `clean_state'=="Illinois" & `clean_county'=="Lake"
	replace `countyfips' ="099" if `clean_state'=="Illinois" & `clean_county'=="La Salle"
	replace `countyfips' ="101" if `clean_state'=="Illinois" & `clean_county'=="Lawrence"
	replace `countyfips' ="103" if `clean_state'=="Illinois" & `clean_county'=="Lee"
	replace `countyfips' ="105" if `clean_state'=="Illinois" & `clean_county'=="Livingston"
	replace `countyfips' ="107" if `clean_state'=="Illinois" & `clean_county'=="Logan"
	replace `countyfips' ="109" if `clean_state'=="Illinois" & `clean_county'=="McDonough"
	replace `countyfips' ="111" if `clean_state'=="Illinois" & `clean_county'=="McHenry"
	replace `countyfips' ="113" if `clean_state'=="Illinois" & `clean_county'=="Mclean"
	replace `countyfips' ="115" if `clean_state'=="Illinois" & `clean_county'=="Macon"
	replace `countyfips' ="117" if `clean_state'=="Illinois" & `clean_county'=="Macoupin"
	replace `countyfips' ="119" if `clean_state'=="Illinois" & `clean_county'=="Madison"
	replace `countyfips' ="121" if `clean_state'=="Illinois" & `clean_county'=="Marion"
	replace `countyfips' ="123" if `clean_state'=="Illinois" & `clean_county'=="Marshall"
	replace `countyfips' ="125" if `clean_state'=="Illinois" & `clean_county'=="Mason"
	replace `countyfips' ="127" if `clean_state'=="Illinois" & `clean_county'=="Massac"
	replace `countyfips' ="129" if `clean_state'=="Illinois" & `clean_county'=="Menard"
	replace `countyfips' ="131" if `clean_state'=="Illinois" & `clean_county'=="Mercer"
	replace `countyfips' ="133" if `clean_state'=="Illinois" & `clean_county'=="Monroe"
	replace `countyfips' ="135" if `clean_state'=="Illinois" & `clean_county'=="Montgomery"
	replace `countyfips' ="137" if `clean_state'=="Illinois" & `clean_county'=="Morgan"
	replace `countyfips' ="139" if `clean_state'=="Illinois" & `clean_county'=="Moultrie"
	replace `countyfips' ="141" if `clean_state'=="Illinois" & `clean_county'=="Ogle"
	replace `countyfips' ="143" if `clean_state'=="Illinois" & `clean_county'=="Peoria"
	replace `countyfips' ="145" if `clean_state'=="Illinois" & `clean_county'=="Perry"
	replace `countyfips' ="147" if `clean_state'=="Illinois" & `clean_county'=="Piatt"
	replace `countyfips' ="149" if `clean_state'=="Illinois" & `clean_county'=="Pike"
	replace `countyfips' ="151" if `clean_state'=="Illinois" & `clean_county'=="Pope"
	replace `countyfips' ="153" if `clean_state'=="Illinois" & `clean_county'=="Pulaski"
	replace `countyfips' ="155" if `clean_state'=="Illinois" & `clean_county'=="Putnam"
	replace `countyfips' ="157" if `clean_state'=="Illinois" & `clean_county'=="Randolph"
	replace `countyfips' ="159" if `clean_state'=="Illinois" & `clean_county'=="Richland"
	replace `countyfips' ="161" if `clean_state'=="Illinois" & `clean_county'=="Rock Island"
	replace `countyfips' ="163" if `clean_state'=="Illinois" & `clean_county'=="St Clair"
	replace `countyfips' ="163" if `clean_state'=="Illinois" & `clean_county'=="St. Clair"
	replace `countyfips' ="165" if `clean_state'=="Illinois" & `clean_county'=="Saline"
	replace `countyfips' ="167" if `clean_state'=="Illinois" & `clean_county'=="Sangamon"
	replace `countyfips' ="169" if `clean_state'=="Illinois" & `clean_county'=="Schuyler"
	replace `countyfips' ="171" if `clean_state'=="Illinois" & `clean_county'=="Scott"
	replace `countyfips' ="173" if `clean_state'=="Illinois" & `clean_county'=="Shelby"
	replace `countyfips' ="175" if `clean_state'=="Illinois" & `clean_county'=="Stark"
	replace `countyfips' ="177" if `clean_state'=="Illinois" & `clean_county'=="Stephenson"
	replace `countyfips' ="179" if `clean_state'=="Illinois" & `clean_county'=="Tazewell"
	replace `countyfips' ="181" if `clean_state'=="Illinois" & `clean_county'=="Union"
	replace `countyfips' ="183" if `clean_state'=="Illinois" & `clean_county'=="Vermilion"
	replace `countyfips' ="185" if `clean_state'=="Illinois" & `clean_county'=="Wabash"
	replace `countyfips' ="187" if `clean_state'=="Illinois" & `clean_county'=="Warren"
	replace `countyfips' ="189" if `clean_state'=="Illinois" & `clean_county'=="Washington"
	replace `countyfips' ="191" if `clean_state'=="Illinois" & `clean_county'=="Wayne"
	replace `countyfips' ="193" if `clean_state'=="Illinois" & `clean_county'=="White"
	replace `countyfips' ="195" if `clean_state'=="Illinois" & `clean_county'=="Whiteside"
	replace `countyfips' ="197" if `clean_state'=="Illinois" & `clean_county'=="Will"
	replace `countyfips' ="199" if `clean_state'=="Illinois" & `clean_county'=="Williamson"
	replace `countyfips' ="201" if `clean_state'=="Illinois" & `clean_county'=="Winnebago"
	replace `countyfips' ="203" if `clean_state'=="Illinois" & `clean_county'=="Woodford"
	