	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Oregon" & `clean_county'=="Baker"
	replace `countyfips' ="003" if `clean_state'=="Oregon" & `clean_county'=="Benton"
	replace `countyfips' ="005" if `clean_state'=="Oregon" & `clean_county'=="Clackamas"
	replace `countyfips' ="007" if `clean_state'=="Oregon" & `clean_county'=="Clatsop"
	replace `countyfips' ="009" if `clean_state'=="Oregon" & `clean_county'=="Columbia"
	replace `countyfips' ="011" if `clean_state'=="Oregon" & `clean_county'=="Coos"
	replace `countyfips' ="013" if `clean_state'=="Oregon" & `clean_county'=="Crook"
	replace `countyfips' ="015" if `clean_state'=="Oregon" & `clean_county'=="Curry"
	replace `countyfips' ="017" if `clean_state'=="Oregon" & `clean_county'=="Deschutes"
	replace `countyfips' ="019" if `clean_state'=="Oregon" & `clean_county'=="Douglas"
	replace `countyfips' ="021" if `clean_state'=="Oregon" & `clean_county'=="Gilliam"
	replace `countyfips' ="023" if `clean_state'=="Oregon" & `clean_county'=="Grant"
	replace `countyfips' ="025" if `clean_state'=="Oregon" & `clean_county'=="Harney"
	replace `countyfips' ="027" if `clean_state'=="Oregon" & `clean_county'=="Hood River"
	replace `countyfips' ="029" if `clean_state'=="Oregon" & `clean_county'=="Jackson"
	replace `countyfips' ="031" if `clean_state'=="Oregon" & `clean_county'=="Jefferson"
	replace `countyfips' ="033" if `clean_state'=="Oregon" & `clean_county'=="Josephine"
	replace `countyfips' ="035" if `clean_state'=="Oregon" & `clean_county'=="Klamath"
	replace `countyfips' ="037" if `clean_state'=="Oregon" & `clean_county'=="Lake"
	replace `countyfips' ="039" if `clean_state'=="Oregon" & `clean_county'=="Lane"
	replace `countyfips' ="041" if `clean_state'=="Oregon" & `clean_county'=="Lincoln"
	replace `countyfips' ="043" if `clean_state'=="Oregon" & `clean_county'=="Linn"
	replace `countyfips' ="045" if `clean_state'=="Oregon" & `clean_county'=="Malheur"
	replace `countyfips' ="047" if `clean_state'=="Oregon" & `clean_county'=="Marion"
	replace `countyfips' ="049" if `clean_state'=="Oregon" & `clean_county'=="Morrow"
	replace `countyfips' ="051" if `clean_state'=="Oregon" & `clean_county'=="Multnomah"
	replace `countyfips' ="053" if `clean_state'=="Oregon" & `clean_county'=="Polk"
	replace `countyfips' ="055" if `clean_state'=="Oregon" & `clean_county'=="Sherman"
	replace `countyfips' ="057" if `clean_state'=="Oregon" & `clean_county'=="Tillamook"
	replace `countyfips' ="059" if `clean_state'=="Oregon" & `clean_county'=="Umatilla"
	replace `countyfips' ="061" if `clean_state'=="Oregon" & `clean_county'=="Union"
	replace `countyfips' ="063" if `clean_state'=="Oregon" & `clean_county'=="Wallowa"
	replace `countyfips' ="065" if `clean_state'=="Oregon" & `clean_county'=="Wasco"
	replace `countyfips' ="067" if `clean_state'=="Oregon" & `clean_county'=="Washington"
	replace `countyfips' ="069" if `clean_state'=="Oregon" & `clean_county'=="Wheeler"
	replace `countyfips' ="071" if `clean_state'=="Oregon" & `clean_county'=="Yamhill"
	