	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Louisiana" & `clean_county'=="Acadia"
	replace `countyfips' ="003" if `clean_state'=="Louisiana" & `clean_county'=="Allen"
	replace `countyfips' ="005" if `clean_state'=="Louisiana" & `clean_county'=="Ascension"
	replace `countyfips' ="007" if `clean_state'=="Louisiana" & `clean_county'=="Assumption"
	replace `countyfips' ="009" if `clean_state'=="Louisiana" & `clean_county'=="Avoyelles"
	replace `countyfips' ="011" if `clean_state'=="Louisiana" & `clean_county'=="Beauregard"
	replace `countyfips' ="013" if `clean_state'=="Louisiana" & `clean_county'=="Bienville"
	replace `countyfips' ="015" if `clean_state'=="Louisiana" & `clean_county'=="Bossier"
	replace `countyfips' ="017" if `clean_state'=="Louisiana" & `clean_county'=="Caddo"
	replace `countyfips' ="019" if `clean_state'=="Louisiana" & `clean_county'=="Calcasieu"
	replace `countyfips' ="021" if `clean_state'=="Louisiana" & `clean_county'=="Caldwell"
	replace `countyfips' ="023" if `clean_state'=="Louisiana" & `clean_county'=="Cameron"
	replace `countyfips' ="025" if `clean_state'=="Louisiana" & `clean_county'=="Catahoula"
	replace `countyfips' ="027" if `clean_state'=="Louisiana" & `clean_county'=="Claiborne"
	replace `countyfips' ="029" if `clean_state'=="Louisiana" & `clean_county'=="Concordia"
	replace `countyfips' ="031" if `clean_state'=="Louisiana" & `clean_county'=="De Soto"
	replace `countyfips' ="033" if `clean_state'=="Louisiana" & `clean_county'=="East Baton Rouge"
	replace `countyfips' ="035" if `clean_state'=="Louisiana" & `clean_county'=="East Carroll"
	replace `countyfips' ="037" if `clean_state'=="Louisiana" & `clean_county'=="East Feliciana"
	replace `countyfips' ="039" if `clean_state'=="Louisiana" & `clean_county'=="Evangeline"
	replace `countyfips' ="041" if `clean_state'=="Louisiana" & `clean_county'=="Franklin"
	replace `countyfips' ="043" if `clean_state'=="Louisiana" & `clean_county'=="Grant"
	replace `countyfips' ="045" if `clean_state'=="Louisiana" & `clean_county'=="Iberia"
	replace `countyfips' ="047" if `clean_state'=="Louisiana" & `clean_county'=="Iberville"
	replace `countyfips' ="049" if `clean_state'=="Louisiana" & `clean_county'=="Jackson"
	replace `countyfips' ="051" if `clean_state'=="Louisiana" & `clean_county'=="Jefferson"
	replace `countyfips' ="053" if `clean_state'=="Louisiana" & `clean_county'=="Jefferson Davis"
	replace `countyfips' ="055" if `clean_state'=="Louisiana" & `clean_county'=="Lafayette"
	replace `countyfips' ="057" if `clean_state'=="Louisiana" & `clean_county'=="Lafourche"
	replace `countyfips' ="059" if `clean_state'=="Louisiana" & `clean_county'=="La Salle"
	replace `countyfips' ="061" if `clean_state'=="Louisiana" & `clean_county'=="Lincoln"
	replace `countyfips' ="063" if `clean_state'=="Louisiana" & `clean_county'=="Livingston"
	replace `countyfips' ="065" if `clean_state'=="Louisiana" & `clean_county'=="Madison"
	replace `countyfips' ="067" if `clean_state'=="Louisiana" & `clean_county'=="Morehouse"
	replace `countyfips' ="069" if `clean_state'=="Louisiana" & `clean_county'=="Natchitoches"
	replace `countyfips' ="071" if `clean_state'=="Louisiana" & `clean_county'=="Orleans"
	replace `countyfips' ="073" if `clean_state'=="Louisiana" & `clean_county'=="Ouachita"
	replace `countyfips' ="075" if `clean_state'=="Louisiana" & `clean_county'=="Plaquemines"
	replace `countyfips' ="077" if `clean_state'=="Louisiana" & `clean_county'=="Pointe Coupee"
	replace `countyfips' ="079" if `clean_state'=="Louisiana" & `clean_county'=="Rapides"
	replace `countyfips' ="081" if `clean_state'=="Louisiana" & `clean_county'=="Red River"
	replace `countyfips' ="083" if `clean_state'=="Louisiana" & `clean_county'=="Richland"
	replace `countyfips' ="085" if `clean_state'=="Louisiana" & `clean_county'=="Sabine"
	replace `countyfips' ="087" if `clean_state'=="Louisiana" & `clean_county'=="St Bernard"
	replace `countyfips' ="089" if `clean_state'=="Louisiana" & `clean_county'=="St Charles"
	replace `countyfips' ="091" if `clean_state'=="Louisiana" & `clean_county'=="St Helena"
	replace `countyfips' ="093" if `clean_state'=="Louisiana" & `clean_county'=="St James"
	replace `countyfips' ="095" if `clean_state'=="Louisiana" & `clean_county'=="St John The Baptist"
	replace `countyfips' ="097" if `clean_state'=="Louisiana" & `clean_county'=="St Landry"
	replace `countyfips' ="099" if `clean_state'=="Louisiana" & `clean_county'=="St Martin"
	replace `countyfips' ="101" if `clean_state'=="Louisiana" & `clean_county'=="St Mary"
	replace `countyfips' ="103" if `clean_state'=="Louisiana" & `clean_county'=="St Tammany"
	replace `countyfips' ="087" if `clean_state'=="Louisiana" & `clean_county'=="St. Bernard"
	replace `countyfips' ="089" if `clean_state'=="Louisiana" & `clean_county'=="St. Charles"
	replace `countyfips' ="091" if `clean_state'=="Louisiana" & `clean_county'=="St. Helena"
	replace `countyfips' ="093" if `clean_state'=="Louisiana" & `clean_county'=="St. James"
	replace `countyfips' ="095" if `clean_state'=="Louisiana" & `clean_county'=="St. John The Baptist"
	replace `countyfips' ="097" if `clean_state'=="Louisiana" & `clean_county'=="St. Landry"
	replace `countyfips' ="099" if `clean_state'=="Louisiana" & `clean_county'=="St. Martin"
	replace `countyfips' ="101" if `clean_state'=="Louisiana" & `clean_county'=="St. Mary"
	replace `countyfips' ="103" if `clean_state'=="Louisiana" & `clean_county'=="St. Tammany"
	replace `countyfips' ="105" if `clean_state'=="Louisiana" & `clean_county'=="Tangipahoa"
	replace `countyfips' ="107" if `clean_state'=="Louisiana" & `clean_county'=="Tensas"
	replace `countyfips' ="109" if `clean_state'=="Louisiana" & `clean_county'=="Terrebonne"
	replace `countyfips' ="111" if `clean_state'=="Louisiana" & `clean_county'=="Union"
	replace `countyfips' ="113" if `clean_state'=="Louisiana" & `clean_county'=="Vermilion"
	replace `countyfips' ="115" if `clean_state'=="Louisiana" & `clean_county'=="Vernon"
	replace `countyfips' ="117" if `clean_state'=="Louisiana" & `clean_county'=="Washington"
	replace `countyfips' ="119" if `clean_state'=="Louisiana" & `clean_county'=="Webster"
	replace `countyfips' ="121" if `clean_state'=="Louisiana" & `clean_county'=="West Baton Rouge"
	replace `countyfips' ="123" if `clean_state'=="Louisiana" & `clean_county'=="West Carroll"
	replace `countyfips' ="125" if `clean_state'=="Louisiana" & `clean_county'=="West Feliciana"
	replace `countyfips' ="127" if `clean_state'=="Louisiana" & `clean_county'=="Winn"
	