	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="New Jersey" & `clean_county'=="Atlantic"
	replace `countyfips' ="003" if `clean_state'=="New Jersey" & `clean_county'=="Bergen"
	replace `countyfips' ="005" if `clean_state'=="New Jersey" & `clean_county'=="Burlington"
	replace `countyfips' ="007" if `clean_state'=="New Jersey" & `clean_county'=="Camden"
	replace `countyfips' ="009" if `clean_state'=="New Jersey" & `clean_county'=="Cape May"
	replace `countyfips' ="011" if `clean_state'=="New Jersey" & `clean_county'=="Cumberland"
	replace `countyfips' ="013" if `clean_state'=="New Jersey" & `clean_county'=="Essex"
	replace `countyfips' ="015" if `clean_state'=="New Jersey" & `clean_county'=="Gloucester"
	replace `countyfips' ="017" if `clean_state'=="New Jersey" & `clean_county'=="Hudson"
	replace `countyfips' ="019" if `clean_state'=="New Jersey" & `clean_county'=="Hunterdon"
	replace `countyfips' ="021" if `clean_state'=="New Jersey" & `clean_county'=="Mercer"
	replace `countyfips' ="023" if `clean_state'=="New Jersey" & `clean_county'=="Middlesex"
	replace `countyfips' ="025" if `clean_state'=="New Jersey" & `clean_county'=="Monmouth"
	replace `countyfips' ="027" if `clean_state'=="New Jersey" & `clean_county'=="Morris"
	replace `countyfips' ="029" if `clean_state'=="New Jersey" & `clean_county'=="Ocean"
	replace `countyfips' ="031" if `clean_state'=="New Jersey" & `clean_county'=="Passaic"
	replace `countyfips' ="033" if `clean_state'=="New Jersey" & `clean_county'=="Salem"
	replace `countyfips' ="035" if `clean_state'=="New Jersey" & `clean_county'=="Somerset"
	replace `countyfips' ="037" if `clean_state'=="New Jersey" & `clean_county'=="Sussex"
	replace `countyfips' ="039" if `clean_state'=="New Jersey" & `clean_county'=="Union"
	replace `countyfips' ="041" if `clean_state'=="New Jersey" & `clean_county'=="Warren"
	