	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Missouri" & `clean_county'=="Adair"
	replace `countyfips' ="003" if `clean_state'=="Missouri" & `clean_county'=="Andrew"
	replace `countyfips' ="005" if `clean_state'=="Missouri" & `clean_county'=="Atchison"
	replace `countyfips' ="007" if `clean_state'=="Missouri" & `clean_county'=="Audrain"
	replace `countyfips' ="009" if `clean_state'=="Missouri" & `clean_county'=="Barry"
	replace `countyfips' ="011" if `clean_state'=="Missouri" & `clean_county'=="Barton"
	replace `countyfips' ="013" if `clean_state'=="Missouri" & `clean_county'=="Bates"
	replace `countyfips' ="015" if `clean_state'=="Missouri" & `clean_county'=="Benton"
	replace `countyfips' ="017" if `clean_state'=="Missouri" & `clean_county'=="Bollinger"
	replace `countyfips' ="019" if `clean_state'=="Missouri" & `clean_county'=="Boone"
	replace `countyfips' ="021" if `clean_state'=="Missouri" & `clean_county'=="Buchanan"
	replace `countyfips' ="023" if `clean_state'=="Missouri" & `clean_county'=="Butler"
	replace `countyfips' ="025" if `clean_state'=="Missouri" & `clean_county'=="Caldwell"
	replace `countyfips' ="027" if `clean_state'=="Missouri" & `clean_county'=="Callaway"
	replace `countyfips' ="029" if `clean_state'=="Missouri" & `clean_county'=="Camden"
	replace `countyfips' ="031" if `clean_state'=="Missouri" & `clean_county'=="Cape Girardeau"
	replace `countyfips' ="033" if `clean_state'=="Missouri" & `clean_county'=="Carroll"
	replace `countyfips' ="035" if `clean_state'=="Missouri" & `clean_county'=="Carter"
	replace `countyfips' ="037" if `clean_state'=="Missouri" & `clean_county'=="Cass"
	replace `countyfips' ="039" if `clean_state'=="Missouri" & `clean_county'=="Cedar"
	replace `countyfips' ="041" if `clean_state'=="Missouri" & `clean_county'=="Chariton"
	replace `countyfips' ="043" if `clean_state'=="Missouri" & `clean_county'=="Christian"
	replace `countyfips' ="045" if `clean_state'=="Missouri" & `clean_county'=="Clark"
	replace `countyfips' ="047" if `clean_state'=="Missouri" & `clean_county'=="Clay"
	replace `countyfips' ="049" if `clean_state'=="Missouri" & `clean_county'=="Clinton"
	replace `countyfips' ="051" if `clean_state'=="Missouri" & `clean_county'=="Cole"
	replace `countyfips' ="053" if `clean_state'=="Missouri" & `clean_county'=="Cooper"
	replace `countyfips' ="055" if `clean_state'=="Missouri" & `clean_county'=="Crawford"
	replace `countyfips' ="057" if `clean_state'=="Missouri" & `clean_county'=="Dade"
	replace `countyfips' ="059" if `clean_state'=="Missouri" & `clean_county'=="Dallas"
	replace `countyfips' ="061" if `clean_state'=="Missouri" & `clean_county'=="Daviess"
	replace `countyfips' ="063" if `clean_state'=="Missouri" & `clean_county'=="Dekalb"
	replace `countyfips' ="065" if `clean_state'=="Missouri" & `clean_county'=="Dent"
	replace `countyfips' ="067" if `clean_state'=="Missouri" & `clean_county'=="Douglas"
	replace `countyfips' ="069" if `clean_state'=="Missouri" & `clean_county'=="Dunklin"
	replace `countyfips' ="071" if `clean_state'=="Missouri" & `clean_county'=="Franklin"
	replace `countyfips' ="073" if `clean_state'=="Missouri" & `clean_county'=="Gasconade"
	replace `countyfips' ="075" if `clean_state'=="Missouri" & `clean_county'=="Gentry"
	replace `countyfips' ="077" if `clean_state'=="Missouri" & `clean_county'=="Greene"
	replace `countyfips' ="079" if `clean_state'=="Missouri" & `clean_county'=="Grundy"
	replace `countyfips' ="081" if `clean_state'=="Missouri" & `clean_county'=="Harrison"
	replace `countyfips' ="083" if `clean_state'=="Missouri" & `clean_county'=="Henry"
	replace `countyfips' ="085" if `clean_state'=="Missouri" & `clean_county'=="Hickory"
	replace `countyfips' ="087" if `clean_state'=="Missouri" & `clean_county'=="Holt"
	replace `countyfips' ="089" if `clean_state'=="Missouri" & `clean_county'=="Howard"
	replace `countyfips' ="091" if `clean_state'=="Missouri" & `clean_county'=="Howell"
	replace `countyfips' ="093" if `clean_state'=="Missouri" & `clean_county'=="Iron"
	replace `countyfips' ="095" if `clean_state'=="Missouri" & `clean_county'=="Jackson"
	replace `countyfips' ="097" if `clean_state'=="Missouri" & `clean_county'=="Jasper"
	replace `countyfips' ="099" if `clean_state'=="Missouri" & `clean_county'=="Jefferson"
	replace `countyfips' ="101" if `clean_state'=="Missouri" & `clean_county'=="Johnson"
	replace `countyfips' ="103" if `clean_state'=="Missouri" & `clean_county'=="Knox"
	replace `countyfips' ="105" if `clean_state'=="Missouri" & `clean_county'=="Laclede"
	replace `countyfips' ="107" if `clean_state'=="Missouri" & `clean_county'=="Lafayette"
	replace `countyfips' ="109" if `clean_state'=="Missouri" & `clean_county'=="Lawrence"
	replace `countyfips' ="111" if `clean_state'=="Missouri" & `clean_county'=="Lewis"
	replace `countyfips' ="113" if `clean_state'=="Missouri" & `clean_county'=="Lincoln"
	replace `countyfips' ="115" if `clean_state'=="Missouri" & `clean_county'=="Linn"
	replace `countyfips' ="117" if `clean_state'=="Missouri" & `clean_county'=="Livingston"
	replace `countyfips' ="119" if `clean_state'=="Missouri" & `clean_county'=="Mcdonald"
	replace `countyfips' ="121" if `clean_state'=="Missouri" & `clean_county'=="Macon"
	replace `countyfips' ="123" if `clean_state'=="Missouri" & `clean_county'=="Madison"
	replace `countyfips' ="125" if `clean_state'=="Missouri" & `clean_county'=="Maries"
	replace `countyfips' ="127" if `clean_state'=="Missouri" & `clean_county'=="Marion"
	replace `countyfips' ="129" if `clean_state'=="Missouri" & `clean_county'=="Mercer"
	replace `countyfips' ="131" if `clean_state'=="Missouri" & `clean_county'=="Miller"
	replace `countyfips' ="133" if `clean_state'=="Missouri" & `clean_county'=="Mississippi"
	replace `countyfips' ="135" if `clean_state'=="Missouri" & `clean_county'=="Moniteau"
	replace `countyfips' ="137" if `clean_state'=="Missouri" & `clean_county'=="Monroe"
	replace `countyfips' ="139" if `clean_state'=="Missouri" & `clean_county'=="Montgomery"
	replace `countyfips' ="141" if `clean_state'=="Missouri" & `clean_county'=="Morgan"
	replace `countyfips' ="143" if `clean_state'=="Missouri" & `clean_county'=="New Madrid"
	replace `countyfips' ="145" if `clean_state'=="Missouri" & `clean_county'=="Newton"
	replace `countyfips' ="147" if `clean_state'=="Missouri" & `clean_county'=="Nodaway"
	replace `countyfips' ="149" if `clean_state'=="Missouri" & `clean_county'=="Oregon"
	replace `countyfips' ="151" if `clean_state'=="Missouri" & `clean_county'=="Osage"
	replace `countyfips' ="153" if `clean_state'=="Missouri" & `clean_county'=="Ozark"
	replace `countyfips' ="155" if `clean_state'=="Missouri" & `clean_county'=="Pemiscot"
	replace `countyfips' ="157" if `clean_state'=="Missouri" & `clean_county'=="Perry"
	replace `countyfips' ="159" if `clean_state'=="Missouri" & `clean_county'=="Pettis"
	replace `countyfips' ="161" if `clean_state'=="Missouri" & `clean_county'=="Phelps"
	replace `countyfips' ="163" if `clean_state'=="Missouri" & `clean_county'=="Pike"
	replace `countyfips' ="165" if `clean_state'=="Missouri" & `clean_county'=="Platte"
	replace `countyfips' ="167" if `clean_state'=="Missouri" & `clean_county'=="Polk"
	replace `countyfips' ="169" if `clean_state'=="Missouri" & `clean_county'=="Pulaski"
	replace `countyfips' ="171" if `clean_state'=="Missouri" & `clean_county'=="Putnam"
	replace `countyfips' ="173" if `clean_state'=="Missouri" & `clean_county'=="Ralls"
	replace `countyfips' ="175" if `clean_state'=="Missouri" & `clean_county'=="Randolph"
	replace `countyfips' ="177" if `clean_state'=="Missouri" & `clean_county'=="Ray"
	replace `countyfips' ="179" if `clean_state'=="Missouri" & `clean_county'=="Reynolds"
	replace `countyfips' ="181" if `clean_state'=="Missouri" & `clean_county'=="Ripley"
	replace `countyfips' ="183" if `clean_state'=="Missouri" & `clean_county'=="St Charles"
	replace `countyfips' ="185" if `clean_state'=="Missouri" & `clean_county'=="St Clair"
	replace `countyfips' ="186" if `clean_state'=="Missouri" & `clean_county'=="Ste Genevieve"
	replace `countyfips' ="187" if `clean_state'=="Missouri" & `clean_county'=="St Francois"
	replace `countyfips' ="189" if `clean_state'=="Missouri" & `clean_county'=="St Louis"
	replace `countyfips' ="183" if `clean_state'=="Missouri" & `clean_county'=="St. Charles"
	replace `countyfips' ="185" if `clean_state'=="Missouri" & `clean_county'=="St. Clair"
	replace `countyfips' ="186" if `clean_state'=="Missouri" & `clean_county'=="Ste. Genevieve"
	replace `countyfips' ="187" if `clean_state'=="Missouri" & `clean_county'=="St. Francois"
	replace `countyfips' ="189" if `clean_state'=="Missouri" & `clean_county'=="St. Louis"
	replace `countyfips' ="195" if `clean_state'=="Missouri" & `clean_county'=="Saline"
	replace `countyfips' ="197" if `clean_state'=="Missouri" & `clean_county'=="Schuyler"
	replace `countyfips' ="199" if `clean_state'=="Missouri" & `clean_county'=="Scotland"
	replace `countyfips' ="201" if `clean_state'=="Missouri" & `clean_county'=="Scott"
	replace `countyfips' ="203" if `clean_state'=="Missouri" & `clean_county'=="Shannon"
	replace `countyfips' ="205" if `clean_state'=="Missouri" & `clean_county'=="Shelby"
	replace `countyfips' ="207" if `clean_state'=="Missouri" & `clean_county'=="Stoddard"
	replace `countyfips' ="209" if `clean_state'=="Missouri" & `clean_county'=="Stone"
	replace `countyfips' ="211" if `clean_state'=="Missouri" & `clean_county'=="Sullivan"
	replace `countyfips' ="213" if `clean_state'=="Missouri" & `clean_county'=="Taney"
	replace `countyfips' ="215" if `clean_state'=="Missouri" & `clean_county'=="Texas"
	replace `countyfips' ="217" if `clean_state'=="Missouri" & `clean_county'=="Vernon"
	replace `countyfips' ="219" if `clean_state'=="Missouri" & `clean_county'=="Warren"
	replace `countyfips' ="221" if `clean_state'=="Missouri" & `clean_county'=="Washington"
	replace `countyfips' ="223" if `clean_state'=="Missouri" & `clean_county'=="Wayne"
	replace `countyfips' ="225" if `clean_state'=="Missouri" & `clean_county'=="Webster"
	replace `countyfips' ="227" if `clean_state'=="Missouri" & `clean_county'=="Worth"
	replace `countyfips' ="229" if `clean_state'=="Missouri" & `clean_county'=="Wright"
	replace `countyfips' ="510" if `clean_state'=="Missouri" & `clean_county'=="St Louis City"
