	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="North Dakota" & `clean_county'=="Adams"
	replace `countyfips' ="003" if `clean_state'=="North Dakota" & `clean_county'=="Barnes"
	replace `countyfips' ="005" if `clean_state'=="North Dakota" & `clean_county'=="Benson"
	replace `countyfips' ="007" if `clean_state'=="North Dakota" & `clean_county'=="Billings"
	replace `countyfips' ="009" if `clean_state'=="North Dakota" & `clean_county'=="Bottineau"
	replace `countyfips' ="011" if `clean_state'=="North Dakota" & `clean_county'=="Bowman"
	replace `countyfips' ="013" if `clean_state'=="North Dakota" & `clean_county'=="Burke"
	replace `countyfips' ="015" if `clean_state'=="North Dakota" & `clean_county'=="Burleigh"
	replace `countyfips' ="017" if `clean_state'=="North Dakota" & `clean_county'=="Cass"
	replace `countyfips' ="019" if `clean_state'=="North Dakota" & `clean_county'=="Cavalier"
	replace `countyfips' ="021" if `clean_state'=="North Dakota" & `clean_county'=="Dickey"
	replace `countyfips' ="023" if `clean_state'=="North Dakota" & `clean_county'=="Divide"
	replace `countyfips' ="025" if `clean_state'=="North Dakota" & `clean_county'=="Dunn"
	replace `countyfips' ="027" if `clean_state'=="North Dakota" & `clean_county'=="Eddy"
	replace `countyfips' ="029" if `clean_state'=="North Dakota" & `clean_county'=="Emmons"
	replace `countyfips' ="031" if `clean_state'=="North Dakota" & `clean_county'=="Foster"
	replace `countyfips' ="033" if `clean_state'=="North Dakota" & `clean_county'=="Golden Valley"
	replace `countyfips' ="035" if `clean_state'=="North Dakota" & `clean_county'=="Grand Forks"
	replace `countyfips' ="037" if `clean_state'=="North Dakota" & `clean_county'=="Grant"
	replace `countyfips' ="039" if `clean_state'=="North Dakota" & `clean_county'=="Griggs"
	replace `countyfips' ="041" if `clean_state'=="North Dakota" & `clean_county'=="Hettinger"
	replace `countyfips' ="043" if `clean_state'=="North Dakota" & `clean_county'=="Kidder"
	replace `countyfips' ="045" if `clean_state'=="North Dakota" & `clean_county'=="Lamoure"
	replace `countyfips' ="047" if `clean_state'=="North Dakota" & `clean_county'=="Logan"
	replace `countyfips' ="049" if `clean_state'=="North Dakota" & `clean_county'=="McHenry"
	replace `countyfips' ="051" if `clean_state'=="North Dakota" & `clean_county'=="McIntosh"
	replace `countyfips' ="053" if `clean_state'=="North Dakota" & `clean_county'=="Mckenzie"
	replace `countyfips' ="055" if `clean_state'=="North Dakota" & `clean_county'=="Mclean"
	replace `countyfips' ="057" if `clean_state'=="North Dakota" & `clean_county'=="Mercer"
	replace `countyfips' ="059" if `clean_state'=="North Dakota" & `clean_county'=="Morton"
	replace `countyfips' ="061" if `clean_state'=="North Dakota" & `clean_county'=="Mountrail"
	replace `countyfips' ="063" if `clean_state'=="North Dakota" & `clean_county'=="Nelson"
	replace `countyfips' ="065" if `clean_state'=="North Dakota" & `clean_county'=="Oliver"
	replace `countyfips' ="067" if `clean_state'=="North Dakota" & `clean_county'=="Pembina"
	replace `countyfips' ="069" if `clean_state'=="North Dakota" & `clean_county'=="Pierce"
	replace `countyfips' ="071" if `clean_state'=="North Dakota" & `clean_county'=="Ramsey"
	replace `countyfips' ="073" if `clean_state'=="North Dakota" & `clean_county'=="Ransom"
	replace `countyfips' ="075" if `clean_state'=="North Dakota" & `clean_county'=="Renville"
	replace `countyfips' ="077" if `clean_state'=="North Dakota" & `clean_county'=="Richland"
	replace `countyfips' ="079" if `clean_state'=="North Dakota" & `clean_county'=="Rolette"
	replace `countyfips' ="081" if `clean_state'=="North Dakota" & `clean_county'=="Sargent"
	replace `countyfips' ="083" if `clean_state'=="North Dakota" & `clean_county'=="Sheridan"
	replace `countyfips' ="085" if `clean_state'=="North Dakota" & `clean_county'=="Sioux"
	replace `countyfips' ="087" if `clean_state'=="North Dakota" & `clean_county'=="Slope"
	replace `countyfips' ="089" if `clean_state'=="North Dakota" & `clean_county'=="Stark"
	replace `countyfips' ="091" if `clean_state'=="North Dakota" & `clean_county'=="Steele"
	replace `countyfips' ="093" if `clean_state'=="North Dakota" & `clean_county'=="Stutsman"
	replace `countyfips' ="095" if `clean_state'=="North Dakota" & `clean_county'=="Towner"
	replace `countyfips' ="097" if `clean_state'=="North Dakota" & `clean_county'=="Traill"
	replace `countyfips' ="099" if `clean_state'=="North Dakota" & `clean_county'=="Walsh"
	replace `countyfips' ="101" if `clean_state'=="North Dakota" & `clean_county'=="Ward"
	replace `countyfips' ="103" if `clean_state'=="North Dakota" & `clean_county'=="Wells"
	replace `countyfips' ="105" if `clean_state'=="North Dakota" & `clean_county'=="Williams"
	