	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Wisconsin" & `clean_county'=="Adams"
	replace `countyfips' ="003" if `clean_state'=="Wisconsin" & `clean_county'=="Ashland"
	replace `countyfips' ="005" if `clean_state'=="Wisconsin" & `clean_county'=="Barron"
	replace `countyfips' ="007" if `clean_state'=="Wisconsin" & `clean_county'=="Bayfield"
	replace `countyfips' ="009" if `clean_state'=="Wisconsin" & `clean_county'=="Brown"
	replace `countyfips' ="011" if `clean_state'=="Wisconsin" & `clean_county'=="Buffalo"
	replace `countyfips' ="013" if `clean_state'=="Wisconsin" & `clean_county'=="Burnett"
	replace `countyfips' ="015" if `clean_state'=="Wisconsin" & `clean_county'=="Calumet"
	replace `countyfips' ="017" if `clean_state'=="Wisconsin" & `clean_county'=="Chippewa"
	replace `countyfips' ="019" if `clean_state'=="Wisconsin" & `clean_county'=="Clark"
	replace `countyfips' ="021" if `clean_state'=="Wisconsin" & `clean_county'=="Columbia"
	replace `countyfips' ="023" if `clean_state'=="Wisconsin" & `clean_county'=="Crawford"
	replace `countyfips' ="025" if `clean_state'=="Wisconsin" & `clean_county'=="Dane"
	replace `countyfips' ="027" if `clean_state'=="Wisconsin" & `clean_county'=="Dodge"
	replace `countyfips' ="029" if `clean_state'=="Wisconsin" & `clean_county'=="Door"
	replace `countyfips' ="031" if `clean_state'=="Wisconsin" & `clean_county'=="Douglas"
	replace `countyfips' ="033" if `clean_state'=="Wisconsin" & `clean_county'=="Dunn"
	replace `countyfips' ="035" if `clean_state'=="Wisconsin" & `clean_county'=="Eau Claire"
	replace `countyfips' ="037" if `clean_state'=="Wisconsin" & `clean_county'=="Florence"
	replace `countyfips' ="039" if `clean_state'=="Wisconsin" & `clean_county'=="Fond Du Lac"
	replace `countyfips' ="041" if `clean_state'=="Wisconsin" & `clean_county'=="Forest"
	replace `countyfips' ="043" if `clean_state'=="Wisconsin" & `clean_county'=="Grant"
	replace `countyfips' ="045" if `clean_state'=="Wisconsin" & `clean_county'=="Green"
	replace `countyfips' ="047" if `clean_state'=="Wisconsin" & `clean_county'=="Green Lake"
	replace `countyfips' ="049" if `clean_state'=="Wisconsin" & `clean_county'=="Iowa"
	replace `countyfips' ="051" if `clean_state'=="Wisconsin" & `clean_county'=="Iron"
	replace `countyfips' ="053" if `clean_state'=="Wisconsin" & `clean_county'=="Jackson"
	replace `countyfips' ="055" if `clean_state'=="Wisconsin" & `clean_county'=="Jefferson"
	replace `countyfips' ="057" if `clean_state'=="Wisconsin" & `clean_county'=="Juneau"
	replace `countyfips' ="059" if `clean_state'=="Wisconsin" & `clean_county'=="Kenosha"
	replace `countyfips' ="061" if `clean_state'=="Wisconsin" & `clean_county'=="Kewaunee"
	replace `countyfips' ="063" if `clean_state'=="Wisconsin" & `clean_county'=="La Crosse"
	replace `countyfips' ="065" if `clean_state'=="Wisconsin" & `clean_county'=="Lafayette"
	replace `countyfips' ="067" if `clean_state'=="Wisconsin" & `clean_county'=="Langlade"
	replace `countyfips' ="069" if `clean_state'=="Wisconsin" & `clean_county'=="Lincoln"
	replace `countyfips' ="071" if `clean_state'=="Wisconsin" & `clean_county'=="Manitowoc"
	replace `countyfips' ="073" if `clean_state'=="Wisconsin" & `clean_county'=="Marathon"
	replace `countyfips' ="075" if `clean_state'=="Wisconsin" & `clean_county'=="Marinette"
	replace `countyfips' ="077" if `clean_state'=="Wisconsin" & `clean_county'=="Marquette"
	replace `countyfips' ="078" if `clean_state'=="Wisconsin" & `clean_county'=="Menominee"
	replace `countyfips' ="079" if `clean_state'=="Wisconsin" & `clean_county'=="Milwaukee"
	replace `countyfips' ="081" if `clean_state'=="Wisconsin" & `clean_county'=="Monroe"
	replace `countyfips' ="083" if `clean_state'=="Wisconsin" & `clean_county'=="Oconto"
	replace `countyfips' ="085" if `clean_state'=="Wisconsin" & `clean_county'=="Oneida"
	replace `countyfips' ="087" if `clean_state'=="Wisconsin" & `clean_county'=="Outagamie"
	replace `countyfips' ="089" if `clean_state'=="Wisconsin" & `clean_county'=="Ozaukee"
	replace `countyfips' ="091" if `clean_state'=="Wisconsin" & `clean_county'=="Pepin"
	replace `countyfips' ="093" if `clean_state'=="Wisconsin" & `clean_county'=="Pierce"
	replace `countyfips' ="095" if `clean_state'=="Wisconsin" & `clean_county'=="Polk"
	replace `countyfips' ="097" if `clean_state'=="Wisconsin" & `clean_county'=="Portage"
	replace `countyfips' ="099" if `clean_state'=="Wisconsin" & `clean_county'=="Price"
	replace `countyfips' ="101" if `clean_state'=="Wisconsin" & `clean_county'=="Racine"
	replace `countyfips' ="103" if `clean_state'=="Wisconsin" & `clean_county'=="Richland"
	replace `countyfips' ="105" if `clean_state'=="Wisconsin" & `clean_county'=="Rock"
	replace `countyfips' ="107" if `clean_state'=="Wisconsin" & `clean_county'=="Rusk"
	replace `countyfips' ="109" if `clean_state'=="Wisconsin" & `clean_county'=="St Croix"
	replace `countyfips' ="111" if `clean_state'=="Wisconsin" & `clean_county'=="Sauk"
	replace `countyfips' ="113" if `clean_state'=="Wisconsin" & `clean_county'=="Sawyer"
	replace `countyfips' ="115" if `clean_state'=="Wisconsin" & `clean_county'=="Shawano"
	replace `countyfips' ="117" if `clean_state'=="Wisconsin" & `clean_county'=="Sheboygan"
	replace `countyfips' ="119" if `clean_state'=="Wisconsin" & `clean_county'=="Taylor"
	replace `countyfips' ="121" if `clean_state'=="Wisconsin" & `clean_county'=="Trempealeau"
	replace `countyfips' ="123" if `clean_state'=="Wisconsin" & `clean_county'=="Vernon"
	replace `countyfips' ="125" if `clean_state'=="Wisconsin" & `clean_county'=="Vilas"
	replace `countyfips' ="127" if `clean_state'=="Wisconsin" & `clean_county'=="Walworth"
	replace `countyfips' ="129" if `clean_state'=="Wisconsin" & `clean_county'=="Washburn"
	replace `countyfips' ="131" if `clean_state'=="Wisconsin" & `clean_county'=="Washington"
	replace `countyfips' ="133" if `clean_state'=="Wisconsin" & `clean_county'=="Waukesha"
	replace `countyfips' ="135" if `clean_state'=="Wisconsin" & `clean_county'=="Waupaca"
	replace `countyfips' ="137" if `clean_state'=="Wisconsin" & `clean_county'=="Waushara"
	replace `countyfips' ="139" if `clean_state'=="Wisconsin" & `clean_county'=="Winnebago"
	replace `countyfips' ="141" if `clean_state'=="Wisconsin" & `clean_county'=="Wood"
	