	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Alabama" & `clean_county'=="Autauga"
	replace `countyfips' ="003" if `clean_state'=="Alabama" & `clean_county'=="Baldwin"
	replace `countyfips' ="005" if `clean_state'=="Alabama" & `clean_county'=="Barbour"
	replace `countyfips' ="007" if `clean_state'=="Alabama" & `clean_county'=="Bibb"
	replace `countyfips' ="009" if `clean_state'=="Alabama" & `clean_county'=="Blount"
	replace `countyfips' ="011" if `clean_state'=="Alabama" & `clean_county'=="Bullock"
	replace `countyfips' ="013" if `clean_state'=="Alabama" & `clean_county'=="Butler"
	replace `countyfips' ="015" if `clean_state'=="Alabama" & `clean_county'=="Calhoun"
	replace `countyfips' ="017" if `clean_state'=="Alabama" & `clean_county'=="Chambers"
	replace `countyfips' ="019" if `clean_state'=="Alabama" & `clean_county'=="Cherokee"
	replace `countyfips' ="021" if `clean_state'=="Alabama" & `clean_county'=="Chilton"
	replace `countyfips' ="023" if `clean_state'=="Alabama" & `clean_county'=="Choctaw"
	replace `countyfips' ="025" if `clean_state'=="Alabama" & `clean_county'=="Clarke"
	replace `countyfips' ="027" if `clean_state'=="Alabama" & `clean_county'=="Clay"
	replace `countyfips' ="029" if `clean_state'=="Alabama" & `clean_county'=="Cleburne"
	replace `countyfips' ="031" if `clean_state'=="Alabama" & `clean_county'=="Coffee"
	replace `countyfips' ="033" if `clean_state'=="Alabama" & `clean_county'=="Colbert"
	replace `countyfips' ="035" if `clean_state'=="Alabama" & `clean_county'=="Conecuh"
	replace `countyfips' ="037" if `clean_state'=="Alabama" & `clean_county'=="Coosa"
	replace `countyfips' ="039" if `clean_state'=="Alabama" & `clean_county'=="Covington"
	replace `countyfips' ="041" if `clean_state'=="Alabama" & `clean_county'=="Crenshaw"
	replace `countyfips' ="043" if `clean_state'=="Alabama" & `clean_county'=="Cullman"
	replace `countyfips' ="045" if `clean_state'=="Alabama" & `clean_county'=="Dale"
	replace `countyfips' ="047" if `clean_state'=="Alabama" & `clean_county'=="Dallas"
	replace `countyfips' ="049" if `clean_state'=="Alabama" & `clean_county'=="De Kalb"
	replace `countyfips' ="051" if `clean_state'=="Alabama" & `clean_county'=="Elmore"
	replace `countyfips' ="053" if `clean_state'=="Alabama" & `clean_county'=="Escambia"
	replace `countyfips' ="055" if `clean_state'=="Alabama" & `clean_county'=="Etowah"
	replace `countyfips' ="057" if `clean_state'=="Alabama" & `clean_county'=="Fayette"
	replace `countyfips' ="059" if `clean_state'=="Alabama" & `clean_county'=="Franklin"
	replace `countyfips' ="061" if `clean_state'=="Alabama" & `clean_county'=="Geneva"
	replace `countyfips' ="063" if `clean_state'=="Alabama" & `clean_county'=="Greene"
	replace `countyfips' ="065" if `clean_state'=="Alabama" & `clean_county'=="Hale"
	replace `countyfips' ="067" if `clean_state'=="Alabama" & `clean_county'=="Henry"
	replace `countyfips' ="069" if `clean_state'=="Alabama" & `clean_county'=="Houston"
	replace `countyfips' ="071" if `clean_state'=="Alabama" & `clean_county'=="Jackson"
	replace `countyfips' ="073" if `clean_state'=="Alabama" & `clean_county'=="Jefferson"
	replace `countyfips' ="075" if `clean_state'=="Alabama" & `clean_county'=="Lamar"
	replace `countyfips' ="077" if `clean_state'=="Alabama" & `clean_county'=="Lauderdale"
	replace `countyfips' ="079" if `clean_state'=="Alabama" & `clean_county'=="Lawrence"
	replace `countyfips' ="081" if `clean_state'=="Alabama" & `clean_county'=="Lee"
	replace `countyfips' ="083" if `clean_state'=="Alabama" & `clean_county'=="Limestone"
	replace `countyfips' ="085" if `clean_state'=="Alabama" & `clean_county'=="Lowndes"
	replace `countyfips' ="087" if `clean_state'=="Alabama" & `clean_county'=="Macon"
	replace `countyfips' ="089" if `clean_state'=="Alabama" & `clean_county'=="Madison"
	replace `countyfips' ="091" if `clean_state'=="Alabama" & `clean_county'=="Marengo"
	replace `countyfips' ="093" if `clean_state'=="Alabama" & `clean_county'=="Marion"
	replace `countyfips' ="095" if `clean_state'=="Alabama" & `clean_county'=="Marshall"
	replace `countyfips' ="097" if `clean_state'=="Alabama" & `clean_county'=="Mobile"
	replace `countyfips' ="099" if `clean_state'=="Alabama" & `clean_county'=="Monroe"
	replace `countyfips' ="101" if `clean_state'=="Alabama" & `clean_county'=="Montgomery"
	replace `countyfips' ="103" if `clean_state'=="Alabama" & `clean_county'=="Morgan"
	replace `countyfips' ="105" if `clean_state'=="Alabama" & `clean_county'=="Perry"
	replace `countyfips' ="107" if `clean_state'=="Alabama" & `clean_county'=="Pickens"
	replace `countyfips' ="109" if `clean_state'=="Alabama" & `clean_county'=="Pike"
	replace `countyfips' ="111" if `clean_state'=="Alabama" & `clean_county'=="Randolph"
	replace `countyfips' ="113" if `clean_state'=="Alabama" & `clean_county'=="Russell"
	replace `countyfips' ="115" if `clean_state'=="Alabama" & `clean_county'=="St Clair"
	replace `countyfips' ="117" if `clean_state'=="Alabama" & `clean_county'=="Shelby"
	replace `countyfips' ="119" if `clean_state'=="Alabama" & `clean_county'=="Sumter"
	replace `countyfips' ="121" if `clean_state'=="Alabama" & `clean_county'=="Talladega"
	replace `countyfips' ="123" if `clean_state'=="Alabama" & `clean_county'=="Tallapoosa"
	replace `countyfips' ="125" if `clean_state'=="Alabama" & `clean_county'=="Tuscaloosa"
	replace `countyfips' ="127" if `clean_state'=="Alabama" & `clean_county'=="Walker"
	replace `countyfips' ="129" if `clean_state'=="Alabama" & `clean_county'=="Washington"
	replace `countyfips' ="131" if `clean_state'=="Alabama" & `clean_county'=="Wilcox"
	replace `countyfips' ="133" if `clean_state'=="Alabama" & `clean_county'=="Winston"

	