	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="New York" & `clean_county'=="Albany"
	replace `countyfips' ="003" if `clean_state'=="New York" & `clean_county'=="Allegany"
	replace `countyfips' ="005" if `clean_state'=="New York" & `clean_county'=="Bronx"
	replace `countyfips' ="007" if `clean_state'=="New York" & `clean_county'=="Broome"
	replace `countyfips' ="009" if `clean_state'=="New York" & `clean_county'=="Cattaraugus"
	replace `countyfips' ="011" if `clean_state'=="New York" & `clean_county'=="Cayuga"
	replace `countyfips' ="013" if `clean_state'=="New York" & `clean_county'=="Chautauqua"
	replace `countyfips' ="015" if `clean_state'=="New York" & `clean_county'=="Chemung"
	replace `countyfips' ="017" if `clean_state'=="New York" & `clean_county'=="Chenango"
	replace `countyfips' ="019" if `clean_state'=="New York" & `clean_county'=="Clinton"
	replace `countyfips' ="021" if `clean_state'=="New York" & `clean_county'=="Columbia"
	replace `countyfips' ="023" if `clean_state'=="New York" & `clean_county'=="Cortland"
	replace `countyfips' ="025" if `clean_state'=="New York" & `clean_county'=="Delaware"
	replace `countyfips' ="027" if `clean_state'=="New York" & `clean_county'=="Dutchess"
	replace `countyfips' ="029" if `clean_state'=="New York" & `clean_county'=="Erie"
	replace `countyfips' ="031" if `clean_state'=="New York" & `clean_county'=="Essex"
	replace `countyfips' ="033" if `clean_state'=="New York" & `clean_county'=="Franklin"
	replace `countyfips' ="035" if `clean_state'=="New York" & `clean_county'=="Fulton"
	replace `countyfips' ="037" if `clean_state'=="New York" & `clean_county'=="Genesee"
	replace `countyfips' ="039" if `clean_state'=="New York" & `clean_county'=="Greene"
	replace `countyfips' ="041" if `clean_state'=="New York" & `clean_county'=="Hamilton"
	replace `countyfips' ="043" if `clean_state'=="New York" & `clean_county'=="Herkimer"
	replace `countyfips' ="045" if `clean_state'=="New York" & `clean_county'=="Jefferson"
	replace `countyfips' ="047" if `clean_state'=="New York" & `clean_county'=="Kings"
	replace `countyfips' ="049" if `clean_state'=="New York" & `clean_county'=="Lewis"
	replace `countyfips' ="051" if `clean_state'=="New York" & `clean_county'=="Livingston"
	replace `countyfips' ="053" if `clean_state'=="New York" & `clean_county'=="Madison"
	replace `countyfips' ="055" if `clean_state'=="New York" & `clean_county'=="Monroe"
	replace `countyfips' ="057" if `clean_state'=="New York" & `clean_county'=="Montgomery"
	replace `countyfips' ="059" if `clean_state'=="New York" & `clean_county'=="Nassau"
	replace `countyfips' ="061" if `clean_state'=="New York" & `clean_county'=="New York"
	replace `countyfips' ="063" if `clean_state'=="New York" & `clean_county'=="Niagara"
	replace `countyfips' ="065" if `clean_state'=="New York" & `clean_county'=="Oneida"
	replace `countyfips' ="067" if `clean_state'=="New York" & `clean_county'=="Onondaga"
	replace `countyfips' ="069" if `clean_state'=="New York" & `clean_county'=="Ontario"
	replace `countyfips' ="071" if `clean_state'=="New York" & `clean_county'=="Orange"
	replace `countyfips' ="073" if `clean_state'=="New York" & `clean_county'=="Orleans"
	replace `countyfips' ="075" if `clean_state'=="New York" & `clean_county'=="Oswego"
	replace `countyfips' ="077" if `clean_state'=="New York" & `clean_county'=="Otsego"
	replace `countyfips' ="079" if `clean_state'=="New York" & `clean_county'=="Putnam"
	replace `countyfips' ="081" if `clean_state'=="New York" & `clean_county'=="Queens"
	replace `countyfips' ="083" if `clean_state'=="New York" & `clean_county'=="Rensselaer"
	replace `countyfips' ="085" if `clean_state'=="New York" & `clean_county'=="Richmond"
	replace `countyfips' ="087" if `clean_state'=="New York" & `clean_county'=="Rockland"
	replace `countyfips' ="089" if `clean_state'=="New York" & `clean_county'=="St Lawrence"
	replace `countyfips' ="089" if `clean_state'=="New York" & `clean_county'=="St. Lawrence"
	replace `countyfips' ="091" if `clean_state'=="New York" & `clean_county'=="Saratoga"
	replace `countyfips' ="093" if `clean_state'=="New York" & `clean_county'=="Schenectady"
	replace `countyfips' ="095" if `clean_state'=="New York" & `clean_county'=="Schoharie"
	replace `countyfips' ="097" if `clean_state'=="New York" & `clean_county'=="Schuyler"
	replace `countyfips' ="099" if `clean_state'=="New York" & `clean_county'=="Seneca"
	replace `countyfips' ="101" if `clean_state'=="New York" & `clean_county'=="Steuben"
	replace `countyfips' ="103" if `clean_state'=="New York" & `clean_county'=="Suffolk"
	replace `countyfips' ="105" if `clean_state'=="New York" & `clean_county'=="Sullivan"
	replace `countyfips' ="107" if `clean_state'=="New York" & `clean_county'=="Tioga"
	replace `countyfips' ="109" if `clean_state'=="New York" & `clean_county'=="Tompkins"
	replace `countyfips' ="111" if `clean_state'=="New York" & `clean_county'=="Ulster"
	replace `countyfips' ="113" if `clean_state'=="New York" & `clean_county'=="Warren"
	replace `countyfips' ="115" if `clean_state'=="New York" & `clean_county'=="Washington"
	replace `countyfips' ="117" if `clean_state'=="New York" & `clean_county'=="Wayne"
	replace `countyfips' ="119" if `clean_state'=="New York" & `clean_county'=="Westchester"
	replace `countyfips' ="121" if `clean_state'=="New York" & `clean_county'=="Wyoming"
	replace `countyfips' ="123" if `clean_state'=="New York" & `clean_county'=="Yates"
	