	args countyfips clean_county clean_state


	replace `countyfips' ="003" if `clean_state'=="South Dakota" & `clean_county'=="Aurora"
	replace `countyfips' ="005" if `clean_state'=="South Dakota" & `clean_county'=="Beadle"
	replace `countyfips' ="007" if `clean_state'=="South Dakota" & `clean_county'=="Bennett"
	replace `countyfips' ="009" if `clean_state'=="South Dakota" & `clean_county'=="Bon Homme"
	replace `countyfips' ="011" if `clean_state'=="South Dakota" & `clean_county'=="Brookings"
	replace `countyfips' ="013" if `clean_state'=="South Dakota" & `clean_county'=="Brown"
	replace `countyfips' ="015" if `clean_state'=="South Dakota" & `clean_county'=="Brule"
	replace `countyfips' ="017" if `clean_state'=="South Dakota" & `clean_county'=="Buffalo"
	replace `countyfips' ="019" if `clean_state'=="South Dakota" & `clean_county'=="Butte"
	replace `countyfips' ="021" if `clean_state'=="South Dakota" & `clean_county'=="Campbell"
	replace `countyfips' ="023" if `clean_state'=="South Dakota" & `clean_county'=="Charles Mix"
	replace `countyfips' ="025" if `clean_state'=="South Dakota" & `clean_county'=="Clark"
	replace `countyfips' ="027" if `clean_state'=="South Dakota" & `clean_county'=="Clay"
	replace `countyfips' ="029" if `clean_state'=="South Dakota" & `clean_county'=="Codington"
	replace `countyfips' ="031" if `clean_state'=="South Dakota" & `clean_county'=="Corson"
	replace `countyfips' ="033" if `clean_state'=="South Dakota" & `clean_county'=="Custer"
	replace `countyfips' ="035" if `clean_state'=="South Dakota" & `clean_county'=="Davison"
	replace `countyfips' ="037" if `clean_state'=="South Dakota" & `clean_county'=="Day"
	replace `countyfips' ="039" if `clean_state'=="South Dakota" & `clean_county'=="Deuel"
	replace `countyfips' ="041" if `clean_state'=="South Dakota" & `clean_county'=="Dewey"
	replace `countyfips' ="043" if `clean_state'=="South Dakota" & `clean_county'=="Douglas"
	replace `countyfips' ="045" if `clean_state'=="South Dakota" & `clean_county'=="Edmunds"
	replace `countyfips' ="047" if `clean_state'=="South Dakota" & `clean_county'=="Fall River"
	replace `countyfips' ="049" if `clean_state'=="South Dakota" & `clean_county'=="Faulk"
	replace `countyfips' ="051" if `clean_state'=="South Dakota" & `clean_county'=="Grant"
	replace `countyfips' ="053" if `clean_state'=="South Dakota" & `clean_county'=="Gregory"
	replace `countyfips' ="055" if `clean_state'=="South Dakota" & `clean_county'=="Haakon"
	replace `countyfips' ="057" if `clean_state'=="South Dakota" & `clean_county'=="Hamlin"
	replace `countyfips' ="059" if `clean_state'=="South Dakota" & `clean_county'=="Hand"
	replace `countyfips' ="061" if `clean_state'=="South Dakota" & `clean_county'=="Hanson"
	replace `countyfips' ="063" if `clean_state'=="South Dakota" & `clean_county'=="Harding"
	replace `countyfips' ="065" if `clean_state'=="South Dakota" & `clean_county'=="Hughes"
	replace `countyfips' ="067" if `clean_state'=="South Dakota" & `clean_county'=="Hutchinson"
	replace `countyfips' ="069" if `clean_state'=="South Dakota" & `clean_county'=="Hyde"
	replace `countyfips' ="071" if `clean_state'=="South Dakota" & `clean_county'=="Jackson"
	replace `countyfips' ="073" if `clean_state'=="South Dakota" & `clean_county'=="Jerauld"
	replace `countyfips' ="075" if `clean_state'=="South Dakota" & `clean_county'=="Jones"
	replace `countyfips' ="077" if `clean_state'=="South Dakota" & `clean_county'=="Kingsbury"
	replace `countyfips' ="079" if `clean_state'=="South Dakota" & `clean_county'=="Lake"
	replace `countyfips' ="081" if `clean_state'=="South Dakota" & `clean_county'=="Lawrence"
	replace `countyfips' ="083" if `clean_state'=="South Dakota" & `clean_county'=="Lincoln"
	replace `countyfips' ="085" if `clean_state'=="South Dakota" & `clean_county'=="Lyman"
	replace `countyfips' ="087" if `clean_state'=="South Dakota" & `clean_county'=="McCook"
	replace `countyfips' ="089" if `clean_state'=="South Dakota" & `clean_county'=="McPherson"
	replace `countyfips' ="091" if `clean_state'=="South Dakota" & `clean_county'=="Marshall"
	replace `countyfips' ="093" if `clean_state'=="South Dakota" & `clean_county'=="Meade"
	replace `countyfips' ="095" if `clean_state'=="South Dakota" & `clean_county'=="Mellette"
	replace `countyfips' ="097" if `clean_state'=="South Dakota" & `clean_county'=="Miner"
	replace `countyfips' ="099" if `clean_state'=="South Dakota" & `clean_county'=="Minnehaha"
	replace `countyfips' ="101" if `clean_state'=="South Dakota" & `clean_county'=="Moody"
	replace `countyfips' ="103" if `clean_state'=="South Dakota" & `clean_county'=="Pennington"
	replace `countyfips' ="105" if `clean_state'=="South Dakota" & `clean_county'=="Perkins"
	replace `countyfips' ="107" if `clean_state'=="South Dakota" & `clean_county'=="Potter"
	replace `countyfips' ="109" if `clean_state'=="South Dakota" & `clean_county'=="Roberts"
	replace `countyfips' ="111" if `clean_state'=="South Dakota" & `clean_county'=="Sanborn"
	replace `countyfips' ="113" if `clean_state'=="South Dakota" & `clean_county'=="Shannon"
	replace `countyfips' ="115" if `clean_state'=="South Dakota" & `clean_county'=="Spink"
	replace `countyfips' ="117" if `clean_state'=="South Dakota" & `clean_county'=="Stanley"
	replace `countyfips' ="119" if `clean_state'=="South Dakota" & `clean_county'=="Sully"
	replace `countyfips' ="121" if `clean_state'=="South Dakota" & `clean_county'=="Todd"
	replace `countyfips' ="123" if `clean_state'=="South Dakota" & `clean_county'=="Tripp"
	replace `countyfips' ="125" if `clean_state'=="South Dakota" & `clean_county'=="Turner"
	replace `countyfips' ="127" if `clean_state'=="South Dakota" & `clean_county'=="Union"
	replace `countyfips' ="129" if `clean_state'=="South Dakota" & `clean_county'=="Walworth"
	replace `countyfips' ="135" if `clean_state'=="South Dakota" & `clean_county'=="Yankton"
	replace `countyfips' ="137" if `clean_state'=="South Dakota" & `clean_county'=="Ziebach"
	