	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Utah" & `clean_county'=="Beaver"
	replace `countyfips' ="003" if `clean_state'=="Utah" & `clean_county'=="Box Elder"
	replace `countyfips' ="005" if `clean_state'=="Utah" & `clean_county'=="Cache"
	replace `countyfips' ="007" if `clean_state'=="Utah" & `clean_county'=="Carbon"
	replace `countyfips' ="009" if `clean_state'=="Utah" & `clean_county'=="Daggett"
	replace `countyfips' ="011" if `clean_state'=="Utah" & `clean_county'=="Davis"
	replace `countyfips' ="013" if `clean_state'=="Utah" & `clean_county'=="Duchesne"
	replace `countyfips' ="015" if `clean_state'=="Utah" & `clean_county'=="Emery"
	replace `countyfips' ="017" if `clean_state'=="Utah" & `clean_county'=="Garfield"
	replace `countyfips' ="019" if `clean_state'=="Utah" & `clean_county'=="Grand"
	replace `countyfips' ="021" if `clean_state'=="Utah" & `clean_county'=="Iron"
	replace `countyfips' ="023" if `clean_state'=="Utah" & `clean_county'=="Juab"
	replace `countyfips' ="025" if `clean_state'=="Utah" & `clean_county'=="Kane"
	replace `countyfips' ="027" if `clean_state'=="Utah" & `clean_county'=="Millard"
	replace `countyfips' ="029" if `clean_state'=="Utah" & `clean_county'=="Morgan"
	replace `countyfips' ="031" if `clean_state'=="Utah" & `clean_county'=="Piute"
	replace `countyfips' ="033" if `clean_state'=="Utah" & `clean_county'=="Rich"
	replace `countyfips' ="035" if `clean_state'=="Utah" & `clean_county'=="Salt Lake"
	replace `countyfips' ="037" if `clean_state'=="Utah" & `clean_county'=="San Juan"
	replace `countyfips' ="039" if `clean_state'=="Utah" & `clean_county'=="Sanpete"
	replace `countyfips' ="041" if `clean_state'=="Utah" & `clean_county'=="Sevier"
	replace `countyfips' ="043" if `clean_state'=="Utah" & `clean_county'=="Summit"
	replace `countyfips' ="045" if `clean_state'=="Utah" & `clean_county'=="Tooele"
	replace `countyfips' ="047" if `clean_state'=="Utah" & `clean_county'=="Uintah"
	replace `countyfips' ="049" if `clean_state'=="Utah" & `clean_county'=="Utah"
	replace `countyfips' ="051" if `clean_state'=="Utah" & `clean_county'=="Wasatch"
	replace `countyfips' ="053" if `clean_state'=="Utah" & `clean_county'=="Washington"
	replace `countyfips' ="055" if `clean_state'=="Utah" & `clean_county'=="Wayne"
	replace `countyfips' ="057" if `clean_state'=="Utah" & `clean_county'=="Weber"
	
	