	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="California" & `clean_county'=="Alameda"
	replace `countyfips' ="003" if `clean_state'=="California" & `clean_county'=="Alpine"
	replace `countyfips' ="005" if `clean_state'=="California" & `clean_county'=="Amador"
	replace `countyfips' ="007" if `clean_state'=="California" & `clean_county'=="Butte"
	replace `countyfips' ="009" if `clean_state'=="California" & `clean_county'=="Calaveras"
	replace `countyfips' ="011" if `clean_state'=="California" & `clean_county'=="Colusa"
	replace `countyfips' ="013" if `clean_state'=="California" & `clean_county'=="Contra Costa"
	replace `countyfips' ="015" if `clean_state'=="California" & `clean_county'=="Del Norte"
	replace `countyfips' ="017" if `clean_state'=="California" & `clean_county'=="El Dorado"
	replace `countyfips' ="019" if `clean_state'=="California" & `clean_county'=="Fresno"
	replace `countyfips' ="021" if `clean_state'=="California" & `clean_county'=="Glenn"
	replace `countyfips' ="023" if `clean_state'=="California" & `clean_county'=="Humboldt"
	replace `countyfips' ="025" if `clean_state'=="California" & `clean_county'=="Imperial"
	replace `countyfips' ="027" if `clean_state'=="California" & `clean_county'=="Inyo"
	replace `countyfips' ="029" if `clean_state'=="California" & `clean_county'=="Kern"
	replace `countyfips' ="031" if `clean_state'=="California" & `clean_county'=="Kings"
	replace `countyfips' ="033" if `clean_state'=="California" & `clean_county'=="Lake"
	replace `countyfips' ="035" if `clean_state'=="California" & `clean_county'=="Lassen"
	replace `countyfips' ="037" if `clean_state'=="California" & `clean_county'=="Los Angeles"
	replace `countyfips' ="039" if `clean_state'=="California" & `clean_county'=="Madera"
	replace `countyfips' ="041" if `clean_state'=="California" & `clean_county'=="Marin"
	replace `countyfips' ="043" if `clean_state'=="California" & `clean_county'=="Mariposa"
	replace `countyfips' ="045" if `clean_state'=="California" & `clean_county'=="Mendocino"
	replace `countyfips' ="047" if `clean_state'=="California" & `clean_county'=="Merced"
	replace `countyfips' ="049" if `clean_state'=="California" & `clean_county'=="Modoc"
	replace `countyfips' ="051" if `clean_state'=="California" & `clean_county'=="Mono"
	replace `countyfips' ="053" if `clean_state'=="California" & `clean_county'=="Monterey"
	replace `countyfips' ="055" if `clean_state'=="California" & `clean_county'=="Napa"
	replace `countyfips' ="057" if `clean_state'=="California" & `clean_county'=="Nevada"
	replace `countyfips' ="059" if `clean_state'=="California" & `clean_county'=="Orange"
	replace `countyfips' ="061" if `clean_state'=="California" & `clean_county'=="Placer"
	replace `countyfips' ="063" if `clean_state'=="California" & `clean_county'=="Plumas"
	replace `countyfips' ="065" if `clean_state'=="California" & `clean_county'=="Riverside"
	replace `countyfips' ="067" if `clean_state'=="California" & `clean_county'=="Sacramento"
	replace `countyfips' ="069" if `clean_state'=="California" & `clean_county'=="San Benito"
	replace `countyfips' ="071" if `clean_state'=="California" & `clean_county'=="San Bernardino"
	replace `countyfips' ="073" if `clean_state'=="California" & `clean_county'=="San Diego"
	replace `countyfips' ="075" if `clean_state'=="California" & `clean_county'=="San Francisco"
	replace `countyfips' ="077" if `clean_state'=="California" & `clean_county'=="San Joaquin"
	replace `countyfips' ="079" if `clean_state'=="California" & `clean_county'=="San Luis Obispo"
	replace `countyfips' ="081" if `clean_state'=="California" & `clean_county'=="San Mateo"
	replace `countyfips' ="083" if `clean_state'=="California" & `clean_county'=="Santa Barbara"
	replace `countyfips' ="085" if `clean_state'=="California" & `clean_county'=="Santa Clara"
	replace `countyfips' ="087" if `clean_state'=="California" & `clean_county'=="Santa Cruz"
	replace `countyfips' ="089" if `clean_state'=="California" & `clean_county'=="Shasta"
	replace `countyfips' ="091" if `clean_state'=="California" & `clean_county'=="Sierra"
	replace `countyfips' ="093" if `clean_state'=="California" & `clean_county'=="Siskiyou"
	replace `countyfips' ="095" if `clean_state'=="California" & `clean_county'=="Solano"
	replace `countyfips' ="097" if `clean_state'=="California" & `clean_county'=="Sonoma"
	replace `countyfips' ="099" if `clean_state'=="California" & `clean_county'=="Stanislaus"
	replace `countyfips' ="101" if `clean_state'=="California" & `clean_county'=="Sutter"
	replace `countyfips' ="103" if `clean_state'=="California" & `clean_county'=="Tehama"
	replace `countyfips' ="105" if `clean_state'=="California" & `clean_county'=="Trinity"
	replace `countyfips' ="107" if `clean_state'=="California" & `clean_county'=="Tulare"
	replace `countyfips' ="109" if `clean_state'=="California" & `clean_county'=="Tuolumne"
	replace `countyfips' ="111" if `clean_state'=="California" & `clean_county'=="Ventura"
	replace `countyfips' ="113" if `clean_state'=="California" & `clean_county'=="Yolo"
	replace `countyfips' ="115" if `clean_state'=="California" & `clean_county'=="Yuba"
	