	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Michigan" & `clean_county'=="Alcona"
	replace `countyfips' ="003" if `clean_state'=="Michigan" & `clean_county'=="Alger"
	replace `countyfips' ="005" if `clean_state'=="Michigan" & `clean_county'=="Allegan"
	replace `countyfips' ="007" if `clean_state'=="Michigan" & `clean_county'=="Alpena"
	replace `countyfips' ="009" if `clean_state'=="Michigan" & `clean_county'=="Antrim"
	replace `countyfips' ="011" if `clean_state'=="Michigan" & `clean_county'=="Arenac"
	replace `countyfips' ="013" if `clean_state'=="Michigan" & `clean_county'=="Baraga"
	replace `countyfips' ="015" if `clean_state'=="Michigan" & `clean_county'=="Barry"
	replace `countyfips' ="017" if `clean_state'=="Michigan" & `clean_county'=="Bay"
	replace `countyfips' ="019" if `clean_state'=="Michigan" & `clean_county'=="Benzie"
	replace `countyfips' ="021" if `clean_state'=="Michigan" & `clean_county'=="Berrien"
	replace `countyfips' ="023" if `clean_state'=="Michigan" & `clean_county'=="Branch"
	replace `countyfips' ="025" if `clean_state'=="Michigan" & `clean_county'=="Calhoun"
	replace `countyfips' ="027" if `clean_state'=="Michigan" & `clean_county'=="Cass"
	replace `countyfips' ="029" if `clean_state'=="Michigan" & `clean_county'=="Charlevoix"
	replace `countyfips' ="031" if `clean_state'=="Michigan" & `clean_county'=="Cheboygan"
	replace `countyfips' ="033" if `clean_state'=="Michigan" & `clean_county'=="Chippewa"
	replace `countyfips' ="035" if `clean_state'=="Michigan" & `clean_county'=="Clare"
	replace `countyfips' ="037" if `clean_state'=="Michigan" & `clean_county'=="Clinton"
	replace `countyfips' ="039" if `clean_state'=="Michigan" & `clean_county'=="Crawford"
	replace `countyfips' ="041" if `clean_state'=="Michigan" & `clean_county'=="Delta"
	replace `countyfips' ="043" if `clean_state'=="Michigan" & `clean_county'=="Dickinson"
	replace `countyfips' ="045" if `clean_state'=="Michigan" & `clean_county'=="Eaton"
	replace `countyfips' ="047" if `clean_state'=="Michigan" & `clean_county'=="Emmet"
	replace `countyfips' ="049" if `clean_state'=="Michigan" & `clean_county'=="Genesee"
	replace `countyfips' ="051" if `clean_state'=="Michigan" & `clean_county'=="Gladwin"
	replace `countyfips' ="053" if `clean_state'=="Michigan" & `clean_county'=="Gogebic"
	replace `countyfips' ="055" if `clean_state'=="Michigan" & `clean_county'=="Grand Traverse"
	replace `countyfips' ="057" if `clean_state'=="Michigan" & `clean_county'=="Gratiot"
	replace `countyfips' ="059" if `clean_state'=="Michigan" & `clean_county'=="Hillsdale"
	replace `countyfips' ="061" if `clean_state'=="Michigan" & `clean_county'=="Houghton"
	replace `countyfips' ="063" if `clean_state'=="Michigan" & `clean_county'=="Huron"
	replace `countyfips' ="065" if `clean_state'=="Michigan" & `clean_county'=="Ingham"
	replace `countyfips' ="067" if `clean_state'=="Michigan" & `clean_county'=="Ionia"
	replace `countyfips' ="069" if `clean_state'=="Michigan" & `clean_county'=="Iosco"
	replace `countyfips' ="071" if `clean_state'=="Michigan" & `clean_county'=="Iron"
	replace `countyfips' ="073" if `clean_state'=="Michigan" & `clean_county'=="Isabella"
	replace `countyfips' ="075" if `clean_state'=="Michigan" & `clean_county'=="Jackson"
	replace `countyfips' ="077" if `clean_state'=="Michigan" & `clean_county'=="Kalamazoo"
	replace `countyfips' ="079" if `clean_state'=="Michigan" & `clean_county'=="Kalkaska"
	replace `countyfips' ="081" if `clean_state'=="Michigan" & `clean_county'=="Kent"
	replace `countyfips' ="083" if `clean_state'=="Michigan" & `clean_county'=="Keweenaw"
	replace `countyfips' ="085" if `clean_state'=="Michigan" & `clean_county'=="Lake"
	replace `countyfips' ="087" if `clean_state'=="Michigan" & `clean_county'=="Lapeer"
	replace `countyfips' ="089" if `clean_state'=="Michigan" & `clean_county'=="Leelanau"
	replace `countyfips' ="091" if `clean_state'=="Michigan" & `clean_county'=="Lenawee"
	replace `countyfips' ="093" if `clean_state'=="Michigan" & `clean_county'=="Livingston"
	replace `countyfips' ="095" if `clean_state'=="Michigan" & `clean_county'=="Luce"
	replace `countyfips' ="097" if `clean_state'=="Michigan" & `clean_county'=="Mackinac"
	replace `countyfips' ="099" if `clean_state'=="Michigan" & `clean_county'=="Macomb"
	replace `countyfips' ="101" if `clean_state'=="Michigan" & `clean_county'=="Manistee"
	replace `countyfips' ="103" if `clean_state'=="Michigan" & `clean_county'=="Marquette"
	replace `countyfips' ="105" if `clean_state'=="Michigan" & `clean_county'=="Mason"
	replace `countyfips' ="107" if `clean_state'=="Michigan" & `clean_county'=="Mecosta"
	replace `countyfips' ="109" if `clean_state'=="Michigan" & `clean_county'=="Menominee"
	replace `countyfips' ="111" if `clean_state'=="Michigan" & `clean_county'=="Midland"
	replace `countyfips' ="113" if `clean_state'=="Michigan" & `clean_county'=="Missaukee"
	replace `countyfips' ="115" if `clean_state'=="Michigan" & `clean_county'=="Monroe"
	replace `countyfips' ="117" if `clean_state'=="Michigan" & `clean_county'=="Montcalm"
	replace `countyfips' ="119" if `clean_state'=="Michigan" & `clean_county'=="Montmorency"
	replace `countyfips' ="121" if `clean_state'=="Michigan" & `clean_county'=="Muskegon"
	replace `countyfips' ="123" if `clean_state'=="Michigan" & `clean_county'=="Newaygo"
	replace `countyfips' ="125" if `clean_state'=="Michigan" & `clean_county'=="Oakland"
	replace `countyfips' ="127" if `clean_state'=="Michigan" & `clean_county'=="Oceana"
	replace `countyfips' ="129" if `clean_state'=="Michigan" & `clean_county'=="Ogemaw"
	replace `countyfips' ="131" if `clean_state'=="Michigan" & `clean_county'=="Ontonagon"
	replace `countyfips' ="133" if `clean_state'=="Michigan" & `clean_county'=="Osceola"
	replace `countyfips' ="135" if `clean_state'=="Michigan" & `clean_county'=="Oscoda"
	replace `countyfips' ="137" if `clean_state'=="Michigan" & `clean_county'=="Otsego"
	replace `countyfips' ="139" if `clean_state'=="Michigan" & `clean_county'=="Ottawa"
	replace `countyfips' ="141" if `clean_state'=="Michigan" & `clean_county'=="Presque Isle"
	replace `countyfips' ="143" if `clean_state'=="Michigan" & `clean_county'=="Roscommon"
	replace `countyfips' ="145" if `clean_state'=="Michigan" & `clean_county'=="Saginaw"
	replace `countyfips' ="147" if `clean_state'=="Michigan" & `clean_county'=="St Clair"
	replace `countyfips' ="149" if `clean_state'=="Michigan" & `clean_county'=="St Joseph"
	replace `countyfips' ="147" if `clean_state'=="Michigan" & `clean_county'=="St. Clair"
	replace `countyfips' ="149" if `clean_state'=="Michigan" & `clean_county'=="St. Joseph"
	replace `countyfips' ="151" if `clean_state'=="Michigan" & `clean_county'=="Sanilac"
	replace `countyfips' ="153" if `clean_state'=="Michigan" & `clean_county'=="Schoolcraft"
	replace `countyfips' ="155" if `clean_state'=="Michigan" & `clean_county'=="Shiawassee"
	replace `countyfips' ="157" if `clean_state'=="Michigan" & `clean_county'=="Tuscola"
	replace `countyfips' ="159" if `clean_state'=="Michigan" & `clean_county'=="Van Buren"
	replace `countyfips' ="161" if `clean_state'=="Michigan" & `clean_county'=="Washtenaw"
	replace `countyfips' ="163" if `clean_state'=="Michigan" & `clean_county'=="Wayne"
	replace `countyfips' ="165" if `clean_state'=="Michigan" & `clean_county'=="Wexford"
	