	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Idaho" & `clean_county'=="Ada"
	replace `countyfips' ="003" if `clean_state'=="Idaho" & `clean_county'=="Adams"
	replace `countyfips' ="005" if `clean_state'=="Idaho" & `clean_county'=="Bannock"
	replace `countyfips' ="007" if `clean_state'=="Idaho" & `clean_county'=="Bear Lake"
	replace `countyfips' ="009" if `clean_state'=="Idaho" & `clean_county'=="Benewah"
	replace `countyfips' ="011" if `clean_state'=="Idaho" & `clean_county'=="Bingham"
	replace `countyfips' ="013" if `clean_state'=="Idaho" & `clean_county'=="Blaine"
	replace `countyfips' ="015" if `clean_state'=="Idaho" & `clean_county'=="Boise"
	replace `countyfips' ="017" if `clean_state'=="Idaho" & `clean_county'=="Bonner"
	replace `countyfips' ="019" if `clean_state'=="Idaho" & `clean_county'=="Bonneville"
	replace `countyfips' ="021" if `clean_state'=="Idaho" & `clean_county'=="Boundary"
	replace `countyfips' ="023" if `clean_state'=="Idaho" & `clean_county'=="Butte"
	replace `countyfips' ="025" if `clean_state'=="Idaho" & `clean_county'=="Camas"
	replace `countyfips' ="027" if `clean_state'=="Idaho" & `clean_county'=="Canyon"
	replace `countyfips' ="029" if `clean_state'=="Idaho" & `clean_county'=="Caribou"
	replace `countyfips' ="031" if `clean_state'=="Idaho" & `clean_county'=="Cassia"
	replace `countyfips' ="033" if `clean_state'=="Idaho" & `clean_county'=="Clark"
	replace `countyfips' ="035" if `clean_state'=="Idaho" & `clean_county'=="Clearwater"
	replace `countyfips' ="037" if `clean_state'=="Idaho" & `clean_county'=="Custer"
	replace `countyfips' ="039" if `clean_state'=="Idaho" & `clean_county'=="Elmore"
	replace `countyfips' ="041" if `clean_state'=="Idaho" & `clean_county'=="Franklin"
	replace `countyfips' ="043" if `clean_state'=="Idaho" & `clean_county'=="Fremont"
	replace `countyfips' ="045" if `clean_state'=="Idaho" & `clean_county'=="Gem"
	replace `countyfips' ="047" if `clean_state'=="Idaho" & `clean_county'=="Gooding"
	replace `countyfips' ="049" if `clean_state'=="Idaho" & `clean_county'=="Idaho"
	replace `countyfips' ="051" if `clean_state'=="Idaho" & `clean_county'=="Jefferson"
	replace `countyfips' ="053" if `clean_state'=="Idaho" & `clean_county'=="Jerome"
	replace `countyfips' ="055" if `clean_state'=="Idaho" & `clean_county'=="Kootenai"
	replace `countyfips' ="057" if `clean_state'=="Idaho" & `clean_county'=="Latah"
	replace `countyfips' ="059" if `clean_state'=="Idaho" & `clean_county'=="Lemhi"
	replace `countyfips' ="061" if `clean_state'=="Idaho" & `clean_county'=="Lewis"
	replace `countyfips' ="063" if `clean_state'=="Idaho" & `clean_county'=="Lincoln"
	replace `countyfips' ="065" if `clean_state'=="Idaho" & `clean_county'=="Madison"
	replace `countyfips' ="067" if `clean_state'=="Idaho" & `clean_county'=="Minidoka"
	replace `countyfips' ="069" if `clean_state'=="Idaho" & `clean_county'=="Nez Perce"
	replace `countyfips' ="071" if `clean_state'=="Idaho" & `clean_county'=="Oneida"
	replace `countyfips' ="073" if `clean_state'=="Idaho" & `clean_county'=="Owyhee"
	replace `countyfips' ="075" if `clean_state'=="Idaho" & `clean_county'=="Payette"
	replace `countyfips' ="077" if `clean_state'=="Idaho" & `clean_county'=="Power"
	replace `countyfips' ="079" if `clean_state'=="Idaho" & `clean_county'=="Shoshone"
	replace `countyfips' ="081" if `clean_state'=="Idaho" & `clean_county'=="Teton"
	replace `countyfips' ="083" if `clean_state'=="Idaho" & `clean_county'=="Twin Falls"
	replace `countyfips' ="085" if `clean_state'=="Idaho" & `clean_county'=="Valley"
	replace `countyfips' ="087" if `clean_state'=="Idaho" & `clean_county'=="Washington"
	