	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Florida" & `clean_county'=="Alachua"
	replace `countyfips' ="003" if `clean_state'=="Florida" & `clean_county'=="Baker"
	replace `countyfips' ="005" if `clean_state'=="Florida" & `clean_county'=="Bay"
	replace `countyfips' ="007" if `clean_state'=="Florida" & `clean_county'=="Bradford"
	replace `countyfips' ="009" if `clean_state'=="Florida" & `clean_county'=="Brevard"
	replace `countyfips' ="011" if `clean_state'=="Florida" & `clean_county'=="Broward"
	replace `countyfips' ="013" if `clean_state'=="Florida" & `clean_county'=="Calhoun"
	replace `countyfips' ="015" if `clean_state'=="Florida" & `clean_county'=="Charlotte"
	replace `countyfips' ="017" if `clean_state'=="Florida" & `clean_county'=="Citrus"
	replace `countyfips' ="019" if `clean_state'=="Florida" & `clean_county'=="Clay"
	replace `countyfips' ="021" if `clean_state'=="Florida" & `clean_county'=="Collier"
	replace `countyfips' ="023" if `clean_state'=="Florida" & `clean_county'=="Columbia"
	replace `countyfips' ="027" if `clean_state'=="Florida" & `clean_county'=="De Soto"
	replace `countyfips' ="029" if `clean_state'=="Florida" & `clean_county'=="Dixie"
	replace `countyfips' ="031" if `clean_state'=="Florida" & `clean_county'=="Duval"
	replace `countyfips' ="033" if `clean_state'=="Florida" & `clean_county'=="Escambia"
	replace `countyfips' ="035" if `clean_state'=="Florida" & `clean_county'=="Flagler"
	replace `countyfips' ="037" if `clean_state'=="Florida" & `clean_county'=="Franklin"
	replace `countyfips' ="039" if `clean_state'=="Florida" & `clean_county'=="Gadsden"
	replace `countyfips' ="041" if `clean_state'=="Florida" & `clean_county'=="Gilchrist"
	replace `countyfips' ="043" if `clean_state'=="Florida" & `clean_county'=="Glades"
	replace `countyfips' ="045" if `clean_state'=="Florida" & `clean_county'=="Gulf"
	replace `countyfips' ="047" if `clean_state'=="Florida" & `clean_county'=="Hamilton"
	replace `countyfips' ="049" if `clean_state'=="Florida" & `clean_county'=="Hardee"
	replace `countyfips' ="051" if `clean_state'=="Florida" & `clean_county'=="Hendry"
	replace `countyfips' ="053" if `clean_state'=="Florida" & `clean_county'=="Hernando"
	replace `countyfips' ="055" if `clean_state'=="Florida" & `clean_county'=="Highlands"
	replace `countyfips' ="057" if `clean_state'=="Florida" & `clean_county'=="Hillsborough"
	replace `countyfips' ="059" if `clean_state'=="Florida" & `clean_county'=="Holmes"
	replace `countyfips' ="061" if `clean_state'=="Florida" & `clean_county'=="Indian River"
	replace `countyfips' ="063" if `clean_state'=="Florida" & `clean_county'=="Jackson"
	replace `countyfips' ="065" if `clean_state'=="Florida" & `clean_county'=="Jefferson"
	replace `countyfips' ="067" if `clean_state'=="Florida" & `clean_county'=="Lafayette"
	replace `countyfips' ="069" if `clean_state'=="Florida" & `clean_county'=="Lake"
	replace `countyfips' ="071" if `clean_state'=="Florida" & `clean_county'=="Lee"
	replace `countyfips' ="073" if `clean_state'=="Florida" & `clean_county'=="Leon"
	replace `countyfips' ="075" if `clean_state'=="Florida" & `clean_county'=="Levy"
	replace `countyfips' ="077" if `clean_state'=="Florida" & `clean_county'=="Liberty"
	replace `countyfips' ="079" if `clean_state'=="Florida" & `clean_county'=="Madison"
	replace `countyfips' ="081" if `clean_state'=="Florida" & `clean_county'=="Manatee"
	replace `countyfips' ="083" if `clean_state'=="Florida" & `clean_county'=="Marion"
	replace `countyfips' ="085" if `clean_state'=="Florida" & `clean_county'=="Martin"
	replace `countyfips' ="086" if `clean_state'=="Florida" & `clean_county'=="Miami-Dade"
	replace `countyfips' ="086" if `clean_state'=="Florida" & `clean_county'=="Dade"
	replace `countyfips' ="087" if `clean_state'=="Florida" & `clean_county'=="Monroe"
	replace `countyfips' ="089" if `clean_state'=="Florida" & `clean_county'=="Nassau"
	replace `countyfips' ="091" if `clean_state'=="Florida" & `clean_county'=="Okaloosa"
	replace `countyfips' ="093" if `clean_state'=="Florida" & `clean_county'=="Okeechobee"
	replace `countyfips' ="095" if `clean_state'=="Florida" & `clean_county'=="Orange"
	replace `countyfips' ="097" if `clean_state'=="Florida" & `clean_county'=="Osceola"
	replace `countyfips' ="099" if `clean_state'=="Florida" & `clean_county'=="Palm Beach"
	replace `countyfips' ="101" if `clean_state'=="Florida" & `clean_county'=="Pasco"
	replace `countyfips' ="103" if `clean_state'=="Florida" & `clean_county'=="Pinellas"
	replace `countyfips' ="105" if `clean_state'=="Florida" & `clean_county'=="Polk"
	replace `countyfips' ="107" if `clean_state'=="Florida" & `clean_county'=="Putnam"
	replace `countyfips' ="109" if `clean_state'=="Florida" & `clean_county'=="St Johns"
	replace `countyfips' ="111" if `clean_state'=="Florida" & `clean_county'=="St Lucie"
	replace `countyfips' ="109" if `clean_state'=="Florida" & `clean_county'=="St. Johns"
	replace `countyfips' ="111" if `clean_state'=="Florida" & `clean_county'=="St. Lucie"
	replace `countyfips' ="113" if `clean_state'=="Florida" & `clean_county'=="Santa Rosa"
	replace `countyfips' ="115" if `clean_state'=="Florida" & `clean_county'=="Sarasota"
	replace `countyfips' ="117" if `clean_state'=="Florida" & `clean_county'=="Seminole"
	replace `countyfips' ="119" if `clean_state'=="Florida" & `clean_county'=="Sumter"
	replace `countyfips' ="121" if `clean_state'=="Florida" & `clean_county'=="Suwannee"
	replace `countyfips' ="123" if `clean_state'=="Florida" & `clean_county'=="Taylor"
	replace `countyfips' ="125" if `clean_state'=="Florida" & `clean_county'=="Union"
	replace `countyfips' ="127" if `clean_state'=="Florida" & `clean_county'=="Volusia"
	replace `countyfips' ="129" if `clean_state'=="Florida" & `clean_county'=="Wakulla"
	replace `countyfips' ="131" if `clean_state'=="Florida" & `clean_county'=="Walton"
	replace `countyfips' ="133" if `clean_state'=="Florida" & `clean_county'=="Washington"
	