	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="Washington" & `clean_county'=="Adams"
	replace `countyfips' ="003" if `clean_state'=="Washington" & `clean_county'=="Asotin"
	replace `countyfips' ="005" if `clean_state'=="Washington" & `clean_county'=="Benton"
	replace `countyfips' ="007" if `clean_state'=="Washington" & `clean_county'=="Chelan"
	replace `countyfips' ="009" if `clean_state'=="Washington" & `clean_county'=="Clallam"
	replace `countyfips' ="011" if `clean_state'=="Washington" & `clean_county'=="Clark"
	replace `countyfips' ="013" if `clean_state'=="Washington" & `clean_county'=="Columbia"
	replace `countyfips' ="015" if `clean_state'=="Washington" & `clean_county'=="Cowlitz"
	replace `countyfips' ="017" if `clean_state'=="Washington" & `clean_county'=="Douglas"
	replace `countyfips' ="019" if `clean_state'=="Washington" & `clean_county'=="Ferry"
	replace `countyfips' ="021" if `clean_state'=="Washington" & `clean_county'=="Franklin"
	replace `countyfips' ="023" if `clean_state'=="Washington" & `clean_county'=="Garfield"
	replace `countyfips' ="025" if `clean_state'=="Washington" & `clean_county'=="Grant"
	replace `countyfips' ="027" if `clean_state'=="Washington" & `clean_county'=="Grays Harbor"
	replace `countyfips' ="029" if `clean_state'=="Washington" & `clean_county'=="Island"
	replace `countyfips' ="031" if `clean_state'=="Washington" & `clean_county'=="Jefferson"
	replace `countyfips' ="033" if `clean_state'=="Washington" & `clean_county'=="King"
	replace `countyfips' ="035" if `clean_state'=="Washington" & `clean_county'=="Kitsap"
	replace `countyfips' ="037" if `clean_state'=="Washington" & `clean_county'=="Kittitas"
	replace `countyfips' ="039" if `clean_state'=="Washington" & `clean_county'=="Klickitat"
	replace `countyfips' ="041" if `clean_state'=="Washington" & `clean_county'=="Lewis"
	replace `countyfips' ="043" if `clean_state'=="Washington" & `clean_county'=="Lincoln"
	replace `countyfips' ="045" if `clean_state'=="Washington" & `clean_county'=="Mason"
	replace `countyfips' ="047" if `clean_state'=="Washington" & `clean_county'=="Okanogan"
	replace `countyfips' ="049" if `clean_state'=="Washington" & `clean_county'=="Pacific"
	replace `countyfips' ="051" if `clean_state'=="Washington" & `clean_county'=="Pend Oreille"
	replace `countyfips' ="053" if `clean_state'=="Washington" & `clean_county'=="Pierce"
	replace `countyfips' ="055" if `clean_state'=="Washington" & `clean_county'=="San Juan"
	replace `countyfips' ="057" if `clean_state'=="Washington" & `clean_county'=="Skagit"
	replace `countyfips' ="059" if `clean_state'=="Washington" & `clean_county'=="Skamania"
	replace `countyfips' ="061" if `clean_state'=="Washington" & `clean_county'=="Snohomish"
	replace `countyfips' ="063" if `clean_state'=="Washington" & `clean_county'=="Spokane"
	replace `countyfips' ="065" if `clean_state'=="Washington" & `clean_county'=="Stevens"
	replace `countyfips' ="067" if `clean_state'=="Washington" & `clean_county'=="Thurston"
	replace `countyfips' ="069" if `clean_state'=="Washington" & `clean_county'=="Wahkiakum"
	replace `countyfips' ="071" if `clean_state'=="Washington" & `clean_county'=="Walla Walla"
	replace `countyfips' ="073" if `clean_state'=="Washington" & `clean_county'=="Whatcom"
	replace `countyfips' ="075" if `clean_state'=="Washington" & `clean_county'=="Whitman"
	replace `countyfips' ="077" if `clean_state'=="Washington" & `clean_county'=="Yakima"
	