	args countyfips clean_county clean_state


	replace `countyfips' ="001" if `clean_state'=="New Mexico" & `clean_county'=="Bernalillo"
	replace `countyfips' ="003" if `clean_state'=="New Mexico" & `clean_county'=="Catron"
	replace `countyfips' ="005" if `clean_state'=="New Mexico" & `clean_county'=="Chaves"
	replace `countyfips' ="006" if `clean_state'=="New Mexico" & `clean_county'=="Cibola"
	replace `countyfips' ="007" if `clean_state'=="New Mexico" & `clean_county'=="Colfax"
	replace `countyfips' ="009" if `clean_state'=="New Mexico" & `clean_county'=="Curry"
	replace `countyfips' ="011" if `clean_state'=="New Mexico" & `clean_county'=="De Baca"
	replace `countyfips' ="013" if `clean_state'=="New Mexico" & `clean_county'=="Dona Ana"
	replace `countyfips' ="015" if `clean_state'=="New Mexico" & `clean_county'=="Eddy"
	replace `countyfips' ="017" if `clean_state'=="New Mexico" & `clean_county'=="Grant"
	replace `countyfips' ="019" if `clean_state'=="New Mexico" & `clean_county'=="Guadalupe"
	replace `countyfips' ="021" if `clean_state'=="New Mexico" & `clean_county'=="Harding"
	replace `countyfips' ="023" if `clean_state'=="New Mexico" & `clean_county'=="Hidalgo"
	replace `countyfips' ="025" if `clean_state'=="New Mexico" & `clean_county'=="Lea"
	replace `countyfips' ="027" if `clean_state'=="New Mexico" & `clean_county'=="Lincoln"
	replace `countyfips' ="028" if `clean_state'=="New Mexico" & `clean_county'=="Los Alamos"
	replace `countyfips' ="029" if `clean_state'=="New Mexico" & `clean_county'=="Luna"
	replace `countyfips' ="031" if `clean_state'=="New Mexico" & `clean_county'=="Mckinley"
	replace `countyfips' ="033" if `clean_state'=="New Mexico" & `clean_county'=="Mora"
	replace `countyfips' ="035" if `clean_state'=="New Mexico" & `clean_county'=="Otero"
	replace `countyfips' ="037" if `clean_state'=="New Mexico" & `clean_county'=="Quay"
	replace `countyfips' ="039" if `clean_state'=="New Mexico" & `clean_county'=="Rio Arriba"
	replace `countyfips' ="041" if `clean_state'=="New Mexico" & `clean_county'=="Roosevelt"
	replace `countyfips' ="043" if `clean_state'=="New Mexico" & `clean_county'=="Sandoval"
	replace `countyfips' ="045" if `clean_state'=="New Mexico" & `clean_county'=="San Juan"
	replace `countyfips' ="047" if `clean_state'=="New Mexico" & `clean_county'=="San Miguel"
	replace `countyfips' ="049" if `clean_state'=="New Mexico" & `clean_county'=="Santa Fe"
	replace `countyfips' ="051" if `clean_state'=="New Mexico" & `clean_county'=="Sierra"
	replace `countyfips' ="053" if `clean_state'=="New Mexico" & `clean_county'=="Socorro"
	replace `countyfips' ="055" if `clean_state'=="New Mexico" & `clean_county'=="Taos"
	replace `countyfips' ="057" if `clean_state'=="New Mexico" & `clean_county'=="Torrance"
	replace `countyfips' ="059" if `clean_state'=="New Mexico" & `clean_county'=="Union"
	replace `countyfips' ="061" if `clean_state'=="New Mexico" & `clean_county'=="Valencia"
	