//label variables for industry 1123

//label output variables
capture label var gp_q_Can_Other1 "Output: Other Can Product 1, qt."
capture label var gp_v_Can_Other1 "Output: Other Can Product 1, value"
capture label var gp_s_Can_Other1 "Output: Other Can Product 1, specify"
capture label var gp_q_Can_Other2 "Output: Other Can Product 2, qt."
capture label var gp_v_Can_Other2 "Output: Other Can Product 2, value"
capture label var gp_s_Can_Other2 "Output: Other Can Product 2, specify"
capture label var gp_q_Can_Other3 "Output: Other Can Product 3, qt."
capture label var gp_v_Can_Other3 "Output: Other Can Product 3, value"
capture label var gp_s_Can_Other3 "Output: Other Can Product 3, specify"
capture label var gp_q_Can_Other4 "Output: Other Can Product 4, qt."
capture label var gp_v_Can_Other4 "Output: Other Can Product 4, value"
capture label var gp_s_Can_Other4 "Output: Other Can Product 4, specify"
capture label var gp_q_Can_Venthole "Output: Packers' Cans, Venthole, qt."
capture label var gp_v_Can_Venthole "Output: Packers' Cans, Venthole, value"
capture label var gp_q_Can_Sanitary "Output: Packers' Cans, Sanitary, qt."
capture label var gp_v_Can_Sanitary "Output: Packers' Cans, Sanitary, value"
capture label var gp_q_Can_IceCream "Output: Cans Ice Cream, qt."
capture label var gp_v_Can_IceCream "Output: Cans Ice Cream, value"
capture label var gp_q_Can_Milk "Output: Cans Milk, qt."
capture label var gp_v_Can_Milk "Output: Cans Milk, value"
capture label var gp_q_Tinware_Stamped "Output: Tinware stamped, qt."
capture label var gp_v_Tinware_Stamped "Output: Tinware stamped, value"
capture label var gp_q_Tinware_Other "Output: Tinware other, qt."
capture label var gp_v_Tinware_Other "Output: Tinware other, value"
