//label variables for industry 407

//label output variables
capture label var gp_q_newsprint_rolls_A "Output: newsprint rolls used in plant, qt."
capture label var gp_v_newsprint_rolls_A "Output: newsprint rolls used in plant, value" 
capture label var gp_q_newsprint_rolls_B "Output: newsprint rolls for other plants, qt."
capture label var gp_v_newsprint_rolls_B "Output: newsprint rolls for other plants, value" 
capture label var gp_q_newsprint_rolls_C "Output: newsprint rolls for sale, qt." 
capture label var gp_v_newsprint_rolls_C "Output: newsprint rolls for sale, value" 
capture label var gp_q_newsprint_sheets_A  "Output: newsprint sheets used in plant, qt." 
capture label var gp_v_newsprint_sheets_A   "Output: newsprint sheets used in plant, value" 
capture label var gp_q_newsprint_sheets_B   "Output: newsprint sheets for other plants, qt." 
capture label var gp_v_newsprint_sheets_B   "Output: newsprint sheets for other plants, value" 
capture label var gp_q_newsprint_sheets_C   "Output: newsprint sheets for sale, qt." 
capture label var gp_v_newsprint_sheets_C   "Output: newsprint sheets for sale, value" 
capture label var gp_q_paper_hanging_A   "Output: paper hanging used in plant, qt." 
capture label var gp_v_paper_hanging_A    "Output: paper hanging used in plant, value" 
capture label var gp_q_paper_hanging_B    "Output: paper hanging for other plants, qt." 
capture label var gp_v_paper_hanging_B    "Output: paper hanging for other plants, value" 
capture label var gp_q_paper_hanging_C    "Output: paper hanging for sale, qt." 
capture label var gp_v_paper_hanging_C    "Output: paper hanging for sale, value" 
capture label var gp_q_paper_catalogue_A "Output: paper catalogue used in plant, qt."
capture label var gp_v_paper_catalogue_A     "Output: paper catalogue used in plant, value" 
capture label var gp_q_paper_catalogue_B     "Output: paper catalogue for other plants, qt." 
capture label var gp_v_paper_catalogue_B     "Output: paper catalogue for other plants, value" 
capture label var gp_q_paper_catalogue_C     "Output: paper catalogue for sale, qt." 
capture label var gp_v_paper_catalogue_C     "Output: paper catalogue for sale, value" 
capture label var gp_q_paper_poster_A     "Output: paper poster used in plant, qt." 
capture label var gp_v_paper_poster_A      "Output: paper poster used in plant, value" 
capture label var gp_q_paper_poster_B      "Output: paper poster for other plants, qt." 
capture label var gp_v_paper_poster_B      "Output: paper poster for other plants, value" 
capture label var gp_q_paper_poster_C      "Output: paper poster for sale, qt." 
capture label var gp_v_paper_poster_C      "Output: paper poster for sale, value" 
capture label var gp_q_book_paper_A "Output: book paper used in plant, qt."
capture label var gp_v_book_paper_A "Output: book paper used in plant, value" 
capture label var gp_q_book_paper_B "Output: book paper for other plants, qt." 
capture label var gp_v_book_paper_B "Output: book paper for other plants, value" 
capture label var gp_q_book_paper_C "Output: book paper for sale, qt." 
capture label var gp_v_book_paper_C "Output: book paper for sale, value" 
capture label var gp_q_body_stock_A "Output: body stock used in plant, qt." 
capture label var gp_v_body_stock_A  "Output: body stock used in plant, value" 
capture label var gp_q_body_stock_B  "Output: body stock for other plants, qt." 
capture label var gp_v_body_stock_B  "Output: body stock for other plants, value" 
capture label var gp_q_body_stock_C  "Output: body stock for sale, qt." 
capture label var gp_v_body_stock_C  "Output: body stock for sale, value" 
capture label var gp_q_lithograph_A  "Output: lithograph used in plant, qt." 
capture label var gp_v_lithograph_A   "Output: lithograph used in plant, value" 
capture label var gp_q_lithograph_B   "Output: lithograph for other plants, qt." 
capture label var gp_v_lithograph_B   "Output: lithograph for other plants, value" 
capture label var gp_q_lithograph_C   "Output: lithograph for sale, qt." 
capture label var gp_v_lithograph_C  "Output: lithograph for sale, value" 
capture label var gp_q_paper_offset_A   "Output: paper offset used in plant, qt." 
capture label var gp_v_paper_offset_A    "Output: paper offset used in plant, value" 
capture label var gp_q_paper_offset_B    "Output: paper offset for other plants, qt." 
capture label var gp_v_paper_offset_B    "Output: paper offset for other plants, value" 
capture label var gp_q_paper_offset_C    "Output: paper offset for sale, qt." 
capture label var gp_v_paper_offset_C    "Output: paper offset for sale, value" 
capture label var gp_q_text_paper_A    "Output: text paper used in plant, qt." 
capture label var gp_v_text_paper_A     "Output: text paper used in plant, value" 
capture label var gp_q_text_paper_B     "Output: text paper for other plants, qt." 
capture label var gp_v_text_paper_B     "Output: text paper for other plants, value" 
capture label var gp_q_text_paper_C     "Output: text paper for sale, qt." 
capture label var gp_v_text_paper_C     "Output: text paper for sale, value" 
capture label var gp_s_other_book_paper_1 "Output: other book paper 1, specify" 
capture label var gp_q_other_book_paper_1_A  "Output: other book paper 1 used in plant, qt." 
capture label var gp_v_other_book_paper_1_A  "Output: other book paper 1 used in plant, value" 
capture label var gp_q_other_book_paper_1_B  "Output: other book paper 1 for other plants, qt." 
capture label var gp_v_other_book_paper_1_B  "Output: other book paper 1 for other plants, value" 
capture label var gp_q_other_book_paper_1_C  "Output: other book paper 1 for sale, qt." 
capture label var gp_v_other_book_paper_1_C  "Output: other book paper 1 for sale, value" 
capture label var gp_s_other_book_paper_2  "Output: other book paper 2, specify" 
capture label var gp_q_other_book_paper_2_A  "Output: other book paper 2 used in plant, qt." 
capture label var gp_v_other_book_paper_2_A  "Output: other book paper 2 used in plant, value" 
capture label var gp_q_other_book_paper_2_B  "Output: other book paper 2 for other plants, qt." 
capture label var gp_v_other_book_paper_2_B  "Output: other book paper 2 for other plants, value" 
capture label var gp_q_other_book_paper_2_C  "Output: other book paper 2 for sale, qt." 
capture label var gp_v_other_book_paper_2_C  "Output: other book paper 2 for sale, value" 
capture label var gp_q_cover_paper_A "Output: cover paper used in plant, qt."
capture label var gp_v_cover_paper_A "Output: cover paper used in plant, value" 
capture label var gp_q_cover_paper_B "Output: cover paper for other plants, qt." 
capture label var gp_v_cover_paper_B "Output: cover paper for other plants, value" 
capture label var gp_q_cover_paper_C "Output: cover paper for sale, qt." 
capture label var gp_v_cover_paper_C "Output: cover paper for sale, value" 
capture label var gp_q_writing_paper_rag_A "Output: writing paper rag used in plant, qt." 
capture label var gp_v_writing_paper_rag_A  "Output: writing paper rag used in plant, value" 
capture label var gp_q_writing_paper_rag_B  "Output: writing paper rag for other plants, qt." 
capture label var gp_v_writing_paper_rag_B  "Output: writing paper rag for other plants, value" 
capture label var gp_q_writing_paper_rag_C  "Output: writing paper rag for sale, qt." 
capture label var gp_v_writing_paper_rag_C  "Output: writing paper rag for sale, value" 
capture label var gp_q_writing_paper_rag_less100_A "Output: writing paper rag less than 100% used in plant, qt." 
capture label var gp_v_writing_paper_rag_less100_A  "Output: writing paper rag less than 100% used in plant, value" 
capture label var gp_q_writing_paper_rag_less100_B  "Output: writing paper rag less than 100% for other plants, qt." 
capture label var gp_v_writing_paper_rag_less100_B  "Output: writing paper rag less than 100% for other plants, value" 
capture label var gp_q_writing_paper_rag_less100_C  "Output: writing paper rag less than 100% for sale, qt." 
capture label var gp_v_writing_paper_rag_less100_C  "Output: writing paper rag less than 100% for sale, value" 
capture label var gp_q_writing_paper_rag_less50_A  "Output: writing paper rag less than 50% used in plant, qt." 
capture label var gp_v_writing_paper_rag_less50_A   "Output: writing paper rag less than 50% used in plant, value" 
capture label var gp_q_writing_paper_rag_less50_B   "Output: writing paper rag less than 50% for other plants, qt." 
capture label var gp_v_writing_paper_rag_less50_B   "Output: writing paper rag less than 50% for other plants, value" 
capture label var gp_q_writing_paper_rag_less50_C   "Output: writing paper rag less than 50% for sale, qt." 
capture label var gp_v_writing_paper_rag_less50_C   "Output: writing paper rag less than 50% for sale, value" 
capture label var gp_q_paper_sulphite_A "Output: paper sulphite used in plant, qt."
capture label var gp_v_paper_sulphite_A  "Output: paper sulphite used in plant, value" 
capture label var gp_q_paper_sulphite_B  "Output: paper sulphite for other plants, qt." 
capture label var gp_v_paper_sulphite_B  "Output: paper sulphite for other plants, value" 
capture label var gp_q_paper_sulphite_C  "Output: paper sulphite for sale, qt." 
capture label var gp_v_paper_sulphite_C  "Output: paper sulphite for sale, value" 
capture label var gp_q_paper_sulphiteBags_A "Output: paper sulphite for bags, qt."
capture label var gp_v_paper_sulphiteBags_A "Output: paper sulphite for bags, value"
capture label var gp_q_paper_sulphiteBags_B "Output: paper sulphite for bags, qt."
capture label var gp_v_paper_sulphiteBags_B "Output: paper sulphate for bags, value"
capture label var gp_q_paper_sulphiteBags_C "Output: paper sulphite for bags, qt."
capture label var gp_v_paper_sulphiteBags_C "Output: paper sulphite for bags, value"
capture label var gp_q_paper_sulphateBags_A "Output: paper sulphate for bags, qt."
capture label var gp_v_paper_sulphateBags_A "Output: paper sulphate for bags, value"
capture label var gp_q_paper_sulphateBags_B "Output: paper sulphate for bags, qt."
capture label var gp_v_paper_sulphateBags_B "Output: paper sulphate for bags, value"
capture label var gp_q_paper_sulphateBags_C "Output: paper sulphate for bags, qt."
capture label var gp_v_paper_sulphateBags_C "Output: paper sulphate for bags, value"
capture label var gp_q_paper_other_chemical_A "Output: paper other chemical used in plant, qt." 
capture label var gp_v_paper_other_chemical_A  "Output: paper other chemical used in plant, value" 
capture label var gp_q_paper_other_chemical_B  "Output: paper other chemical for other plants, qt." 
capture label var gp_v_paper_other_chemical_B  "Output: paper other chemical for other plants, value" 
capture label var gp_q_paper_other_chemical_C  "Output: paper other chemical for sale, qt." 
capture label var gp_v_paper_other_chemical_C  "Output: paper other chemical for sale, value" 
capture label var gp_q_wrapping_paper_unbleached_A "Output: wrapping paper unbleached used in plant, qt." 
capture label var gp_v_wrapping_paper_unbleached_A  "Output: wrapping paper unbleached used in plant, value" 
capture label var gp_q_wrapping_paper_unbleached_B  "Output: wrapping paper unbleached for other plants, qt." 
capture label var gp_v_wrapping_paper_unbleached_B  "Output: wrapping paper unbleached for other plants, value" 
capture label var gp_q_wrapping_paper_unbleached_C  "Output: wrapping paper unbleached for sale, qt." 
capture label var gp_v_wrapping_paper_unbleached_C  "Output: wrapping paper unbleached for sale, value" 
capture label var gp_q_wrapping_paper_bleached_A  "Output: wrapping paper bleached used in plant, qt." 
capture label var gp_v_wrapping_paper_bleached_A   "Output: wrapping paper bleached used in plant, value" 
capture label var gp_q_wrapping_paper_bleached_B   "Output: wrapping paper bleached for other plants, qt." 
capture label var gp_v_wrapping_paper_bleached_B   "Output: wrapping paper bleached for other plants, value" 
capture label var gp_q_wrapping_paper_bleached_C   "Output: wrapping paper bleached for sale, qt." 
capture label var gp_v_wrapping_paper_bleached_C   "Output: wrapping paper bleached for sale, value" 
capture label var gp_q_wrapping_paper_sulphite_A   "Output: wrapping paper sulphite used in plant, qt." 
capture label var gp_v_wrapping_paper_sulphite_A    "Output: wrapping paper sulphite used in plant, value" 
capture label var gp_q_wrapping_paper_sulphite_B    "Output: wrapping paper sulphite for other plants, qt." 
capture label var gp_v_wrapping_paper_sulphite_B    "Output: wrapping paper sulphite for other plants, value" 
capture label var gp_q_wrapping_paper_sulphite_C    "Output: wrapping paper sulphite for sale, qt." 
capture label var gp_v_wrapping_paper_sulphite_C    "Output: wrapping paper sulphite for sale, value" 
capture label var gp_q_wrapping_paper_sulphate_A   "Output: wrapping paper sulphate used in plant, qt." 
capture label var gp_v_wrapping_paper_sulphate_A    "Output: wrapping paper sulphate used in plant, value" 
capture label var gp_q_wrapping_paper_sulphate_B    "Output: wrapping paper sulphate for other plants, qt." 
capture label var gp_v_wrapping_paper_sulphate_B    "Output: wrapping paper sulphate for other plants, value" 
capture label var gp_q_wrapping_paper_sulphate_C    "Output: wrapping paper sulphate for sale, qt." 
capture label var gp_v_wrapping_paper_sulphate_C    "Output: wrapping paper sulphate for sale, value" 
capture label var gp_q_wrapping_paper_kraft_nor_A    "Output: wrapping paper kraft Northern used in plant, qt." 
capture label var gp_v_wrapping_paper_kraft_nor_A     "Output: wrapping paper kraft Northern used in plant, value" 
capture label var gp_q_wrapping_paper_kraft_nor_B     "Output: wrapping paper kraft Northern for other plants, qt." 
capture label var gp_v_wrapping_paper_kraft_nor_B     "Output: wrapping paper kraft Northern for other plants, value" 
capture label var gp_q_wrapping_paper_kraft_nor_C     "Output: wrapping paper kraft Northern for sale, qt." 
capture label var gp_v_wrapping_paper_kraft_nor_C     "Output: wrapping paper kraft Northern for sale, value" 
capture label var gp_q_wrapping_paper_kraft_sot_A     "Output: wrapping paper kraft Southern used in plant, qt." 
capture label var gp_v_wrapping_paper_kraft_sot_A      "Output: wrapping paper kraft Southern used in plant, value" 
capture label var gp_q_wrapping_paper_kraft_sot_B      "Output: wrapping paper kraft Southern for other plants, qt." 
capture label var gp_v_wrapping_paper_kraft_sot_B      "Output: wrapping paper kraft Southern for other plants, value" 
capture label var gp_q_wrapping_paper_kraft_sot_C      "Output: wrapping paper kraft Southern for sale, qt." 
capture label var gp_v_wrapping_paper_kraft_sot_C      "Output: wrapping paper kraft Southern for sale, value" 
capture label var gp_q_wrapping_paper_kraft_pac_A     "Output: wrapping paper kraft Pacific used in plant, qt." 
capture label var gp_v_wrapping_paper_kraft_pac_A      "Output: wrapping paper kraft Pacific used in plant, value" 
capture label var gp_q_wrapping_paper_kraft_pac_B      "Output: wrapping paper kraft Pacific for other plants, qt." 
capture label var gp_v_wrapping_paper_kraft_pac_B      "Output: wrapping paper kraft Pacific for other plants, value" 
capture label var gp_q_wrapping_paper_kraft_pac_C      "Output: wrapping paper kraft Pacific for sale, qt." 
capture label var gp_v_wrapping_paper_kraft_pac_C      "Output: wrapping paper kraft Pacific for sale, value" 
capture label var gp_q_wrapping_paper_bogus_A "Output: wrapping paper bogus used in plant, qt." 
capture label var gp_v_wrapping_paper_bogus_A  "Output: wrapping paper bogus used in plant, value" 
capture label var gp_q_wrapping_paper_bogus_B  "Output: wrapping paper bogus for other plants, qt." 
capture label var gp_v_wrapping_paper_bogus_B  "Output: wrapping paper bogus for other plants, value" 
capture label var gp_q_wrapping_paper_bogus_C  "Output: wrapping paper bogus for sale, qt." 
capture label var gp_v_wrapping_paper_bogus_C  "Output: wrapping paper bogus for sale, value" 
capture label var gp_q_wrapping_paper_greasepf_A  "Output: wrapping paper greaseproof used in plant, qt." 
capture label var gp_v_wrapping_paper_greasepf_A   "Output: wrapping paper greaseproof used in plant, value" 
capture label var gp_q_wrapping_paper_greasepf_B   "Output: wrapping paper greaseproof for other plants, qt." 
capture label var gp_v_wrapping_paper_greasepf_B   "Output: wrapping paper greaseproof for other plants, value" 
capture label var gp_q_wrapping_paper_greasepf_C   "Output: wrapping paper greaseproof for sale, qt." 
capture label var gp_v_wrapping_paper_greasepf_C   "Output: wrapping paper greaseproof for sale, value" 
capture label var gp_q_wrapping_paper_glassine_A   "Output: wrapping paper glassine used in plant, qt." 
capture label var gp_v_wrapping_paper_glassine_A    "Output: wrapping paper glassine used in plant, value" 
capture label var gp_q_wrapping_paper_glassine_B    "Output: wrapping paper glassine for other plants, qt." 
capture label var gp_v_wrapping_paper_glassine_B    "Output: wrapping paper glassine for other plants, value" 
capture label var gp_q_wrapping_paper_glassine_C    "Output: wrapping paper glassine for sale, qt." 
capture label var gp_v_wrapping_paper_glassine_C    "Output: wrapping paper glassine for sale, value" 
capture label var gp_q_wrapping_paper_heavy_A    "Output: wrapping paper heavy used in plant, qt." 
capture label var gp_v_wrapping_paper_heavy_A     "Output: wrapping paper heavy used in plant, value" 
capture label var gp_q_wrapping_paper_heavy_B     "Output: wrapping paper heavy for other plants, qt." 
capture label var gp_v_wrapping_paper_heavy_B     "Output: wrapping paper heavy for other plants, value" 
capture label var gp_q_wrapping_paper_heavy_C     "Output: wrapping paper heavy for sale, qt." 
capture label var gp_v_wrapping_paper_heavy_C     "Output: wrapping paper heavy for sale, value" 
capture label var gp_q_wrapping_paper_rope_A     "Output: wrapping paper rope used in plant, qt." 
capture label var gp_v_wrapping_paper_rope_A      "Output: wrapping paper rope used in plant, value" 
capture label var gp_q_wrapping_paper_rope_B      "Output: wrapping paper rope for other plants, qt." 
capture label var gp_v_wrapping_paper_rope_B      "Output: wrapping paper rope for other plants, value" 
capture label var gp_q_wrapping_paper_rope_C      "Output: wrapping paper rope for sale, qt." 
capture label var gp_v_wrapping_paper_rope_C      "Output: wrapping paper rope for sale, value" 
capture label var gp_q_wrapping_paper_groundwood_A      "Output: wrapping paper groundwood used in plant, qt." 
capture label var gp_v_wrapping_paper_groundwood_A       "Output: wrapping paper groundwood used in plant, value" 
capture label var gp_q_wrapping_paper_groundwood_B       "Output: wrapping paper groundwood for other plants, qt." 
capture label var gp_v_wrapping_paper_groundwood_B       "Output: wrapping paper groundwood for other plants, value" 
capture label var gp_q_wrapping_paper_groundwood_C       "Output: wrapping paper groundwood for sale, qt." 
capture label var gp_v_wrapping_paper_groundwood_C       "Output: wrapping paper groundwood for sale, value" 
capture label var gp_q_wrapping_paper_tag_A       "Output: wrapping paper tag used in plant, qt." 
capture label var gp_v_wrapping_paper_tag_A        "Output: wrapping paper tag used in plant, value" 
capture label var gp_q_wrapping_paper_tag_B        "Output: wrapping paper tag for other plants, qt." 
capture label var gp_v_wrapping_paper_tag_B        "Output: wrapping paper tag for other plants, value" 
capture label var gp_q_wrapping_paper_tag_C        "Output: wrapping paper tag for sale, qt." 
capture label var gp_v_wrapping_paper_tag_C        "Output: wrapping paper tag for sale, value" 
capture label var gp_q_wrapping_paper_vegetable_A        "Output: wrapping paper vegetable used in plant, qt." 
capture label var gp_v_wrapping_paper_vegetable_A         "Output: wrapping paper vegetable used in plant, value" 
capture label var gp_q_wrapping_paper_vegetable_B         "Output: wrapping paper vegetable for other plants, qt." 
capture label var gp_v_wrapping_paper_vegetable_B         "Output: wrapping paper vegetable for other plants, value" 
capture label var gp_q_wrapping_paper_vegetable_C         "Output: wrapping paper vegetable for sale, qt." 
capture label var gp_v_wrapping_paper_vegetable_C         "Output: wrapping paper vegetable for sale, value" 
capture label var gp_s_wrapping_paper_other_1 "Output: wrapping paper other 1, specify" 
capture label var gp_q_wrapping_paper_other_1_A  "Output: wrapping paper other 1 used in plant, qt." 
capture label var gp_v_wrapping_paper_other_1_A  "Output: wrapping paper other 1 used in plant, value" 
capture label var gp_q_wrapping_paper_other_1_B  "Output: wrapping paper other 1 for other plants, qt." 
capture label var gp_v_wrapping_paper_other_1_B  "Output: wrapping paper other 1 for other plants, value" 
capture label var gp_q_wrapping_paper_other_1_C  "Output: wrapping paper other 1 for sale, qt." 
capture label var gp_v_wrapping_paper_other_1_C  "Output: wrapping paper other 1 for sale, value" 
capture label var gp_s_wrapping_paper_other_2   "Output: wrapping paper other 2, specify" 
capture label var gp_q_wrapping_paper_other_2_A  "Output: wrapping paper other 2 used in plant, qt." 
capture label var gp_v_wrapping_paper_other_2_A  "Output: wrapping paper other 2 used in plant, value" 
capture label var gp_q_wrapping_paper_other_2_B  "Output: wrapping paper other 2 for other plants, qt." 
capture label var gp_v_wrapping_paper_other_2_B  "Output: wrapping paper other 2 for other plants, value" 
capture label var gp_q_wrapping_paper_other_2_B "Output: wrapping paper other 2 for other plants, qt." 
capture label var gp_v_wrapping_paper_other_2_C "Output: wrapping paper other 2 for sale, value" 
capture label var gp_q_board_paper_kraft_A "Output: board paper kraft used in plant, qt." 
capture label var gp_v_board_paper_kraft_A  "Output: board paper kraft used in plant, value" 
capture label var gp_q_board_paper_kraft_B  "Output: board paper kraft for other plants, qt." 
capture label var gp_v_board_paper_kraft_B  "Output: board paper kraft for other plants, value" 
capture label var gp_q_board_paper_kraft_C  "Output: board paper kraft for sale, qt." 
capture label var gp_v_board_paper_kraft_C  "Output: board paper kraft for sale, value" 
capture label var gp_q_board_paper_other_A  "Output: board paper other used in plant, qt." 
capture label var gp_v_board_paper_other_A   "Output: board paper other used in plant, value" 
capture label var gp_q_board_paper_other_B   "Output: board paper other for other plants, qt." 
capture label var gp_v_board_paper_other_B   "Output: board paper other for other plants, value" 
capture label var gp_q_board_paper_other_C   "Output: board paper other for sale, qt." 
capture label var gp_v_board_paper_other_C   "Output: board paper other for sale, value" 
capture label var gp_q_board_paper_other_D   "Output: board paper other for sale, qt." 
capture label var gp_v_board_paper_other_D   "Output: board paper other for sale, value" 
capture label var gp_q_board_paper_other_E   "Output: board paper other for sale, qt." 
capture label var gp_v_board_paper_other_E   "Output: board paper other for sale, value" 
capture label var gp_q_board_paper_other_F   "Output: board paper other for sale, qt." 
capture label var gp_v_board_paper_other_G   "Output: board paper other for sale, value" 
capture label var gp_q_board_paper_chip_A   "Output: board paper chip used in plant, qt." 
capture label var gp_v_board_paper_chip_A    "Output: board paper chip used in plant, value" 
capture label var gp_q_board_paper_chip_B    "Output: board paper chip for other plants, qt." 
capture label var gp_v_board_paper_chip_B    "Output: board paper chip for other plants, value" 
capture label var gp_q_board_paper_chip_C    "Output: board paper chip for sale, qt." 
capture label var gp_v_board_paper_chip_C    "Output: board paper chip for sale, value" 
capture label var gp_q_board_paper_straw_A    "Output: board paper straw used in plant, qt." 
capture label var gp_v_board_paper_straw_A     "Output: board paper straw used in plant, value" 
capture label var gp_q_board_paper_straw_B     "Output: board paper straw for other plants, qt." 
capture label var gp_v_board_paper_straw_B     "Output: board paper straw for other plants, value" 
capture label var gp_q_board_paper_straw_C     "Output: board paper straw for sale, qt." 
capture label var gp_v_board_paper_straw_C     "Output: board paper straw for sale, value" 
capture label var gp_q_board_paper_folding_A     "Output: board paper folding used in plant, qt." 
capture label var gp_v_board_paper_folding_A      "Output: board paper folding used in plant, value" 
capture label var gp_q_board_paper_folding_B      "Output: board paper folding for other plants, qt." 
capture label var gp_v_board_paper_folding_B      "Output: board paper folding for other plants, value" 
capture label var gp_q_board_paper_folding_C      "Output: board paper folding for sale, qt." 
capture label var gp_v_board_paper_folding_C      "Output: board paper folding for sale, value" 
capture label var gp_q_board_paper_patent_A      "Output: board paper patent used in plant, qt." 
capture label var gp_v_board_paper_patent_A       "Output: board paper patent used in plant, value" 
capture label var gp_q_board_paper_patent_B       "Output: board paper patent for other plants, qt." 
capture label var gp_v_board_paper_patent_B       "Output: board paper patent for other plants, value" 
capture label var gp_q_board_paper_patent_C       "Output: board paper patent for sale, qt." 
capture label var gp_v_board_paper_patent_C       "Output: board paper patent for sale, value" 
capture label var gp_q_board_paper_other_folding_A       "Output: board paper other folding used in plant, qt." 
capture label var gp_v_board_paper_other_folding_A        "Output: board paper other folding used in plant, value" 
capture label var gp_q_board_paper_other_folding_B        "Output: board paper other folding for other plants, qt." 
capture label var gp_v_board_paper_other_folding_B        "Output: board paper other folding for other plants, value" 
capture label var gp_q_board_paper_other_folding_C        "Output: board paper other folding for sale, qt." 
capture label var gp_v_board_paper_other_folding_C        "Output: board paper other folding for sale, value" 
capture label var gp_q_board_paper_setup_box_A        "Output: board paper setup box used in plant, qt." 
capture label var gp_v_board_paper_setup_box_A         "Output: board paper setup box used in plant, value" 
capture label var gp_q_board_paper_setup_box_B         "Output: board paper setup box for other plants, qt." 
capture label var gp_v_board_paper_setup_box_B         "Output: board paper setup box for other plants, value" 
capture label var gp_q_board_paper_setup_box_C         "Output: board paper setup box for sale, qt." 
capture label var gp_v_board_paper_setup_box_C         "Output: board paper setup for other plants ox for sale, value" 
capture label var gp_q_board_paper_news_A         "Output: board paper news used in plant, qt." 
capture label var gp_v_board_paper_news_A          "Output: board paper news used in plant, value" 
capture label var gp_q_board_paper_news_B          "Output: board paper news for other plants, qt." 
capture label var gp_v_board_paper_news_B          "Output: board paper news for other plants, value" 
capture label var gp_q_board_paper_news_C          "Output: board paper news for sale, qt." 
capture label var gp_v_board_paper_news_C          "Output: board paper news for sale, value" 
capture label var gp_q_board_paper_other_A          "Output: board paper other used in plant, qt." 
capture label var gp_v_board_paper_other_A           "Output: board paper other used in plant, value" 
capture label var gp_q_board_paper_other_B           "Output: board paper other for other plants, qt." 
capture label var gp_v_board_paper_other_B           "Output: board paper other for other plants, value" 
capture label var gp_q_board_paper_other_C           "Output: board paper other for sale, qt." 
capture label var gp_v_board_paper_other_C           "Output: board paper other for sale, value" 
capture label var gp_q_board_paper_wall_A           "Output: board paper wall used in plant, qt." 
capture label var gp_v_board_paper_wall_A            "Output: board paper wall used in plant, value" 
capture label var gp_q_board_paper_wall_B            "Output: board paper wall for other plants, qt." 
capture label var gp_v_board_paper_wall_B            "Output: board paper wall for other plants, value" 
capture label var gp_q_board_paper_wall_C            "Output: board paper wall for sale, qt." 
capture label var gp_v_board_paper_wall_C            "Output: board paper wall for sale, value" 
capture label var gp_q_board_paper_insulating_A            "Output: board paper insulating used in plant, qt." 
capture label var gp_v_board_paper_insulating_A             "Output: board paper insulating used in plant, value" 
capture label var gp_q_board_paper_insulating_B             "Output: board paper insulating for other plants, qt." 
capture label var gp_v_board_paper_insulating_B             "Output: board paper insulating for other plants, value" 
capture label var gp_q_board_paper_insulating_C             "Output: board paper insulating for sale, qt." 
capture label var gp_v_board_paper_insulating_C             "Output: board paper insulating for sale, value" 
capture label var gp_s_board_paper_other_1              "Output: board paper other 1, specify" 
capture label var gp_q_board_paper_other_1_A              "Output: board paper other 1  used in plant, qt." 
capture label var gp_v_board_paper_other_1_A              "Output: board paper other 1  used in plant, value" 
capture label var gp_q_board_paper_other_1_B              "Output: board paper other 1  for other plants, qt." 
capture label var gp_v_board_paper_other_1_B              "Output: board paper other 1  for other plants, value" 
capture label var gp_q_board_paper_other_1_C              "Output: board paper other 1  for sale, qt." 
capture label var gp_v_board_paper_other_1_C              "Output: board paper other 1  for sale, value" 
capture label var gp_s_board_paper_other_2              "Output: board paper other 2, specify" 
capture label var gp_q_board_paper_other_2_A              "Output: board paper other 2  used in plant, qt." 
capture label var gp_v_board_paper_other_2_A              "Output: board paper other 2  used in plant, value" 
capture label var gp_q_board_paper_other_2_B              "Output: board paper other 2  for other plants, qt." 
capture label var gp_v_board_paper_other_2_B              "Output: board paper other 2  for other plants, value" 
capture label var gp_q_board_paper_other_2_C              "Output: board paper other 2  for sale, qt." 
capture label var gp_v_board_paper_other_2_C              "Output: board paper other 2  for sale, value" 
capture label var gp_s_board_paper_other_3               "Output: board paper other 3, specify" 
capture label var gp_q_board_paper_other_3_A              "Output: board paper other 3  used in plant, qt." 
capture label var gp_v_board_paper_other_3_A              "Output: board paper other 3  used in plant, value" 
capture label var gp_q_board_paper_other_3_B              "Output: board paper other 3  for other plants, qt." 
capture label var gp_v_board_paper_other_3_B              "Output: board paper other 3  for other plants, value" 
capture label var gp_q_board_paper_other_3_C              "Output: board paper other 3  for sale, qt." 
capture label var gp_v_board_paper_other_3_C              "Output: board paper other 3  for sale, value" 
capture label var gp_s_board_paper_other_4              "Output: board paper other 4, specify" 
capture label var gp_q_board_paper_other_4_A               "Output: board paper other 4 used in plant, qt." 
capture label var gp_v_board_paper_other_4_A               "Output: board paper other 4 used in plant, value" 
capture label var gp_q_board_paper_other_4_B               "Output: board paper other 4 for other plants, qt." 
capture label var gp_v_board_paper_other_4_B              "Output: board paper other 4 for other plants, value" 
capture label var gp_q_board_paper_other_4_C               "Output: board paper other 4 for sale, qt." 
capture label var gp_v_board_paper_other_4_C               "Output: board paper other 4 for sale, value" 
capture label var gp_q_board_paper_binders_A               "Output: board paper binders used in plant, qt." 
capture label var gp_v_board_paper_binders_A                "Output: board paper binders used in plant , value" 
capture label var gp_q_board_paper_binders_B                "Output: board paper binders for other plants , qt." 
capture label var gp_v_board_paper_binders_B                "Output: board paper binders for other plants , value" 
capture label var gp_q_board_paper_binders_C                "Output: board paper binders for sale, qt." 
capture label var gp_v_board_paper_binders_C                "Output: board paper binders for sale, value" 
capture label var gp_q_cardboard_bristol_A "Output: cardboard bristol used in plant, qt."
capture label var gp_v_cardboard_bristol_A "Output: cardboard bristol used in plant, value" 
capture label var gp_q_cardboard_bristol_B "Output: cardboard bristol for other plants, qt." 
capture label var gp_v_cardboard_bristol_B "Output: cardboard bristol for other plants, value" 
capture label var gp_q_cardboard_bristol_C "Output: cardboard bristol for sale, qt." 
capture label var gp_v_cardboard_bristol_C "Output: cardboard bristol for sale, value" 
capture label var gp_q_cardboard_other_A "Output: cardboard other used in plant, qt." 
capture label var gp_v_cardboard_other_A  "Output: cardboard other used in plant, value" 
capture label var gp_q_cardboard_other_B  "Output: cardboard other for other plants, qt." 
capture label var gp_v_cardboard_other_B  "Output: cardboard other for other plants, value" 
capture label var gp_q_cardboard_other_C  "Output: cardboard other for sale, qt." 
capture label var gp_v_cardboard_other_C  "Output: cardboard other for sale, value" 
capture label var gp_q_cardboard_leather_A  "Output: cardboard leather used in plant, qt." 
capture label var gp_v_cardboard_leather_A   "Output: cardboard leather used in plant, value" 
capture label var gp_q_cardboard_leather_B   "Output: cardboard leather for other plants, qt." 
capture label var gp_v_cardboard_leather_B   "Output: cardboard leather for other plants, value" 
capture label var gp_q_cardboard_leather_C   "Output: cardboard leather for sale, qt." 
capture label var gp_v_cardboard_leather_C   "Output: cardboard leather for sale, value" 
capture label var gp_q_cardboard_press_A   "Output: cardboard press used in plant, qt." 
capture label var gp_v_cardboard_press_A    "Output: cardboard press used in plant, value" 
capture label var gp_q_cardboard_press_B    "Output: cardboard press for other plants, qt." 
capture label var gp_v_cardboard_press_B    "Output: cardboard press for other plants, value" 
capture label var gp_q_cardboard_press_C    "Output: cardboard press for sale, qt." 
capture label var gp_v_cardboard_press_C    "Output: cardboard press for sale, value" 
capture label var gp_s_cardboard_other_2  "Output: cardboard other 2, specify"
capture label var gp_q_cardboard_other_2_A "Output: cardboard other 2 used in plant, qt." 
capture label var gp_v_cardboard_other_2_A "Output: cardboard other 2 used in plant, value" 
capture label var gp_q_cardboard_other_2_B "Output: cardboard other 2 for other plants, qt." 
capture label var gp_v_cardboard_other_2_B "Output: cardboard other 2 for other plants, value" 
capture label var gp_q_cardboard_other_2_C "Output: cardboard other 2 for sale, qt." 
capture label var gp_v_cardboard_other_2_C "Output: cardboard other 2 for sale, value" 
capture label var gp_s_cardboard_other_3  "Output: cardboard other 3, specify" 
capture label var gp_q_cardboard_other_3_A  "Output: cardboard other 3 used in plant, qt." 
capture label var gp_v_cardboard_other_3_A  "Output: cardboard other 3 used in plant, value" 
capture label var gp_q_cardboard_other_3_B  "Output: cardboard other 3 for other plants, qt." 
capture label var gp_v_cardboard_other_3_B  "Output: cardboard other 3 for other plants, value" 
capture label var gp_q_cardboard_other_3_C  "Output: cardboard other 3 for sale, qt." 
capture label var gp_v_cardboard_other_3_C  "Output: cardboard other 3 for sale, value" 
capture label var gp_q_cardboard_tissue_A "Output: cardboard tissue used in plant, qt." 
capture label var gp_v_cardboard_tissue_A  "Output: cardboard tissue used in plant, value" 
capture label var gp_q_cardboard_tissue_B  "Output: cardboard tissue for other plants, qt." 
capture label var gp_v_cardboard_tissue_B  "Output: cardboard tissue for other plants, value" 
capture label var gp_q_cardboard_tissue_C  "Output: cardboard tissue for sale, qt." 
capture label var gp_v_cardboard_tissue_C  "Output: cardboard tissue for sale, value" 
capture label var gp_q_tissue_paper_high_A   "Output: tissue paper high used in plant, qt." 
capture label var gp_v_tissue_paper_high_A    "Output: tissue paper high used in plant, value" 
capture label var gp_q_tissue_paper_high_B    "Output: tissue paper high for other plants, qt." 
capture label var gp_v_tissue_paper_high_B    "Output: tissue paper high for other plants, value" 
capture label var gp_q_tissue_paper_high_C    "Output: tissue paper high for sale, qt." 
capture label var gp_v_tissue_paper_high_C    "Output: tissue paper high for sale, value" 
capture label var gp_q_tissue_paper_manila_A     "Output: tissue paper manila used in plant, qt." 
capture label var gp_v_tissue_paper_manila_A      "Output: tissue paper manila used in plant, value" 
capture label var gp_q_tissue_paper_manila_B      "Output: tissue paper manila for other plants, qt." 
capture label var gp_v_tissue_paper_manila_B      "Output: tissue paper manila for other plants, value" 
capture label var gp_q_tissue_paper_manila_C      "Output: tissue paper manila for sale, qt." 
capture label var gp_v_tissue_paper_manila_C      "Output: tissue paper manila for sale, value" 
capture label var gp_q_tissue_paper_napkin_A      "Output: tissue paper napkin used in plant, qt." 
capture label var gp_v_tissue_paper_napkin_A       "Output: tissue paper napkin used in plant, value" 
capture label var gp_q_tissue_paper_napkin_B       "Output: tissue paper napkin for other plants, qt." 
capture label var gp_v_tissue_paper_napkin_B       "Output: tissue paper napkin for other plants, value" 
capture label var gp_q_tissue_paper_napkin_C       "Output: tissue paper napkin for sale, qt." 
capture label var gp_v_tissue_paper_napkin_C       "Output: tissue paper napkin for sale, value" 
capture label var gp_q_tissue_paper_toilet_A       "Output: tissue paper toilet used in plant, qt." 
capture label var gp_v_tissue_paper_toilet_A        "Output: tissue paper toilet used in plant, value" 
capture label var gp_q_tissue_paper_toilet_B        "Output: tissue paper toilet for other plants, qt." 
capture label var gp_v_tissue_paper_toilet_B        "Output: tissue paper toilet for other plants, value" 
capture label var gp_q_tissue_paper_toilet_C        "Output: tissue paper toilet for sale, qt." 
capture label var gp_v_tissue_paper_toilet_C        "Output: tissue paper toilet for sale, value" 
capture label var gp_q_tissue_paper_towel_A        "Output: tissue paper towel used in plant, qt." 
capture label var gp_v_tissue_paper_towel_A         "Output: tissue paper towel used in plant, value" 
capture label var gp_q_tissue_paper_towel_B         "Output: tissue paper towel for other plants, qt." 
capture label var gp_v_tissue_paper_towel_B         "Output: tissue paper towel for other plants, value" 
capture label var gp_q_tissue_paper_towel_C         "Output: tissue paper towel for sale, qt." 
capture label var gp_v_tissue_paper_towel_C         "Output: tissue paper towel for sale, value" 
capture label var gp_q_tissue_paper_waxing_A         "Output: tissue paper waxing used in plant, qt." 
capture label var gp_v_tissue_paper_waxing_A          "Output: tissue paper waxing used in plant, value" 
capture label var gp_q_tissue_paper_waxing_B          "Output: tissue paper waxing for other plants, qt." 
capture label var gp_v_tissue_paper_waxing_B          "Output: tissue paper waxing for other plants, value" 
capture label var gp_q_tissue_paper_waxing_C          "Output: tissue paper waxing for sale, qt." 
capture label var gp_v_tissue_paper_waxing_C          "Output: tissue paper waxing for sale, value" 
capture label var gp_s_tissue_paper_other1 "Output: tissue paper other 1, specify"
capture label var gp_q_tissue_paper_other1_A "Output: tissue paper other 1 A, qt."
capture label var gp_v_tissue_paper_other1_A "Output: tissue paper other 1 A, qt."
capture label var gp_q_tissue_paper_other1_B "Output: tissue paper other 1 B, qt." 
capture label var gp_v_tissue_paper_other1_B "Output: tissue paper other 1 B, qt."
capture label var gp_q_tissue_paper_other1_C "Output: tissue paper other 1 C, qt."
capture label var gp_v_tissue_paper_other1_C "Output: tissue paper other 1 C, qt."
capture label var gp_s_tissue_paper_other2 "Output: tissue paper other 2, specify"
capture label var gp_q_tissue_paper_other2_A "Output: tissue paper other 2 A, qt."
capture label var gp_v_tissue_paper_other2_A "Output: tissue paper other 2 A, qt."
capture label var gp_q_tissue_paper_other2_B "Output: tissue paper other 2 B, qt."
capture label var gp_v_tissue_paper_other2_B "Output: tissue paper other 2 B, qt." 
capture label var gp_q_tissue_paper_other2_C "Output: tissue paper other 2 C, qt."
capture label var gp_v_tissue_paper_other2_C "Output: tissue paper other 2 C, qt."
capture label var gp_q_absorbent_paper_blotting_A          "Output: absorbent paper blotting used in plant, qt." 
capture label var gp_v_absorbent_paper_blotting_A           "Output: absorbent paper blotting used in plant, value" 
capture label var gp_q_absorbent_paper_blotting_B           "Output: absorbent paper blotting for other plants, qt." 
capture label var gp_v_absorbent_paper_blotting_B           "Output: absorbent paper blotting for other plants, value" 
capture label var gp_q_absorbent_paper_blotting_C           "Output: absorbent paper blotting for sale, qt." 
capture label var gp_v_absorbent_paper_blotting_C           "Output: absorbent paper blotting for sale, value" 
capture label var gp_q_absorbent_paper_filter_A           "Output: absorbent paper filter used in plant, qt." 
capture label var gp_v_absorbent_paper_filter_A            "Output: absorbent paper filter used in plant, value" 
capture label var gp_q_absorbent_paper_filter_B            "Output: absorbent paper filter for other plants, qt." 
capture label var gp_v_absorbent_paper_filter_B            "Output: absorbent paper filter for other plants, value" 
capture label var gp_q_absorbent_paper_filter_C            "Output: absorbent paper filter for sale, qt." 
capture label var gp_v_absorbent_paper_filter_C            "Output: absorbent paper filter for sale, value" 
capture label var gp_q_absorbent_paper_matrix_A            "Output: absorbent paper matrix used in plant, qt." 
capture label var gp_v_absorbent_paper_matrix_A             "Output: absorbent paper matrix used in plant, value" 
capture label var gp_q_absorbent_paper_matrix_B             "Output: absorbent paper matrix for other plants, qt." 
capture label var gp_v_absorbent_paper_matrix_B             "Output: absorbent paper matrix for other plants, value" 
capture label var gp_q_absorbent_paper_matrix_C             "Output: absorbent paper matrix for sale, qt." 
capture label var gp_v_absorbent_paper_matrix_C             "Output: absorbent paper matrix for sale, value" 
capture label var gp_q_absrbent_ppr_vlcn_A             "Output: absorbent paper vulcanized used in plant, qt." 
capture label var gp_v_absrbent_ppr_vlcn_A              "Output: absorbent paper vulcanized used in plant, value" 
capture label var gp_q_absrbent_ppr_vlcn_B              "Output: absorbent paper vulcanized for other plants, qt." 
capture label var gp_v_absrbent_ppr_vlcn_B              "Output: absorbent paper vulcanized for other plants, value" 
capture label var gp_q_absrbent_ppr_vlcn_C              "Output: absorbent paper vulcanized for sale, qt." 
capture label var gp_v_absrbent_ppr_vlcn_C              "Output: absorbent paper vulcanized for sale, value" 
capture label var gp_q_absorbent_paper_celluloid_A              "Output: absorbent paper celluloid used in plant, qt." 
capture label var gp_v_absorbent_paper_celluloid_A               "Output: absorbent paper celluloid used in plant, value" 
capture label var gp_q_absorbent_paper_celluloid_B               "Output: absorbent paper celluloid for other plants, qt." 
capture label var gp_v_absorbent_paper_celluloid_B               "Output: absorbent paper celluloid for other plants, value" 
capture label var gp_q_absorbent_paper_celluloid_C               "Output: absorbent paper celluloid for sale, qt." 
capture label var gp_v_absorbent_paper_celluloid_C               "Output: absorbent paper celluloid for sale, value" 
capture label var gp_q_absorbent_paper_parchmenting_A               "Output: absorbent paper parchmenting used in plant, qt." 
capture label var gp_v_absorbent_paper_parchmenting_A                "Output: absorbent paper parchmenting used in plant , value" 
capture label var gp_q_absorbent_paper_parchmenting_B                "Output: absorbent paper parchmenting for other plants , qt." 
capture label var gp_v_absorbent_paper_parchmenting_B                "Output: absorbent paper parchmenting for other plants , value" 
capture label var gp_q_absorbent_paper_parchmenting_C                "Output: absorbent paper parchmenting for sale, qt." 
capture label var gp_v_absorbent_paper_parchmenting_C                "Output: absorbent paper parchmenting for sale, value" 
capture label var gp_s_absorbent_paper_other_1               "Output: absorbent paper other 1, specify" 
capture label var gp_q_absorbent_paper_other_1_A                "Output: absorbent paper other 1 used in plant , qt." 
capture label var gp_v_absorbent_paper_other_1_A                "Output: absorbent paper other 1 used in plant , value" 
capture label var gp_q_absorbent_paper_other_1_B                "Output: absorbent paper other 1 for other plants , qt." 
capture label var gp_v_absorbent_paper_other_1_B                "Output: absorbent paper other 1 for other plants , value" 
capture label var gp_q_absorbent_paper_other_1_C                "Output: absorbent paper other 1 for sale, qt." 
capture label var gp_v_absorbent_paper_other_1_C                "Output: absorbent paper other 1 for sale, value" 
capture label var gp_s_absorbent_paper_other_2                 "Output: absorbent paper other 2, specify" 
capture label var gp_q_absorbent_paper_other_2_A                 "Output: absorbent paper other 2  used in plant  , qt." 
capture label var gp_v_absorbent_paper_other_2_A                 "Output: absorbent paper other 2  used in plant  , value" 
capture label var gp_q_absorbent_paper_other_2_B                 "Output: absorbent paper other 2  for other plants  , qt." 
capture label var gp_v_absorbent_paper_other_2_B                 "Output: absorbent paper other 2  for other plants  , value" 
capture label var gp_q_absorbent_paper_other_2_C                 "Output: absorbent paper other 2  for sale , qt." 
capture label var gp_v_absorbent_paper_other_2_C                 "Output: absorbent paper other 2  for sale , value" 
capture label var gp_s_absorbent_paper_other_3                  "Output: absorbent paper other 3 , specify" 
capture label var gp_q_absorbent_paper_other_3_A                  "Output: absorbent paper other 3  used in plant   , qt." 
capture label var gp_v_absorbent_paper_other_3_A                  "Output: absorbent paper other 3  used in plant   , value" 
capture label var gp_q_absorbent_paper_other_3_B                  "Output: absorbent paper other 3  for other plants   , qt." 
capture label var gp_v_absorbent_paper_other_3_B                  "Output: absorbent paper other 3  for other plants   , value" 
capture label var gp_q_absorbent_paper_other_3_C                  "Output: absorbent paper other 3  for sale  , qt." 
capture label var gp_v_absorbent_paper_other_3_C                  "Output: absorbent paper other 3  for sale  , value" 
capture label var gp_q_building_paper_sheathing_A "Output: building paper sheathing used in plant, qt." 
capture label var gp_v_building_paper_sheathing_A  "Output: building paper sheathing used in plant, value" 
capture label var gp_q_building_paper_sheathing_B  "Output: building paper sheathing for other plants, qt." 
capture label var gp_v_building_paper_sheathing_B  "Output: building paper sheathing for other plants, value" 
capture label var gp_q_building_paper_sheathing_C  "Output: building paper sheathing for sale, qt." 
capture label var gp_v_building_paper_sheathing_C  "Output: building paper sheathing for sale, value" 
capture label var gp_q_building_paper_felt_A  "Output: building paper felt used in plant, qt." 
capture label var gp_v_building_paper_felt_A   "Output: building paper felt used in plant, value" 
capture label var gp_q_building_paper_felt_B   "Output: building paper felt for other plants, qt." 
capture label var gp_v_building_paper_felt_B   "Output: building paper felt for other plants, value" 
capture label var gp_q_building_paper_felt_C   "Output: building paper felt for sale, qt." 
capture label var gp_v_building_paper_felt_C   "Output: building paper felt for sale, value" 
capture label var gp_q_building_paper_asbestos_A   "Output: building paper asbestos used in plant, qt." 
capture label var gp_v_building_paper_asbestos_A    "Output: building paper asbestos used in plant, value" 
capture label var gp_q_building_paper_asbestos_B    "Output: building paper asbestos for other plants, qt." 
capture label var gp_v_building_paper_asbestos_B    "Output: building paper asbestos for other plants, value" 
capture label var gp_q_building_paper_asbestos_C    "Output: building paper asbestos for sale, qt." 
capture label var gp_v_building_paper_asbestos_C    "Output: building paper asbestos for sale, value" 
capture label var gp_s_building_paper_other_1    "Output: building paper other 1, specify" 
capture label var gp_q_building_paper_other_1_A     "Output: building paper other 1 used in plant, qt." 
capture label var gp_v_building_paper_other_1_A     "Output: building paper other 1 used in plant, value" 
capture label var gp_q_building_paper_other_1_B     "Output: building paper other 1 for other plants, qt." 
capture label var gp_v_building_paper_other_1_B     "Output: building paper other 1 for other plants, value" 
capture label var gp_q_building_paper_other_1_C     "Output: building paper other 1 for sale, qt." 
capture label var gp_v_building_paper_other_1_C     "Output: building paper other 1 for sale, value" 
capture label var gp_s_building_paper_other_2      "Output: building paper other 2, specify" 
capture label var gp_q_building_paper_other_2_A     "Output: building paper other 2 used in plant, qt." 
capture label var gp_v_building_paper_other_2_A "Output: building paper other 2 used in plant, value"
capture label var gp_q_building_paper_other_2_B     "Output: building paper other 2 for other plants, qt." 
capture label var gp_v_building_paper_other_2_B     "Output: building paper other 2 for other plants, value" 
capture label var gp_q_building_paper_other_2_C     "Output: building paper other 2 for sale, qt." 
capture label var gp_v_building_paper_other_2_C     "Output: building paper other 2 for sale, value" 
capture label var gp_s_other_paper_1     "Output: other paper 1, specify" 
capture label var gp_q_other_paper_1_A "Output: other paper 1 used in plant, qt." 
capture label var gp_v_other_paper_1_A "Output: other paper 1 used in plant, value" 
capture label var gp_q_other_paper_1_B "Output: other paper 1 for other plants, qt." 
capture label var gp_v_other_paper_1_B "Output: other paper 1 for other plants, value" 
capture label var gp_q_other_paper_1_C "Output: other paper 1 for sale, qt." 
capture label var gp_v_other_paper_1_C "Output: other paper 1 for sale, value" 
capture label var gp_s_other_paper_2 "Output: other paper 2, specify" 
capture label var gp_q_other_paper_2_A "Output: other paper 2 used in plant, qt." 
capture label var gp_v_other_paper_2_A "Output: other paper 2 used in plant, value" 
capture label var gp_q_other_paper_2_B "Output: other paper 2 for other plants, qt." 
capture label var gp_v_other_paper_2_B "Output: other paper 2 for other plants, value" 
capture label var gp_q_other_paper_2_C "Output: other paper 2 for sale, qt." 
capture label var gp_v_other_paper_2_C "Output: other paper 2 for sale, value" 
capture label var gp_q_total_paper_A "Output: total paper used in plant, qt." 
capture label var gp_v_total_paper_A  "Output: total paper used in plant, value" 
capture label var gp_q_total_paper_B  "Output: total paper for other plants, qt." 
capture label var gp_v_total_paper_B  "Output: total paper for other plants, value" 
capture label var gp_q_total_paper_C  "Output: total paper for sale, qt." 
capture label var gp_v_total_paper_C  "Output: total paper for sale, value" 
capture label var gp_q_converted_paper_kraft "Output: converted paper kraft, qt."
capture label var gp_v_converted_paper_kraft "Output: converted paper kraft, value" 
capture label var gp_q_converted_paper_other "Output: converted paper other, qt." 
capture label var gp_v_converted_paper_other "Output: converted paper other, value" 
capture label var gp_q_boxes_corregated "Output: boxes corregated, qt." 
capture label var gp_v_boxes_corregated "Output: boxes corregated, value" 
capture label var gp_q_boxes_solid "Output: boxes solid, qt." 
capture label var gp_v_boxes_solid "Output: boxes solid, value"
capture label var gp_q_cartons "Output: cartons, qt." 
capture label var gp_v_cartons "Output: cartons, value" 
capture label var gp_q_setup_paper "Output: setup paper, qt." 
capture label var gp_v_setup_paper "Output: setup paper, value" 
capture label var gp_q_paper_cans "Output: paper cans, qt." 
capture label var gp_v_paper_cans "Output: paper cans, value" 
capture label var gp_q_decorated_paper "Output: decorated paper, qt." 
capture label var gp_v_decorated_paper "Output: decorated paper, value" 
capture label var gp_s_converted_paper_other_1 "Output: converted paper other 1, specify" 
capture label var gp_q_converted_paper_other_1 "Output: converted paper other 1, qt." 
capture label var gp_v_converted_paper_other_1 "Output: converted paper other 1, value" 
capture label var gp_s_converted_paper_other_2  "Output: converted paper other 2, specify" 
capture label var gp_q_converted_paper_other_2  "Output: converted paper other 2, qt." 
capture label var gp_v_converted_paper_other_2  "Output: converted paper other 2, value" 
capture label var gp_s_converted_paper_other_3  "Output: converted paper other 3, specify" 
capture label var gp_q_converted_paper_other_3  "Output: converted paper other 3, qt." 
capture label var gp_v_converted_paper_other_3  "Output: converted paper other 3, value" 
capture label var gp_v_cardboard_paper_converted "Output: carboard paper converted, value" 
capture label var gp_q_cardboard_paper_converted  "Output: carboard paper converted, qt." 
capture label var gp_q_cigarette_paper "Output: cigarette paper, qt." 
capture label var gp_v_cigarette_paper  "Output: cigarette paper, value" 
capture label var gp_q_coated_book_paper "Output: coated book paper, value"
capture label var gp_v_coated_book_paper "Output: coated book paper, value" 
capture label var gp_q_crepe_paper "Output: crepe paper, qt." 
capture label var gp_v_crepe_paper "Output: crepe paper, value"
capture label var gp_q_file_folders "Output: file folders, qt." 
capture label var gp_v_file_folders "Output: file folders, value" 
capture label var gp_q_glazed_paper "Output: glazed paper, qt." 
capture label var gp_v_glazed_paper "Output: glazed paper, value"
capture label var gp_q_board_container_A "Output: board container A, quantity"
capture label var gp_v_board_container_A "Output: board container A, value"
capture label var gp_q_board_container_B "Output: board container B, quantity"
capture label var gp_v_board_container_B "Output: board container B, value"
capture label var gp_q_board_container_C "Output: board container C, quantity"
capture label var gp_v_board_container_C "Output: board container C, value"
capture label var gp_q_board_folding_A "Output: board folding A, quantity"
capture label var gp_v_board_folding_A "Output: board folding A, value"
capture label var gp_q_board_folding_B "Output: board folding B, quantity"
capture label var gp_v_board_folding_B "Output: board folding B, value"
capture label var gp_q_board_folding_C "Output: board folding C, quantity"
capture label var gp_v_board_folding_C "Output: board folding C, value"
capture label var gp_q_board_setup_A "Output: board setup A, quantity"
capture label var gp_v_board_setup_A "Output: board setup A, value"
capture label var gp_q_board_setup_B "Output: board setup B, quantity"
capture label var gp_v_board_setup_B "Output: board setup B, value"
capture label var gp_q_board_setup_C "Output: board setup C, quantity"
capture label var gp_v_board_setup_C "Output: board setup C, value"
capture label var gp_q_board_buildings_A "Output: board buildings A, quantity"
capture label var gp_v_board_buildings_A "Output: board buildings A, value"
capture label var gp_q_board_buildings_B "Output: board buildings B, quantity"
capture label var gp_v_board_buildings_B "Output: board buildings B, value"
capture label var gp_q_board_buildings_C "Output: board buildings C, quantity"
capture label var gp_v_board_buildings_C "Output: board buildings C, value"
capture label var gp_q_board_binders_A "Output: board binders A, quantity"
capture label var gp_v_board_binders_A "Output: board binders A, value"
capture label var gp_q_board_binders_B "Output: board binders B, quantity"
capture label var gp_v_board_binders_B "Output: board binders B, value"
capture label var gp_q_board_binders_C "Output: board binders C, quantity"
capture label var gp_v_board_binders_C "Output: board binders C, value"
capture label var gp_q_board_cardboard_A "Output: board cardboard A, quantity"
capture label var gp_v_board_cardboard_A "Output: board cardboard A, value"
capture label var gp_q_board_cardboard_B "Output: board cardboard B, quantity"
capture label var gp_v_board_cardboard_B "Output: board cardboard B, value"
capture label var gp_q_board_cardboard_C "Output: board cardboard C, quantity"
capture label var gp_v_board_cardboard_C "Output: board cardboard C, value"
capture label var gp_q_napkins "Output: napkins, qt." 
capture label var gp_v_napkins "Output: napkins, value" 
capture label var gp_q_papeleries "Output: papeleries, qt." 
capture label var gp_v_papeleries "Output: papeleries, value"
capture label var gp_q_roofing_paper "Output: roofing paper, qt." 
capture label var gp_v_roofing_paper "Output: roofing paper, value" 
capture label var gp_q_tablets_book "Output: tablets book, qt."
capture label var gp_v_tablets_book "Output: tablets book, value" 
capture label var gp_q_tablets_news "Output: tablets news, qt." 
capture label var gp_v_tablets_news "Output: tablets news, value" 
capture label var gp_q_tablets_writing "Output: tablets writing, qt." 
capture label var gp_v_tablets_writing "Output: tablets writing, value" 
capture label var gp_s_tablets_other_1 "Output: tablets other 1, specify" 
capture label var gp_q_tablets_other_1  "Output: tablets other 1, qt." 
capture label var gp_v_tablets_other_1  "Output: tablets other 1, value" 
capture label var gp_s_tablets_other_2   "Output: tablets other 2, specify" 
capture label var gp_q_tablets_other_2   "Output: tablets other 2, qt." 
capture label var gp_v_tablets_other_2   "Output: tablets other 2, value" 
capture label var gp_q_toilet_paper "Output: toilet paper, qt." 
capture label var gp_v_toilet_paper "Output: toilet paper, value" 
capture label var gp_q_towels "Output: towels, qt." 
capture label var gp_v_towels "Output: towels, value" 
capture label var gp_q_twisted_paper "Output: twisted paper, qt." 
capture label var gp_v_twister_paper "Output: twister paper, value" 
capture label var gp_q_waterproof_wrapping "Output: waterproof wrapping, qt." 
capture label var gp_v_waterproof_wrapping "Output: waterproof wrapping, value" 
capture label var gp_q_waxed_paper "Output: waxed paper, qt." 
capture label var gp_v_waxed_paper "Output: waxed paper, value" 
capture label var gp_v_cardboard_paper_converted "Output: Cardboard paper converted, value"
capture label var gp_s_converted_paper_other_4 "Output: converted paper other 4, specify" 
capture label var gp_q_converted_paper_other_4  "Output: converted paper other 4, qt." 
capture label var gp_v_converted_paper_other_4  "Output: converted paper other 4, value" 
capture label var gp_s_converted_paper_other_5  "Output: converted paper other 5, specify" 
capture label var gp_q_converted_paper_other_5  "Output: converted paper other 5, qt." 
capture label var gp_v_converted_paper_other_5  "Output: converted paper other 5, value" 
capture label var gp_v_total_converted_paper "Output: total converted paper, value" 
capture label var gp_s_boxes1 "Output: boxes 1, specify"
capture label var gp_v_boxes1 "Output: boxes 1, value"
capture label var gp_s_boxes2 "Output: boxes 2, specify"
capture label var gp_v_boxes2 "Output: boxes 2, value"
capture label var gp_s_boxes3 "Output: boxes 3, specify"
capture label var gp_v_boxes3 "Output: boxes 3, value"

//label equipment variables
capture label var z_equipment_newsprint_fourdr_num "Equipment: Newsprint fourdriner, number"
capture label var z_equipment_newsprint_fourdr_cap "Equipment: Newsprint fourdriner, capacity"
capture label var z_equipment_newsprint_cyl_num "Equipment: Newsprint cylinder, number"
capture label var z_equipment_newsprint_cyl_cap "Equipment: Newsprint cylinder, capacity"
capture label var z_equipment_bookpaper_fourdr_num "Equipment: Book paper fourdrinier, number"
capture label var z_equipment_bookpaper_fourdr_cap "Equipment: Book paper fourdrinier, capacity"
capture label var z_equipment_bookpaper_cyl_num "Equipment: Book paper cylinder, number"
capture label var z_equipment_bookpaper_cyl_cap "Equipment: Book paper cylinder, capacity"
capture label var z_equipment_coverppr_fourdr_num "Equipment: Cover paper fourdrinier, number"
capture label var z_equipment_coverppr_fourdr_cap "Equipment: Cover paper fourdrinier, capacity"
capture label var z_equipment_coverppr_cyl_num "Equipment: Cover paper cylinder, number" 
capture label var z_equipment_coverppr_cyl_cap "Equipment: Cover paper cylinder, capacity"
capture label var z_equipment_wrtngppr_fourdr_num "Equipment:  Writing paper fourdrinier, number"
capture label var z_equipment_wrtngppr_fourdr_cap "Equipment: Writing paper fourdrinier, capacity"
capture label var z_equipment_wrtngppr_cyl_num "Equipment: Writing paper cylinder, number"
capture label var z_equipment_wrtngppr_cyl_cap "Equipment: Writing paper cylinder, capacity"
capture label var z_equipment_wrppngppr_fourdr_num "Equipment: Wrapping paper fourdrinier, number"
capture label var z_equipment_wrppngppr_fourdr_cap "Equipment: Wrapping paper fourdrinier, capacity"
capture label var z_equipment_wrppngppr_cyl_num "Equipment: Wrapping paper cylinder, number"
capture label var z_equipment_wrppngppr_cyl_cap "Equipment: Wrapping paper cylinder, capacity"
capture label var z_equipment_boards_fourdr_num "Equipment: Boards fourdrinier, number"
capture label var z_equipment_boards_fourdr_cap "Equipment: Boards fourdrinier, capacity"
capture label var z_equipment_boards_cyl_num "Equipment: Boards cylinder, number"
capture label var z_equipment_boards_cyl_cap "Equipment: Boards cylinder, capacity"
capture label var z_equipment_tissueppr_fourdr_num "Equipment: Tissue paper fourdrinier, number"
capture label var z_equipment_tissueppr_fourdr_cap "Equipment: Tissue paper fourdrinier, capacity"
capture label var z_equipment_tissueppr_cyl_num "Equipment: Tissue paper cylinder, number"
capture label var z_equipment_tissueppr_cyl_cap "Equipment: Tissue paper cylinder, capacity"
capture label var z_equipment_absrbppr_fourdr_num "Equipment: Absorbent paper fourdrinier, number"
capture label var z_equipment_absrbppr_fourdr_cap "Equipment: Absorbent paper fourdrinier, capacity"
capture label var z_equipment_absrbppr_cyl_num "Equipment: Absorbent paper cylinder, number"
capture label var z_equipment_absrbppr_cyl_cap "Equipment: Absorbent paper cylinder, capacity"
capture label var z_equipment_bldppr_fourdr_numb "Equipment: Building paper fourdrinier, number"
capture label var z_equipment_bldppr_fourdr_cap "Equipment: Building paper fourdrinier, capacity"
capture label var z_equipment_bldppr_cyl_num "Equipment: Building paper cylinder, number"
capture label var z_equipment_bldppr_cyl_cap "Equipment: Building paper cylinder, capacity"
capture label var z_equipment_otherpaper1 "Equipment: Other paper 1, specify"
capture label var z_equipment_otherppr1_fourdr_num "Equipment: Other paper fourdrinier 1, number"
capture label var z_equipment_otherppr1_fourdr_cap "Equipment: Other paper fourdrinier 1, capacity"
capture label var z_equipment_otherppr1_cyl_num "Equipment: Other paper cylinder 1, number"
capture label var z_equipment_otherppr1_cyl_cap "Equipment: Other paper cylinder 1, capacity"
capture label var z_equipment_otherpaper2 "Equipment: Other paper 2, specify"
capture label var z_equipment_otherppr2_fourdr_num "Equipment: Other paper fourdrinier 2, number"
capture label var z_equipment_otherppr2_fourdr_cap "Equipment: Other paper fourdrinier 2, capacity"
capture label var z_equipment_otherppr2_cyl_num "Equipment: Other paper cylinder 2, number"
capture label var z_equipment_otherppr2_cyl_cap "Equipment: Other paper cylinder 2, capacity"
capture label var z_ratedCapacity_paper "Rated Capaity of Paper Mill"
