//label variables for industry 116

//label output variables
capture label var	gp_q_wheat_flour_white	"Output: Wheat flour, white, qt."		
capture label var	gp_v_wheat_flour_white	"Output: Wheat flour, white, value"		
capture label var	gp_q_wheat_flour_graham	"Output: Wheat flour, graham, qt."		
capture label var	gp_v_wheat_flour_graham	"Output: Wheat flour, graham, value"		
capture label var	gp_q_wheat_flour_whole	"Output: 	Wheat flour whole grain	, qt."
capture label var	gp_v_wheat_flour_whole	"Output: 	Wheat flour whole grain	, value"
capture label var	gp_q_wheat_flour_semolina	"Output: 	Wheat flour semolina	, qt."
capture label var	gp_v_wheat_flour_semolina	"Output: 	Wheat flour semolina	, value"
capture label var	gp_q_rye_flour	"Output: 	Rye flour	, qt."
capture label var	gp_v_rye_flour	"Output: 	Rye flour	, value"
capture label var	gp_q_corn_flour	"Output: 	Corn flour	, qt."
capture label var	gp_v_corn_flour	"Output: 	Corn flour	, value"
capture label var	gp_q_buckwheat_flour	"Output: 	Buckwheat flour	, qt."
capture label var	gp_v_buckwheat_flour	"Output: 	Buckwheat flour	, value"
capture label var	gp_s_flour_other1	"Output: 	Flour Other 1	, specify"
capture label var	gp_q_flour_other1	"Output: 	Flour Other 1	, qt."
capture label var	gp_v_flour_other1	"Output: 	Flour Other 1	, value"
capture label var	gp_s_flour_other2	"Output: 	Flour Other 2	, specify"
capture label var	gp_q_flour_other2	"Output: 	Flour Other 2	, qt."
capture label var	gp_v_flour_other2	"Output: 	Flour Other 2	, value"
capture label var	gp_q_corn_meal	"Output: 	Corn meal	, qt."
capture label var	gp_v_corn_meal	"Output: 	Corn meal	, value"
capture label var	gp_q_bran	"Output: 	Bran	, qt."
capture label var	gp_v_bran	"Output: 	Bran	, value"
capture label var	gp_q_feed	"Output: 	Feed	, qt."
capture label var	gp_v_feed	"Output: 	Feed	, value"
capture label var	gp_q_alfalfa_meal	"Output: 	Alfalfa meal	, qt."
capture label var	gp_v_alfalfa_meal	"Output: 	Alfalfa meal	, value"
capture label var	gp_q_prepared_flour	"Output: 	Prepared flour (self-rising)	, qt."
capture label var	gp_v_prepared_flour	"Output: 	Prepared flour (self-rising)	, value"
capture label var	gp_q_cereal_breakfast_corn	"Output: 	Cereal breakfast, corn	, qt."
capture label var	gp_v_cereal_breakfast_corn	"Output: 	Cereal breakfast, corn	, value"
capture label var	gp_q_cereal_breakfast_wheat	"Output: 	Cereal breakfast, wheat	, qt."
capture label var	gp_v_cereal_breakfast_wheat	"Output: 	Cereal breakfast, wheat	, value"
capture label var	gp_q_cereal_breakfast_oats	"Output: 	Cereal breakfast, oats	, qt."
capture label var	gp_v_cereal_breakfast_oats	"Output: 	Cereal breakfast, oats	, value"
capture label var	gp_q_cereal_breakfast_otherGrains	"Output: 	Cereal breakfast, other grains	, qt."
capture label var	gp_v_cereal_breakfast_otherGrains	"Output: 	Cereal breakfast, other grains	, value"
capture label var	gp_q_cerealCoffee_substitutes	"Output: 	Cereal coffee substitutes	, qt."
capture label var	gp_v_cerealCoffee_substitutes	"Output: 	Cereal coffee substitutes	, value"
capture label var	gp_s_otherCereal_products1	"Output: 	Other cereal products 1	, specify"
capture label var	gp_q_otherCereal_products1	"Output: 	Other cereal products 1	, qt."
capture label var	gp_v_otherCereal_products1	"Output: 	Other cereal products 1	, value"
capture label var	gp_s_otherCereal_products2	"Output: 	Other cereal products 2	, specify"
capture label var	gp_q_otherCereal_products2	"Output: 	Other cereal products 2	, qt."
capture label var	gp_v_otherCereal_products2	"Output: 	Other cereal products 2	, value"
capture label var	gp_s_otherFood_products2	"Output: 	All other food products 1	, specify"
capture label var	gp_q_otherFood_products2	"Output: 	All other food products 1	, qt."
capture label var	gp_v_otherFood_products2	"Output: 	All other food products 1	, value"
capture label var	gp_s_otherFood_products2	"Output: 	All other food products 2	, specify"
capture label var	gp_q_otherFood_products2	"Output: 	All other food products 2	, qt."
capture label var	gp_v_otherFood_products2	"Output: 	All other food products 2	, value"
capture label var	gp_q_preparedFeed	"Output: 	Prepared feed for stock and poultry	, qt."
capture label var	gp_v_preparedFeed	"Output: 	Prepared feed for stock and poultry	, value"
capture label var	gp_s_otherPreparedFeed1	"Output: 	Other prepared feed 1	, specify"
capture label var	gp_q_otherPreparedFeed1	"Output: 	Other prepared feed 1	, qt."
capture label var	gp_v_otherPreparedFeed1	"Output: 	Other prepared feed 1	, value"
capture label var	gp_s_otherPreparedFeed2	"Output: 	Other prepared feed 2	, specify"
capture label var	gp_q_otherPreparedFeed2	"Output: 	Other prepared feed 2	, qt."
capture label var	gp_v_otherPreparedFeed2	"Output: 	Other prepared feed 2	, value"
capture label var	gp_q_malt_barley	"Output: 	Malt, barley	, qt."
capture label var	gp_v_malt_barley	"Output: 	Malt, barley	, value"
capture label var	gp_q_malt_rye	"Output: 	Malt, rye	, qt."
capture label var	gp_v_malt_rye	"Output: 	Malt, rye	, value"
capture label var	gp_q_sprouts	"Output: 	Sprouts (malt)	, qt."
capture label var	gp_v_sprouts	"Output: 	Sprouts (malt)	, value"
capture label var	gp_q_screenings	"Output: 	Screenings (barley)	, qt."
capture label var	gp_v_screenings	"Output: 	Screenings (barley)	, value"
capture label var	gp_s_otherMaltByproducts1	"Output: 	Other byproduct from malt 1	, specify"
capture label var	gp_q_otherMaltByproducts1	"Output: 	Other byproduct from malt 1	, qt."
capture label var	gp_v_otherMaltByproducts1	"Output: 	Other byproduct from malt 1	, value"
capture label var	gp_s_otherMaltByproducts2	"Output: 	Other byproduct from malt 2	, specify"
capture label var	gp_q_otherMaltByproducts2	"Output: 	Other byproduct from malt 2	, qt."
capture label var	gp_v_otherMaltByproducts2	"Output: 	Other byproduct from malt 2	, value"
