//labeling script for 314 industry 1935

//label output variables 
capture label var gp_q_doors "Output: Doors, qt."
capture label var gp_v_doors "Output: Doors, value"
capture label var gp_q_doors_dwellings "Output: Doors dwellings, qt."
capture label var gp_v_doors_dwellings "Output: Doors dwellings, value"
capture label var gp_s_doors_other1 "Output: Doors other 1, specify"
capture label var gp_q_doors_other1 "Output: Doors other 1, qt."
capture label var gp_v_doors_other1 "Output: Doors other 1, value"
capture label var gp_s_doors_other2 "Output: Doors other 2, specify"
capture label var gp_q_doors_other2 "Output: Doors other 2, qt."
capture label var gp_v_doors_other2 "Output: Doors other 2, value"
capture label var gp_s_doors_other3 "Output: Doors other 3, specify"
capture label var gp_q_doors_other3 "Output: Doors other 3, qt."
capture label var gp_v_doors_other3 "Output: Doors other 3, value"
capture label var gp_q_sash "Output: Sash, qt."
capture label var gp_v_sash "Output: Sash, value"
capture label var gp_q_window_door_frames "Output: Window and door frames, qt."
capture label var gp_v_window_door_frames "Output: Window and door frames, value"
capture label var gp_q_window_door_screens "Output: Window and door screens, qt."
capture label var gp_v_window_door_screens "Output: Window and door screens, value"
capture label var gp_q_portable_houses "Output: Portable houses, qt."
capture label var gp_v_portable_houses "Output: Portable houses, value"
capture label var gp_q_tanks_vats "Output: Tanks and vats, qt."
capture label var gp_v_tanks_vats "Output: Tanks and vats, value"
capture label var gp_q_silow_stock "Output: Silow stock, qt."
capture label var gp_v_silow_stock "Output: Silow stock, value"
capture label var gp_q_dressed_lumber "Output: Dressed lumber, qt."
capture label var gp_v_dressed_lumber "Output: Dressed lumber, value"
capture label var gp_q_plywood "Output: Plywood, qt."
capture label var gp_v_plywood "Output: Plywood, value"
capture label var gp_v_moldings "Output: Moldings, value"
capture label var gp_v_builtIn_furniture "Output: Built-in furniture, value"
capture label var gp_v_battery_separators "Output: Battery separators, value"
capture label var gp_v_custom_planing "Output: Custom planing, value"
capture label var gp_v_box_wdn_lmbr_noWire "Output: Boxes - lumber and no wire, value"
capture label var gp_v_box_wdn_vnr_noWire "Output: Boxes - veneer and no wire, value"
capture label var gp_v_box_wdn_lmbr_wire "Output: Boxes - lumber and wire, value"
capture label var gp_q_venetian_blinds "Output: Venetian blinds, qt."
capture label var gp_v_venetian_blinds "Output: Venetian blinds, value"
capture label var gp_q_doors_construction_pine "Output: Doors construction, pine, qt."
capture label var gp_v_doors_construction_pine "Output: Doors construction, pine, value"
capture label var gp_q_doors_construction_fir "Output: Doors construction, fir, qt."
capture label var gp_v_doors_construction_fir "Output: Doors construction, fir, value"
capture label var gp_q_doors_construction_hardwood "Output: Doors construction, hardwood, qt."
capture label var gp_v_doors_construction_hardwood "Output: Doors construction, hardwood, value"
capture label var gp_q_doors_construction_other "Output: Doors construction, other, qt."
capture label var gp_v_doors_construction_other "Output: Doors construction, other, value"
capture label var gp_q_doors_garages "Output: Doors, garages, qt."
capture label var gp_v_doors_garages "Output: Doors, garages, value"
capture label var gp_q_plywood_utility "Output: Plywood utility, qt."
capture label var gp_v_plywood_utility "Output: Plywood utility, value"
capture label var gp_q_plywood_plain "Output: Plywood plain, qt."
capture label var gp_v_plywood_plain "Output: Plywood plain, value"
capture label var gp_q_box_wdn_lmbr_noWire_FV "Output: Boxes - lumber and no wire (fruit+veg), qt."
capture label var gp_q_box_wdn_lmbr_noWire_ind "Output: Boxes - lumber and no wire (industrial), qt."
capture label var gp_q_box_wdn_lmbr_wire_FV "Output: Boxes - lumber and wire (fruit+veg), qt."
capture label var gp_q_box_wdn_lmbr_wire_ind "Output: Boxes - lumber and wire (industrial), qt."
capture label var gp_q_box_wdn_vnr_noWire_FV "Output: Boxes - veneer and no wire (fruit+veg), qt."
capture label var gp_q_box_wdn_vnr_noWire_ind "Output: Boxes - veneer and no wire (industrial), qt."
capture label var gp_q_box_wdn_vnr_wire_FV "Output: Boxes - veneer and wire (fruit+veg), qt."
capture label var gp_q_box_wdn_vnr_wire_ind "Output: Boxes - veneer and wire (industrial), qt."
capture label var gp_v_box_wdn_vnr_wire "Output: Boxes - veneer and wire, value"
capture label var gp_q_box_wooden_combo_FV "Output: Boxes - combo (fruit+veg), qt."
capture label var gp_q_box_wooden_combo_ind "Output: Boxes - combo (industrial), qt."
capture label var gp_v_box_wooden_combo "Output: Boxes - combo, value"
capture label var gp_q_baskets_veneer_FV "Output: Baskets - veneer (fruit+veg), qt."
capture label var gp_q_baskets_veneer_ind "Output: Baskets - veneer (industrial), qt."
capture label var gp_v_baskets_veneer "Output: Baskets - veneer, value"
capture label var gp_q_baskets_reed_FV "Output: Baskets - reed (fruit+veg), qt."
capture label var gp_q_baskets_reed_ind "Output: Baskets - reed (industrial), qt."
capture label var gp_v_baskets_reed "Output: Baskets - reed, value"
capture label var gp_q_baskets_other_FV "Output: Baskets - other (fruit+veg), qt."
capture label var gp_q_baskets_other_ind "Output: Baskets - other (industrial), qt."
capture label var gp_v_baskets_other "Output: Baskets - other, value"

//label input variables
capture label var j_q_softwood "Input: Lumber Softwood, qt"
capture label var j_v_softwood "Input: Lumber Softwood, value"
capture label var j_q_hardwood "Input: Lumber Hardwood, qt"
capture label var j_v_hardwood "Input: Lumber Hardwood, value"
