//label variables for industry 907

//label output variables
capture label var gp_q_sole_leather_oak "Output: Sole leather oak, qt."
capture label var gp_v_sole_leather_oak "Output: Sole leather oak, value"
capture label var gp_q_sole_leather_chrome "Output: Sole leather chrome, qt."
capture label var gp_v_sole_leather_chrome "Output: Sole leather chrome, value"
capture label var gp_q_sole_leather_horse "Output: Sole leather horse, qt."
capture label var gp_v_sole_leather_horse "Output: Sole leather horse, value"
capture label var gp_q_sole_leather_butts_rough "Output: Sole leather butts rough, qt."
capture label var gp_v_sole_leather_butts_rough "Output: Sole leather butts rough, value"
capture label var gp_q_sole_leather_butts_curried "Output: Sole leather butts curried, qt."
capture label var gp_v_sole_leather_butts_curried "Output: Sole leather butts curried, value"
capture label var gp_q_sole_leather_offal "Output: Sole leather offal, qt."
capture label var gp_v_sole_leather_offal "Output: Sole leather offal, value"
capture label var gp_q_harness_leather_union "Output: Harness leather union, qt."
capture label var gp_v_harness_leather_union "Output: Harness leather union, value"
capture label var gp_q_harness_leather_oak "Output: Harness leather oak, qt."
capture label var gp_v_harness_leather_oak "Output: Harness leather oak, value"
capture label var gp_q_harness_leather_bag "Output: Harness leather bag, qt."
capture label var gp_v_harness_leather_bag "Output: Harness leather bag, value"
capture label var gp_q_harness_leather_skirting "Output: Harness leather skirting, qt."
capture label var gp_v_harness_leather_skirting "Output: Harness leather skirting, value"
capture label var gp_q_harness_leather_collar "Output: Harness leather collar, qt."
capture label var gp_v_harness_leather_collar "Output: Harness leather collar, value"
capture label var gp_q_harness_leather "Output: Harnesses, qt."
capture label var gp_v_harness_leather "Output: Harnesses, value"
capture label var gp_q_harness_leather_latigo "Output: Harness leather latigo, qt."
capture label var gp_v_harness_leather_latigo "Output: Harness leather latigo, value"
capture label var gp_q_harness_leather_lace "Output: Harness leather lace, qt."
capture label var gp_v_harness_leather_lace "Output: Harness leather lace, value"
capture label var gp_q_welting_cattle_sides "Output: Welting cattle sides, qt."
capture label var gp_v_welting_cattle_sides "Output: Welting cattle sides, value"
capture label var gp_q_welting_cattle_shoulders "Output: Welting cattle shoulders, qt."
capture label var gp_v_welting_cattle_shoulders "Output: Welting cattle shoulders, value"
capture label var gp_q_welting_pigskin "Output: Welting pigskin, qt."
capture label var gp_v_welting_pigskin "Output: Welting pigskin, value"
capture label var gp_q_upholstery_leather_hide "Output: Upholstery leather hide, qt."
capture label var gp_v_upholstery_leather_hide "Output: Upholstery leather hide, value"
capture label var gp_q_upholstery_leather_buffings "Output: Upholstery leather buffings, qt."
capture label var gp_v_upholstery_leather_buffings "Output: Upholstery leather buffings, value"
capture label var gp_q_upholstery_leather_splits "Output: Upholstery leather splits, qt."
capture label var gp_v_upholstery_leather_splits "Output: Upholstery leather splits, value"
capture label var gp_q_upper_leather_cattle "Output: Upper leather cattle, qt."
capture label var gp_v_upper_leather_cattle "Output: Upper leather cattle, value"
capture label var gp_q_upper_leather_calf "Output: Upper leather calf, qt."
capture label var gp_v_upper_leather_calf "Output: Upper leather calf, value"
capture label var gp_q_upper_leather_kip "Output: Upper leather kip, qt."
capture label var gp_v_upper_leather_kip "Output: Upper leather kip, value"
capture label var gp_q_upper_leather_goat "Output: Upper leather goat, qt."
capture label var gp_v_upper_leather_goat "Output: Upper leather goat, value"
capture label var gp_q_upper_leather_cabretta "Output: Upper leather cabretta, qt."
capture label var gp_v_upper_leather_cabretta "Output: Upper leather cabretta, value"
capture label var gp_q_upper_leather_sheep "Output: Upper leather sheep, qt."
capture label var gp_v_upper_leather_sheep "Output: Upper leather sheep, value"
capture label var gp_q_upper_leather_deer "Output: Upper leather deer, qt."
capture label var gp_v_upper_leather_deer "Output: Upper leather deer, value"
capture label var gp_q_upper_leather_kangaroo "Output: Upper leather kangaroo, qt."
capture label var gp_v_upper_leather_kangaroo "Output: Upper leather kangaroo, value"
capture label var gp_q_upper_leather_horse_half "Output: Upper leather horse half, qt."
capture label var gp_v_upper_leather_horse_half "Output: Upper leather horse half, value"
capture label var gp_q_upper_leather_horse_butts "Output: Upper leather horse butts, qt."
capture label var gp_v_upper_leather_horse_butts "Output: Upper leather horse butts, value"
capture label var gp_q_upper_leather_horse_shanks "Output: Upper leather horse shanks, qt."
capture label var gp_v_upper_leather_horse_shanks "Output: Upper leather horse shanks, value"
capture label var gp_s_upper_leather_other_1 "Output: Upper leather other 1, specify"
capture label var gp_q_upper_leather_other_1 "Output: Upper leather other 1, qt."
capture label var gp_v_upper_leather_other_1 "Output: Upper leather other 1, value"
capture label var gp_s_upper_leather_other_2 "Output: Upper leather other 2, specify"
capture label var gp_q_upper_leather_other_2 "Output: Upper leather other 2, qt."
capture label var gp_v_upper_leather_other_2 "Output: Upper leather other 2, value"
capture label var gp_q_patent_leather_cattle "Output: Patent leather cattle, qt."
capture label var gp_v_patent_leather_cattle "Output: Patent leather cattle, value"
capture label var gp_q_patent_leather_calf "Output: Patent leather calf, qt."
capture label var gp_v_patent_leather_calf "Output: Patent leather calf, value"
capture label var gp_q_patent_leather_goat "Output: Patent leather goat, qt."
capture label var gp_v_patent_leather_goat "Output: Patent leather goat, value"
capture label var gp_q_patent_leather_sheep "Output: Patent leather sheep, qt."
capture label var gp_v_patent_leather_sheep "Output: Patent leather sheep, value"
capture label var gp_q_patent_leather_horse "Output: Patent leather horse, qt."
capture label var gp_v_patent_leather_horse "Output: Patent leather horse, value"
capture label var gp_q_glove_leather_cattle "Output: Glove leather cattle, qt."
capture label var gp_v_glove_leather_cattle "Output: Glove leather cattle, value"
capture label var gp_q_glove_leather_calf "Output: Glove leather calf, qt."
capture label var gp_v_glove_leather_calf "Output: Glove leather calf, value"
capture label var gp_q_glove_leather_cowhide "Output: Glove leather cowhide, qt."
capture label var gp_v_glove_leather_cowhide "Output: Glove leather cowhide, value"
capture label var gp_q_glove_leather_horse_half "Output: Glove leather horse half, qt."
capture label var gp_v_glove_leather_horse_half "Output: Glove leather horse half, value"
capture label var gp_q_glove_leather_horse_butts "Output: Glove leather horse butts, qt."
capture label var gp_v_glove_leather_horse_butts "Output: Glove leather horse butts, value"
capture label var gp_q_glove_leather_horse_shanks "Output: Glove leather horse shanks, qt."
capture label var gp_v_glove_leather_horse_shanks "Output: Glove leather horse shanks, value"
capture label var gp_q_glove_leather_pig "Output: Glove leather pig, qt."
capture label var gp_v_glove_leather_pig "Output: Glove leather pig, value"
capture label var gp_q_glove_leather_goat "Output: Glove leather goat, qt."
capture label var gp_v_glove_leather_goat "Output: Glove leather goat, value"
capture label var gp_q_glove_leather_cabretta "Output: Glove leather cabretta, qt."
capture label var gp_v_glove_leather_cabretta "Output: Glove leather cabretta, value"
capture label var gp_q_glove_leather_sheep "Output: Glove leather sheep, qt."
capture label var gp_v_glove_leather_sheep "Output: Glove leather sheep, value"
capture label var gp_q_glove_leather_shearlings "Output: Glove leather shearlings, qt."
capture label var gp_v_glove_leather_shearlings "Output: Glove leather shearlings, value"
capture label var gp_q_glove_leather_deer "Output: Glove leather deer, qt."
capture label var gp_v_glove_leather_deer "Output: Glove leather deer, value"
capture label var gp_q_fancy_leather_cowhide "Output: Fancy leather cowhide, qt."
capture label var gp_v_fancy_leather_cowhide "Output: Fancy leather cowhide, value"
capture label var gp_q_fancy_leather_buffings "Output: Fancy leather buffings, qt."
capture label var gp_v_fancy_leather_buffings "Output: Fancy leather buffings, value"
capture label var gp_q_fancy_leather_goat "Output: Fancy leather goat, qt."
capture label var gp_v_fancy_leather_goat "Output: Fancy leather goat, value"
capture label var gp_q_fancy_leather_cabretta "Output: Fancy leather cabretta, qt."
capture label var gp_v_fancy_leather_cabretta "Output: Fancy leather cabretta, value"
capture label var gp_q_fancy_leather_sheep "Output: Fancy leather sheep, qt."
capture label var gp_v_fancy_leather_sheep "Output: Fancy leather sheep, value"
capture label var gp_q_fancy_leather_calf "Output: Fancy leather calf, qt."
capture label var gp_v_fancy_leather_calf "Output: Fancy leather calf, value"
capture label var gp_q_fancy_leather_pig "Output: Fancy leather pig, qt."
capture label var gp_v_fancy_leather_pig "Output: Fancy leather pig, value"
capture label var gp_q_fancy_leather_pigskin "Output: Fancy leather pigskin, qt."
capture label var gp_v_fancy_leather_pigskin "Output: Fancy leather pigskin, value"
capture label var gp_q_fancy_leather_reptile "Output: Fancy leather reptile, qt."
capture label var gp_v_fancy_leather_reptile "Output: Fancy leather reptile, value"
capture label var gp_q_fancy_leather_seal "Output: Fancy leather seal, qt."
capture label var gp_v_fancy_leather_seal "Output: Fancy leather seal, value"
capture label var gp_s_fancy_leather_other "Output: Fancy leather other, specify"
capture label var gp_q_fancy_leather_other "Output: Fancy leather other, qt."
capture label var gp_v_fancy_leather_other "Output: Fancy leather other, value"
capture label var gp_q_splits_not_upholstery "Output: Splits not upholstery, qt."
capture label var gp_v_splits_not_upholstery "Output: Splits not upholstery, value"
capture label var gp_q_roller_leather "Output: Roller leather, qt."
capture label var gp_v_roller_leather "Output: Roller leather, value"
capture label var gp_q_half_sweat_skivers "Output: Half sweat skivers, qt."
capture label var gp_v_half_sweat_skivers "Output: Half sweat skivers, value"
capture label var gp_q_skivers "Output: Skivers, qt."
capture label var gp_v_skivers "Output: Skivers, value"
capture label var gp_q_chamola "Output: Chamola, qt."
capture label var gp_v_chamola "Output: Chamola, value"
capture label var gp_q_fleshers "Output: Fleshers, qt."
capture label var gp_v_fleshers "Output: Fleshers, value"
capture label var gp_q_rough_unsplit "Output: Rough unsplit, qt."
capture label var gp_v_rough_unsplit "Output: Rough unsplit, value"
capture label var gp_q_rough_splits "Output: Rough splits, qt."
capture label var gp_v_rough_splits "Output: Rough splits, value"
capture label var gp_s_all_other_leather "Output: All other leather products, specify"
capture label var gp_v_all_other_leather "Output: All other leather products, value"
capture label var gp_v_byproducts "Output: Leather by products, value"
capture label var gp_q_miscellaneous "Output: Miscellaneous leather, qt."
capture label var gp_v_miscellaneous "Output: Miscellaneous leather, value"
capture label var gp_v_all_other_products "Output: All other products, value"

