//label variables for industry 1210

//label output variables
capture label var gp_v_jewelry_platinum "Output: Finished jewelry platinum, value"
capture label var gp_v_jewelry_solid_gold "Output: Finished jewelry solid gold, value"
capture label var gp_v_jewelry_filled_gold "Output: Finished jewelry gold filled and plated, value"
capture label var gp_v_jewelry_solid_silver "Output: Finished jewelry solid silver, value"
capture label var gp_v_jewelry_sterling_silver "Output: Finished jewelry sterling silver, value"
capture label var gp_v_jewelryEP_platinum "Output: Electroplated jewelry platinum, value"
capture label var gp_v_jewelryEP_solid_gold "Output: Electroplated jewelry solid gold, value"
capture label var gp_v_jewelryEP_filled_gold "Output: Electroplated jewelry gold filled and plated, value"
capture label var gp_v_jewelryEP_solid_silver "Output: Electroplated jewelry silver, value"
capture label var gp_s_other_jewelry_1 "Output: Other finished jewelry 1, specify"
capture label var gp_v_other_jewelry_1 "Output: Other finished jewelry 1, value"
capture label var gp_s_other_jewelry_2 "Output: Other finished jewelry 2, specify"
capture label var gp_v_other_jewelry_2 "Output: Other finished jewelry 2, value"
capture label var gp_v_jewelry_findings "Output: Jewelry findings, value"
capture label var gp_v_jewelers_materials_stock "Output: Jeweler's materials stock shop, value"
capture label var gp_v_jewelers_materials_platinum "Output: Jeweler's materials platinum stock, value"
capture label var gp_v_all_other_products "Output: All other jewelry products, value" 
capture label var gp_v_jewelryEP_gold_plated "Output: Electroplated on base metals, gold plated, value"
capture label var gp_v_jewelryEP_silver_plated "Output: Electroplated on base metals, silver plated, value"
capture label var gp_v_jewelryEP_other_plated "Output: Electroplated on base metals, platinum plated, value"
