//label variables for industry 106

//label output variables
capture label var gp_q_flour_white "Output: Flour white, qt."
capture label var gp_v_flour_white "Output: Flour white, value"
capture label var gp_q_flour_graham "Output: Flour graham, qt."
capture label var gp_v_flour_graham "Output: Flour graham, value"
capture label var gp_q_flour_semolina "Output: Flour semolina, qt."
capture label var gp_v_flour_semolina "Output: Flour semolina, value"
capture label var gp_q_flour_rye "Output: Flour rye, qt."
capture label var gp_v_flour_rye "Output: Flour rye, value"
capture label var gp_q_flour_corn "Output: Flour corn, qt."
capture label var gp_v_flour_corn "Output: Flour corn, value"
capture label var gp_q_flour_buckwheat "Output: Flour buckwheat, qt."
capture label var gp_v_flour_buckwheat "Output: Flour buckwheat, value"
capture label var gp_s_flour_other_1 "Output: Flour other 1, specify"
capture label var gp_q_flour_other_1 "Output: Flour other 1, qt."
capture label var gp_v_flour_other_1 "Output: Flour other 1, value"
capture label var gp_s_flour_other_2 "Output: Flour other 2, specify"
capture label var gp_q_flour_other_2 "Output: Flour other 2, qt."
capture label var gp_v_flour_other_2 "Output: Flour other 2, value"
capture label var gp_q_corn_meal "Output: Corn meal, qt."
capture label var gp_v_corn_meal "Output: Corn meal, value"
capture label var gp_q_bran "Output: Bran, qt."
capture label var gp_v_bran "Output: Bran, value"
capture label var gp_q_feed "Output: Feed, qt."
capture label var gp_v_feed "Output: Feed, value"
capture label var gp_q_prepared_flour "Output: Prepared flour, qt."
capture label var gp_v_prepared_flour "Output: Prepared flour, value"
capture label var gp_q_cereal_corn "Output: Cereal corn, qt."
capture label var gp_v_cereal_corn "Output: Cereal corn, value"
capture label var gp_q_cereal_wheat "Output: Cereal wheat, qt."
capture label var gp_v_cereal_wheat "Output: Cereal wheat, value"
capture label var gp_q_cereal_oats "Output: Cereal oats, qt."
capture label var gp_v_cereal_oats "Output: Cereal oats, value"
capture label var gp_q_cereal_other_grains "Output: Cereal other grains, qt."
capture label var gp_v_cereal_other_grains "Output: Cereal other grains, value"
capture label var gp_q_cereal_coffee_sub "Output: Cereal coffee substitute, qt."
capture label var gp_v_cereal_coffee_sub "Output: Cereal coffee substitute, value"
capture label var gp_s_other_cereal_1 "Output: Other Cereal 1, specify"
capture label var gp_q_other_cereal_1 "Output: Other Cereal 1, qt."
capture label var gp_v_other_cereal_1 "Output: Other Cereal 1, value"
capture label var gp_s_all_other_cereal "Output: All other cereals, specify"
capture label var gp_q_all_other_cereal "Output: All other cereals, qt."
capture label var gp_v_all_other_cereal "Output: All other cereals, value"
capture label var gp_u_all_other_cereal "Output: All other cereals, unit"
capture label var gp_q_alfalfa_meal "Output: Alfalfa meal, qt."
capture label var gp_v_alfalfa_meal "Output: Alfalfa meal, value"
capture label var gp_q_prepared_feed "Output: Prepared feed, qt."
capture label var gp_v_prepared_feed "Output: Prepared feed, value"
capture label var gp_s_other_prepared_feed_1 "Output: Other prepared feed 1, specify"
capture label var gp_q_other_prepared_feed_1 "Output: Other prepared feed 1, qt."
capture label var gp_v_other_prepared_feed_1 "Output: Other prepared feed 1, value"
capture label var gp_q_malt_barley "Output: Malt barley, qt."
capture label var gp_v_malt_barley "Output: Malt barley, value"
capture label var gp_q_malt_rye "Output: Malt rye, qt."
capture label var gp_v_malt_rye "Output: Malt rye, value"
capture label var gp_q_sprouts "Output: Sprouts, qt."
capture label var gp_v_sprouts "Output: Sprouts, value"
capture label var gp_q_screenings "Output: Screenings, qt."
capture label var gp_v_screenings "Output: Screenings, value"
capture label var gp_s_other_by_products "Output: Other flour by products, specify"
capture label var gp_q_other_by_products "Output: Other flour by products, qt."
capture label var gp_v_other_by_products "Output: Other flour by products, value"
capture label var gp_q_flour_corn_meal "Output: Flour, Corn Meal, qt."
capture label var gp_v_flour_corn_meal "Output: Flour, Corn Meal, value"

//label input variables
capture label var jp_q_wheat "Input: Wheat for flour, qt."
capture label var jp_v_wheat "Input: Wheat for flour, value" 
capture label var jp_q_corn "Input: Corn for flour, qt."
capture label var jp_v_corn "Input: Corn for flour, value"
capture label var jp_q_rye "Input: Rye for flour, qt."
capture label var jp_v_rye "Input: Rye for flour, value"
capture label var jp_q_barley "Input: Barley for flour, qt."
capture label var jp_v_barley "Input: Barley for flour, value"
capture label var jp_q_buckwheat "Input: Buckwheat for flour, qt."
capture label var jp_v_buckwheat "Input: Buckwheat for flour, value" 
capture label var jp_q_oats "Input: Oats for flour, qt."
capture label var jp_v_oats "Input: Oats for flour, value"
capture label var jp_s_other "Input: Other flour input, specify"
capture label var jp_q_other "Input: Other flour input, qt."
capture label var jp_v_other "Input: Other flour input, value"
capture label var jp_q_soybean_whole "Inputs: Soybeans, whole, qt."
capture label var jp_q_soybean_beanoil "Inputs: Soybeans, bean-oil cake, qt."
capture label var jp_q_soybean "Inputs: Total Soybeans, lbs., qt."
capture label var jp_v_soybean "Inputs: Total Soybeans, value"

//label capacity variable
capture label var z_capacity_flour_mill "Capacity: Flour Mill"

