//labels variables for industries derived from 234

//label output variables
capture label var gp_q_hosiery_cottonF_m "Output: Hosiery All-cotton, full fashioned men's, qt"
capture label var gp_v_hosiery_cottonF_m "Output: Hosiery All-cotton, full fashioned men's, value"
capture label var gp_q_hosiery_cottonF_w "Output: Hosiery All-cotton, full fashioned women's, qt"
capture label var gp_v_hosiery_cottonF_w "Output: Hosiery All-cotton, full fashioned women's, value"
capture label var gp_q_hosiery_cottonF_b "Output: Hosiery All-cotton, full fashioned boy's, qt"
capture label var gp_v_hosiery_cottonF_b "Output: Hosiery All-cotton, full fashioned boy's, value"
capture label var gp_q_hosiery_cottonF_i "Output: Hosiery All-cotton, full fashioned infant's, qt"
capture label var gp_v_hosiery_cottonF_i "Output: Hosiery All-cotton, full fashioned infant's, value"
capture label var gp_q_hosiery_cottonS_m "Output: Hosiery All-cotton, seamless men's, qt"
capture label var gp_v_hosiery_cottonS_m "Output: Hosiery All-cotton, seamless men's, value" 
capture label var gp_q_hosiery_cottonS_w "Output: Hosiery All-cotton, seamless women's, qt" 
capture label var gp_v_hosiery_cottonS_w "Output: Hosiery All-cotton, seamless women's, value"
capture label var gp_q_hosiery_cottonS_b "Output: Hosiery All-cotton, seamless boy's, qt"
capture label var gp_v_hosiery_cottonS_b "Output: Hosiery All-cotton, seamless boy's, value"
capture label var gp_q_hosiery_cottonS_i "Output: Hosiery All-cotton, seamless infant's, qt"
capture label var gp_v_hosiery_cottonS_i "Output: Hosiery All-cotton, seamless infant's, value"
capture label var gp_q_hosiery_woolF_m "Output: Hosiery Wool, full fashioned men's, qt"
capture label var gp_v_hosiery_woolF_m "Output: Hosiery Wool, full fashioned men's, value"
capture label var gp_q_hosiery_woolF_w "Output: Hosiery Wool, full fashioned women's, qt"
capture label var gp_v_hosiery_woolF_w "Output: Hosiery Wool, full fashioned women's, value"
capture label var gp_q_hosiery_woolF_b "Output: Hosiery Wool, full fashioned boy's, qt" 
capture label var gp_v_hosiery_woolF_b "Output: Hosiery Wool, full fashioned boy's, value"
capture label var gp_q_hosiery_woolF_i "Output: Hosiery Wool, full fashioned infant's, qt"
capture label var gp_v_hosiery_woolF_i "Output: Hosiery Wool, full fashioned infant's, value"
capture label var gp_q_hosiery_woolS_m  "Output: Hosiery Wool, seamless men's, qt"
capture label var gp_v_hosiery_woolS_m "Output: Hosiery Wool, seamless men's, value"
capture label var gp_q_hosiery_woolS_w "Output: Hosiery Wool, seamless women's, qt"
capture label var gp_v_hosiery_woolS_w "Output: Hosiery Wool, seamless women's, value"
capture label var gp_q_hosiery_woolS_b "Output: Hosiery Wool, seamless boy's, qt"
capture label var gp_v_hosiery_woolS_b "Output: Hosiery Wool, seamless boy's, value"
capture label var gp_q_hosiery_woolS_i "Output: Hosiery Wool, seamless infant's, qt"
capture label var gp_v_hosiery_woolS_i "Output: Hosiery Wool, seamless infant's, value"
capture label var gp_q_hosiery_threadF_m "Output: Hosiery All-thread, full fashioned men's, qt."
capture label var gp_v_hosiery_threadF_m "Output: Hosiery All-thread, full fashioned men's, value"
capture label var gp_q_hosiery_threadF_w "Output: Hosiery All-thread, full fashioned women's, qt."
capture label var gp_v_hosiery_threadF_w "Output: Hosiery All-thread, full fashioned women's, value"
capture label var gp_q_hosiery_threadF_b "Output: Hosiery All-thread, full fashioned boy's, qt."
capture label var gp_v_hosiery_threadF_b "Output: Hosiery All-thread, full fashioned boy's, value"
capture label var gp_q_hosiery_threadF_i "Output: Hosiery All-thread, full fashioned infant's, qt."
capture label var gp_v_hosiery_threadF_i "Output: Hosiery All-thread, full fashioned infant's, value"
capture label var gp_q_hosiery_threadS_m "Output: Hosiery All-thread, seamless men's, qt."
capture label var gp_v_hosiery_threadS_m "Output: Hosiery All-thread, seamless men's, value" 
capture label var gp_q_hosiery_threadS_w "Output: Hosiery All-thread, seamless women's, qt."
capture label var gp_v_hosiery_threadS_w "Output: Hosiery All-thread, seamless women's, value"
capture label var gp_q_hosiery_threadS_b "Output: Hosiery All-thread, seamless boy's, qt."
capture label var gp_v_hosiery_threadS_b "Output: Hosiery All-thread, seamless boy's, value"
capture label var gp_q_hosiery_threadS_i "Output: Hosiery All-thread, seamless infant's, qt."
capture label var gp_v_hosiery_threadS_i "Output: Hosiery All-thread, seamless infant's, qt."
capture label var gp_q_hosiery_silkF_m  "Output: Hosiery Silk Full Fashioned Men's, qt."
capture label var gp_v_hosiery_silkF_m "Output: Hosiery Silk Full Fashioned Men's, value"
capture label var gp_q_hosiery_silkF_w "Output: Hosiery Silk Full Fashioned Women's, qt."
capture label var gp_v_hosiery_silkF_w "Output: Hosiery Silk Full Fashioned Women's, value"
capture label var gp_q_hosiery_silkF_b "Output: Hosiery Silk Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_silkF_b "Output: Hosiery Silk Full Fashioned Boy's, value"
capture label var gp_q_hosiery_silkF_i "Output: Hosiery Silk Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_silkF_i "Output: Hosiery Silk Full Fashioned Infant's, value"
capture label var gp_q_hosiery_silkS_m "Output: Hosiery Silk Seamless Men's, qt."
capture label var gp_v_hosiery_silkS_m "Output: Hosiery Silk Seamless Men's, value"
capture label var gp_q_hosiery_silkS_w "Output: Hosiery Silk Seamless Women's, qt."
capture label var gp_v_hosiery_silkS_w "Output: Hosiery Silk Seamless Women's, value"
capture label var gp_q_hosiery_silkS_b "Output: Hosiery Silk Seamless Boy's, qt."
capture label var gp_v_hosiery_silkS_b "Output: Hosiery Silk Seamless Boy's, value"
capture label var gp_q_hosiery_silkS_i "Output: Hosiery Silk Seamless Infant's, qt."
capture label var gp_v_hosiery_silkS_i "Output: Hosiery Silk Seamless Infant's, value"
capture label var gp_q_hosiery_rayonF_m "Output: Hosiery Rayon Full Fashioned Men's, qt."
capture label var gp_v_hosiery_rayonF_m  "Output: Hosiery Rayon Full Fashioned Men's, value"
capture label var gp_q_hosiery_rayonF_w  "Output: Hosiery Rayon Full Fashioned Women's, qt."
capture label var gp_v_hosiery_rayonF_w  "Output: Hosiery Rayon Full Fashioned Women's, value"
capture label var gp_q_hosiery_rayonF_b "Output: Hosiery Rayon Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_rayonF_b "Output: Hosiery Rayon Full Fashioned Boy's, value"
capture label var gp_q_hosiery_rayonF_i "Output: Hosiery Rayon Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_rayonF_i "Output: Hosiery Rayon Full Fashioned Infant's, value"
capture label var gp_q_hosiery_rayonS_m  "Output: Hosiery Rayon Seamless Men's, qt."
capture label var gp_v_hosiery_rayonS_m  "Output: Hosiery Rayon Seamless Men's, value"
capture label var gp_q_hosiery_rayonS_w  "Output: Hosiery Rayon Seamless Women's, qt."
capture label var gp_v_hosiery_rayonS_w  "Output: Hosiery Rayon Seamless Women's, value"
capture label var gp_q_hosiery_rayonS_b "Output: Hosiery Rayon Seamless Boy's, qt."
capture label var gp_v_hosiery_rayonS_b "Output: Hosiery Rayon Seamless Boy's, value"
capture label var gp_q_hosiery_rayonS_i "Output: Hosiery Rayon Seamless Infant's, qt."
capture label var gp_v_hosiery_rayonS_i "Output: Hosiery Rayon Seamless Infant's, value"
capture label var gp_q_hosiery_mixRayonCottonF_m  "Output: Hosiery Mix Cotton Rayon Full Fashioned Men's, qt."
capture label var gp_v_hosiery_mixRayonCottonF_m   "Output: Hosiery Mix Cotton Rayon Full Fashioned Men's, value"
capture label var gp_q_hosiery_mixRayonCottonF_w   "Output: Hosiery Mix Cotton Rayon Full Fashioned Women's, qt."
capture label var gp_v_hosiery_mixRayonCottonF_w   "Output: Hosiery Mix Cotton Rayon Full Fashioned Women's, value"
capture label var gp_q_hosiery_mixRayonCottonF_b "Output: Hosiery Mix Cotton Rayon Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_mixRayonCottonF_b "Output: Hosiery Mix Cotton Rayon Full Fashioned Boy's, value"
capture label var gp_q_hosiery_mixRayonCottonF_i "Output: Hosiery Mix Cotton Rayon Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_mixRayonCottonF_i "Output: Hosiery Mix Cotton Rayon Full Fashioned Infant's, value"
capture label var gp_q_hosiery_mixRayonCottonS_m   "Output: Hosiery Mix Cotton Rayon Seamless Men's, qt."
capture label var gp_v_hosiery_mixRayonCottonS_m   "Output: Hosiery Mix Cotton Rayon Seamless Men's, value"
capture label var gp_q_hosiery_mixRayonCottonS_w   "Output: Hosiery Mix Cotton Rayon Seamless Women's, qt."
capture label var gp_v_hosiery_mixRayonCottonS_w   "Output: Hosiery Mix Cotton Rayon Seamless Women's, value"
capture label var gp_q_hosiery_mixRayonCottonS_b   "Output: Hosiery Mix Cotton Rayon Seamless Boy's, qt."
capture label var gp_v_hosiery_mixRayonCottonS_b "Output: Hosiery Mix Cotton Rayon Seamless Boy's, value"
capture label var gp_q_hosiery_mixRayonCottonS_i "Output: Hosiery Mix Cotton Rayon Seamless Infant's, qt."
capture label var gp_v_hosiery_mixRayonCottonS_i   "Output: Hosiery Mix Cotton Rayon Seamless Infant's, value"
capture label var gp_q_hosiery_CttnWoolF_m "Output: Hosiery Mix Cotton Wool Full Fashioned Men's, qt."
capture label var gp_v_hosiery_CttnWoolF_m "Output: Hosiery Mix Cotton Wool Full Fashioned Men's, value"
capture label var gp_q_hosiery_CttnWoolF_w "Output: Hosiery Mix Cotton Wool Full Fashioned Women's, qt."
capture label var gp_v_hosiery_CttnWoolF_w  "Output: Hosiery Mix Cotton Wool Full Fashioned Women's, value"
capture label var gp_q_hosiery_CttnWoolF_b "Output: Hosiery Mix Cotton Wool Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_CttnWoolF_b "Output: Hosiery Mix Cotton Wool Full Fashioned Boy's, value"
capture label var gp_q_hosiery_CttnWoolF_i "Output: Hosiery Mix Cotton Wool Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_CttnWoolF_i "Output: Hosiery Mix Cotton Wool Full Fashioned Infant's, value"
capture label var gp_q_hosiery_CttnWoolS_m  "Output: Hosiery Mix Cotton Wool Seamless Men's, qt."
capture label var gp_v_hosiery_CttnWoolS_m  "Output: Hosiery Mix Cotton Wool Seamless Men's, value"
capture label var gp_q_hosiery_CttnWoolS_w  "Output: Hosiery Mix Cotton Wool Seamless Women's, qt."
capture label var gp_v_hosiery_CttnWoolS_w  "Output: Hosiery Mix Cotton Wool Seamless Women's, value"
capture label var gp_q_hosiery_CttnWoolS_b "Output: Hosiery Mix Cotton Wool Seamless Boy's, qt."
capture label var gp_v_hosiery_CttnWoolS_b "Output: Hosiery Mix Cotton Wool Seamless Boy's, value"
capture label var gp_q_hosiery_CttnWoolS_i "Output: Hosiery Mix Cotton Wool Seamless Infant's, qt."
capture label var gp_v_hosiery_CttnWoolS_i "Output: Hosiery Mix Cotton Wool Seamless Infant's, value"
capture label var gp_q_hosiery_mixSilkWoolF_m "Output: Hosiery Mix Silk Wool Full Fashioned Men's, qt."
capture label var gp_v_hosiery_mixSilkWoolF_m  "Output: Hosiery Mix Silk Wool Full Fashioned Men's, value"
capture label var gp_q_hosiery_mixSilkWoolF_w  "Output: Hosiery Mix Silk Wool Full Fashioned Women's, qt."
capture label var gp_v_hosiery_mixSilkWoolF_w  "Output: Hosiery Mix Silk Wool Full Fashioned Women's, value"
capture label var gp_q_hosiery_mixSilkWoolF_b "Output: Hosiery Mix Silk Wool Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_mixSilkWoolF_b "Output: Hosiery Mix Silk Wool Full Fashioned Boy's, value"
capture label var gp_q_hosiery_mixSilkWoolF_i "Output: Hosiery Mix Silk Wool Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_mixSilkWoolF_i "Output: Hosiery Mix Silk Wool Full Fashioned Infant's, value"
capture label var gp_q_hosiery_mixSilkWoolS_m  "Output: Hosiery Mix Silk Wool Seamless Men's, qt."
capture label var gp_v_hosiery_mixSilkWoolS_m  "Output: Hosiery Mix Silk Wool Seamless Men's, value"
capture label var gp_q_hosiery_mixSilkWoolS_w  "Output: Hosiery Mix Silk Wool Seamless Women's, qt."
capture label var gp_v_hosiery_mixSilkWoolS_w  "Output: Hosiery Mix Silk Wool Seamless Women's, value"
capture label var gp_q_hosiery_mixSilkWoolS_b  "Output: Hosiery Mix Silk Wool Seamless Boy's, qt."
capture label var gp_v_hosiery_mixSilkWoolS_b "Output: Hosiery Mix Silk Wool Seamless Boy's, value"
capture label var gp_q_hosiery_mixSilkWoolS_i "Output: Hosiery Mix Silk Wool Seamless Infant's, qt."
capture label var gp_v_hosiery_mixSilkWoolS_i "Output: Hosiery Mix Silk Wool Seamless Infant's, value"
capture label var gp_q_hosiery_mixSilkCottonF_m  "Output: Hosiery Mix Silk Cotton Full Fashioned Men's, qt."
capture label var gp_v_hosiery_mixSilkCottonF_m  "Output: Hosiery Mix Silk Cotton Full Fashioned Men's, value"
capture label var gp_q_hosiery_mixSilkCottonF_w  "Output: Hosiery Mix Silk Cotton Full Fashioned Women's, qt."
capture label var gp_v_hosiery_mixSilkCottonF_w  "Output: Hosiery Mix Silk Cotton Full Fashioned Women's, value"
capture label var gp_q_hosiery_mixSilkCottonF_b "Output: Hosiery Mix Silk Cotton Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_mixSilkCottonF_b "Output: Hosiery Mix Silk Cotton Full Fashioned Boy's, value"
capture label var gp_q_hosiery_mixSilkCottonF_i "Output: Hosiery Mix Silk Cotton Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_mixSilkCottonF_i "Output: Hosiery Mix Silk Cotton Full Fashioned Infant's, value"
capture label var gp_q_hosiery_mixSilkCottonS_m  "Output: Hosiery Mix Silk Cotton Seamless Men's, qt."
capture label var gp_v_hosiery_mixSilkCottonS_m  "Output: Hosiery Mix Silk Cotton Seamless Men's, value"
capture label var gp_q_hosiery_mixSilkCottonS_w  "Output: Hosiery Mix Silk Cotton Seamless Women's, qt."
capture label var gp_v_hosiery_mixSilkCottonS_w  "Output: Hosiery Mix Silk Cotton Seamless Women's, value"
capture label var gp_q_hosiery_mixSilkCottonS_b "Output: Hosiery Mix Silk Cotton Seamless Boy's, qt."
capture label var gp_v_hosiery_mixSilkCottonS_b "Output: Hosiery Mix Silk Cotton Seamless Boy's, value"
capture label var gp_q_hosiery_mixSilkCottonS_i "Output: Hosiery Mix Silk Cotton Seamless Infant's, qt."
capture label var gp_v_hosiery_mixSilkCottonS_i "Output: Hosiery Mix Silk Rayon Seamless Infant's, value"
capture label var gp_q_hosiery_mixSilkRayonF_m  "Output: Hosiery Mix Silk Rayon Full Fashioned Men's, qt."
capture label var gp_v_hosiery_mixSilkRayonF_m  "Output: Hosiery Mix Silk Rayon Full Fashioned Men's, value"
capture label var gp_q_hosiery_mixSilkRayonF_w  "Output: Hosiery Mix Silk Rayon Full Fashioned Women's, qt."
capture label var gp_v_hosiery_mixSilkRayonF_w  "Output: Hosiery Mix Silk Rayon Full Fashioned Women's, value"
capture label var gp_q_hosiery_mixSilkRayonF_b "Output: Hosiery Mix Silk Rayon Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_mixSilkRayonF_b "Output: Hosiery Mix Silk Rayon Full Fashioned Boy's, value"
capture label var gp_q_hosiery_mixSilkRayonF_i "Output: Hosiery Mix Silk Rayon Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_mixSilkRayonF_i "Output: Hosiery Mix Silk Rayon Full Fashioned Infant's, value"
capture label var gp_q_hosiery_mixSilkRayonS_m  "Output: Hosiery Mix Silk Rayon Seamless Men's, qt."
capture label var gp_v_hosiery_mixSilkRayonS_m  "Output: Hosiery Mix Silk Rayon Seamless Men's, value"
capture label var gp_q_hosiery_mixSilkRayonS_w  "Output: Hosiery Mix Silk Rayon Seamless Women's, qt."
capture label var gp_v_hosiery_mixSilkRayonS_w  "Output: Hosiery Mix Silk Rayon Seamless Women's, value"
capture label var gp_q_hosiery_mixSilkRayonS_b "Output: Hosiery Mix Silk Rayon Seamless Boy's, qt."
capture label var gp_v_hosiery_mixSilkRayonS_b "Output: Hosiery Mix Silk Rayon Seamless Boy's, value"
capture label var gp_q_hosiery_mixSilkRayonS_i "Output: Hosiery Mix Silk Rayon Seamless Infant's, qt."
capture label var gp_v_hosiery_mixSilkRayonS_i "Output: Hosiery Mix Silk Rayon Seamless Infant's, value"
capture label var gp_q_hosiery_mixWoolRayonF_m  "Output: Hosiery Mix Wool Rayon Full Fashioned Men's, qt."
capture label var gp_v_hosiery_mixWoolRayonF_m  "Output: Hosiery Mix Wool Rayon Full Fashioned Men's, value"
capture label var gp_q_hosiery_mixWoolRayonF_w  "Output: Hosiery Mix Wool Rayon Full Fashioned Women's, qt."
capture label var gp_v_hosiery_mixWoolRayonF_w  "Output: Hosiery Mix Wool Rayon Full Fashioned Women's, value"
capture label var gp_q_hosiery_mixWoolRayonF_b "Output: Hosiery Mix Wool Rayon Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_mixWoolRayonF_b  "Output: Hosiery Mix Wool Rayon Full Fashioned Boy's, value"
capture label var gp_q_hosiery_mixWoolRayonF_i "Output: Hosiery Mix Wool Rayon Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_mixWoolRayonF_i "Output: Hosiery Mix Wool Rayon Full Fashioned Infant's, value"
capture label var gp_q_hosiery_mixWoolRayonS_m  "Output: Hosiery Mix Wool Rayon Seamless Men's, qt."
capture label var gp_v_hosiery_mixWoolRayonS_m  "Output: Hosiery Mix Wool Rayon Seamless Men's, value"
capture label var gp_q_hosiery_mixWoolRayonS_w  "Output: Hosiery Mix Wool Rayon Seamless Women's, qt."
capture label var gp_v_hosiery_mixWoolRayonS_w  "Output: Hosiery Mix Wool Rayon Seamless Women's, value"
capture label var gp_q_hosiery_mixWoolRayonS_b  "Output: Hosiery Mix Wool Rayon Seamless Boy's, qt."
capture label var gp_v_hosiery_mixWoolRayonS_b "Output: Hosiery Mix Wool Rayon Seamless Boy's, value"
capture label var gp_q_hosiery_mixWoolRayonS_i "Output: Hosiery Mix Wool Rayon Seamless Infant's, qt."
capture label var gp_v_hosiery_mixWoolRayonS_i "Output: Hosiery Mix Wool Rayon Seamless Infant's, value"
capture label var gp_q_hosiery_mixCottonRayonF_m "Output: Hosiery Mix Cotton Rayon Full Fashioned Men's, qt."
capture label var gp_v_hosiery_mixCottonRayonF_m "Output: Hosiery Mix Cotton Rayon Full Fashioned Men's, value"
capture label var gp_q_hosiery_mixCottonRayonF_w "Output: Hosiery Mix Cotton Rayon Full Fashioned Women's, qt."
capture label var gp_v_hosiery_mixCottonRayonF_w "Output: Hosiery Mix Cotton Rayon Full Fashioned Women's, value"
capture label var gp_q_hosiery_mixCottonRayonF_b "Output: Hosiery Mix Cotton Rayon Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_mixCottonRayonF_b "Output: Hosiery Mix Cotton Rayon Full Fashioned Boy's, value"
capture label var gp_q_hosiery_mixCottonRayonF_i "Output: Hosiery Mix Cotton Rayon Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_mixCottonRayonF_i "Output: Hosiery Mix Cotton Rayon Full Fashioned Infant's, value"
capture label var gp_q_hosiery_mixCottonRayonS_m "Output: Hosiery Mix Cotton Rayon Seamless Men's, qt."
capture label var gp_v_hosiery_mixCottonRayonS_m "Output: Hosiery Mix Cotton Rayon Seamless Men's, value"
capture label var gp_q_hosiery_mixCottonRayonS_w "Output: Hosiery Mix Cotton Rayon Seamless Women's, qt."
capture label var gp_v_hosiery_mixCottonRayonS_w "Output: Hosiery Mix Cotton Rayon Seamless Women's, value"
capture label var gp_q_hosiery_mixCottonRayonS_b "Output: Hosiery Mix Cotton Rayon Seamless Boy's, qt."
capture label var gp_v_hosiery_mixCottonRayonS_b "Output: Hosiery Mix Cotton Rayon Seamless Boy's, value"
capture label var gp_q_hosiery_mixCottonRayonS_i "Output: Hosiery Mix Cotton Rayon Seamless Infant's, qt."
capture label var gp_v_hosiery_mixCottonRayonS_i "Output: Hosiery Mix Cotton Rayon Seamless Infant's, value"
capture label var gp_q_hosiery_mixTripleF_m "Output: Hosiery Mix Triple Fabrics Full Fashioned Men's, qt."
capture label var gp_v_hosiery_mixTripleF_m  "Output: Hosiery Mix Triple Fabrics Full Fashioned Men's, value"
capture label var gp_q_hosiery_mixTripleF_w  "Output: Hosiery Mix Triple Fabrics Full Fashioned Women's, qt."
capture label var gp_v_hosiery_mixTripleF_w  "Output: Hosiery Mix Triple Fabrics Full Fashioned Women's, value"
capture label var gp_q_hosiery_mixTripleF_b "Output: Hosiery Mix Triple Fabrics Full Fashioned Boy's, qt."
capture label var gp_v_hosiery_mixTripleF_b "Output: Hosiery Mix Triple Fabrics Full Fashioned Boy's, value"
capture label var gp_q_hosiery_mixTripleF_i "Output: Hosiery Mix Triple Fabrics Full Fashioned Infant's, qt."
capture label var gp_v_hosiery_mixTripleF_i "Output: Hosiery Mix Triple Fabrics Full Fashioned Infant's, value"
capture label var gp_q_hosiery_mixTripleS_m  "Output: Hosiery Mix Triple Fabrics Seamless Men's, qt."
capture label var gp_v_hosiery_mixTripleS_m  "Output: Hosiery Mix Triple Fabrics Seamless Men's, value"
capture label var gp_q_hosiery_mixTripleS_w  "Output: Hosiery Mix Triple Fabrics Seamless Women's, qt."
capture label var gp_v_hosiery_mixTripleS_w  "Output: Hosiery Mix Triple Fabrics Seamless Women's, value"
capture label var gp_q_hosiery_mixTripleS_b  "Output: Hosiery Mix Triple Fabrics Seamless Boy's, qt."
capture label var gp_v_hosiery_mixTripleS_b "Output: Hosiery Mix Triple Fabrics Seamless Boy's, value"
capture label var gp_q_hosiery_mixTripleS_i "Output: Hosiery Mix Triple Fabrics Seamless Infant's, qt."
capture label var gp_v_hosiery_mixTripleS_i  "Output: Hosiery Mix Triple Fabrics Seamless Infant's, value"
capture label var gp_q_underwear_cotton_shirt "Output: Underwear Cotton , qt."
capture label var gp_v_underwear_cotton_shirt "Output: Underwear Cotton, value"
capture label var gp_q_underwear_cotton_uSuit "Output: Underwear Cotton, qt."
capture label var gp_v_underwear_cotton_uSuit "Output: Underwear Cotton, value"
capture label var gp_q_underwear_cotton_blm "Output: Underwear Cotton, qt."
capture label var gp_v_underwear_cotton_blm "Output: Underwear Cotton, value"
capture label var gp_q_underwear_cotton_slip "Output: Underwear Cotton, qt."
capture label var gp_v_underwear_cotton_slip "Output: Underwear Cotton, value"
capture label var gp_q_underwear_wool_shirt "Output: Underwear Wool, qt."
capture label var gp_v_underwear_wool_shirt "Output: Underwear Wool, value"
capture label var gp_q_underwear_wool_uSuit "Output: Underwear Wool, qt."
capture label var gp_v_underwear_wool_uSuit  "Output: Underwear Wool, value"
capture label var gp_q_underwear_wool_blm  "Output: Underwear Wool, qt."
capture label var gp_v_underwear_wool_blm "Output: Underwear Wool, value"
capture label var gp_q_underwear_wool_slip "Output: Underwear Wool, qt."
capture label var gp_v_underwear_wool_slip "Output: Underwear Wool, value"
capture label var gp_q_underwear_CttnWool_shirt "Output: Underwear Mix Cotton Wool , qt."
capture label var gp_v_underwear_CttnWool_shirt "Output: Underwear Mix Cotton Wool , value"
capture label var gp_q_underwear_CttnWool_uSuit "Output: Underwear Mix Cotton Wool , qt."
capture label var gp_v_underwear_CttnWool_uSuit "Output: Underwear Mix Cotton Wool , value"
capture label var gp_q_underwear_CttnWool_blm "Output: Underwear Mix Cotton Wool , qt."
capture label var gp_v_underwear_CttnWool_blm "Output: Underwear Mix Cotton Wool , value"
capture label var gp_q_underwear_CttnWool_slip "Output: Underwear Mix Cotton Wool , qt."
capture label var gp_v_underwear_CttnWool_slip "Output: Underwear Mix Cotton Wool , value"
capture label var gp_q_underwear_silkWarp_shirt "Output: Underwear Silk Warp, qt."
capture label var gp_v_underwear_silkWarp_shirt "Output: Underwear Silk Warp, value"
capture label var gp_q_underwear_silkWarp_uSuit "Output: Underwear Silk Warp, qt."
capture label var gp_v_underwear_silkWarp_uSuit  "Output: Underwear Silk Warp, value"
capture label var gp_q_underwear_silkWarp_blm "Output: Underwear Silk Warp, qt."
capture label var gp_v_underwear_silkWarp_blm "Output: Underwear Silk Warp , value"
capture label var gp_q_underwear_silkWarp_slip  "Output: Underwear Silk Warp, qt."
capture label var gp_v_underwear_silkWarp_slip  "Output: Underwear Silk Warp, value"
capture label var gp_q_underwear_silkCone_shirt "Output: Underwear Silk Cone, qt."
capture label var gp_v_underwear_silkCone_shirt "Output: Underwear Silk Cone, value"
capture label var gp_q_underwear_silkCone_uSuit "Output: Underwear Silk Cone, qt."
capture label var gp_v_underwear_silkCone_uSuit  "Output: Underwear Silk Cone, value"
capture label var gp_q_underwear_silkCone_blm  "Output: Underwear Silk Cone, qt."
capture label var gp_v_underwear_silkCone_blm  "Output: Underwear Silk Cone, value"
capture label var gp_q_underwear_silkCone_slip  "Output: Underwear Silk Cone, qt."
capture label var gp_v_underwear_silkCone_slip "Output: Underwear Silk Cone, value"
capture label var gp_q_underwear_silkShtl_shirt "Output: Underwear Silk Shuttle, qt."
capture label var gp_v_underwear_silkShtl_shirt "Output: Underwear Silk Shuttle, value"
capture label var gp_q_underwear_silkShtl_uSuit "Output: Underwear Silk Shuttle, qt."
capture label var gp_v_underwear_silkShtl_uSuit "Output: Underwear Silk Shuttle, value"
capture label var gp_q_underwear_silkShtl_blm "Output: Underwear Silk Shuttle, qt."
capture label var gp_v_underwear_silkShtl_blm "Output: Underwear Silk Shuttle, value"
capture label var gp_q_underwear_silkShtl_slip "Output: Underwear Silk Shuttle, qt."
capture label var gp_v_underwear_silkShtl_slip "Output: Underwear Silk Shuttle, value"
capture label var gp_q_underwear_rayonWarp_shirt "Output: Underwear Rayon Warp, qt."
capture label var gp_v_underwear_rayonWarp_shirt "Output: Underwear Rayon Warp, value"
capture label var gp_q_underwear_rayonWarp_uSuit "Output: Underwear Rayon Warp, qt."
capture label var gp_v_underwear_rayonWarp_uSuit  "Output: Underwear Rayon Warp, value"
capture label var gp_q_underwear_rayonWarp_blm  "Output: Underwear Rayon Warp, qt."
capture label var gp_v_underwear_rayonWarp_blm  "Output: Underwear Rayon Warp, value"
capture label var gp_q_underwear_rayonWarp_slip  "Output: Underwear Rayon Warp, qt."
capture label var gp_v_underwear_rayonWarp_slip  "Output: Underwear Rayon Warp, value"
capture label var gp_q_underwear_rayonCone_shirt "Output: Underwear Rayon Cone, qt."
capture label var gp_v_underwear_rayonCone_shirt  "Output: Underwear Rayon Cone, value"
capture label var gp_q_underwear_rayonCone_uSuit  "Output: Underwear Rayon Cone , qt."
capture label var gp_v_underwear_rayonCone_uSuit "Output: Underwear Rayon Cone, value"
capture label var gp_q_underwear_rayonCone_blm  "Output: Underwear Rayon Cone, qt."
capture label var gp_v_underwear_rayonCone_blm  "Output: Underwear Rayon Cone, value"
capture label var gp_q_underwear_rayonCone_slip  "Output: Underwear Rayon Cone, qt."
capture label var gp_v_underwear_rayonCone_slip "Output: Underwear Rayon Cone, value"
capture label var gp_q_underwear_silkRynWrp_shirt  "Output: Underwear Mix Silk and Rayon Warp, qt."
capture label var gp_v_underwear_silkRynWrp_shirt  "Output: Underwear Mix Silk and Rayon Warp, value"
capture label var gp_q_underwear_silkRynWrp_uSuit "Output: Underwear Mix Silk and Rayon Warp, qt."
capture label var gp_v_underwear_silkRynWrp_uSuit  "Output: Underwear Mix Silk and Rayon Warp, value"
capture label var gp_q_underwear_silkRynWrp_blm  "Output: Underwear Mix Silk and Rayon Warp, qt."
capture label var gp_v_underwear_silkRynWrp_blm  "Output: Underwear Mix Silk and Rayon Warp, value"
capture label var gp_q_underwear_silkRynWrp_slip  "Output: Underwear Mix Silk and Rayon Warp, qt."
capture label var gp_v_underwear_silkRynWrp_slip "Output: Underwear Mix Silk and Rayon Warp, value"
capture label var gp_q_underwear_silkRynCn_shirt  "Output: Underwear Mix Silk and Rayon Cone, qt."
capture label var gp_v_underwear_silkRynCn_shirt  "Output: Underwear Mix Silk and Rayon Cone, value"
capture label var gp_q_underwear_silkRynCn_uSuit "Output: Underwear Mix Silk and Rayon Cone, qt."
capture label var gp_v_underwear_silkRynCn_uSuit "Output: Underwear Mix Silk and Rayon Cone, value"
capture label var gp_q_underwear_silkRynCn_blm "Output: Underwear Mix Silk and Rayon Cone, qt."
capture label var gp_v_underwear_silkRynCn_blm "Output: Underwear Mix Silk and Rayon Cone, value"
capture label var gp_q_underwear_silkRynCn_slip "Output: Underwear Mix Silk and Rayon Cone, qt."
capture label var gp_v_underwear_silkRynCn_slip "Output: Underwear Mix Silk and Rayon Cone, value"
capture label var gp_s_underwear_other1 "Output: Underwear Other 1 Seamless, specify"
capture label var gp_q_underwear_other1_shirt "Output: Underwear Other 1, qt."
capture label var gp_v_underwear_other1_shirt "Output: Underwear Other 1, value"
capture label var gp_v_underwear_other1_uSuit "Output: Underwear Other 1, value"
capture label var gp_q_underwear_other1_uSuit "Output: Underwear Other 1, qt."
capture label var gp_v_underwear_other1_blm "Output: Underwear Other 1, value"
capture label var gp_q_underwear_other1_blm "Output: Underwear Other 1, qt."
capture label var gp_v_underwear_other1_slip "Output: Underwear Other 1, value"
capture label var gp_q_underwear_other1_slip "Output: Underwear Other 1, qt."
capture label var gp_s_underwear_other2 "Output: Underwear Other 2 Seamless, specify"
capture label var gp_q_underwear_other2_shirt "Output: Underwear Other 2, qt."
capture label var gp_v_underwear_other2_shirt "Output: Underwear Other 2, value"
capture label var gp_q_underwear_other2_uSuit "Output: Underwear Other 2, qt."
capture label var gp_v_underwear_other2_uSuit "Output: Underwear Other 2, value"
capture label var gp_q_underwear_other2_blm "Output: Underwear Other 2, qt."
capture label var gp_v_underwear_other2_blm "Output: Underwear Other 2, value"
capture label var gp_q_underwear_other2_slip "Output: Underwear Other 2, qt."
capture label var gp_v_underwear_other2_slip "Output: Underwear Other 2, value"
capture label var gp_s_underwear_other3 "Output: Underwear Other 3 Seamless, specify"
capture label var gp_q_underwear_other3_shirt "Output: Underwear Other 3, qt."
capture label var gp_v_underwear_other3_shirt "Output: Underwear Other 3, value"
capture label var gp_q_underwear_other3_uSuit "Output: Underwear Other 3, qt."
capture label var gp_v_underwear_other3_uSuit "Output: Underwear Other 3, value"
capture label var gp_q_underwear_other3_blm "Output: Underwear Other 3, qt."
capture label var gp_v_underwear_other3_blm "Output: Underwear Other 3, value"
capture label var gp_q_underwear_other3_slip "Output: Underwear Other 3, qt."
capture label var gp_v_underwear_other3_slip "Output: Underwear Other 3, value"
capture label var gp_q_outerwear_sweater "Output: Outerwear Sweater, qt."
capture label var gp_v_outerwear_sweater "Output: Outerwear Sweater, value"
capture label var gp_q_outerwear_bathrobe "Output: Outerwear Bathrobe, qt."
capture label var gp_v_outerwear_bathrobe "Output: Outerwear Bathrobe, value"
capture label var gp_q_outerwear_scarf "Output: Outerwear Scarf, qt."
capture label var gp_v_outerwear_scarf "Output: Outerwear Scarf, value"
capture label var gp_q_outerwear_muffler "Output: Outerwear Muffler, qt."
capture label var gp_v_outerwear_muffler "Output: Outerwear Muffler, value"
capture label var gp_q_outerwear_headwear "Output: Outerwear Headwear , qt."
capture label var gp_v_outerwear_headwear "Output: Outerwear Headwear, value"
capture label var gp_q_outerwear_necktie "Output: Outerwear Necktie, qt."
capture label var gp_v_outerwear_necktie "Output: Outerwear Necktie, value"
capture label var gp_q_outerwear_gloveS_suede "Output: Outerwear Gloves Suede Seamless, qt."
capture label var gp_v_outerwear_gloveS_suede "Output: Outerwear Gloves Suede Seamless, value"
capture label var gp_q_outerwear_gloveS_notSuede "Output: Outerwear Gloves Not Suede Seamless, qt."
capture label var gp_v_outerwear_gloveS_notSuede "Output: Outerwear Gloves Not Suede Seamless, value"
capture label var gp_q_outerwear_gloveS_cone "Output: Outerwear Gloves Cone Seamless, qt."
capture label var gp_v_outerwear_gloveS_cone "Output: Outerwear Gloves Cone Seamless, value"
capture label var gp_q_outerwear_gloveS_woolen "Output: Outerwear Gloves Woolen Seamless, qt."
capture label var gp_v_outerwear_gloveS_woolen "Output: Outerwear Gloves Woolen Seamless, value"
capture label var gp_q_outerwear_gloveS_silk "Output: Outerwear Gloves Silk Seamless, qt."
capture label var gp_v_outerwear_gloveS_silk "Output: Outerwear Gloves Silk Seamless, value"
capture label var gp_s_outerwear_gloves_other1 "Output: Outerwear Gloves Other 2 Seamless, specify"
capture label var gp_q_outerwear_gloveS_other1 "Output: Outerwear Gloves Other 1 Seamless, qt."
capture label var gp_v_outerwear_gloveS_other1 "Output: Outerwear Gloves Other 1 Seamless, value"
capture label var gp_s_outerwear_gloves_other2 "Output: Outerwear Gloves Other 2 Seamless, specify"
capture label var gp_q_outerwear_gloveS_other2 "Output: Outerwear Gloves Other 2 Seamless, qt."
capture label var gp_v_outerwear_gloveS_other2 "Output: Outerwear Gloves Other 2 Seamless, value"
capture label var gp_q_outerwear_mittenS_worsted "Output: Outerwear Mittens Worsted Seamless, qt."
capture label var gp_v_outerwear_mittenS_worsted  "Output: Outerwear Mittens Worsted Seamless, value"
capture label var gp_q_outerwear_mittenS_wool "Output: Outerwear Mittens Wool Seamless, qt."
capture label var gp_v_outerwear_mittenS_wool "Output: Outerwear Mittens Wool Seamless, value"
capture label var gp_q_outerwear_athletic_hose "Output: Outerwear Athletic Hose, qt."
capture label var gp_v_outerwear_athletic_hose "Output: Outerwear Athletic Hose, value"
capture label var gp_q_outerwear_dresseS_suits  "Output: Outerwear Dresses and Suits Seamless, qt."
capture label var gp_v_outerwear_dresseS_suits "Output: Outerwear Dresses and Suits Seamless, value"
capture label var gp_q_outerwear_i "Output: Outerwear Infants, qt."
capture label var gp_v_outerwear_i "Output: Outerwear Infants, value"
capture label var gp_s_outerwear_other1  "Output: Outerwear Other 2 Seamless, specify"
capture label var gp_v_outerwear_other1 "Output: Outerwear Other 1, value"
capture label var gp_s_outerwear_other2 "Output: Outerwear Other 2 Seamless, specify"
capture label var gp_v_outerwear_other2 "Output: Outerwear Other 2, value"
capture label var gp_q_knitCloth_wool "Output: Knit Cloth Wool, qt."
capture label var gp_v_knitCloth_wool "Output: Knit Cloth Wool , value"
capture label var gp_s_knitCloth_otherWool1 "Output: Knit Cloth Other Wool 3 Seamless, specify"
capture label var gp_q_knitCloth_otherWool1 "Output: Knit Cloth Other Wool 1, qt."
capture label var gp_v_knitCloth_otherWool1 "Output: Knit Cloth Other Wool 1, value"
capture label var gp_s_knitCloth_otherWool2 "Output: Knit Cloth Other Wool 2 Seamless, specify"
capture label var gp_q_knitCloth_otherWool2 "Output: Knit Cloth Other Wool 2, qt."
capture label var gp_v_knitCloth_otherWool2 "Output: Knit Cloth Other Wool 2, value"
capture label var gp_s_knitCloth_otherWool3 "Output: Knit Cloth Other Wool 3 Seamless, specify"
capture label var gp_q_knitCloth_otherWool3 "Output: Knit Cloth Other Wool 3 , qt."
capture label var gp_v_knitCloth_otherWool3 "Output: Knit Cloth Other Wool 3, value"
capture label var gp_q_knitCloth_silkJersey "Output: Knit Cloth Silk Jersey, qt."
capture label var gp_v_knitCloth_silkJersey  "Output: Knit Cloth Silk Jersey, value"
capture label var gp_q_knitCloth_rayonTubing "Output: Knit Cloth Rayon Tubing, qt."
capture label var gp_v_knitCloth_rayonTubing  "Output: Knit Cloth Rayon Tubing, value"
capture label var gp_q_knitCloth_otherRayon "Output: Knit Cloth Other Rayon, qt."
capture label var gp_v_knitCloth_otherRayon  "Output: Knit Cloth Other Rayon, value"
capture label var gp_v_knitCloth_glove  "Output: Knit Cloth Glove, value"
capture label var gp_q_knitCloth_cottonJersey "Output: Knit Cloth Cotton Jersey, qt."
capture label var gp_v_knitCloth_cottonJersey  "Output: Knit Cloth Cotton Jersey, value"
capture label var gp_q_knitCloth_corsetRayon "Output: Knit Cloth Corset Rayon , qt."
capture label var gp_v_knitCloth_corsetRayon "Output: Knit Cloth Corset Rayon, value"
capture label var gp_s_knitCloth_corsetOther1 "Output: Knit Cloth Corset Other 1 Seamless, specify"
capture label var gp_q_knitCloth_corsetOther1 "Output: Knit Cloth Corset Other 1, qt."
capture label var gp_v_knitCloth_corsetOther1 "Output: Knit Cloth Corset Other 1, value"
capture label var gp_q_knitCloth_towel "Output: Knit Cloth Towel, qt."
capture label var gp_v_knitCloth_towel "Output: Knit Cloth Towel, value"
capture label var gp_v_knitCloth_stockinet "Output: Knit Cloth Stockinet, value"
capture label var gp_s_knitCloth_other1 "Output: Knit Cloth Other 1 Seamless, specify"
capture label var gp_v_knitCloth_other1 "Output: Knit Cloth Other 1, value"
capture label var gp_v_knitCloth_iUnderwear "Output: Knit Cloth Infant Underwear, value"
capture label var gp_s_knit_other1 "Output: knit Other 1 Seamless, specify"
capture label var gp_v_knit_other1  "Output: Knit Other 1, value"
capture label var gp_s_knit_other2 "Output: Knit Other 2 Seamless, specify"
capture label var gp_v_knit_other2 "Output: Knit Other 2, value"
capture label var gp_s_knit_other3 "Output: Knit Other 3 Seamless, specify"
capture label var gp_v_knit_other3 "Output: Knit Other 3, value"
capture label var gp_q_sewingThread_cotton "Output: Sewing Thread Cotton, qt."
capture label var gp_v_sewingThread_cotton  "Output: Sewing Thread Cotton, value"
capture label var gp_q_sewingThread_cottonCrochet "Output: Sewing Thread Cotton Crochet, qt."
capture label var gp_v_sewingThread_cottonCrochet "Output: Sewing Thread Cotton Crochet, value"
capture label var gp_q_sewingThread_cottonWaste "Output: Sewing Thread Cotton Waste, qt."
capture label var gp_v_sewingThread_cottonWaste "Output: Sewing Thread Cotton Waste, value"
capture label var gp_s_sewingThread_other1 "Output: Sewing Thread Other 1, specify"
capture label var gp_q_sewingThread_other1 "Output: Sewing Thread Other 1, qt."
capture label var gp_v_sewingThread_other1 "Output: Sewing Thread Other 1, value"
capture label var gp_s_sewingThread_other2 "Output: Sewing Thread Other 2, specify"
capture label var gp_q_sewingThread_other2 "Output: Sewing Thread Other 2, qt." 
capture label var gp_v_sewingThread_other2 "Output: Sewing Thread Other 2, value"
capture label var gp_v_old_bagging "Output: Old Bagging, value"
//capture label var contract_work
capture label var g000v 

//label input variables
capture label var j_q_cotton_domestic "Input: Cotton Domestic, qt."
capture label var j_v_cotton_domestic "Input: Cotton Domestic, value"
capture label var j_q_cotton_foreign "Input: Cotton Foreign, qt." 
capture label var j_v_cotton_foreign "Input: Corron Foreign, value"
capture label var j_q_wool_domestic_grease "Input: Woolen Domestic Grease, qt."
capture label var j_v_wool_domestic_grease "Input: Woole Domestic Grease, value"
capture label var j_q_wool_domestic_pulled "Input: Woolen Domestic Pulled, qt."
capture label var j_v_wool_domestic_pulled "Input: Woolen Domestic Pulled, value"
capture label var j_q_wool_domestic_scoured "Input: Woolen Domestic Scoured, qt."
capture label var j_v_wool_domestic_scoured "Input: Woolen Domestic Scoured, value"
capture label var j_q_wool_domestic_total_scoured "Input: Woolen Domestic Total Scoured, qt."
capture label var j_q_wool_foreign_grease "Input: Woolen Foreign Grease, qt."
capture label var j_v_wool_foreign_grease "Input: Woolen Foreign Grease, value"
capture label var j_q_wool_foreign_pulled "Input: Woolen Foreign Pulled, qt."
capture label var j_v_wool_foreign_pulled "Input: Woolen Foreign Pulled, value"
capture label var j_q_wool_foreign_scoured "Input: Woolen Foreign Scoured, value"
capture label var j_v_wool_foreign_scoured "Input: Woolen Foreign Scoured, qt."
capture label var j_q_wool_foreign_total_scoured "Input: Woolen Foreign Total Scoured, qt."
capture label var j_q_silk_raw "Input: Silk raw, qt"
capture label var j_v_silk_raw "Input: Silk raw, value"
capture label var j_q_yarn_woolen "Input: Yarn woolen, qt."
capture label var j_v_yarn_woolen "Input: Yarn woolen, value"
capture label var j_q_yarn_worsted "Input: Yarn worsted, qt."
capture label var j_v_yarn_worsted "Input: Yarn worsted, value"
capture label var j_q_yarn_mixedWoolCotton "Input: Mixed Wool and Cotton, qt."
capture label var j_v_yarn_mixedWoolCotton "Input: Mixed Wool and Cotton, value"
capture label var j_q_yarn_mixedWorstedCotton "Input: Mixed Worsted and Cotton, qt."
capture label var j_v_yarn_mixedWorstedCotton "Input: Yarn Mixed Worsted and Cotton, value"
capture label var j_q_yarn_cottonNotMercerized "Input: Yarn Cotton Not Mercerized, qt."
capture label var j_v_yarn_cottonNotMercerized "Input: Yarn Cotton Not Mercerized, value"
capture label var j_q_yarn_cottonMercerized "Input: Yarn Cotton Mercerized, qt."
capture label var j_v_yarn_cottonMercerized "Input: Yarn Cotton Mercerized, value"
capture label var j_q_yarn_silk "Input: Yarn silk, qt."
capture label var j_v_yarn_silk "Input: Yarn silk, value"
capture label var j_q_yarn_rayon "Input: Yarn rayon, qt."
capture label var j_v_yarn_rayon "Input: Yarn rayon, value"
capture label var j_s_yarn_other1 "Input: Yarn other 1, specify"
capture label var j_q_yarn_other1 "Input: Yarn other 1, qt."
capture label var j_v_yarn_other1 "Input: Yarn other 1, value"
capture label var j_q_wool_noils "Input: Wool noils, qt."
capture label var j_v_wool_noils "Input: Wool noils, value"
capture label var j_q_silk_noils "Input: Silk noils, qt."
capture label var j_v_silk_noils "Input: Silk noils, value"
capture label var j_q_cotton_waste "Input: Cotton waste, qt."
capture label var j_v_cotton_waste "Input: Cotton waste, value"
capture label var j_q_wool_waste "Input: Wool waste, qt."
capture label var j_v_wool_waste "Input: Wool waste, value"
capture label var j_q_silk_waste "Input: Silk waste, qt."
capture label var j_v_silk_waste "Input: Silk waste, value"
capture label var j_q_recovered_wool "Input: Recovered wool, qt."
capture label var j_v_recovered_wool "Input: Recovered wool, value"
