//label variables for industry 1307

//output variables
capture label var gp_q_bendingMachine "Output: Bending Machine, qt."
capture label var gp_v_bendingMachine  "Output: Bending Machines, value"
capture label var gp_q_boringHorizontal  "Output: Boring Machine Horizontal, qt."
capture label var gp_v_boringHorizontal  "Output: Boring Machine Horizontal, value"
capture label var gp_q_boringVert_general  "Output: Boring Machine Vertical General utility, qt."
capture label var gp_v_boringVert_general "Output: Boring Machine Vertical General utility, value"
capture label var gp_q_boringVert_heavy   "Output: Boring Machine Vertical Heavy duty, qt."
capture label var gp_v_boringVert_heavy   "Output: Boring Machine Vertical Heavy duty, value"
capture label var gp_q_boring_special "Output: Boring Machine Special combined boring, drilling, and milling, qt."
capture label var gp_v_boring_special  "Output: Boring Machine Special combined boring, drilling, and milling, value"
capture label var gp_q_boring_special_turning  "Output: Boring Machine Special boring and Turning, qt."
capture label var gp_v_boring_special_turning  "Output: Boring Machine Special boring and Turning, value"
capture label var gp_s_boring_other1  "Output: Boring Machine Other 1, specify"
capture label var gp_q_boring_other1  "Output: Boring Machine Other 1, qt."
capture label var gp_v_boring_other1  "Output: Boring Machine Other 1, value"
capture label var gp_s_boring_other2  "Output: Boring Machine Other 2, specify"
capture label var gp_q_boring_other2  "Output: Boring Machine Other 2, qt."
capture label var gp_v_boring_other2  "Output: Boring Machine Other 2, value"
capture label var gp_q_broaching "Output: Broaching Machine, qt."
capture label var gp_v_broaching  "Output: Broaching Machine, value"
capture label var gp_q_cutting_off_auto  "Output: Cutting off machine automatic, qt."
capture label var gp_v_cutting_off_auto  "Output: Cutting off machine automatic, value"
capture label var gp_q_cutting_off_band  "Output: Cutting off Bandsaw, qt."
capture label var gp_v_cutting_off_band  "Output: Cutting off Bandsaw, value"
capture label var gp_q_cutting_off_coldsaw  "Output: Cutting off Coldsaw, qt."
capture label var gp_v_cutting_off_coldsaw  "Output: Cutting off Coldsaw, value"
capture label var gp_q_cutting_off_hacksaw  "Output: Cutting off Hacksaw, qt."
capture label var gp_v_cutting_off_hacksaw "Output: Cutting off Hacksaw, value"
capture label var gp_q_drilling_auto  "Output: Drilling machine automatic, qt."
capture label var gp_v_drilling_auto  "Output: Drilling machine automatic, value"
capture label var gp_q_drilling_bench  "Output: Drilling machine bench, qt."
capture label var gp_v_drilling_bench "Output: Drilling machine bench, value"
capture label var gp_q_drilling_horizSingle  "Output: Drilling machine horizontal single-spindle, qt."
capture label var gp_v_drilling_horizSingle  "Output: Drilling machine horizontal single-spindle, value"
capture label var gp_q_drilling_horizMult  "Output: Drilling machine horizontal multiple-spindle, qt."
capture label var gp_v_drilling_horizMult "Output: Drilling machine horizontal multiple-spindle, value"
capture label var gp_q_drilling_vertMult "Output: Drilling machine vertical multiple-spindle, qt."
capture label var gp_v_drilling_vertMult  "Output: Drilling machine vertical multiple-spindle, value"
capture label var gp_q_drilling_vertUniv  "Output: Drilling machine vertical universal-head, qt."
capture label var gp_v_drilling_vertUniv  "Output: Drilling machine vertical universal-head, value"
capture label var gp_q_drilling_vertStd "Output: Drilling machine vertical standard, qt."
capture label var gp_v_drilling_vertStd  "Output: Drilling machine vertical standard, value"
capture label var gp_q_drilling_sensitiveSingle "Output: Drilling machine Sensitive single-spindle, qt."
capture label var gp_v_drilling_sensitiveSingle "Output: Drilling machine Sensitive single-spindle, value"
capture label var gp_q_drilling_sensitiveMult "Output: Drilling machine Sensitive spindle, qt."
capture label var gp_v_drilling_sensitiveMult  "Output: Drilling machine Sensitive spindle, value"
capture label var gp_q_drilling_radialPlain  "Output: Drilling machine Radial Plain, qt."
capture label var gp_v_drilling_radialPlain  "Output: Drilling machine Radial Plain, value"
capture label var gp_q_drilling_radialUniv  "Output: Drilling machine Radial Universal, qt."
capture label var gp_v_drilling_radialUniv "Output: Drilling machine Radial Universal, value"
capture label var gp_q_drilling_combined  "Output: Drilling machine Combined Vertical and Horizontal, qt."
capture label var gp_v_drilling_combined  "Output: Drilling machine Combined Vertical and Horizontal, value"
capture label var gp_v_drilling_other  "Output: Drilling machine Other, value"
capture label var gp_q_honing  "Output: Honing machine, qt."
capture label var gp_v_honing "Output: Honing machine, value"
capture label var gp_q_forging_bulldozer "Output: Forging machine bulldozer, qt."
capture label var gp_v_forging_bulldozer  "Output: Forging machine, value"
capture label var gp_q_forging_bolt  "Output: Forging machine bolt, nut, rivet, qt."
capture label var gp_v_forging_bolt  "Output: Forging machine bolt, nut, rivet, value"
capture label var gp_s_forging_other  "Output: Forging machine other, specify"
capture label var gp_v_forging_other  "Output: Forging machine other, value"
capture label var gp_q_gearCutting_hobbing  "Output: Gear cutting machine Hobbing, qt."
capture label var gp_v_gearCutting_hobbing  "Output: Gear cutting machine Hobbing, value"
capture label var gp_q_gearCutting_spur  "Output: Gear cutting machine Formed rotary cutter, type spur, qt."
capture label var gp_v_gearCutting_spur  "Output: Gear cutting machine Formed rotary cutter, type spur, value"
capture label var gp_q_gearCutting_bevel  "Output: Gear cutting machine Formed rotary cutter, type bevel, qt."
capture label var gp_v_gearCutting_bevel  "Output: Gear cutting machine Formed rotary cutter, type bevel, value"
capture label var gp_q_gearCutting_generator  "Output: Gear cutting machine Generator, qt."
capture label var gp_v_gearCutting_generator  "Output: Gear cutting machine Generator, value"
capture label var gp_q_grinding_cutter "Output: Grinding Machine Cutter, qt."
capture label var gp_v_grinding_cutter "Output: Grinding Machine Cutter, value"
capture label var gp_q_grinding_drill  "Output: Grinding Machine Drill, qt."
capture label var gp_v_grinding_drill "Output: Grinding Machine Drill, value"
capture label var gp_q_grinding_disk  "Output: Grinding Machine Disk, qt."
capture label var gp_v_grinding_disk  "Output: Grinding Machine Disk, value"
capture label var gp_q_grinding_externalPl "Output: Grinding Machine External Cylindrical Plain, qt."
capture label var gp_v_grinding_externalPl  "Output: Grinding Machine External Cylindrical Plain, value"
capture label var gp_q_grinding_externalUniv "Output: Grinding Machine External Cylindrical Universal, qt."
capture label var gp_v_grinding_externalUniv   "Output: Grinding Machine External Cylindrical Universal, value"
capture label var gp_q_grinding_internal   "Output: Grinding Machine Internal Cylindrical, qt."
capture label var gp_v_grinding_internal "Output: Grinding Machine Internal Cylindrical, value"
capture label var gp_q_grinding_sufaceHoriz   "Output: Grinding Machine Surface Horizontal, qt."
capture label var gp_v_grinding_sufaceHoriz   "Output: Grinding Machine Surface Horizontal, value"
capture label var gp_q_grinding_sufaceVert   "Output: Grinding Machine Surface Vertical, qt."
capture label var gp_v_grinding_sufaceVert  "Output: Grinding Machine Surface Vertical, value"
capture label var gp_q_grinding_wet  "Output: Grinding Machine Wet, qt."
capture label var gp_v_grinding_wet  "Output: Grinding Machine Wet, value"
capture label var gp_s_grinding_other1  "Output: Grinding Machine Other 1, specify"
capture label var gp_q_grinding_other1  "Output: Grinding Machine Other 1, qt."
capture label var gp_v_grinding_other1  "Output: Grinding Machine Other 1, value"
capture label var gp_s_grinding_other2  "Output: Grinding Machine Other 2, specify"
capture label var gp_q_grinding_other2  "Output: Grinding Machine Other 2, qt."
capture label var gp_v_grinding_other2  "Output: Grinding Machine Other 2, value"
capture label var gp_q_hammers_steamSingle  "Output: Hammers not portable, qt."
capture label var gp_v_hammers_steamSingle  "Output: Hammers not portable, value"
capture label var gp_q_hammers_steamDouble  "Output: Hammers not portable, qt."
capture label var gp_v_hammers_steamDouble  "Output: Hammers not portable, value"
capture label var gp_q_hammers_air  "Output: Hammers not portable Air, qt."
capture label var gp_v_hammers_air  "Output: Hammers not portable Air, value"
capture label var gp_q_hammers_drop  "Output: Hammers not portable Drop, qt."
capture label var gp_v_hammers_drop  "Output: Hammers not portable Drop, value"
capture label var gp_q_hammers_power "Output: Hammers not portable Power, qt."
capture label var gp_v_hammers_power  "Output: Hammers not portable Power, value"
capture label var gp_s_hammers_other  "Output: Hammers not portable other, specify"
capture label var gp_q_hammers_other  "Output: Hammers not portable other, qt."
capture label var gp_v_hammers_other  "Output: Hammers not portable other, value"
capture label var gp_q_keyseaters  "Output: Keyseaters, qt."
capture label var gp_v_keyseaters  "Output: Keyseaters, value"
capture label var gp_q_lathes_bench  "Output: Lathes Bench, qt."
capture label var gp_v_lathes_bench  "Output: Lathes Bench, value"
capture label var gp_q_lathes_engine "Output: Lathes Engine  General, qt."
capture label var gp_v_lathes_engine  "Output: Lathes Engine General, value"
capture label var gp_q_lathes_engine_under16 "Output: Lathes Engine under 16 inches, qt."
capture label var gp_v_lathes_engine_under16  "Output: Lathes Engine under 16 inches, value"
capture label var gp_q_lathes_engine_16_22  "Output: Lathes Engine 16-22 inches, qt."
capture label var gp_v_lathes_engine_16_22 "Output: Lathes Engine 16-22 inches, value"
capture label var gp_q_lathes_engine_22_36 "Output: Lathes Engine 22-36 inches, qt."
capture label var gp_v_lathes_engine_22_36 "Output: Lathes Engine 22-36 inches, value"
capture label var gp_q_lathes_heavy "Output: Lathes Heavy Duty, qt."
capture label var gp_v_lathes_heavy  "Output: Lathes Heavy duty, value"
capture label var gp_q_lathes_gap  "Output: Lathes Gap, qt."
capture label var gp_v_lathes_gap  "Output: Lathes Gap, value"
capture label var gp_q_lathes_hand  "Output: Lathes Hand or speed, qt."
capture label var gp_v_lathes_hand  "Output: Lathes Hand or speed, value"
capture label var gp_q_lathes_polishing  "Output: Lathes Polishing and buffing, qt."
capture label var gp_v_lathes_polishing "Output: Lathes Polishing and buffing, value"
capture label var gp_q_lathes_automaticSingle_bar "Output: Lathes Automatic single-spindle, qt."
capture label var gp_v_lathes_automaticSingle_bar  "Output: Lathes Automatic single-spindle, value"
capture label var gp_q_lathes_automaticSingle_chucking  "Output: Lathes Automatic single-spindle, qt."
capture label var gp_v_lathes_automaticSingle_chucking  "Output: Lathes Automatic single-spindle, value"
capture label var gp_q_lathes_automaticMult_bar  "Output: Lathes Automatic multiple-spindle, qt."
capture label var gp_v_lathes_automaticMult_bar  "Output: Lathes Automatic multiple-spindle, value"
capture label var gp_q_lathes_automaticMult_chucking  "Output: Lathes Automatic multiple-spindle, qt."
capture label var gp_v_lathes_automaticMult_chucking   "Output: Lathes Automatic multiple-spindle, value"
capture label var gp_q_lathes_turret_horizRam  "Output: Lathes Horizontal Hand-operated Ram-type, qt."
capture label var gp_v_lathes_turret_horizRam  "Output: Lathes Horizontal Hand-operated Ram-type, value"
capture label var gp_q_lathes_turret_horizSaddle_std  "Output: Lathes Horizontal Hand-operated Saddle-type standard, qt."
capture label var gp_v_lathes_turret_horizSaddle_std   "Output: Lathes Horizontal Hand-operated Saddle-type standard, value"
capture label var gp_q_lathes_turret_horizSaddle_heavy "Output: Lathes Horizontal Hand-operated Saddle-type heavy duty, qt."
capture label var gp_v_lathes_turret_horizSaddle_heavy  "Output: Lathes Horizontal Hand-operated Saddle-type heavy duty, value"
capture label var gp_q_lathes_turret_vert_hand  "Output: Lathes Vertical Hand-operated, qt."
capture label var gp_v_lathes_turret_vert_hand  "Output: Lathes Vertical Hand-operated, value"
capture label var gp_q_lathes_turret_vert_auto  "Output: Lathes Vertical Automatic, qt."
capture label var gp_v_lathes_turret_vert_auto  "Output: Lathes Vertical Automatic, value"
capture label var gp_q_milling_hand  "Output: Milling Machines Hand feed, qt."
capture label var gp_v_milling_hand  "Output: Milling Machines Hand feed, value"
capture label var gp_q_milling_power_auto  "Output: Milling Machines Power feed Automatic, qt."
capture label var gp_v_milling_power_auto  "Output: Milling Machines Power feed Automatic, value"
capture label var gp_q_milling_power_plain "Output: Milling Machines Power feed Plain, qt."
capture label var gp_v_milling_power_plain  "Output: Milling Machines Power feed Plain, value"
capture label var gp_q_milling_power_univ  "Output: Milling Machines Power feed Universal, qt."
capture label var gp_v_milling_power_univ  "Output: Milling Machines Power feed Universal, value"
capture label var gp_q_milling_power_vert  "Output: Milling Machines Power feed Vertical, qt."
capture label var gp_v_milling_power_vert  "Output: Milling Machines Power feed Vertical, value"
capture label var gp_q_milling_power_lincoln  "Output: Milling Machines Power feed Lincoln type, qt."
capture label var gp_v_milling_power_lincoln  "Output: Milling Machines Power feed Lincoln type, value"
capture label var gp_q_milling_power_planer  "Output: Milling Machines Power feed Planer type, qt."
capture label var gp_v_milling_power_planer  "Output: Milling Machines Power feed Planer type, value"
capture label var gp_s_milling_power_other1 "Output: Milling Machines Power feed Other 1, specify"
capture label var gp_q_milling_power_other1 "Output: Milling Machines Power feed Other 1, qt."
capture label var gp_v_milling_power_other1 "Output: Milling Machines Power feed Other 1, value"
capture label var gp_s_milling_power_other2 "Output: Milling Machines Power feed Other 2, specify"
capture label var gp_q_milling_power_other2 "Output: Milling Machines Power feed Other 2, qt."
capture label var gp_v_milling_power_other2 "Output: Milling Machines Power feed Other 2, value"
capture label var gp_s_milling_power_other3 "Output: Milling Machines Power feed Other 3, specify"
capture label var gp_q_milling_power_other3 "Output: Milling Machines Power feed Other 3, qt."
capture label var gp_v_milling_power_other3  "Output: Milling Machines Power feed Other 3, value"
capture label var gp_q_planer_under36  "Output: Planers Under 36 inches, qt."
capture label var gp_v_planer_under36  "Output: Planers Under 36 inches, value"
capture label var gp_q_planer_over36 "Output: Planers Over 36 inches, qt."
capture label var gp_v_planer_over36  "Output: Planers Over 36 inches, value"
capture label var gp_q_planer_openSide  "Output: Planers Open-side, qt."
capture label var gp_v_planer_openSide  "Output: Planers Open-side, value"
capture label var gp_s_planer_special1  "Output: Planers Special 2, specify"
capture label var gp_q_planer_special1 "Output: Planers Special 2, qt."
capture label var gp_v_planer_special1  "Output: Planers Special 2, value"
capture label var gp_s_planer_special2  "Output: Planers Special 2, specify"
capture label var gp_q_planer_special2  "Output: Planers Special 2, qt."
capture label var gp_v_planer_special2  "Output: Planers Special 2, value"
capture label var gp_q_pipecutting_single  "Output: Pipecutting and threading machines Single-head, qt."
capture label var gp_v_pipecutting_single  "Output: Pipecutting and threading machines Single-head, value"
capture label var gp_q_pipecutting_mult  "Output: Pipecutting and threading machines Multiple-head, qt."
capture label var gp_v_pipecutting_mult  "Output: Pipecutting and threading machines Multiple-head, value"
capture label var gp_q_portable_drill_elec "Output: Portable tools Drill Electric, qt."
capture label var gp_v_portable_drill_elec  "Output: Portable tools Drill Electric, value"
capture label var gp_q_portable_drill_pneu  "Output: Portable tools Drill Pneumatic, qt."
capture label var gp_v_portable_drill_pneu "Output: Portable tools Drill Pneumatic, value"
capture label var gp_q_portable_grinder_elec  "Output: Portable tools Grinder Electric, qt."
capture label var gp_v_portable_grinder_elec  "Output: Portable tools Grinder Electric, value"
capture label var gp_q_portable_grinder_pneu  "Output: Portable tools Grinder Pneumatic, qt."
capture label var gp_v_portable_grinder_pneu  "Output: Portable tools Grinder Pneumatic, value"
capture label var gp_q_portable_hammer_elec  "Output: Portable tools Hammer Electric, qt."
capture label var gp_v_portable_hammer_elec  "Output: Portable tools Hammer Electric, value"
capture label var gp_q_portable_hammer_pneu  "Output: Portable tools Hammer Pneumatic, qt."
capture label var gp_v_portable_hammer_pneu  "Output: Portable tools Hammer  Pneumatic, value"
capture label var gp_q_portable_woodworking_elec  "Output: Portable tools Woodworking Electric, qt."
capture label var gp_v_portable_woodworking_elec  "Output: Portable tools Woodworking Electric, value"
capture label var gp_s_portable_woodworking_other1  "Output: Portable tools Woodworking Other 2, specify"
capture label var gp_q_portable_woodworking_other1  "Output: Portable tools Woodworking Other 1, qt."
capture label var gp_v_portable_woodworking_other1  "Output: Portable tools Woodworking Other 1, value"
capture label var gp_s_portable_woodworking_other2  "Output: Portable tools Woodworking Other 2, specify"
capture label var gp_q_portable_woodworking_other2  "Output: Portable tools Woodworking Other 2, qt."
capture label var gp_v_portable_woodworking_other2 "Output: Portable tools Woodworking Other 2, value"
capture label var gp_s_portable_other1 "Output: Portable tools Other 1, specify"
capture label var gp_q_portable_other1  "Output: Portable tools Other 1, qt."
capture label var gp_v_portable_other1 "Output: Portable tools Other 1, value"
capture label var gp_s_portable_other2  "Output: Portable tools Other 2, specify"
capture label var gp_q_portable_other2  "Output: Portable tools Other 2, qt."
capture label var gp_v_portable_other2  "Output: Portable tools Other 2, value"
capture label var gp_q_portable_flexShaft "Output: Portable tools Flexible Shaft, qt."
capture label var gp_v_portable_flexShaft  "Output: Portable tools Flexible Shaft, value"
capture label var gp_q_press_arbor  "Output: Presses Arbor, qt."
capture label var gp_v_press_arbor  "Output: Presses Arbor, value"
capture label var gp_q_press_forming "Output: Presses Forming, qt."
capture label var gp_v_press_forming  "Output: Presses Forming, value"
capture label var gp_q_press_hand "Output: Presses Hand, qt."
capture label var gp_v_press_hand "Output: Presses Hand, value"
capture label var gp_q_press_hydraulic  "Output: Presses Hydraulic, qt."
capture label var gp_v_press_hydraulic "Output: Presses Hydraulic, value"
capture label var gp_q_press_stampingFoot  "Output: Presses Stamping Foot, qt."
capture label var gp_v_press_stampingFoot  "Output: Presses Stamping Foot, value"
capture label var gp_q_press_stampingPower  "Output: Presses Stamping Power, qt."
capture label var gp_v_press_stampingPower  "Output: Presses Stamping Power, value"
capture label var gp_q_press_punch  "Output: Presses Punch, qt."
capture label var gp_v_press_punch "Output: Presses Punch, value"
capture label var gp_q_press_other  "Output: Presses Other, qt."
capture label var gp_v_press_other  "Output: Presses Other, value"
capture label var gp_q_punching_notPortable "Output: Punching machines not portable, qt."
capture label var gp_v_punching_notPortable  "Output: Punching machines not portable, value"
capture label var gp_q_riveting_light "Output: Riveting machines not portable light duty, qt."
capture label var gp_v_riveting_light "Output: Riveting machines not portable light duty, value"
capture label var gp_q_riveting_heavy "Output: Riveting machines not portable heavy duty, qt."
capture label var gp_v_riveting_heavy  "Output: Riveting machines not portable heavy duty, value"
capture label var gp_q_sharper_vert  "Output: Sharpers Vertical, qt."
capture label var gp_v_sharper_vert  "Output: Sharpers Vertical, value"
capture label var gp_q_sharper_horizUnder20  "Output: Sharpers Horizontal Under 20 inch stroke, qt."
capture label var gp_v_sharper_horizUnder20  "Output: Sharpers Horizontal Under 20 inch stroke, value"
capture label var gp_q_sharper_horizOver20 "Output: Sharpers Horizontal Over 20 and Under 28 inch stroke, qt."
capture label var gp_v_sharper_horizOver20  "Output: Sharpers Horizontal Over 20 and Under 28 inch stroke, value"
capture label var gp_q_sharper_horizOver28  "Output: Sharpers Horizontal Over 28 inch stroke, qt."
capture label var gp_v_sharper_horizOver28  "Output: Sharpers Horizontal Over 28 inch stroke, value"
capture label var gp_q_shears_alligator "Output: Shears Alligator, qt."
capture label var gp_v_shears_alligator  "Output: Shears Alligator, value"
capture label var gp_q_shears_comboPunch  "Output: Shears Combination punch and shear, qt."
capture label var gp_v_shears_comboPunch  "Output: Shears Combination punch and shear, value"
capture label var gp_q_shears_rotary  "Output: Shears Rotary, qt."
capture label var gp_v_shears_rotary  "Output: Shears Rotary, value"
capture label var gp_q_shears_straight  "Output: Shears Straight, qt."
capture label var gp_v_shears_straight  "Output: Shears Straight, value"
capture label var gp_s_shears_other1  "Output: Shears Other 1, specify"
capture label var gp_q_shears_other1  "Output: Shears Other 1, qt."
capture label var gp_v_shears_other1  "Output: Shears Other 1, value"
capture label var gp_q_slotters  "Output: Slotters, qt."
capture label var gp_v_slotters  "Output: Slotters, value"
capture label var gp_q_threading_die  "Output: Threading Machines Die Type, qt."
capture label var gp_v_threading_die  "Output: Threading Machines Die Type, value"
capture label var gp_q_threading_milling "Output: Threading Machines Milling Type, qt."
capture label var gp_v_threading_milling "Output: Threading Machines Milling Type, value"
capture label var gp_q_threading_rolling  "Output: Threading Machines Rolling Type, qt."
capture label var gp_v_threading_rolling  "Output: Threading Machines Rolling Type, value"
capture label var gp_q_threading_tapping  "Output: Threading Machines Tapping Type, qt."
capture label var gp_v_threading_tapping  "Output: Threading Machines Tapping Type, value"
capture label var gp_s_machineTool_other1  "Output: Machine Tool Other 1, specify"
capture label var gp_q_machineTool_other1  "Output: Machine Tool Other 1, qt."
capture label var gp_v_machineTool_other1  "Output: Machine Tool Other 1, value"
capture label var gp_s_replacement1 "Output: Replacement and repair parts 1, specify"
capture label var gp_q_replacement1  "Output: Replacement and repair parts 1, qt."
capture label var gp_v_replacement1  "Output: Replacement and repair parts 1, value"
capture label var gp_s_replacement2  "Output: Replacement and repair parts 2, specify"
capture label var gp_q_replacement2  "Output: Replacement and repair parts 2, qt."
capture label var gp_v_replacement2  "Output: Replacement and repair parts 2, value"
capture label var gp_s_replacement3  "Output: Replacement and repair parts 3, specify"
capture label var gp_q_replacement3  "Output: Replacement and repair parts 3, qt."
capture label var gp_v_replacement3  "Output: Replacement and repair parts 3, value"
capture label var gp_s_replacement4  "Output: Replacement and repair parts 4, specify"
capture label var gp_q_replacement4  "Output: Replacement and repair parts 4, qt."
capture label var gp_v_replacement4  "Output: Replacement and repair parts 4, value"
capture label var gp_s_replacement5  "Output: Replacement and repair parts 5, specify"
capture label var gp_q_replacement5  "Output: Replacement and repair parts 5, qt."
capture label var gp_v_replacement5  "Output: Replacement and repair parts 5, value"
capture label var gp_v_attachment_chucksDrills  "Output: Attachments Chucks Drilles, value"
capture label var gp_v_attachment_chucksLathes  "Output: Attachments Chucks Lathes, value"
capture label var gp_v_attachment_chucksMagnetic "Output: Attachments Chucks Magnetic, value"
capture label var gp_v_attachment_vises "Output: Attachments Vises, value"
capture label var gp_v_attachment_boring "Output: Attachments Boring, value"
capture label var gp_v_attachment_drilling "Output: Attachments Drilling, value"
capture label var gp_v_attachment_lathe "Output: Attachments Lathe, value"
capture label var gp_v_attachment_milling "Output: Attachments Milling, value"
capture label var gp_v_attachment_other  "Output: Attachments Other, value"
capture label var gp_v_special_jigs  "Output: Jigs and fixtures, value"
capture label var gp_v_special_subpresses  "Output: Subpresses, punches, etc., value"
capture label var gp_v_special_diecasting  "Output: Die casting dies, value"
capture label var gp_v_special_tools_screw "Output: Tools for screw and automatic machines, value"
capture label var gp_v_special_tools_designed  "Output: Tools Designed, value"
capture label var gp_v_special_machinery  "Output: Special machinery, model and experimental work, value"
capture label var gp_s_special_other1 "Output: Special Tool Other 1, specify"
capture label var gp_v_special_other1  "Output: Special Tool Other 1, value"
capture label var gp_s_special_other2  "Output: Special Tool Other 2, specify"
capture label var gp_v_special_other2  "Output: Special Tool Other 2, value"
capture label var gp_s_special_other3  "Output: Special Tool Other 3, specify"
capture label var gp_v_special_other3  "Output: Special Tool Other 3, value"
capture label var gp_s_special_other4  "Output: Special Tool Other 4, specify"
capture label var gp_v_special_other4  "Output: Special Tool Other 4, value"
capture label var gp_s_special_other5  "Output: Special Tool Other 5, specify"
capture label var gp_v_special_other5  "Output: Special Tool Other 5, value"
capture label var gp_s_special_other6  "Output: Special Tool Other 6, specify"
capture label var gp_v_special_other6  "Output: Special Tool Other 6, value"
capture label var gp_v_smallTools_arbors "Output: Small Tools Arbors, value"
capture label var gp_v_smallTools_collets "Output: Small Tools Collets, value"
capture label var gp_v_smallTools_counterbores  "Output: Small Tools Counterbores, value"
capture label var gp_v_smallTools_countersinks "Output: Small Tools Countersinks, value"
capture label var gp_v_smallTools_drills_carbon "Output: Small Tools Drills, value"
capture label var gp_v_smallTools_drills_HS "Output: Small Tools Drills, value"
capture label var gp_v_smallTools_hobbingCutters_carbon  "Output: Small Tools Hobbing Cutters, value"
capture label var gp_v_smallTools_hobbingCutters_HS "Output: Small Tools Hobbing Cutters, value"
capture label var gp_v_smallTools_lathes_tools_carbon  "Output: Small Tools Lathe Tool, value"
capture label var gp_v_smallTools_lathes_tools_HS  "Output: Small Tools Lathe Tool, value"
capture label var gp_v_smallTools_milling_solid_carbon  "Output: Small Tools Milling Cutter Solid, value"
capture label var gp_v_smallTools_milling_solid_HS "Output: Small Tools Milling Cutter Solid, value"
capture label var gp_v_smallTools_milling_insertedTeeth  "Output: Small Tools Milling Inserted Teeth, value"
capture label var gp_v_smallTools_reamer_carbon "Output: Small Tools Reamer, value"
capture label var gp_v_smallTools_reamer_HS "Output: Small Tools Reamer, value"
capture label var gp_v_smallTools_sawBlade_hack_carbon "Output: Small Tools Saw blade Hack, value"
capture label var gp_v_smallTools_sawBlade_hack_HS  "Output: Small Tools Saw blade Hack, value"
capture label var gp_v_smallTools_sawBlade_band_carbon "Output: Small Tools Saw blade Band, value"
capture label var gp_v_smallTools_sawBlade_band_HS  "Output: Small Tools Saw blade Band, value"
capture label var gp_v_smallTools_sawBlade_cold_carbon "Output: Small Tools Saw blade Cold, value"
capture label var gp_v_smallTools_sawBlade_cold_HS "Output: Small Tools Saw blade Cold, value"
capture label var gp_v_smallTools_taps_carbon  "Output: Small Tools Taps and dies (not pipe threading) Carbon, value"
capture label var gp_v_smallTools_taps_HS "Output: Small Tools Taps and dies (not pipe threading) High Speed, value"
capture label var gp_v_smallTools_dies_carbon "Output: Small Tools Taps and dies (not pipe threading) Carbon, value"
capture label var gp_v_smallTools_dies_HS  "Output: Small Tools Taps and dies (not pipe threading) High Speed, value"
capture label var gp_v_smallTools_taps_chasers "Output: Small Tools Taps and dies (not pipe threading) chasers, value"
capture label var gp_v_smallTools_pipe_threadingTaps  "Output: Small Tools Pipe threading taps, value"
capture label var gp_v_smallTools_pipe_threadingDie "Output: Small Tools Pipe threading dies, value"
capture label var gp_v_smallTools_pipe_threadingPipe "Output: Small Tools Pipe threading pipe stocks, value"
capture label var gp_v_smallTools_otherCutting  "Output: Small Tools Other Cutting, value"
capture label var gp_v_smallTools_precisionMeasuring "Output: Small Tools Precision Measuring Tools, value"
capture label var gp_v_smallTools_gauges "Output: Small Tools Gauges, value"
capture label var gp_v_smallTools_otherMeasuring  "Output: Small Tools Other Measuring Tools, value"
capture label var gp_u_foundry_ironCastings  "Output:  Foundry Iron Castings, unit"
capture label var gp_v_foundry_ironCastings  "Output: Foundry Iron Castings, value"
capture label var gp_u_foundry_greyCastings_sand  "Output: Foundry Grey Castings made in sand molds, unit"
capture label var gp_v_foundry_greyCastings_sand  "Output: Foundry Grey Castings made in sand molds, value"
capture label var gp_u_foundry_greyCastings_metal  "Output: Foundry Grey Castings made in metal molds, unit"
capture label var gp_v_foundry_greyCastings_metal  "Output: Foundry  Grey Castings made in metal molds, value"
capture label var gp_u_foundry_alCastings  "Output: Foundry Aluminum castings, unit"
capture label var gp_v_foundry_alCastings  "Output: Foundry Aluminum castings, value"
capture label var gp_u_foundry_nonFerrousCastings "Output: Foundry, unit"
capture label var gp_v_foundry_nonFerrousCastings  "Output: Foundry, value"
capture label var gp_u_foundry_stampings  "Output: Foundry Metal Stampings, unit"
capture label var gp_v_foundry_stampings "Output: Foundry Metal Stampings, value"
 
//label machinery variables
capture label var z_motors_n  "Machinery (industry 1307): Motors, value"
capture label var z_motors_c  "Machinery (industry 1307): Motors, capacity"
capture label var z_motors_v  "Machinery (industry 1307): Motors, value"
capture label var z_control_apparatus_n "Machinery (industry 1307): Control Apparatus, Number"
capture label var z_control_apparatus_v  "Machinery (industry 1307): Control Apparatus, value"
