//label variables for industry 118

//label input variables
capture label var j_q_milk_fluid "Input: milk (fluid), qt"
capture label var j_v_milk_fluid "Input: milk (fluid), value"
capture label var j_q_milk_powdered "Input: milk (powdered), qt"
capture label var j_v_milk_powdered "Input: milk (powdered), value"
capture label var j_q_milk_evaporated "Input: milk (evaporated), qt"
capture label var j_v_milk_evaporated "Input: milk (evaporated), value"
capture label var j_q_cream "Input: cream, qt"
capture label var j_v_cream "Input: cream, value"
capture label var j_q_ice_cream_mix "Input: ice cream mix, qt"
capture label var j_v_ice_cream_mix "Input: ice cream mix, value"
capture label var j_q_creamery_butter "Input: creamery butter, qt"
capture label var j_v_creamery_butter "Input: creamery butter, value"
capture label var j_q_sugar "Input: sugar, qt"
capture label var j_v_sugar "Input: sugar, value"
capture label var j_v_flavors "Input: flavors, value"
capture label var j_v_eggs "Input: eggs, value"
capture label var j_q_eggs "Input: eggs, qt."
capture label var j_q_butter_fat "Input: butter fat, qt"
capture label var j_v_butter_fat "Input: butter fat, value"
capture label var j_s_other1 "Input: other 1, specify"
capture label var j_q_other1 "Input: other 1, qt"
capture label var j_v_other1 "Input: other 1, value"
capture label var j_s_other2 "Input: other 2, specify"
capture label var j_q_other2 "Input: other 2, qt"
capture label var j_v_other2 "Input: other 2, value"

//label distribution variables
capture label var wholesale_exclusive "Do you sell wholesale exclusively?"
capture label var retail_exclusive "Do you sell retail exclusively?"
capture label var wholesale_and_retail "Or both wholesale and retail?"

//label output variables
capture label var gp_q_ice_cream "Output: ice cream, qt"
capture label var gp_v_ice_cream "Output: ice cream, value"
capture label var gp_q_ices "Output: ices, qt"
capture label var gp_v_ices "Output: ices, value"
capture label var gp_q_specialties "Output: specialties, qt"
capture label var gp_v_specialties "Output: specialties, value"
capture label var gp_q_ice_cream_mix "Output: ice cream mix, qt"
capture label var gp_v_ice_cream_mix "Output: ice cream mix, value"
capture label var gp_q_ice_sale "Output: ice made for sale, qt"
capture label var gp_v_ice_sale "Output: ice made for sale, value"
capture label var gp_q_ice_consumed "Output: ice consumed, qt"
capture label var gp_v_ice_consumed "Output: ice consumed, value"
capture label var gp_q_butter "Output: butter, qt"
capture label var gp_v_butter "Output: butter, value"
capture label var gp_q_cheese "Output: cheese, qt"
capture label var gp_v_cheese "Output: cheese, value"
capture label var gp_q_condensed_milk "Output: condensed milk, qt"
capture label var gp_v_condensed_milk "Output: condensed milk, value"
capture label var gp_q_evaporated_milk "Output: evaporated milk, qt"
capture label var gp_v_evaporated_milk "Output: evaporated milk, value"
capture label var gp_q_confectionery "Output: confectionery, qt"
capture label var gp_v_confectionery "Output: confectionery, value"
capture label var gp_q_beverages "Output: beverages, qt"
capture label var gp_v_beverages "Output: beverages, value"
capture label var gp_q_creamery_butter "Output: Creamery butter, qt."
capture label var gp_v_creamery_butter "Output: Creamery butter, value"
capture label var gp_q_cheese_whole_milk "Output: Cheese, American or Cheddar: whole milk, qt"
capture label var gp_v_cheese_whole_milk "Output: Cheese, American or Cheddar: whole milk, value"
capture label var gp_q_cheese_part_skim "Output: Cheese, American or Cheddar: part skim, qt"
capture label var gp_v_cheese_part_skim "Output: Cheese, American or Cheddar: part skim, value"
capture label var gp_q_cheese_full_skim "Output: Cheese, American or Cheddar: full skim, qt"
capture label var gp_v_cheese_full_skim "Output: Cheese, American or Cheddar: full skim, value"
capture label var gp_q_swiss "Output: Swiss (including block), qt"
capture label var gp_v_swiss "Output: Swiss (including block), value"
capture label var gp_q_brick "Output: Brick, qt"
capture label var gp_v_brick "Output: Brick, value"
capture label var gp_q_munster "Output: Munster, qt"
capture label var gp_v_munster "Output: Munster, value"
capture label var gp_q_limburger "Output: Limburger, qt"
capture label var gp_v_limburger "Output: Limburger, value"
capture label var gp_q_cottage "Output: Cottage, pot, and bakery, qt"
capture label var gp_v_cottage "Output: Cottage, pot, and bakery, value"
capture label var gp_q_cream "Output: Cream (not cottage), qt"
capture label var gp_v_cream "Output: Cream (not cottage), value"
capture label var gp_q_neufchatel "Output: Neufchatel, qt"
capture label var gp_v_neufchatel "Output: Neufchatel, value"
capture label var gp_s_italian_varieties "Output: All Italian varieties, specify"
capture label var gp_q_italian_varieties "Output: All Italian varieties, qt"
capture label var gp_v_italian_varieties "Output: All Italian varieties, value"
capture label var gp_q_whey_butter "Output: Whey butter, qt"
capture label var gp_v_whey_butter "Output: Whey butter, value"
capture label var gp_q_dried_casein "Output: Dried casein, qt"
capture label var gp_v_dried_casein "Output: Dried casein, value"
capture label var gp_q_wet_casein "Output: Wet casein, qt"
capture label var gp_v_wet_casein "Output: Wet casein, value
capture label var gp_q_condensed_milk "Output: Condensed milk, qt"
capture label var gp_v_condensed_milk "Output: Condensed milk, value"
capture label var gp_q_whole_case_goods "Output: Made from whole milk: case goods, qt"
capture label var gp_v_whole_case_goods "Output: Made from whole milk: case goods, value"
capture label var gp_q_whole_bulk_goods "Output: Made from whole milk: bulk goods, qt"
capture label var gp_v_whole_bulk_goods "Output: Made from whole milk: bulk goods, value"
capture label var gp_q_skim_case_goods "Output: Made from skim milk: case goods, qt"
capture label var gp_v_skim_case_goods "Output: Made from skim milk: case goods, value"
capture label var gp_q_skim_bulk_goods "Output: Made from skim milk: bulk goods, qt"
capture label var gp_v_skim_bulk_goods "Output: Made from skim milk: bulk goods, value"
capture label var gp_q_evaporated_case_goods "Output: Evaporated milk (made from whole milk): case goods, qt"
capture label var gp_v_evaporated_case_goods "Output: Evaporated milk (made from whole milk): case goods, value"
capture label var gp_q_evaporated_bulk_goods "Output: Evaporated milk (made from whole milk): bulk goods, qt"
capture label var gp_v_evaporated_bulk_goods "Output: Evaporated milk (made from whole milk): bulk goods, value"
capture label var gp_q_concentrated_skim "Output: Concentrated skim milk, qt"
capture label var gp_v_concentrated_skim "Output: Concentrated skim milk, value"
capture label var gp_q_condensed_evaporated "Output: Condensed and evaporated, qt"
capture label var gp_v_condensed_evaporated "Output: Condensed and evaporated, value"
capture label var gp_q_dried_buttermilk "Output: Dried or powdered buttermilk, qt"
capture label var gp_v_dried_buttermilk "Output: Dried or powdered buttermilk, value"
capture label var gp_q_dried_cream "Output: Dried or powdered cream, qt"
capture label var gp_v_dried_cream "Output: Dried or powdered cream, value"
capture label var gp_q_dried_skim "Output: Dried or powdered skim milk, qt"
capture label var gp_v_dried_skim "Output: Dried or powdered skim milk, value"
capture label var gp_q_dried_whole "Output: Dried or powdered whole milk, qt"
capture label var gp_v_dried_whole "Output: Dried or powdered whole milk, value"
capture label var gp_q_milk_sugar_crude "Output: Milk sugar (crude), qt"
capture label var gp_v_milk_sugar_crude "Output: Milk sugar (crude), value"
capture label var gp_q_milk_sugar_refined "Output: Milk sugar (refined), qt"
capture label var gp_v_milk_sugar_refined "Output: Milk sugar (refined), value"
capture label var gp_q_ice_cream "Output: Ice cream, qt"
capture label var gp_v_ice_cream "Output: Ice cream, value"
capture label var gp_q_ices_sherbets "Output: Ices, sherbets, qt"
capture label var gp_v_ices_sherbets "Output: Ices, sherbets, value"
capture label var gp_q_specialties "Output: Specialties (cups, sticks, etc), qt"
capture label var gp_v_specialties "Output: Specialties (cups, sticks, etc), value"
capture label var gp_q_ice_cream_mix "Output: Ice cream mix, qt"
capture label var gp_v_ice_cream_mix "Output: Ice cream mix, value"
capture label var gp_q_ice_sale "Output: Ice (made for sale), qt"
capture label var gp_v_ice_sale "Output: Ice (made for sale), value"
capture label var gp_q_ice_consumed "Output: Ice (made and consumed), qt"
capture label var gp_v_ice_consumed "Output: Ice (made and consumed), value"
capture label var gp_q_confectionery "Output: Confectionery, qt"
capture label var gp_v_confectionery "Output: Confectionery, value"
capture label var gp_q_beverages "Output: Beverages (cereal, carbonated), qt"
capture label var gp_v_beverages "Output: Beverages (cereal, carbonated), value"
capture label var gp_q_bakery "Output: Bakery products, qt"
capture label var gp_v_bakery "Output: Bakery products, value"
capture label var gp_q_malted_milk "Output: Malted milk, qt"
capture label var gp_v_malted_milk "Output: Malted milk, value"
capture label var gp_q_skim_sold "Output: Skimmed milk sold, qt"
capture label var gp_v_skim_sold "Output: Skimmed milk sold, value"
capture label var gp_q_buttermilk_sold "Output: Buttermilk sold, qt"
capture label var gp_v_buttermilk_sold "Output: Buttermilk sold, value"
capture label var gp_q_whey_sold "Output: Whey sold, qt"
capture label var gp_v_whey_sold "Output: Whey sold, value"
capture label var gp_q_milk_sold "Output: Milk sold, qt"
capture label var gp_v_milk_sold "Output: Milk sold, value"
capture label var gp_q_cream_sold "Output: Cream sold, qt"
capture label var gp_v_cream_sold "Output: Cream sold, value"

//capital variables
capture label z_vehicles_horse "Capital: Horse Vehicles"
capture label z_vehicles_gasoline "Capital: Gasoline Vehicles"
capture label z_vehicles_electric "Capital: Electric Vehicles"
