#this writes do file for renaming common variables in particular year

root_user='/Users/nlz1'
letters_fixed = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm','n','o','p','q','r','s','t','u','v','w','x','y','z']
letters_forward = ['b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm','n','o','p','q','r','s','t','u','v','w','x','y','z', 'a']
dict_forward = dict(zip([letter.upper() for letter in letters_fixed], [letter.upper() for letter in letters_forward]))

ind_dir = root_user+'/Dropbox (SES1459263)/Cleaning Scripts'
python_dir = root_user+'/Dropbox (SES1459263)/Python Scripts'

def update_col(a):
	
	a[-1]=dict_forward[a[-1]]
	if a[-1]=='A':
		if len(a)==1:
			a.append('A')
		else:
			a[0:len(a)-1] = update_col(a[0:len(a)-1])	

	return a

f1=open(python_dir+'/ind_cols_years.txt','r')
dict_stringCols={}
for line in f1.readlines():
	split_line = line.split(',')
	if line !='\n':
		dict_stringCols[split_line[0]] =  split_line[1]
f1.close()

for year in dict_stringCols.keys():

	col_name=[temp.lower().strip('\'') for temp in  dict_stringCols[year].split('\t')]	
	f=open(ind_dir+'/'+str(year)+'/rename_common_'+str(year)+'.do', 'w+')
	f.write('//Rename common variables for year: '+str(year)+'. Generated by write_rename_common.py and ind_cols_years.txt.\n')
	current_col = ['A']

	for i in col_name:

		f.write('capture rename '+''.join(current_col) +' '+ i+'\n')
		current_col = update_col(current_col)
	
	f.close()
